from aiohttp import ClientTimeout
from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1LocalSubjectAccessReview
from kubernetes_asyncio.client.models import V1SelfSubjectAccessReview
from kubernetes_asyncio.client.models import V1SelfSubjectRulesReview
from kubernetes_asyncio.client.models import V1SubjectAccessReview
from multidict import CIMultiDictProxy
from typing import Any
from typing import Awaitable

class AuthorizationV1Api:
    def __init__(self, api_client: ApiClient | None = None) -> None: ...
    def create_namespaced_local_subject_access_review(self, namespace: str, body: V1LocalSubjectAccessReview, *, dry_run: str = ..., field_manager: str = ..., field_validation: str = ..., pretty: str = ..., async_req: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ...) -> Awaitable[V1LocalSubjectAccessReview]: ...
    def create_namespaced_local_subject_access_review_with_http_info(self, namespace: str, body: V1LocalSubjectAccessReview, *, dry_run: str = ..., field_manager: str = ..., field_validation: str = ..., pretty: str = ..., async_req: bool = ..., _return_http_data_only: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ..., _request_auth: dict = ...) -> Awaitable[tuple[V1LocalSubjectAccessReview, int, CIMultiDictProxy]]: ...
    def create_self_subject_access_review(self, body: V1SelfSubjectAccessReview, *, dry_run: str = ..., field_manager: str = ..., field_validation: str = ..., pretty: str = ..., async_req: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ...) -> Awaitable[V1SelfSubjectAccessReview]: ...
    def create_self_subject_access_review_with_http_info(self, body: V1SelfSubjectAccessReview, *, dry_run: str = ..., field_manager: str = ..., field_validation: str = ..., pretty: str = ..., async_req: bool = ..., _return_http_data_only: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ..., _request_auth: dict = ...) -> Awaitable[tuple[V1SelfSubjectAccessReview, int, CIMultiDictProxy]]: ...
    def create_self_subject_rules_review(self, body: V1SelfSubjectRulesReview, *, dry_run: str = ..., field_manager: str = ..., field_validation: str = ..., pretty: str = ..., async_req: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ...) -> Awaitable[V1SelfSubjectRulesReview]: ...
    def create_self_subject_rules_review_with_http_info(self, body: V1SelfSubjectRulesReview, *, dry_run: str = ..., field_manager: str = ..., field_validation: str = ..., pretty: str = ..., async_req: bool = ..., _return_http_data_only: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ..., _request_auth: dict = ...) -> Awaitable[tuple[V1SelfSubjectRulesReview, int, CIMultiDictProxy]]: ...
    def create_subject_access_review(self, body: V1SubjectAccessReview, *, dry_run: str = ..., field_manager: str = ..., field_validation: str = ..., pretty: str = ..., async_req: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ...) -> Awaitable[V1SubjectAccessReview]: ...
    def create_subject_access_review_with_http_info(self, body: V1SubjectAccessReview, *, dry_run: str = ..., field_manager: str = ..., field_validation: str = ..., pretty: str = ..., async_req: bool = ..., _return_http_data_only: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ..., _request_auth: dict = ...) -> Awaitable[tuple[V1SubjectAccessReview, int, CIMultiDictProxy]]: ...
    def get_api_resources(self, *, async_req: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ...) -> Awaitable[V1APIResourceList]: ...
    def get_api_resources_with_http_info(self, *, async_req: bool = ..., _return_http_data_only: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ..., _request_auth: dict = ...) -> Awaitable[tuple[V1APIResourceList, int, CIMultiDictProxy]]: ...
