from aiohttp import ClientTimeout
from kubernetes_asyncio.client.api_client import ApiClient
from typing import Any
from typing import Awaitable

class LogsApi:
    def __init__(self, api_client: ApiClient | None = None) -> None: ...
    def log_file_handler(self, logpath: str, *, async_req: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ...) -> Awaitable[None]: ...
    def log_file_handler_with_http_info(self, logpath: str, *, async_req: bool = ..., _return_http_data_only: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ..., _request_auth: dict = ...) -> Awaitable[None]: ...
    def log_file_list_handler(self, *, async_req: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ...) -> Awaitable[None]: ...
    def log_file_list_handler_with_http_info(self, *, async_req: bool = ..., _return_http_data_only: bool = ..., _preload_content: bool = ..., _request_timeout: None | int | float | tuple[float, float] | ClientTimeout = ..., _request_auth: dict = ...) -> Awaitable[None]: ...
