LIBRARY(clicommands)

SRCS(
    interactive/interactive_cli.cpp
    interactive/yql_highlight.cpp
    interactive/line_reader.cpp
    benchmark_utils.cpp
    topic_operations_scenario.cpp
    topic_read_scenario.cpp
    topic_write_scenario.cpp
    topic_readwrite_scenario.cpp
    query_workload.cpp
    ydb_admin.cpp
    ydb_benchmark.cpp
    ydb_dynamic_config.cpp
    ydb_profile.cpp
    ydb_root_common.cpp
    ydb_service_auth.cpp
    ydb_service_export.cpp
    ydb_service_import.cpp
    ydb_service_monitoring.cpp
    ydb_service_operation.cpp
    ydb_service_scheme.cpp
    ydb_service_scripting.cpp
    ydb_service_topic.cpp
    ydb_service_table.cpp
    ydb_sql.cpp
    ydb_tools.cpp
    ydb_workload.cpp
    ydb_workload_import.cpp
    ydb_yql.cpp
)

PEERDIR(
    contrib/libs/fmt
    contrib/restricted/patched/replxx
    library/cpp/histogram/hdr
    library/cpp/protobuf/json
    library/cpp/regex/pcre
    library/cpp/threading/local_executor
    ydb/library/backup
    ydb/library/workload
    ydb/library/yaml_config/public
    ydb/public/lib/operation_id
    ydb/public/lib/stat_visualization
    ydb/public/lib/ydb_cli/common
    ydb/public/lib/ydb_cli/commands/command_base
    ydb/public/lib/ydb_cli/commands/interactive/antlr
    ydb/public/lib/ydb_cli/commands/topic_workload
    ydb/public/lib/ydb_cli/commands/transfer_workload
    ydb/public/lib/ydb_cli/commands/ydb_discovery
    ydb/public/lib/ydb_cli/commands/sdk_core_access
    ydb/public/lib/ydb_cli/dump
    ydb/public/lib/ydb_cli/import
    ydb/public/lib/ydb_cli/topic
    ydb/public/sdk/cpp/client/draft
    ydb/public/sdk/cpp/client/ydb_coordination
    ydb/public/sdk/cpp/client/ydb_export
    ydb/public/sdk/cpp/client/ydb_import
    ydb/public/sdk/cpp/client/ydb_monitoring
    ydb/public/sdk/cpp/client/ydb_operation
    ydb/public/sdk/cpp/client/ydb_persqueue_public
    ydb/public/sdk/cpp/client/ydb_proto
    ydb/public/sdk/cpp/client/ydb_scheme
    ydb/public/sdk/cpp/client/ydb_table
    ydb/public/sdk/cpp/client/ydb_topic
    ydb/public/sdk/cpp/client/ydb_types/credentials/login
)

END()

RECURSE_FOR_TESTS(
    topic_workload/ut
)
