YQL_UDF_CONTRIB(datetime2_udf)
    YQL_ABI_VERSION(
        2
        43
        0
    )
    SRCS(
        datetime_udf.cpp
    )
    PEERDIR(
        util/draft
        library/cpp/type_info/tz
        yql/essentials/public/udf/arrow
        yql/essentials/public/langver
        yql/essentials/minikql
        yql/essentials/minikql/datetime
    )
    END()

RECURSE_FOR_TESTS(
    test
    test_bigdates
)
