YQL_UDF_YDB(datetime2_udf)
YQL_ABI_VERSION(
    2
    37
    0
)
SRCS(
    datetime_udf.cpp
)
PEERDIR(
    yql/essentials/public/udf/arrow
    yql/essentials/minikql
    yql/essentials/minikql/datetime
    yql/essentials/public/udf/tz
)
END()