PY2_LIBRARY()

LICENSE(MIT)

VERSION(0.2.0)

PEERDIR(
    contrib/python/clickhouse-cityhash
    contrib/python/lz4
    contrib/python/pytz
    contrib/python/tzlocal
    contrib/python/zstandard
    contrib/deprecated/python/enum34
    contrib/deprecated/python/ipaddress
)

NO_LINT()

NO_CHECK_IMPORTS(
    clickhouse_driver.columns.numpy.*
    clickhouse_driver.numpy.*
)

PY_SRCS(
    TOP_LEVEL
    clickhouse_driver/__init__.py
    clickhouse_driver/block.py
    clickhouse_driver/blockstreamprofileinfo.py
    clickhouse_driver/client.py
    clickhouse_driver/clientinfo.py
    clickhouse_driver/columns/__init__.py
    clickhouse_driver/columns/arraycolumn.py
    clickhouse_driver/columns/base.py
    clickhouse_driver/columns/datecolumn.py
    clickhouse_driver/columns/datetimecolumn.py
    clickhouse_driver/columns/decimalcolumn.py
    clickhouse_driver/columns/enumcolumn.py
    clickhouse_driver/columns/exceptions.py
    clickhouse_driver/columns/floatcolumn.py
    clickhouse_driver/columns/intcolumn.py
    clickhouse_driver/columns/intervalcolumn.py
    clickhouse_driver/columns/ipcolumn.py
    clickhouse_driver/columns/lowcardinalitycolumn.py
    clickhouse_driver/columns/nothingcolumn.py
    clickhouse_driver/columns/nullablecolumn.py
    clickhouse_driver/columns/nullcolumn.py
    clickhouse_driver/columns/numpy/__init__.py
    clickhouse_driver/columns/numpy/base.py
    clickhouse_driver/columns/numpy/datecolumn.py
    clickhouse_driver/columns/numpy/datetimecolumn.py
    clickhouse_driver/columns/numpy/floatcolumn.py
    clickhouse_driver/columns/numpy/intcolumn.py
    clickhouse_driver/columns/numpy/lowcardinalitycolumn.py
    clickhouse_driver/columns/numpy/service.py
    clickhouse_driver/columns/numpy/stringcolumn.py
    clickhouse_driver/columns/service.py
    clickhouse_driver/columns/simpleaggregatefunctioncolumn.py
    clickhouse_driver/columns/stringcolumn.py
    clickhouse_driver/columns/tuplecolumn.py
    clickhouse_driver/columns/uuidcolumn.py
    clickhouse_driver/compression/__init__.py
    clickhouse_driver/compression/base.py
    clickhouse_driver/compression/lz4.py
    clickhouse_driver/compression/lz4hc.py
    clickhouse_driver/compression/zstd.py
    clickhouse_driver/connection.py
    clickhouse_driver/context.py
    clickhouse_driver/dbapi/__init__.py
    clickhouse_driver/dbapi/connection.py
    clickhouse_driver/dbapi/cursor.py
    clickhouse_driver/dbapi/errors.py
    clickhouse_driver/defines.py
    clickhouse_driver/errors.py
    clickhouse_driver/log.py
    clickhouse_driver/numpy/__init__.py
    clickhouse_driver/numpy/block.py
    clickhouse_driver/numpy/helpers.py
    clickhouse_driver/numpy/result.py
    clickhouse_driver/progress.py
    clickhouse_driver/protocol.py
    clickhouse_driver/queryprocessingstage.py
    clickhouse_driver/reader.py
    clickhouse_driver/readhelpers.py
    clickhouse_driver/result.py
    clickhouse_driver/settings/__init__.py
    clickhouse_driver/settings/available.py
    clickhouse_driver/settings/types.py
    clickhouse_driver/settings/writer.py
    clickhouse_driver/streams/__init__.py
    clickhouse_driver/streams/compressed.py
    clickhouse_driver/streams/native.py
    clickhouse_driver/util/__init__.py
    clickhouse_driver/util/compat.py
    clickhouse_driver/util/escape.py
    clickhouse_driver/util/helpers.py
    clickhouse_driver/writer.py

    CYTHON_C
    clickhouse_driver/bufferedreader.pyx
    clickhouse_driver/bufferedwriter.pyx
    clickhouse_driver/varint.pyx
)

RESOURCE_FILES(
    PREFIX contrib/python/clickhouse-driver/py2/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
