# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(0.2.2)

LICENSE(MIT)

NO_COMPILER_WARNINGS()

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    weighted_levenshtein/__init__.py
    CYTHON_CPP
    weighted_levenshtein/clev.pyx
)

RESOURCE_FILES(
    PREFIX contrib/python/weighted-levenshtein/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
