# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(1.5.0)

LICENSE(BSD-3-Clause AND LicenseRef-scancode-unknown-license-reference)

PEERDIR(
    contrib/libs/gdal
    contrib/python/affine
    contrib/python/attrs
    contrib/python/certifi
    contrib/python/click
    contrib/python/cligj
    contrib/python/numpy
    contrib/python/pyparsing
)

ADDINCL(
    FOR cython contrib/python/rasterio
    FOR cython contrib/python/numpy/py3
)

NO_COMPILER_WARNINGS()

NO_LINT()

CYTHON_FLAGS(
    -ECTE_GDAL_MAJOR_VERSION=3
    -ECTE_GDAL_MINOR_VERSION=11
    -ECTE_GDAL_PATCH_VERSION=4
)

PY_SRCS(
    TOP_LEVEL
    rasterio/__init__.py
    rasterio/_path.py
    rasterio/_show_versions.py
    rasterio/_vendor/__init__.py
    rasterio/_vendor/click_plugins.py
    rasterio/_vendor/snuggs.py
    rasterio/abc.py
    rasterio/control.py
    rasterio/coords.py
    rasterio/drivers.py
    rasterio/dtypes.py
    rasterio/enums.py
    rasterio/env.py
    rasterio/errors.py
    rasterio/features.py
    rasterio/fill.py
    rasterio/io.py
    rasterio/mask.py
    rasterio/merge.py
    rasterio/path.py
    rasterio/plot.py
    rasterio/profiles.py
    rasterio/rio/__init__.py
    rasterio/rio/blocks.py
    rasterio/rio/bounds.py
    rasterio/rio/calc.py
    rasterio/rio/clip.py
    rasterio/rio/convert.py
    rasterio/rio/create.py
    rasterio/rio/edit_info.py
    rasterio/rio/env.py
    rasterio/rio/gcps.py
    rasterio/rio/helpers.py
    rasterio/rio/info.py
    rasterio/rio/insp.py
    rasterio/rio/main.py
    rasterio/rio/mask.py
    rasterio/rio/merge.py
    rasterio/rio/options.py
    rasterio/rio/overview.py
    rasterio/rio/rasterize.py
    rasterio/rio/rm.py
    rasterio/rio/sample.py
    rasterio/rio/shapes.py
    rasterio/rio/stack.py
    rasterio/rio/transform.py
    rasterio/rio/warp.py
    rasterio/rpc.py
    rasterio/sample.py
    rasterio/session.py
    rasterio/stack.py
    rasterio/tools.py
    rasterio/transform.py
    rasterio/vrt.py
    rasterio/warp.py
    rasterio/windows.py
    CYTHON_DIRECTIVE
    language_level=3
    CYTHON_C
    rasterio/_base.pyx
    rasterio/_env.pyx
    rasterio/_err.pyx
    rasterio/_example.pyx
    rasterio/_features.pyx
    rasterio/_io.pyx
    rasterio/_transform.pyx
    rasterio/_version.pyx
    rasterio/_vsiopener.pyx
    rasterio/cache.pyx
    rasterio/crs.pyx
    rasterio/shutil.pyx
    CYTHON_CPP
    rasterio/_filepath.pyx
    rasterio/_fill.pyx
    rasterio/_warp.pyx
)

RESOURCE_FILES(
    PREFIX contrib/python/rasterio/
    .dist-info/METADATA
    .dist-info/entry_points.txt
    .dist-info/top_level.txt
)

END()
