OWNER(g:contrib g:python-contrib)

RECURSE(
    absl-py
    adblockparser
    aenum
    ago
    aio-pika
    aioboto3
    aiobotocore
    aioch
    aiochclient
    aiodns
    aiodocker
    aiofiles
    aioftp
    aiogram
    aiographite
    aiohttp
    aiohttp-apispec
    aiohttp-cors
    aiohttp-jinja2
    aiohttp-remotes
    aiohttp-retry
    aiohttp-swagger
    aiohttp-xmlrpc
    aioitertools
    aiojobs
    aiomysql
    aiopg
    aioredis
    aioredis-lock
    aioresponses
    aiormq
    aiosignal
    aiosmtpd
    aiosmtplib
    aiosocksy
    aiosqlite
    aiotg
    aiounittest
    aiozipkin
    aiozk
    alabaster
    alembic
    allpairspy
    amqp
    aniso8601
    annoy
    antlr4
    ansiwrap
    anyconfig
    anyio
    anytree
    apipkg
    apispec
    apispec-flask-restful
    appdirs
    APScheduler
    apsw
    aresponses
    argcomplete
    argon2-cffi
    argon2-cffi-bindings
    argparse-addons
    arq
    arrow
    asciitree
    asgiref
    asn1crypto
    astroid
    asttokens
    astunparse
    async-generator
    async-lru
    async-timeout
    asyncio-pool
    asyncmc
    asyncpg
    asyncssh
    asynctest
    asyncwhois
    atomicwrites
    atpublic
    AttrDict
    attrs
    Authlib
    autobahn
    Automat
    awscli
    Babel
    backcall
    backports_abc
    backports.csv
    backports.functools-lru-cache
    backports.lzma
    backports.shutil-get-terminal-size
    backports.ssl_match_hostname
    backports.tempfile
    backports.weakref
    banal
    bandit
    bcrypt
    beautifulsoup4
    behave
    betamax
    betamax-serializers
    billiard
    binaryornot
    bincopy
    biplist
    bitarray
    black
    bleach
    blinker
    blis
    bokeh
    boltons
    boolean.py
    bootstrapped
    boto
    boto3
    botocore
    braceexpand
    bravado
    bravado-core
    bsddb3
    bson
    bz2file
    cached-property
    cachelib
    cachetools
    catalogue
    cattrs
    cbor2
    cchardet
    celery
    celery-mock
    Cerberus
    certifi
    certipy
    cffi
    channels
    chardet
    charset-normalizer
    channels
    chart-studio
    CherryPy
    cherrypy-cors
    ciso8601
    clang
    clang/example
    cli-helpers
    click
    click-didyoumean
    click-plugins
    click-repl
    clickhouse-cityhash
    clickhouse-driver
    clickhouse-sqlalchemy
    cloudpickle
    color
    colorama
    coloredlogs
    colorhash
    colorlog
    commoncode
    commonmark
    ConfigArgParse
    configobj
    configparser
    confluent-kafka
    constantly
    contextdecorator
    contextlib2
    convertdate
    cookies
    cov-core
    coverage
    coverage/bin
    cpu-cores
    crcmod
    croniter
    crontab
    cryptography
    cssselect
    cssutils
    curlify
    cx-Oracle
    cycler
    cymem
    cytoolz
    czipfile
    daphne
    dask
    daphne
    databases
    dataclasses-json
    datadiff
    dateparser
    dateutil
    DAWG-Python
    dbf_light
    debian-inspector
    decorator
    deepdiff
    deepmerge
    defusedxml
    demjson
    Deprecated
    dictpath
    diff-match-patch
    directio
    distro
    django
    django-admin-inline-paginator
    django-admin-rangefilter
    django-admin-view-permission
    django-advanced-filters
    django-ajax-selects
    django-alive
    django-autoconfig
    django-appconf
    django-bootstrap3
    django-braces
    django-bulk-update
    django-cachalot
    django-cache-memoize
    django-celery-beat
    django-celery-email
    django-celery-results
    django-closuretree
    django-constance
    django-cors-headers
    django-cors-middleware
    django-crispy-forms
    django-cron
    django-csp
    django-cte
    django-datetime-widget
    django-db-geventpool
    django-dbtemplates
    django-debug-panel
    django-debug-toolbar
    django-dirtyfields
    django-dynamic-raw-id
    django-enumfields
    django-environ
    django-etc
    django-export-action-py3
    django-extensions
    django-fernet-fields
    django-filebrowser-no-grappelli
    django-filter
    django-fsm
    django-grappelli
    django-guardian
    django-hosts
    django-http-proxy
    django-import-export
    django-introspection
    django-jinja
    django-js-asset
    django-json-widget
    django-markwhat
    django-model-choices
    django-model-utils
    django-modeladmin-reorder
    django-modeltranslation
    django-moderation
    django-mptt
    django-mptt-admin
    django-nested-inline
    django-netfields
    django-ninja
    django-object-actions
    django-opentracing
    django-partial-index
    django-pdb
    django-phonenumbers
    django-picklefield
    django-post-office
    django-postgrespool2
    django-proxy-storage
    django-query-exchange
    django-redis
    django-redis-cache
    django-replicated
    django-rest-framework-docs
    django-rest-multiple-models
    django-reversion
    django-select2-forms
    django-sentinel
    django-simple-history
    django-siteforms
    django-sitemessage
    django-sitetree
    django-sortedm2m
    django-storages
    django-tastypie
    django-test-migrations
    django-timezone-field
    django-treebeard
    django-waffle
    django-webpack-loader
    django-webtest
    django-whatever
    django-widget-tweaks
    djangorestframework
    djangorestframework-camel-case
    djangorestframework-csv
    djangorestframework-filters
    djangorestframework-jsonp
    djangorestframework-xml
    dm.xmlsec.binding
    dnspython
    docker
    docopt
    docstring-parser
    docutils
    dohq-teamcity
    dominate
    dotmap
    dparse
    dpath
    dpkt
    drf-extensions
    drf_ujson
    drf-yasg
    easywebdav
    ecdsa
    edera
    editdistance
    elasticsearch
    elasticsearch-dsl
    email-validator
    emoji
    entrypoints
    enum34
    environ-config
    environs
    envoy
    ephem
    escapism
    etcd3
    excel-formulas-calculator
    execnet
    executing
    ExifRead
    extractcode
    fabric
    face
    facebook-business
    factory-boy
    Faker
    fakeredis
    falcon
    falcon-cors
    falcon-multipart
    fallocate
    fancycompleter
    fastapi
    fastapi-utils
    fastdtw
    fasteners
    fastjsonschema
    fastsnmp
    faulthandler
    fbprophet
    feedparser
    ffmpeg-python
    fido2
    filelock
    fingerprints
    fire
    flake8
    flake8-bandit
    flake8-commas
    flake8-docstrings
    flake8-polyfill
    flake8-quotes
    flake8-string-format
    flaky
    Flask
    Flask-Admin
    flask-appconfig
    Flask-Babel
    Flask-Bootstrap
    Flask-Bootstrap/example
    Flask-Caching
    flask-cors
    flask_graphql
    Flask-Humanize
    Flask-Log-Request-ID
    Flask-Login
    Flask-Mail
    flask-marshmallow
    Flask-Menu
    flask_migrate
    flask-mongoengine
    Flask-OpenTracing
    Flask-Principal
    Flask-Pydantic
    Flask-PyMongo
    Flask-RESTful
    flask-restplus
    flask-restx
    Flask-Script
    flask-shell-ipython
    Flask-Shelve
    Flask-SQLAlchemy
    Flask-SSLify
    flask-swagger
    flask-swagger-ui
    Flask-Table
    Flask-UUID
    Flask-WTF
    flatbuffers
    flex
    flup
    frozendict
    frozenlist
    fsspec
    ftfy
    funcparserlib
    funcsigs
    functools32
    furl
    future
    futures
    gast
    gcovr
    GDAL
    gemfileparser
    gensim
    GeoAlchemy2
    geobuf
    geoindex
    gevent
    gino
    gitdb2
    github3.py
    GitPython
    glob2
    glom
    goerr
    google-api-core
    google-api-python-client
    google-auth
    google-auth-httplib2
    google-auth-oauthlib
    google-cloud-speech
    google-pasta
    googleads
    gpxpy
    GPy
    GPyOpt
    grafanalib
    graphene
    graphene-django
    graphene-sqlalchemy
    graphql-core
    graphql-relay
    graphviz
    greenify
    greenlet
    grequests
    grpcio-opentracing
    gspread
    gunicorn
    h11
    h2
    h3
    h5py
    hammock
    hexdump
    hijri-converter
    hiredis
    hjson
    holidays
    horovod
    hpack
    hstspreload
    html2text
    html5lib
    httmock
    http-parser
    httpagentparser
    httpcore
    httplib2
    httpretty
    httptools
    httpx
    humanfriendly
    humanize
    humongous
    hurry.filesize
    Hydra
    hypercorn
    hyperframe
    hyperlink
    hyperopt
    hypothesis
    ibm-db
    icalendar
    idna
    idna-ssl
    ijson
    imagesize
    IMAPClient
    imgkit
    implicit
    importlib-metadata
    importlib-resources
    incremental
    infi.clickhouse-orm
    inflect
    inflection
    influxdb
    iniconfig
    iniherit
    Inject
    inlinestyler
    intbitset
    intspan
    invoke
    ipaddr
    ipaddress
    ipadic
    ipdb
    ipykernel
    ipython
    ipython-genutils
    ipython-sql
    ipywidgets
    iso3166
    iso8601
    isodate
    isort
    itsdangerous
    jaeger-client
    janus
    jaraco.functools
    javaproperties
    jdcal
    jedi
    Jinja2
    jinja2-time
    jmespath
    joblib
    jmespath
    json-rpc
    json2html
    jsondiff
    jsonfield
    jsonobject
    jsonpath-rw
    jsonpickle
    jsonpointer
    jsonref
    jsonschema
    jsonstreams
    juggler_sdk
    juggler_sdk/cli
    junitparser
    jupyter_client
    jupyter_core
    jupyter-telemetry
    jupyterhub
    jupyterhub-traefik-proxy
    jupytext
    kaitaistruct
    kazoo
    Keras-Preprocessing
    kiwisolver
    kombu
    korean-lunar-calendar
    kubernetes
    langcodes
    lark-parser
    lazy
    lazy-object-proxy
    lcov_cobertura
    lcov_cobertura/bin
    legacycontour
    license-expression
    line_profiler
    linecache2
    llist
    lmdb
    localshop
    lockfile
    logging-tree
    loguru
    logutils
    luigi
    LunarCalendar
    lunardate
    lunr
    lxml
    lz4
    M2Crypto
    m3u8
    Mako
    marisa_trie
    markdown2
    Markdown
    MarkupSafe
    marshmallow
    marshmallow_dataclass
    marshmallow-enum
    marshmallow-mongoengine
    marshmallow-oneofschema
    marshmallow-sqlalchemy
    marshmallow-union
    matplotlib
    matplotlib-inline
    mccabe
    mecab-python3
    meld3
    memory-profiler
    mercurial
    mistune
    mitmproxy
    mkdocs
    mkdocs-material
    mock
    model-mommy
    Momoko
    MongoDBProxy
    mongoengine
    mongolock
    mongomock
    monotonic
    more-itertools
    moto
    moto/standalone
    motor
    mpegdash
    mpi4py
    mpmath
    msal
    msgpack
    mujson
    multidict
    multitasking
    munch
    murmurhash
    mutablerecords
    mypy
    mypy-extensions
    mypy-protobuf
    mypy-zope
    MySQL-python
    mysqlclient-python
    namedlist
    natsort
    nbclient
    nbconvert
    nbformat
    ncclient
    ndg-httpsclient
    nest-asyncio
    nested-diff
    netaddr
    netifaces
    networkx
    nltk
    normality
    nose
    notebook
    num2words
    numpy
    oauth2client
    oauthlib 
    objgraph
    observable
    odfpy
    Office365-REST-Python-Client
    olefile
    openapi-codec
    openapi-core
    openapi-schema-validator
    openapi-spec-validator
    opencv-python
    openpyxl
    opensfm
    opentok
    opentracing
    opentracing-async-instrumentation
    opentracing-instrumentation
    opt-einsum
    option
    ordered-set
    orderedmultidict
    orderedset
    os-fast-reservoir
    packageurl-python
    packaging
    paginate
    pamela
    pampy
    pamqp
    panamap
    panamap_proto
    pandas
    pandocfilters
    papermill
    parameterized
    paramiko
    paramz
    parse
    parse-type
    parsedatetime
    parsel
    Parsley
    parso
    partd
    passlib
    patch
    patched
    path.py
    pathlib2
    pathspec
    pathtools
    pathy
    patsy
    paypalrestsdk
    pdbpp
    pdfminer.six
    pecan
    peewee
    peewee/playhouse
    pefile
    pem
    pexpect
    pgcli
    PGPy
    pgspecial
    phonenumbers
    pickleshare
    pika
    Pillow
    pip
    pkginfo
    platformdirs
    plotly
    plotly/_plotly_utils
    pluggy
    plugincode
    plumbum
    ply
    plyvel
    polib
    portalocker
    portpicker
    ppdeep
    pq
    pql
    prance
    premailer
    preshed
    pretend
    prettytable
    priority
    progressbar2
    prometheus-client
    prometheus-flask-exporter
    promise
    prompt-toolkit
    prophet
    protobuf
    protobuf_std
    protobuf_to_dict
    psutil
    psycogreen
    psycopg2
    ptpython
    ptyprocess
    publicsuffix2
    pure-eval
    pure-python-adb
    pure-sasl
    py
    py-asciimath
    py-expression-eval
    py-radix
    py3c
    py4j
    pyaes
    pyahocorasick
    pyaml
    pyasn1
    pyasn1-modules
    pybreaker
    pycares
    pycbrf
    pycodestyle
    pycollada
    pycountry
    pycparser
    pycrypto
    pycryptodome
    pycurl
    pycurl/example
    pydantic
    pydash
    PyDispatcher
    pyDOE
    pydocstyle
    pydot
    pydub
    pyelftools
    pyelftools/readelf
    pyfakefs
    pyflakes
    pyfst
    pygit2
    PyGithub
    Pygments
    pygrib
    pygtrie
    PyHamcrest
    pyjavaproperties
    PyJWT
    pykdtree
    pyketama
    pylev
    pylint
    pylxd
    pylzma
    pymaven-patch
    PyMeeus
    pymongo
    pymorphy2
    pymorphy2-dicts-ru
    pymqi
    PyMySQL
    pynacl
    pynetbox
    pyodbc
    pyOpenSSL
    pyparsing
    PyPDF2
    pyperclip
    PyPika
    pyproj
    pyre2
    pyrepl
    pyresample
    pyrsistent
    pysctp
    pysendfile
    pyserial
    PySocks
    pystan
    pystan/pystan_model
    pysyncobj
    pyTelegramBotAPI
    pytest
    pytest-allure-adaptor
    pytest-asyncio
    pytest-bdd
    pytest-datadir
    pytest-datafixtures
    pytest-django
    pytest-falcon
    pytest-falcon-client
    pytest-fixture-config
    pytest-flake8
    pytest-flakes
    pytest-flask
    pytest-forked
    pytest-freezegun
    pytest-httpretty
    pytest-lazy-fixture
    pytest-localserver
    pytest-mock
    pytest-randomly
    pytest-responsemock
    pytest-responses
    pytest-server-fixtures
    pytest-shutil
    pytest-timeout
    pytest-tornado
    pytest-twisted
    pytest-vcr
    pytest-xdist
    pytest-xprocess
    python-crfsuite
    python-crontab
    python-daemon
    python-datemath
    python-debian
    python-decouple
    python-docx
    python-dotenv
    python-editor
    python-geohash
    python-gnupg
    python-hglib
    python-i18n
    python-jose
    python-json-logger
    python-ldap
    python-libarchive
    python-magic
    python-memcached
    python-mimeparse
    python-multipart
    python-pptx
    python-prctl
    python-rapidjson
    python-saml
    python-slugify
    python-telegram-bot
    python-utils
    python3-saml
    pytils
    pytracemalloc
    pytz
    pyudev
    pyusb
    PyWavelets
    PyYAML
    pyzmq
    qemu
    qrcode
    quart
    queuelib
    rarfile
    ratelimit
    raven
    razdel
    rdflib
    readabilipy
    redis
    redis-cache-lock
    regex 
    reportlab
    repoze.lru
    repr
    requests
    requests-file
    requests-mock
    requests-oauthlib
    requests-toolbelt
    requests-unixsocket
    responses
    respx
    retry
    retrying
    rfc3986
    rfc3986-validator
    RPi.GPIO
    RPI-ST7789
    rsa
    rstr
    ruamel.std.pathlib
    ruamel.yaml
    Rx
    s3-tests
    s3transfer
    sacrebleu
    salt-pepper
    saneyaml
    sanic
    sanic-routing
    sanic-testing
    scales
    scancode-toolkit
    scandir
    schedule
    schema
    schematics 
    schwifty
    scikit-image
    scikit-learn
    scipy
    scour
    scp
    Scrapy
    seaborn
    selectors2
    selenium
    semantic-version
    semver
    Send2Trash
    sentinels
    sentry-sdk
    service-identity
    setproctitle
    setuptools
    sgmllib3k
    sh
    Shapely
    shortuuid
    simplediff
    simplegeneric
    simplejson
    singledispatch
    six
    skynet_pyro4
    slack-sdk
    slackclient
    smart-open
    smmap
    snappy
    sniffio
    snowballstemmer
    sobol-seq
    sockjs
    soft-webauthn
    sortedcontainers
    soupsieve
    spacy
    spacy-legacy
    spacy-loggers
    sparse-dot-topn
    spdx-tools
    spidev
    spintop-openhtf
    splunk-sdk-python
    sqlalchemy
    SQLAlchemy-Continuum
    sqlalchemy-stubs
    SQLAlchemy-Utils
    sqlparse
    sqltap
    srptools
    srsly
    sshpubkeys
    sshtunnel
    stack-data
    starlette
    statsd
    statsmodels
    stevedore
    StrEnum
    structlog
    subprocess32
    subword-nmt
    suds-jurko
    supervenn
    supervisor
    svn
    swagger-spec-validator
    sympy
    sysv-ipc
    tableauserverclient
    tablib
    tabulate
    tblib
    Telethon
    tenacity
    tensorflow-estimator
    termcolor
    terminado
    terminaltables
    testpath
    text-unidecode
    textdata
    texttable
    textwrap3
    thinc
    threadloop
    thrift
    timelib
    timeout-decorator
    tinycss2
    tinyrpc
    tldextract
    toml
    tomli
    toolz
    toposort
    toredis
    tornado
    tornado-opentracing
    toro
    tqdm
    trace_event
    traceback2
    traitlets
    transfer_manager_client
    transitions
    transliterate
    trollius
    trollsift
    Twiggy
    twiggy-goodies
    Twisted
    txaio
    txredisapi
    typecode
    typed-argument-parser
    typed-ast
    typeguard
    typer
    typing
    typing-extensions
    typing-inspect
    tzlocal
    ua-parser
    udatetime
    uhashring
    ujson
    ulid2
    umalqurra
    umongo
    unicodecsv
    Unidecode
    unidiff
    uplink
    uritemplate
    uritools
    urllib3
    urlpy
    user-agents
    uvicorn
    uvloop
    uwsgi
    uwsgi/bin
    uwsgi/examples
    uwsgiconf
    validators
    validr
    vcrpy
    viberbot
    vine
    visitor
    voluptuous
    w3lib
    waitress
    walrus
    Wand
    wasabi
    watchdog
    watchgod
    wcwidth
    webargs
    webauthn
    webcolors
    webencodings
    WebOb
    websocket-client
    websockets
    webstruct
    WebTest
    webvtt-py
    weighted-levenshtein
    Werkzeug
    wheel
    whitenoise
    whodap
    wmctrl
    wrapt
    ws4py
    wsgi-intercept
    wsgi-profiler
    wsproto
    wtf-peewee
    WTForms
    WTForms-JSON
    wurlitzer
    xhtml2pdf
    xlrd
    XlsxWriter
    xlutils
    xlwt
    xmlsec
    xmltodict
    xxhash
    yandex-pgmigrate
    yappi
    yarl
    yfinance
    youtube-dl
    yoyo-migrations
    yt-dlp
    zake
    zeep
    zero-downtime-migrations
    zope.event
    zope.interface
    zope.schema
    zstandard
)

IF (OS_WINDOWS)
    RECURSE(
        win_unicode_console
    )
ENDIF()

IF (OS_DARWIN)
    RECURSE(
        appnope
    )
ENDIF ()

IF (OS_LINUX)
    RECURSE(
        pyroute2
    )

    IF (OS_SDK != "ubuntu-12")
        RECURSE(
            cysystemd
        )
    ENDIF()
ENDIF ()
