# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(0.0.2)

LICENSE(MIT)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    jstyleson.py
)

RESOURCE_FILES(
    PREFIX contrib/python/jstyleson/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
