from box.box import Box as Box
from typing import Any

class ConfigBox(Box):
    def __getattr__(self, item: Any): ...
    def __dir__(self) -> list[str]: ...
    def bool(self, item: Any, default: Any | None = ...): ...
    def int(self, item: Any, default: Any | None = ...): ...
    def float(self, item: Any, default: Any | None = ...): ...
    def list(self, item: Any, default: Any | None = ..., spliter: str = ..., strip: bool = ..., mod: Any | None = ...): ...  # type: ignore
    def getboolean(self, item: Any, default: Any | None = ...): ...
    def getint(self, item: Any, default: Any | None = ...): ...
    def getfloat(self, item: Any, default: Any | None = ...): ...
    def copy(self) -> ConfigBox: ...
    def __copy__(self) -> ConfigBox: ...
