{
 "title": "Database hive",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": { "query": "label_values(database)" } },
   { "name": "ds", "query": "prometheus" },
   { "name": "localtx", "label": "local-tx", "query": { "query": "label_values(__name__)" } }
  ]
 },
 "panels": [
  {
   "title": "hive+balancer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(rate(utils_ElapsedMicrosecByActivity{execpool=\"System\", activity=\"HIVE_ACTOR\", database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "HIVE_ACTOR"
    },
    {
     "expr": "max(rate(utils_ElapsedMicrosecByActivity{execpool=\"System\", activity=\"HIVE_BALANCER_ACTOR\", database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "HIVE_BALANCER_ACTOR"
    }
   ]
  },
  {
   "title": "tablet count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(tablets_MAX_Hive_TabletsTotal_{type=\"Hive\", category=\"app\", database=\"$database\"})",
     "legendFormat": "MAX(Hive/TabletsTotal)"
    },
    {
     "expr": "max(tablets_MAX_Hive_TabletsAlive_{type=\"Hive\", category=\"app\", database=\"$database\"})",
     "legendFormat": "MAX(Hive/TabletsAlive)"
    },
    {
     "expr": "max(tablets_SUM_Hive_TabletsStarting_{type=\"Hive\", category=\"app\", database=\"$database\"})",
     "legendFormat": "SUM(Hive/TabletsStarting)"
    }
   ]
  },
  {
   "title": "hive self-ping time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(tablets_MAX_Hive_ResponseTimeMicrosec_{database=\"$database\"})",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "event queue size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "max(tablets_SUM_Hive_EventQueueSize_{database=\"$database\", type=\"Hive\", category=\"app\"})",
     "legendFormat": "EventQueueSize"
    }
   ]
  },
  {
   "title": "hive local transaction times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "((label_replace(max({database=\"$database\",category=\"app\", type = \"Hive\", __name__=~\"tablets_MAX_Hive_Tx.*_ExecuteCPUTime_\"}), \"name_label\", \"$1\", \"__name__\", \"tablets_MAX_Hive_(.*)_ExecuteCPUTime_\")))",
     "legendFormat": "{{name_label}}"
    },
    {
     "expr": "max_over_time(sum({database=\"$database\",category=\"app\", type = \"Hive\", __name__=~\"tablets_MAX_Hive_Tx.*_ExecuteCPUTime_\"})[15m:])",
     "legendFormat": "ExecuteCpuTime total"
    }
   ]
  },
  {
   "title": "versions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "count by (revision) (utils_version{database=\"$database\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hive node",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "utils_ActorsAliveByActivity{activity=\"HIVE_ACTOR\", execpool=\"System\", database=\"$database\"}",
     "legendFormat": "{{host}} {{instance}}"
    }
   ]
  },
  {
   "title": "$localtx avg time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max((rate(tablets_Hive_${localtx}_RoCompleted{database=\"$database\",category=\"app\",type=\"Hive\"}[$__rate_interval])) + (rate(tablets_Hive_${localtx}_RwCompleted{database=\"$database\",category=\"app\",type=\"Hive\"}[$__rate_interval])))",
     "legendFormat": "$localtx count"
    },
    {
     "expr": "max((tablets_MAX_Hive_${localtx}_ExecuteCPUTime_{database=\"$database\",category=\"app\",type=\"Hive\"}) / ((rate(tablets_Hive_${localtx}_RoCompleted{database=\"$database\",category=\"app\",type=\"Hive\"}[$__rate_interval])) + (rate(tablets_Hive_${localtx}_RwCompleted{database=\"$database\",category=\"app\",type=\"Hive\"}[$__rate_interval]))))",
     "legendFormat": "$localtx avg time"
    },
    {
     "expr": "max(max_over_time(((rate(tablets_Hive_${localtx}_RoCompleted{database=\"$database\",category=\"app\",type=\"Hive\"}[$__rate_interval])) + (rate(tablets_Hive_${localtx}_RwCompleted{database=\"$database\",category=\"app\",type=\"Hive\"}[$__rate_interval])))[15m:]))",
     "legendFormat": "$localtx count, total on 15 min window"
    }
   ]
  }
 ]
}