{
 "title": "DB overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": { "query": "label_values(database)" } },
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Health (Storage)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(ydb_healthcheck{counter=\"healthcheck\"}) by (MESSAGE, STATUS, DOMAIN, DATABASE)",
     "legendFormat": "{{STATUS}} at {{ DATABASE }} ({{MESSAGE}})"
    }
   ]
  },
  {
   "title": "Cluster Health (Compute)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count(ydb_healthcheck{DATABASE=\"$database\", counter=\"healthcheck-dynamic\"}) by (MESSAGE,STATUS,TYPE)",
     "legendFormat": "{{STATUS}} ({{MESSAGE}})"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(ydb_api_grpc_request_count{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(ydb_api_grpc_response_count{database=\"$database\",container=\"ydb-dynamic\",status!=\"SUCCESS\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(ydb_api_grpc_request_bytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Response size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(ydb_api_grpc_response_bytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hard errors (non-retriable)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(ydb_api_grpc_response_count{database=\"$database\",container=\"ydb-dynamic\",status=~\"BAD_REQUEST|NOT_FOUND|ALREADY_EXISTS|UNSPECIFIED|SCHEME_ERROR|PRECONDITION_FAILED|TIMEOUT|GENERIC_ERROR|INTERNAL_ERROR|RESOURCE_EXHAUSTED|SESSION_EXPIRED|UNAUTHENTICATED|UNAUTHORIZED\"}[$__rate_interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Soft errors (retriable)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(ydb_api_grpc_response_count{database=\"$database\",container=\"ydb-dynamic\",status=~\"BAD_SESSION|UNAVAILABLE|OVERLOADED|CANCELLED|ABORTED|SESSION_BUSY\"}[$__rate_interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Dropped requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (method) (rate(ydb_api_grpc_request_dropped_count{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Dropped responses",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (method) (rate(ydb_api_grpc_response_dropped_count{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Requests in flight",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (method) (ydb_api_grpc_request_inflight_count{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Request bytes in flight",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (method) (ydb_api_grpc_request_inflight_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU by execution pool",
   "type": "timeseries",
   "description": "all values are in core percents",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pool) (rate(ydb_resources_cpu_used_core_percents{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "User pool - CPU by host",
   "type": "timeseries",
   "description": "all values are in core percents<br>min limit - minimum of per-host pool limits<br>max limit - maximum of per-host pool limits",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min(ydb_resources_cpu_limit_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"user\"})",
     "legendFormat": "min limit"
    },
    {
     "expr": "max(ydb_resources_cpu_limit_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"user\"})",
     "legendFormat": "max limit"
    },
    {
     "expr": "rate(ydb_resources_cpu_used_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"user\"}[$__rate_interval])",
     "legendFormat": "{{host}}{{pod}}"
    }
   ]
  },
  {
   "title": "CPU pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "System pool - CPU by host",
     "type": "timeseries",
     "description": "all values are in core percents<br>min limit - minimum of per-host pool limits<br>max limit - maximum of per-host pool limits",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "min(ydb_resources_cpu_limit_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"system\"})",
       "legendFormat": "min limit"
      },
      {
       "expr": "max(ydb_resources_cpu_limit_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"system\"})",
       "legendFormat": "max limit"
      },
      {
       "expr": "rate(ydb_resources_cpu_used_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"system\"}[$__rate_interval])",
       "legendFormat": "{{host}}{{pod}}"
      }
     ]
    },
    {
     "title": "Batch pool - CPU by host",
     "type": "timeseries",
     "description": "all values are in core percents<br>min limit - minimum of per-host pool limits<br>max limit - maximum of per-host pool limits",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "min(ydb_resources_cpu_limit_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"batch\"})",
       "legendFormat": "min limit"
      },
      {
       "expr": "max(ydb_resources_cpu_limit_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"batch\"})",
       "legendFormat": "max limit"
      },
      {
       "expr": "rate(ydb_resources_cpu_used_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"batch\"}[$__rate_interval])",
       "legendFormat": "{{host}}{{pod}}"
      }
     ]
    },
    {
     "title": "IC pool - CPU by host",
     "type": "timeseries",
     "description": "all values are in core percents<br>min limit - minimum of per-host pool limits<br>max limit - maximum of per-host pool limits",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "min(ydb_resources_cpu_limit_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"ic\"})",
       "legendFormat": "min limit"
      },
      {
       "expr": "max(ydb_resources_cpu_limit_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"ic\"})",
       "legendFormat": "max limit"
      },
      {
       "expr": "rate(ydb_resources_cpu_used_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"ic\"}[$__rate_interval])",
       "legendFormat": "{{host}}{{pod}}"
      }
     ]
    },
    {
     "title": "IO pool - CPU by host",
     "type": "timeseries",
     "description": "all values are in core percents<br>min limit - minimum of per-host pool limits<br>max limit - maximum of per-host pool limits",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "min(ydb_resources_cpu_limit_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"io\"})",
       "legendFormat": "min limit"
      },
      {
       "expr": "max(ydb_resources_cpu_limit_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"io\"})",
       "legendFormat": "max limit"
      },
      {
       "expr": "rate(ydb_resources_cpu_used_core_percents{database=\"$database\",container=\"ydb-dynamic\",pool=\"io\"}[$__rate_interval])",
       "legendFormat": "{{host}}{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory by host",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(ydb_resources_memory_limit_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "min limit"
    },
    {
     "expr": "max(ydb_resources_memory_limit_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "max limit"
    },
    {
     "expr": "ydb_resources_memory_used_bytes{database=\"$database\",container=\"ydb-dynamic\"}",
     "legendFormat": "{{host}}{{pod}}"
    }
   ]
  },
  {
   "title": "Memory by activities and instances",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(activity, instance) (utils_tcmalloc_sampled_size_by_activity{database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "{{activity}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ydb_resources_memory_limit_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "limit sum"
    },
    {
     "expr": "sum(ydb_resources_memory_used_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "usage"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ydb_resources_storage_limit_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(ydb_resources_storage_used_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Storage utlilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(ydb_resources_storage_used_bytes{database=\"$database\",container=\"ydb-dynamic\"}) / sum(ydb_resources_storage_limit_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "utilization"
    }
   ]
  },
  { "title": "DataShard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Throughput (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(ydb_table_datashard_write_bytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(ydb_table_datashard_read_bytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(ydb_table_datashard_bulk_upsert_bytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "bulk upsert"
    },
    {
     "expr": "sum(rate(ydb_table_datashard_scan_bytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "scan"
    },
    {
     "expr": "sum(rate(ydb_table_datashard_erase_bytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "erase"
    }
   ]
  },
  {
   "title": "Overloaded shard count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(ydb_table_datashard_used_core_percents_bucket{database=\"$database\",container=\"ydb-dynamic\",le=\"70\"}) - sum(ydb_table_datashard_used_core_percents_bucket{database=\"$database\",container=\"ydb-dynamic\",le=\"60\"})",
     "legendFormat": "70%"
    },
    {
     "expr": "sum(ydb_table_datashard_used_core_percents_bucket{database=\"$database\",container=\"ydb-dynamic\",le=\"80\"}) - sum(ydb_table_datashard_used_core_percents_bucket{database=\"$database\",container=\"ydb-dynamic\",le=\"70\"})",
     "legendFormat": "80%"
    },
    {
     "expr": "sum(ydb_table_datashard_used_core_percents_bucket{database=\"$database\",container=\"ydb-dynamic\",le=\"90\"}) - sum(ydb_table_datashard_used_core_percents_bucket{database=\"$database\",container=\"ydb-dynamic\",le=\"80\"})",
     "legendFormat": "90%"
    },
    {
     "expr": "sum(ydb_table_datashard_used_core_percents_bucket{database=\"$database\",container=\"ydb-dynamic\",le=\"100\"}) - sum(ydb_table_datashard_used_core_percents_bucket{database=\"$database\",container=\"ydb-dynamic\",le=\"90\"})",
     "legendFormat": "100%"
    }
   ]
  },
  {
   "title": "DataShard details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput (rows)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(ydb_table_datashard_write_rows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "write"
      },
      {
       "expr": "sum(rate(ydb_table_datashard_read_rows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(ydb_table_datashard_bulk_upsert_rows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "bulk upsert"
      },
      {
       "expr": "sum(rate(ydb_table_datashard_scan_rows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "scan"
      },
      {
       "expr": "sum(rate(ydb_table_datashard_erase_rows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "erase"
      }
     ]
    },
    {
     "title": "Shard distribution by workload",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "sum by (le) (ydb_table_datashard_used_core_percents_bucket{database=\"$database\",container=\"ydb-dynamic\",le!=\"+Inf\"})",
       "legendFormat": "{{le}}%"
      }
     ]
    },
    {
     "title": "Row count",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(ydb_table_datashard_row_count{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "rows"
      }
     ]
    },
    {
     "title": "Data size",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(ydb_table_datashard_size_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "rows"
      }
     ]
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Read only tx server latency percentiles",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"read_only\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"read_only\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"read_only\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"read_only\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Read only tx server latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"read_only\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Write only tx server latency percentiles",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"write_only\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"write_only\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"write_only\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"write_only\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Write only tx server latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"write_only\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Read/Write tx server latency percentiles",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"read_write\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"read_write\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"read_write\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"read_write\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Read/Write tx server latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ydb_table_transaction_server_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\",tx_kind=\"read_write\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}