{
 "title": "DB status",
 "tags": [ "ydb" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": { "query": "label_values(database)" } },
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Queries per second by latency buckets",
   "type": "timeseries",
   "description": "Displays the number of queries per second grouped by latency bins.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(ydb_table_query_execution_latency_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Session count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kqp_SessionActors_Active{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "Active sessions"
    }
   ]
  },
  {
   "title": "CPU by thread pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (execpool) (rate(utils_ElapsedMicrosec{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])/1000000)",
     "legendFormat": "{{execpool}}"
    }
   ]
  },
  {
   "title": "DataShard TX Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"tablets_DataShard_.+Completed\"}, \"name_label\", \"$1\", \"__name__\", \"tablets_DataShard_(.+)Completed\")[$__rate_interval:]))",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Transactions per second by latency buckets",
   "type": "timeseries",
   "description": "Displays the number of transactions per second grouped by latency bins.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(proxy_TxTotalTimesMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Session count by host",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "sum by (host, pod) (kqp_SessionActors_Active{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "{{host}}{{pod}}"
    }
   ]
  },
  {
   "title": "CPU in user pool utilization by host",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / ($A + $B)", "type": "math" }
   ]
  },
  {
   "title": "DataShard ExecuteCPUTime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"tablets_DataShard_.+_ExecuteCPUTime\"}, \"name_label\", \"$1\", \"__name__\", \"tablets_DataShard_(.+)_ExecuteCPUTime\")[$__rate_interval:])/1000000) ",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "TxTotalTimes percentiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(proxy_TxTotalTimesMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(proxy_TxTotalTimesMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(proxy_TxTotalTimesMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(proxy_TxTotalTimesMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Consumed memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(tablets_SUM_ConsumedMemory_{database=\"$database\",container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "Tablets"
    },
    {
     "expr": "sum(followers_SUM_ConsumedMemory_{database=\"$database\",container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "Followers"
    }
   ]
  },
  {
   "title": "RSS size by dynnode",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (host, pod) (utils_Process_AnonRssSize{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "{{host}}{{pod}}"
    },
    {
     "expr": "min(utils_Process_CGroupMemLimit{database=\"$database\"})",
     "legendFormat": "CGroup memory limit"
    }
   ]
  },
  {
   "title": "Memory overview",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (utils_Process_AnonRssSize{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "RSS (system)"
    },
    {
     "expr": "sum (utils_generic_physical_memory_used{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "Physical memory used (TCMalloc)"
    },
    {
     "expr": "sum (utils_generic_bytes_in_use_by_app{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "Bytes in use by app (TCMalloc)"
    },
    {
     "expr": "sum (utils_tcmalloc_sampled_size_by_activity{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "Sampled size (TCMalloc)"
    },
    {
     "expr": "sum (utils_MT_Memory{label=\"Tablet/TSharedData/Buffers\", database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "TSharedData buffers (memory tracker)"
    }
   ]
  },
  {
   "title": "DataShard range read rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_EngineHostRangeReadRows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "RangeRead rows"
    }
   ]
  },
  {
   "title": "DataShard single row read rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_EngineHostRowReads{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Read from tablets"
    },
    {
     "expr": "sum(rate(followers_DataShard_EngineHostRowReads{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Read from followers"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(ydb_table_query_compilation_cache_size_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(ydb_resources_storage_table_used_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "Tables"
    },
    {
     "expr": "sum(ydb_resources_storage_limit_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(ydb_resources_storage_topic_used_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "Topics"
    },
    {
     "expr": "sum(ydb_resources_storage_used_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "Total used"
    }
   ]
  },
  {
   "title": "DataShard range read bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_EngineHostRangeReadBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Read from tablets"
    },
    {
     "expr": "sum(rate(followers_DataShard_EngineHostRangeReadBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Read from followers"
    }
   ]
  },
  {
   "title": "DataShard single row read bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_EngineHostRowReadBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Read from tablets"
    },
    {
     "expr": "sum(rate(followers_DataShard_EngineHostRowReadBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Read from followers"
    }
   ]
  },
  {
   "title": "DataShards Count and Limit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(tablets_MAX_SchemeShard_ShardsQuota_{database=\"$database\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(utils_ActorsAliveByActivity{database=\"$database\", activity=\"TX_DATASHARD_ACTOR\"})",
     "legendFormat": "DataShard count"
    }
   ]
  },
  {
   "title": "DbDataBytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(tablets_SUM_DbDataBytes_{database=\"$database\",container=\"ydb-dynamic\",category=\"executor\"})",
     "legendFormat": "Database size"
    }
   ]
  },
  {
   "title": "Range read request count grouped by rows per request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(tablets_DataShard_RangeReadRowsPerRequest_bucket{database=\"$database\",container=\"ydb-dynamic\", counter=\"tablets\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "sum by (le) (rate(followers_DataShard_RangeReadRowsPerRequest_bucket{database=\"$database\",container=\"ydb-dynamic\", counter=\"followers\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Single row read requests count grouped by rows per request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(tablets_DataShard_SelectRowsPerRequest_bucket{database=\"$database\",container=\"ydb-dynamic\", counter=\"tablets\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "sum by (le) (rate(followers_DataShard_SelectRowsPerRequest_bucket{database=\"$database\",container=\"ydb-dynamic\", counter=\"followers\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Database rows total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(tablets_SUM_DbUniqueRowsTotal_{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "DbUniqueDataBytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(tablets_SUM_DbUniqueDataBytes_{database=\"$database\",container=\"ydb-dynamic\",category=\"executor\"})",
     "legendFormat": "Database unique data size"
    }
   ]
  },
  {
   "title": "DataShard tablets count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(utils_ActorsAliveByActivity{database=\"$database\",container=\"ydb-dynamic\",activity=\"TX_DATASHARD_ACTOR\"})",
     "legendFormat": "tablets"
    }
   ]
  },
  {
   "title": "Aborted transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    {
     "expr": "sum(rate(kqp_Transactions_Aborted{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "transactions aborted"
    }
   ]
  },
  {
   "title": "YQL issues",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"kqp_Issues_YQL:.+\"}, \"name_label\", \"$1\", \"__name__\", \"kqp_Issues_YQL:(.+)\")[$__rate_interval:]))",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "YQL issues: unavailable",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "sum(rate(kqp_YdbResponses_Unavailable{database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "UNAVAILABLE"
    }
   ]
  },
  {
   "title": "gRpc StreamReadTable",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(grpc_infly{database=\"$database\", request=\"StreamReadTable\"})",
     "legendFormat": "Infly requests"
    }
   ]
  },
  {
   "title": "DataShard upload rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_UploadRows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Uploaded rows per second"
    }
   ]
  },
  {
   "title": "DataShard UploadRows bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_UploadRowsBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "UploadRows bytes per second"
    }
   ]
  },
  {
   "title": "DataShard max(TxCompleteLag)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(tablets_MAX_DataShard_TxCompleteLag_{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "max(TxCompleteLag)"
    }
   ]
  },
  {
   "title": "DataShard ReadColumns rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_ReadColumnsRows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Read from tablets"
    },
    {
     "expr": "sum(rate(followers_DataShard_ReadColumnsRows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Read from followers"
    }
   ]
  },
  {
   "title": "DataShard ReadColumns bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_ReadColumnsBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Read from tablets"
    },
    {
     "expr": "sum(rate(followers_DataShard_ReadColumnsBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Read from followers"
    }
   ]
  },
  {
   "title": "Overloaded shard count",
   "type": "timeseries",
   "description": "Shows the number of shards experiencing high CPU load (from 50% to 100%). Helps assess the level of system overload.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(tablets_HIST_ConsumedCPU_{range=\"50%\", type=\"DataShard\", database=\"$database\"})",
     "legendFormat": "50%"
    },
    {
     "expr": "sum(tablets_HIST_ConsumedCPU_{range=\"60%\", type=\"DataShard\", database=\"$database\"})",
     "legendFormat": "60%"
    },
    {
     "expr": "sum(tablets_HIST_ConsumedCPU_{range=\"70%\", type=\"DataShard\", database=\"$database\"})",
     "legendFormat": "70%"
    },
    {
     "expr": "sum(tablets_HIST_ConsumedCPU_{range=\"80%\", type=\"DataShard\", database=\"$database\"})",
     "legendFormat": "80%"
    },
    {
     "expr": "sum(tablets_HIST_ConsumedCPU_{range=\"90%\", type=\"DataShard\", database=\"$database\"})",
     "legendFormat": "90%"
    },
    {
     "expr": "sum(tablets_HIST_ConsumedCPU_{range=\"100%\", type=\"DataShard\", database=\"$database\"})",
     "legendFormat": "100%"
    }
   ]
  },
  {
   "title": "Tasks in ResourceBroker queues",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (queue) (tablets_EnqueuedTasks{database=\"$database\",container=\"ydb-dynamic\",queue!=\"\",queue!=\"total\"})",
     "legendFormat": "{{queue}}: EnqueuedTasks"
    },
    {
     "expr": "sum by (queue) (rate(tablets_FinishedTasks{database=\"$database\",container=\"ydb-dynamic\",queue!=\"\",queue!=\"total\"}[$__rate_interval]))",
     "legendFormat": "{{queue}}: FinishedTasks"
    },
    {
     "expr": "sum by (queue) (tablets_InFlyTasks{database=\"$database\",container=\"ydb-dynamic\",queue!=\"\",queue!=\"total\"})",
     "legendFormat": "{{queue}}: InFlyTasks"
    }
   ]
  },
  {
   "title": "Interconnect connected",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(interconnect_Connected{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "Coordinator cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "(sum by (host, execpool) (rate(utils_ElapsedMicrosecByActivity{database=\"$database\",container=\"ydb-dynamic\",activity=\"TX_COORDINATOR_ACTOR\"}[$__rate_interval]))) / 1000000",
     "legendFormat": "{{host}}, {{execpool}}"
    }
   ]
  },
  {
   "title": "Mediator cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "(sum by (host, execpool) (rate(utils_ElapsedMicrosecByActivity{database=\"$database\",container=\"ydb-dynamic\",activity=\"TX_MEDIATOR_ACTOR\"}[$__rate_interval]))) / 1000000",
     "legendFormat": "{{host}}, {{execpool}}"
    }
   ]
  },
  {
   "title": "DataShard ImmediateTxInFly",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(tablets_SUM_DataShard_ImmediateTxInFly_{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "InFly transactions"
    }
   ]
  },
  {
   "title": "Cache miss bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_CacheMissBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Cache misses"
    }
   ]
  },
  {
   "title": "Cache miss pages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_CacheMissPages{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Cache missed pages"
    }
   ]
  },
  {
   "title": "Cache hit bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_CacheHitBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Cache hits"
    }
   ]
  },
  {
   "title": "Cache hit pages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_CacheHitPages{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Cache hit pages"
    }
   ]
  },
  {
   "title": "ExecPrepared queries per second by latency buckets",
   "type": "timeseries",
   "description": "Displays the number of queries per second grouped by latency bins.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(kqp_Query_ExecPreparedLatencyMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ReadReplicas count by sync latency buckets (us)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(tablets_FollowerSyncLatency_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RowsTotal | RowsErased",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(tablets_SUM_DbRowsTotal_{database=\"$database\",container=\"ydb-dynamic\", type!=\"all\"})",
     "legendFormat": "Rows total"
    },
    {
     "expr": "sum(tablets_SUM_DbRowsErase_{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "Rows erased"
    }
   ]
  },
  {
   "title": "Split / Merge partitions avg per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 55 },
   "targets": [
    {
     "expr": "sum(rate(tablets_SchemeShard_FinishedOps_SplitTablePartition{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Partitions split"
    },
    {
     "expr": "sum(rate(tablets_SchemeShard_FinishedOps_MergeTablePartition{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Partitions merged"
    }
   ]
  },
  {
   "title": "DSProxy PutTabletLog rps by latency buckets",
   "type": "timeseries",
   "description": "Displays the number of queries per second grouped by latency bins.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{storagePool!=\"static\",database=\"$database\",container=\"ydb-dynamic\",handleClass=\"PutTabletLog\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DSProxy PutUserData rps by latency buckets",
   "type": "timeseries",
   "description": "Displays the number of queries per second grouped by latency bins.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{storagePool!=\"static\",database=\"$database\",container=\"ydb-dynamic\",handleClass=\"PutUserData\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DSProxy PutAsync rps by latency buckets",
   "type": "timeseries",
   "description": "Displays the number of queries per second grouped by latency bins.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{storagePool!=\"static\",database=\"$database\",container=\"ydb-dynamic\",handleClass=\"PutAsync\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "EventDeliveryTimeUs In UserPool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(utils_EventDeliveryTimeUs_bucket{database=\"$database\", execpool=\"User\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DSProxy GetFast rps by latency buckets",
   "type": "timeseries",
   "description": "Displays the number of queries per second grouped by latency bins.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{storagePool!=\"static\",database=\"$database\",container=\"ydb-dynamic\",handleClass=\"GetFast\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DSProxy GetDiscover rps by latency buckets",
   "type": "timeseries",
   "description": "Displays the number of queries per second grouped by latency bins.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{storagePool!=\"static\",database=\"$database\",container=\"ydb-dynamic\",handleClass=\"GetDiscover\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DSProxy GetAsync rps by latency buckets",
   "type": "timeseries",
   "description": "Displays the number of queries per second grouped by latency bins.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{storagePool!=\"static\",database=\"$database\",container=\"ydb-dynamic\",handleClass=\"GetAsync\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "EventProcessingTimeUs In UserPool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(utils_EventProcessingTimeUs_bucket{database=\"$database\", execpool=\"User\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tablet moved by Hive",
   "type": "timeseries",
   "description": "Tablets can be moved by Balancer, Drain or Fill",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(tablets_Hive_TabletsMoved{database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "Tablets moved per second"
    }
   ]
  },
  {
   "title": "CDC Delivery Lag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max(tablets_MAX_DataShard_ChangeDeliveryLag_{database=\"$database\"})",
     "legendFormat": "CDC Delivery Lag"
    }
   ]
  },
  {
   "title": "BulkUpsert Latency gRPC API call latency",
   "type": "timeseries",
   "description": "Displays the number of queries per second grouped by latency bins.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(grpc_LatencyMs_bucket{request=\"BulkUpsert\",database=\"$database\", le!~\".*\\\\.0$\", le!=\"+Inf\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PQ Cache Bytes by dynnode",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host) (tablets_NodeCacheSizeBytes{type=\"PQ_CACHE\", database=\"$database\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ydbd version by node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (revision) (utils_version{database=\"$database\"})",
     "legendFormat": "{{revision}}"
    }
   ]
  },
  {
   "title": "Nodes Uptime",
   "type": "timeseries",
   "description": "Displays the uptime of each node since its startup. Helps track restarts and identify unstable nodes.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "utils_Process_UptimeSeconds{container=\"ydb-dynamic\", database=\"$database\"}",
     "legendFormat": "dynnode: {{host}}"
    },
    {
     "expr": "utils_Process_UptimeSeconds{container=\"ydb-static\"}",
     "legendFormat": "storage node: {{instance}}"
    }
   ]
  },
  {
   "title": "Alerts tablet broken",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tablets_alerts_boot_nodata{database=\"$database\"}",
     "legendFormat": "alerts_boot_nodata"
    },
    {
     "expr": "tablets_alerts_broken{database=\"$database\"}",
     "legendFormat": "alerts_broken"
    },
    {
     "expr": "tablets_alerts_pending_nodata{database=\"$database\"}",
     "legendFormat": "alerts_pending_nodata"
    },
    {
     "expr": "tablets_alerts_boot_nodata{database=\"$database\"}",
     "legendFormat": "alerts_boot_nodata"
    }
   ]
  },
  {
   "title": "Max TxCompleteLag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(tablets_MAX_PQ_TxCompleteLag_{database=\"$database\"})",
     "legendFormat": "max(PQ_TxCompleteLag)"
    },
    {
     "expr": "max(tablets_MAX_DataShard_TxCompleteLag_{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "max(DataShard_TxCompleteLag)"
    }
   ]
  }
 ]
}