{
 "title": "Distributed Storage performance metrics by storagePool",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "storagePool", "label": "storagePool", "query": { "query": "label_values(storagePool)" } }
  ]
 },
 "panels": [
  {
   "title": "DiskTimeAvailable and total Cost relation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(vdisks_DiskTimeAvailable{storagePool=\"$storagePool\"})",
     "legendFormat": "DiskTimeAvailable"
    },
    {
     "expr": "(sum(rate(vdisks_UserDiskCost{storagePool=\"$storagePool\"}[$__rate_interval]))) + (sum(rate(vdisks_InternalDiskCost{storagePool=\"$storagePool\"}[$__rate_interval]))) + (sum(rate(vdisks_CompactionDiskCost{storagePool=\"$storagePool\"}[$__rate_interval]))) + (sum(rate(vdisks_DefragDiskCost{storagePool=\"$storagePool\"}[$__rate_interval]))) + (sum(rate(vdisks_ScrubDiskCost{storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "Total Cost"
    },
    {}
   ]
  },
  {
   "title": "Cost by source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(vdisks_UserDiskCost{storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "UserDiskCost"
    },
    {
     "expr": "sum(rate(vdisks_InternalDiskCost{storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "InternalDiskCost"
    },
    {
     "expr": "sum(rate(vdisks_CompactionDiskCost{storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "CompactionDiskCost"
    },
    {
     "expr": "sum(rate(vdisks_DefragDiskCost{storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "DefragDiskCost"
    },
    {
     "expr": "sum(rate(vdisks_ScrubDiskCost{storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "ScrubDiskCost"
    }
   ]
  },
  {
   "title": "Total burst duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(vdisks_BurstDetector_redMs{storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "BurstTime"
    }
   ]
  }
 ]
}