{
 "title": "Distributed Storage Latency Overview",
 "tags": [ "ydb" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "database", "query": { "query": "label_values(database)" } },
   { "name": "storagePool", "label": "storagePool", "query": { "query": "label_values(storagePool)" } }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# DSProxy" } },
  {
   "title": "DSProxy PutTabletLog Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutTabletLog\", storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DSProxy PutTabletLog Percentile",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutTabletLog\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutTabletLog\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutTabletLog\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutTabletLog\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by(le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutTabletLog\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.999"
    }
   ]
  },
  {
   "title": "DSProxy PutUserData Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutUserData\", storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DSProxy PutUserData Percentile",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutUserData\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutUserData\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutUserData\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutUserData\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "DSProxy PutAsync Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutAsync\", storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DSProxy PutAsync Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutAsync\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutAsync\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutAsync\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutAsync\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by(le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"PutAsync\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.999"
    }
   ]
  },
  {
   "title": "DSProxy GetFast Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetFast\", storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DSProxy GetFast Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetFast\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetFast\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetFast\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetFast\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "DSProxy GetDiscover Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetDiscover\", storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DSProxy GetDiscover Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetDiscover\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetDiscover\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetDiscover\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetDiscover\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "DSProxy GetAsync Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetAsync\", storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DSProxy GetAsync Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetAsync\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetAsync\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetAsync\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(dsproxynode_responseTimeMs_bucket{container=\"ydb-dynamic\", database=\"$database\", handleClass=\"GetAsync\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 }, "options": { "content": "# VDisks" } },
  {
   "title": "VDisk PutTabletLog Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(le) (rate(vdisks_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"PutTabletLog\", storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "VDisk PutTabletLog Percentile",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vdisks_LatencyMs_bucket{container=\"ydb-storage\", handleclass=\"PutTabletLog\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vdisks_LatencyMs_bucket{container=\"ydb-storage\", handleclass=\"PutTabletLog\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vdisks_LatencyMs_bucket{container=\"ydb-storage\", handleclass=\"PutTabletLog\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vdisks_LatencyMs_bucket{container=\"ydb-storage\", handleclass=\"PutTabletLog\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by(le) (rate(vdisks_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"PutTabletLog\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.999"
    }
   ]
  },
  {
   "title": "VDisk PutUserData Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(le) (rate(vdisks_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"PutUserData\", storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "VDisk PutUserData Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vdisks_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"PutUserData\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vdisks_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"PutUserData\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vdisks_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"PutUserData\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vdisks_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"PutUserData\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "VDisk PutAsyncBlob Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"PutAsyncBlob\", storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "VDisk PutAsyncBlob Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"PutAsyncBlob\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"PutAsyncBlob\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"PutAsyncBlob\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"PutAsyncBlob\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "VDisk GetFast Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(le) (rate(vdisks_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetFast\", storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "VDisk GetFast Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vdisks_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetFast\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vdisks_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetFast\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vdisks_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetFast\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vdisks_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetFast\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "VDisk GetDiscover Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetDiscover\", storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "VDisk GetDiscover Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetDiscover\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetDiscover\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetDiscover\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetDiscover\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "VDisk GetAsync Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetAsync\", storagePool=\"$storagePool\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "VDisk GetAsync Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetAsync\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetAsync\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetAsync\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vdisks_async_LatencyMs_bucket{container=~\"ydb-static|ydb-storage\", handleclass=\"GetAsync\", storagePool=\"$storagePool\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    }
   ]
  }
 ]
}