{
 "title": "YDB Memory",
 "tags": [ "ydb" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "database", "query": { "query": "label_values(database)" } }
  ]
 },
 "panels": [
  {
   "title": "RSS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (utils_Process_AnonRssSize{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "RSS (system)"
    },
    {
     "expr": "sum(utils_Process_CGroupMemLimit{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "CGroup memory limit"
    }
   ]
  },
  {
   "title": "RSS by host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (host) (utils_Process_AnonRssSize{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (utils_Process_AnonRssSize{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "RSS (system)"
    },
    {
     "expr": "sum (utils_generic_physical_memory_used{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "Physical memory used (TCMalloc)"
    },
    {
     "expr": "sum (utils_generic_bytes_in_use_by_app{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "Bytes in use by app (TCMalloc)"
    },
    {
     "expr": "sum (utils_tcmalloc_sampled_size_by_activity{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "Sampled size (TCMalloc)"
    },
    {
     "expr": "sum (utils_MT_Memory{label=\"Tablet/TSharedData/Buffers\", database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "TSharedData buffers (memory tracker)"
    },
    {
     "expr": "sum(utils_Stats_AllocatedMemory{database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "Allocated memory (memory controller)"
    }
   ]
  },
  {
   "title": "TCMalloc",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (utils_generic_bytes_in_use_by_app{database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "Bytes in use by app"
    },
    {
     "expr": "sum (utils_generic_physical_memory_used{database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "Physical memory used"
    }
   ]
  },
  {
   "title": "Allocators",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (utils_generic_physical_memory_used{database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "TCMalloc (Physical memory used"
    },
    {
     "expr": "sum (utils_GlobalPoolTotalBytes{database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "MiniKQL (GlobalPoolTotalBytes)"
    }
   ]
  },
  {
   "title": "TCMalloc caches",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (utils_tcmalloc_page_heap_free{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "page heap free"
    },
    {
     "expr": "sum (utils_tcmalloc_cpu_free{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "cpu free"
    },
    {
     "expr": "sum (utils_tcmalloc_thread_cache_free{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "thread cache free"
    },
    {
     "expr": "sum (utils_tcmalloc_transfer_cache_free{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "transfer cache free"
    },
    {
     "expr": "sum (utils_tcmalloc_sharded_transfer_cache_free{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "sharded transfer cache free"
    },
    {
     "expr": "sum (utils_tcmalloc_central_cache_free{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "central cache free"
    },
    {
     "expr": "sum (utils_tcmalloc_metadata_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "metadata bytes"
    }
   ]
  },
  {
   "title": "TCMalloc sampled size by activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (activity) (utils_tcmalloc_sampled_size_by_activity{database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "{{activity}}"
    }
   ]
  },
  {
   "title": "TCMalloc sampled size histogram",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (utils_tcmalloc_sampled_size_bucket{database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCMalloc sampled count by activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (activity) (utils_tcmalloc_sampled_count_by_activity{database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "{{activity}}"
    }
   ]
  },
  {
   "title": "TCMalloc sampled count histogram",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (utils_tcmalloc_sampled_count_bucket{database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tablets details",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(tablets_SUM_DbMetaBytes_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "SUM(DbMetaBytes)"
    },
    {
     "expr": "sum(tablets_SUM_DbByKeyBytes_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "SUM(DbByKeyBytes)"
    },
    {
     "expr": "sum(tablets_SUM_DbMemTableBytes_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "SUM(DbMemTableBytes)"
    },
    {
     "expr": "sum(tablets_SUM_DbBTreeIndexBytes_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "Sum(DbBTreeIndexBytes)"
    },
    {
     "expr": "sum(tablets_SUM_DbFlatIndexBytes_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "SUM(DbFlatIndexBytes)"
    },
    {
     "expr": "sum(tablets_SUM_UsedTabletMemory_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "SUM(UsedTabletMemory)"
    },
    {
     "expr": "sum(tablets_SUM_ConsumedMemory_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "SUM(ConsumedMemory)"
    }
   ]
  },
  {
   "title": "Tablets details (followers)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(followers_SUM_DbIndexBytes_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "SUM(DbIndexBytes)"
    },
    {
     "expr": "sum(followers_SUM_DbMetaBytes_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "SUM(DbMetaBytes)"
    },
    {
     "expr": "sum(followers_SUM_DbByKeyBytes_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "SUM(DbByKeyBytes)"
    },
    {
     "expr": "sum(followers_SUM_DbMemTableBytes_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "SUM(DbMemTableBytes)"
    },
    {
     "expr": "sum(followers_SUM_DbBTreeIndexBytes_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "Sum(DbBTreeIndexBytes)"
    },
    {
     "expr": "sum(followers_SUM_DbFlatIndexBytes_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "SUM(DbFlatIndexBytes)"
    },
    {
     "expr": "sum(followers_SUM_UsedTabletMemory_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "SUM(UsedTabletMemory)"
    },
    {
     "expr": "sum(followers_SUM_ConsumedMemory_{database=\"$database\", container=\"ydb-dynamic\", type=\"all\"})",
     "legendFormat": "SUM(ConsumedMemory)"
    }
   ]
  },
  {
   "title": "TSharedData buffers (memory tracker)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (utils_MT_Memory{label=\"Tablet/TSharedData/Buffers\", database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "Tablet/TSharedData/Buffers"
    }
   ]
  },
  { "title": "Shared Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (tablets_ActiveLimitBytes{type=\"S_CACHE\", database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "ActiveLimitBytes"
    },
    {
     "expr": "sum (tablets_MemLimitBytes{type=\"S_CACHE\", database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "MemLimitBytes"
    },
    {
     "expr": "sum (tablets_PassiveBytes{type=\"S_CACHE\", database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "PassiveBytes"
    },
    {
     "expr": "sum (tablets_ActiveBytes{type=\"S_CACHE\", database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "ActiveBytes"
    },
    {
     "expr": "sum(tablets_SUM_CacheTotalExclusive_{type=\"all\", database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "Private cache"
    },
    {
     "expr": "sum(tablets_LoadInFlyBytes{type=\"S_CACHE\", database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "LoadInFlyBytes"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(utils_ElapsedMicrosecByActivity{database=\"$database\",container=\"ydb-dynamic\",activity=\"SAUSAGE_CACHE\"}[$__rate_interval]))/1000000",
     "legendFormat": "SAUSAGE_CACHE"
    }
   ]
  },
  {
   "title": "Transactions Retries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_TxPostponed{type=\"all\", category=\"executor\", database=\"$database\", container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "TxPostponed"
    },
    {
     "expr": "sum(rate(tablets_TxRetried{type=\"all\", category=\"executor\", database=\"$database\", container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "TxRetried"
    },
    {
     "expr": "sum(rate(tablets_TxFinished{type=\"all\", category=\"executor\", database=\"$database\", container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "TxFinished"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_CacheHitBytes{type=\"S_CACHE\", database=\"$database\", container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "SS Cache Hits"
    },
    {
     "expr": "sum(rate(tablets_TxCachedBytes{type=\"all\",database=\"$database\", container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Tablets Cache Hits"
    }
   ]
  },
  {
   "title": "Cache misses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_TxReadBytes{type=\"all\", category=\"executor\", database=\"$database\", container=\"ydb-dynamic\"}[$__rate_interval])) ",
     "legendFormat": "Tablets Cache Misses"
    },
    {
     "expr": "sum(rate(tablets_CacheMissBytes{type=\"S_CACHE\", database=\"$database\", container=\"ydb-dynamic\"}[$__rate_interval])) ",
     "legendFormat": "SS Cache Misses"
    }
   ]
  },
  {
   "title": "In Fly",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(tablets_LoadInFlyBytes{type=\"S_CACHE\", database=\"$database\", container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "InFly"
    }
   ]
  },
  { "title": "Shared Cache Detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (tablets_ActiveBytes{type=\"S_CACHE\", database=\"$database\", container=\"ydb-dynamic\"}) + sum (tablets_PassiveBytes{type=\"S_CACHE\", database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "SS Shared Body"
    },
    {
     "expr": "sum (tablets_SUM_CacheTotalSharedBody_{type=\"all\", category=\"executor\", database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "Tablets Shared Body"
    }
   ]
  },
  {
   "title": "Page Collections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(tablets_SUM_CacheTotalCollections_{type=\"all\", category=\"executor\", database=\"$database\", container=\"ydb-dynamic\"})",
     "legendFormat": "Tablets Collections"
    }
   ]
  },
  {
   "title": "Replacement Policy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(tablets_ReplacementPolicySize_S3FIFO)",
     "legendFormat": "ReplacementPolicySize/S3FIFO"
    }
   ]
  },
  {
   "title": "Touched Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(tablets_TouchedBlocks_bucket{database=\"$database\", category=\"executor\", type=\"all\", container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Memory Controller Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(utils_Stats_OtherConsumption{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Stats/OtherConsumption"
    },
    {
     "expr": "sum(utils_Stats_ExternalConsumption{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Stats/ExternalConsumption"
    },
    {
     "expr": "sum by (name_label) ((label_replace({database=\"$database\", component=\"memory_controller\", __name__=~\"utils_Consumer_.*_Consumption\"}, \"name_label\", \"$1\", \"__name__\", \"utils_Consumer_(.*)_Consumption\")))",
     "legendFormat": "Consumer/{{name_label}}/Consumption"
    },
    { "expression": "$H - $I", "type": "math" },
    {
     "expr": "sum(utils_Consumer_MemTable_Reservation{database=\"$database\",container=\"ydb-dynamic\", component=\"memory_controller\"})",
     "legendFormat": "Consumer/MemTable/Reservation"
    },
    {
     "expr": "sum(utils_Consumer_SharedCache_Reservation{database=\"$database\",container=\"ydb-dynamic\", component=\"memory_controller\"})",
     "legendFormat": "Consumer/SharedCache/Reservation"
    },
    {
     "expr": "sum(utils_Stats_TargetUtilization{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Stats/TargetUtilization"
    },
    {
     "expr": "sum(utils_Stats_HardLimit{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Stats/HardLimit"
    },
    {
     "expr": "sum(utils_Stats_SoftLimit{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Stats/SoftLimit"
    }
   ]
  },
  {
   "title": "Memory Controller Overview",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(utils_Stats_OtherConsumption{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Stats/OtherConsumption"
    },
    {
     "expr": "sum(utils_Stats_ExternalConsumption{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Stats/ExternalConsumption"
    },
    {
     "expr": "sum by (name_label) ((label_replace({database=\"$database\", component=\"memory_controller\", __name__=~\"utils_Consumer_.*_Consumption\"}, \"name_label\", \"$1\", \"__name__\", \"utils_Consumer_(.*)_Consumption\")))",
     "legendFormat": "Consumer/{{name_label}}/Consumption"
    },
    { "expression": "$H - $I", "type": "math" },
    {
     "expr": "sum(utils_Consumer_MemTable_Reservation{database=\"$database\",container=\"ydb-dynamic\", component=\"memory_controller\"})",
     "legendFormat": "Consumer/MemTable/Reservation"
    },
    {
     "expr": "sum(utils_Consumer_SharedCache_Reservation{database=\"$database\",container=\"ydb-dynamic\", component=\"memory_controller\"})",
     "legendFormat": "Consumer/SharedCache/Reservation"
    }
   ]
  },
  {
   "title": "SharedCache Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(utils_Consumer_SharedCache_Consumption{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/SharedCache/Consumption"
    },
    {
     "expr": "sum(utils_Consumer_SharedCache_LimitMin{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/SharedCache/LimitMin"
    },
    {
     "expr": "sum(utils_Consumer_SharedCache_LimitMax{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/SharedCache/LimitMax"
    },
    {
     "expr": "sum(utils_Consumer_SharedCache_Limit{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/SharedCache/Limit"
    }
   ]
  },
  {
   "title": "Activities Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(utils_Stats_ActivitiesLimitBytes{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Stats/ActivitiesLimitBytes"
    },
    {
     "expr": "sum by (queue) (rate(tablets_MemoryConsumption{container=\"ydb-dynamic\", database=\"$database\", queue!=\"total\"}[$__rate_interval]))",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum by (queue) (rate(tablets_MemoryConsumption{container=\"ydb-dynamic\", database=\"$database\", queue=\"total\"}[$__rate_interval]))",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "MemTable Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(utils_Consumer_MemTable_Consumption{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/MemTable/Consumption"
    },
    {
     "expr": "sum(utils_Consumer_MemTable_Total{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/MemTable/Total"
    },
    {
     "expr": "sum(utils_Consumer_MemTable_LimitMin{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/MemTable/LimitMin"
    },
    {
     "expr": "sum(utils_Consumer_MemTable_LimitMax{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/MemTable/LimitMax"
    },
    {
     "expr": "sum(utils_Consumer_MemTable_Limit{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/MemTable/Limit"
    },
    {
     "expr": "sum(utils_Consumer_MemTable_Compacting{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/MemTable/Compacting"
    },
    {
     "expr": "sum(utils_Consumer_MemTable_Compacted{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/MemTable/Compacted"
    }
   ]
  },
  {
   "title": "Compaction Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(utils_Consumer_ColumnTablesCompGroupedMemory_Consumption{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/ColumnTablesCompGroupedMemory/Consumption"
    },
    {
     "expr": "sum(utils_Consumer_ColumnTablesCompGroupedMemory_Limit{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/ColumnTablesCompGroupedMemory/Limit"
    }
   ]
  },
  {
   "title": "QueryExecution Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(utils_Consumer_QueryExecution_Consumption{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/QueryExecution/Consumption"
    },
    {
     "expr": "sum(utils_Consumer_QueryExecution_Limit{component=\"memory_controller\", database=\"$database\"})",
     "legendFormat": "Consumer/QueryExecution/Limit"
    }
   ]
  }
 ]
}