{
 "title": "Topic — Consumer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "database", "query": { "query": "label_values(database)" } },
   { "name": "topic", "query": { "query": "label_values(topic)" } },
   {
    "name": "consumer",
    "query": {
     "query": "label_values({topic=\"$topic\"},consumer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total incoming records (bytes) per second",
   "type": "timeseries",
   "description": "Number of bytes per second written to the topic using `Ydb::TopicService::StreamWrite`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(ydb_topic_write_bytes{database=\"$database\", topic=\"$topic\"}[$__rate_interval:]))",
     "legendFormat": "Write bytes"
    },
    {
     "expr": "sum(rate(ydb_topic_write_discarded_bytes{database=\"$database\", topic=\"$topic\"}[$__rate_interval:]))",
     "legendFormat": "Discarded bytes"
    },
    {
     "expr": "sum(rate(ydb_topic_write_uncommited_bytes{database=\"$database\", topic=\"$topic\"}[$__rate_interval:]))",
     "legendFormat": "Uncommited bytes"
    }
   ]
  },
  {
   "title": "Total outgoing records (bytes) per second",
   "type": "timeseries",
   "description": "Number of bytes per second read from the topic by the consumer using `Ydb::TopicService::StreamRead`",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(ydb_topic_read_bytes{database=\"$database\", topic=\"$topic\", consumer=\"$consumer\"}[$__rate_interval:]))",
     "legendFormat": "Read bytes"
    }
   ]
  },
  {
   "title": "Total incoming records (count) per second",
   "type": "timeseries",
   "description": "Number of messages per second written using `Ydb::TopicService::StreamWrite`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(ydb_topic_write_messages{database=\"$database\", topic=\"$topic\"}[$__rate_interval:]))",
     "legendFormat": "Write messages"
    },
    {
     "expr": "sum(rate(ydb_topic_write_discarded_messages{database=\"$database\", topic=\"$topic\"}[$__rate_interval:]))",
     "legendFormat": "Discarded messages"
    },
    {
     "expr": "sum(rate(ydb_topic_write_uncommited_messages{database=\"$database\", topic=\"$topic\"}[$__rate_interval:]))",
     "legendFormat": "Uncommited messages"
    }
   ]
  },
  {
   "title": "Total outgoing messages per second",
   "type": "timeseries",
   "description": "Number of messages per second read from the topic by the consumer using `Ydb::TopicService::StreamRead`",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(ydb_topic_read_messages{database=\"$database\", topic=\"$topic\", consumer=\"$consumer\"}[$__rate_interval:]))",
     "legendFormat": "Read messages"
    }
   ]
  },
  {
   "title": "End-to-end latency",
   "type": "timeseries",
   "description": "Distribution of the time from message creation to its being read from the topic by the consumer, by time intervals in milliseconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum by (bin) (rate(ydb_topic_read_lag_milliseconds{database=\"$database\", topic=\"$topic\", consumer=\"$consumer\"}[45s:])))",
     "legendFormat": "{{bin}}"
    }
   ]
  },
  {
   "title": "Read latency max",
   "type": "timeseries",
   "description": "The maximum (across all partitions) difference between the current time and the recording time of the last recorded message",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(ydb_topic_partition_read_lag_milliseconds_max{database=\"$database\", topic=\"$topic\", consumer=\"$consumer\"})",
     "legendFormat": "Read latency max"
    }
   ]
  },
  {
   "title": "Unread messages max",
   "type": "timeseries",
   "description": "The maximum difference (across all partitions) of the last offset in the partition and the last subtracted offset",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(ydb_topic_partition_read_lag_messages_max{database=\"$database\", topic=\"$topic\", consumer=\"$consumer\"})",
     "legendFormat": " Unread messages max"
    }
   ]
  },
  {
   "title": "Read idle time max",
   "type": "timeseries",
   "description": "Maximum idle time (how long the topic partition was not read by the consumer) for all partitions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(ydb_topic_partition_read_idle_milliseconds_max{database=\"$database\", topic=\"$topic\", consumer=\"$consumer\"})",
     "legendFormat": " Read idle time max"
    }
   ]
  },
  {
   "title": "Uncommitted messages max",
   "type": "timeseries",
   "description": "The maximum (across all partitions) difference between the last partition offset and the recorded partition offset",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(ydb_topic_partition_committed_lag_messages_max{database=\"$database\", topic=\"$topic\", consumer=\"$consumer\"})",
     "legendFormat": "Ucommitted messages max"
    }
   ]
  },
  {
   "title": "Committed read lag max",
   "type": "timeseries",
   "description": "The maximum (across all partitions) difference between the current time and the recording time of the last recorded message",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(ydb_topic_partition_committed_read_lag_milliseconds_max{database=\"$database\", topic=\"$topic\", consumer=\"$consumer\"})",
     "legendFormat": " Committed read lag max"
    }
   ]
  },
  {
   "title": "Partition sessions started",
   "type": "timeseries",
   "description": "Number of topic read sessions started by the consumer per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ydb_api_grpc_topic_stream_read_partition_session_started{database=\"$database\", topic=\"$topic\", consumer=\"$consumer\"}[30s:])",
     "legendFormat": "Sessions per second"
    }
   ]
  }
 ]
}