{
 "title": "Topic",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "database", "query": { "query": "label_values(database)" } },
   { "name": "topic", "query": { "query": "label_values(topic)" } }
  ]
 },
 "panels": [
  {
   "title": "Total incoming records (bytes) per second",
   "type": "timeseries",
   "description": "Number of bytes per second written to the topic using `Ydb::TopicService::StreamWrite`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(ydb_topic_write_bytes{database=\"$database\", topic=\"$topic\"}[$__rate_interval:]))",
     "legendFormat": "Write bytes"
    },
    {
     "expr": "sum(rate(ydb_topic_write_discarded_bytes{database=\"$database\", topic=\"$topic\"}[$__rate_interval:]))",
     "legendFormat": "Discarded bytes"
    },
    {
     "expr": "sum(rate(ydb_topic_write_uncommited_bytes{database=\"$database\", topic=\"$topic\"}[$__rate_interval:]))",
     "legendFormat": "Uncommited bytes"
    }
   ]
  },
  {
   "title": "Total incoming records (count) per second",
   "type": "timeseries",
   "description": "Number of messages per second written using `Ydb::TopicService::StreamWrite`",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(ydb_topic_write_messages{database=\"$database\", topic=\"$topic\"}[$__rate_interval:]))",
     "legendFormat": "Write messages"
    },
    {
     "expr": "sum(rate(ydb_topic_write_discarded_messages{database=\"$database\", topic=\"$topic\"}[$__rate_interval:]))",
     "legendFormat": "Discarded messages"
    },
    {
     "expr": "sum(rate(ydb_topic_write_uncommited_messages{database=\"$database\", topic=\"$topic\"}[$__rate_interval:]))",
     "legendFormat": "Uncommited messages"
    }
   ]
  },
  {
   "title": "Write latency",
   "type": "timeseries",
   "description": "Distribution of the time from message creation to its being written to the topic, by time intervals in milliseconds",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum by (bin) (rate(ydb_topic_write_lag_milliseconds{database=\"$database\", topic=\"$topic\"}[45s:])))",
     "legendFormat": "{{bin}}"
    }
   ]
  },
  {
   "title": "Partition throttling",
   "type": "timeseries",
   "description": "Distribution of write throttling duration (waiting for quota), by time intervals in milliseconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum by (bin) (rate(ydb_topic_write_partition_throttled_milliseconds{database=\"$database\", topic=\"$topic\"}[45s:])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition quota usage",
   "type": "timeseries",
   "description": "Utilization of the topic partitions’ write quotas",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(ydb_topic_partition_write_throttled_microseconds_max{database=\"$database\", topic=\"$topic\"}/1000000)",
     "legendFormat": "Partition quota usage"
    }
   ]
  },
  {
   "title": "Write sessions active",
   "type": "timeseries",
   "description": "Number of open write sessions to the topic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ydb_api_grpc_topic_stream_write_sessions_active_count{database=\"$database\", topic=\"$topic\"})",
     "legendFormat": "Active sessions"
    }
   ]
  },
  {
   "title": "Write sessions created",
   "type": "timeseries",
   "description": "Number of write sessions to the topic created per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(ydb_api_grpc_topic_stream_write_sessions_created{database=\"$database\", topic=\"$topic\"}[45s:]))",
     "legendFormat": "Sessions per second"
    }
   ]
  }
 ]
}