SET(MRJOB_RESOURCE None)

IF (NOT OPENSOURCE AND NOT BUILD_YQL_FROM_SOURCES AND OS_LINUX)
    INCLUDE(${ARCADIA_ROOT}/yql/resources.inc)
    IF (SANITIZER_TYPE == "address")
        SET(MRJOB_RESOURCE ${MRJOB_RESOURCE_ASAN})
    ELSEIF (SANITIZER_TYPE == "memory")
        SET(MRJOB_RESOURCE ${MRJOB_RESOURCE_MSAN})
    ELSEIF (SANITIZER_TYPE == "thread")
        SET(MRJOB_RESOURCE ${MRJOB_RESOURCE_TSAN})
    ELSEIF (SANITIZER_TYPE == "undefined")
        SET(MRJOB_RESOURCE ${MRJOB_RESOURCE_UBSAN})
    ELSE()
        SET(MRJOB_RESOURCE ${MRJOB_RESOURCE_DEFAULT})
    ENDIF()
ENDIF()

IF (MRJOB_RESOURCE != "None")
    PACKAGE()

    FROM_SANDBOX(FILE ${MRJOB_RESOURCE} RENAME RESOURCE OUT_NOAUTO mrjob)

    END()
ELSE()
    PROGRAM(mrjob)

    INCLUDE(ya.make.inc)

    END()
ENDIF()

RECURSE_FOR_TESTS(
    test
)
