# Generated by devtools/yamaker.

LIBRARY()

WITHOUT_LICENSE_TEXTS()

VERSION(4.15.2)

LICENSE(MIT)

ADDINCL(
    contrib/libs/z3-solver/src
    contrib/libs/z3-solver/src/ast
    contrib/libs/z3-solver/src/ast/converters
    contrib/libs/z3-solver/src/ast/euf
    contrib/libs/z3-solver/src/ast/rewriter
    contrib/libs/z3-solver/src/model
    contrib/libs/z3-solver/src/params
    contrib/libs/z3-solver/src/sat
    contrib/libs/z3-solver/src/sat/smt
    contrib/libs/z3-solver/src/solver
    contrib/libs/z3-solver/src/tactic
    contrib/libs/z3-solver/src/util
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -D_EXTERNAL_RELEASE
    -D_MP_INTERNAL
)

SRCS(
    goal2sat.cpp
    sat2goal.cpp
    sat_tactic.cpp
)

END()
