syntax = "proto3";

package NKikimrBlobStorage;

// Enum defining PDisk underlying drive type (rotational or solid state)
enum EPDiskType {
    ROT = 0; // rotational drives (HDD)
    SSD = 1; // solid state drives (SSD)
    NVME = 2; // PCIe-connected solid state drives (NVMe SSD)
    UNKNOWN_TYPE = 3; // used if device type is unknown or if group consists of different PDisk device types
}

// Virtual group life cycle state
enum EVirtualGroupState {
    NEW = 0; // just created
    CREATE_FAILED = 1; // error while creating VirtualGroup
    WORKING = 2; // operational
    DELETING = 3; // going to delete from Hive
}

message TGroupDecommitStatus {
    enum E {
        NONE = 0; // no decomission
        PENDING = 1; // decommission machinery is starting
        IN_PROGRESS = 2; // decomission underway
        DONE = 3; // group decomission complete
        RECOMMISSIONING = 4; // group is being recommissioned
    }
}

enum EDriveStatus {
    UNKNOWN = 0; // value of status is unknown (default)
    ACTIVE = 1; // working as expected
    INACTIVE = 2; // new groups are not created over this drive, but existing ones continue to work as expected
    BROKEN = 3; // drive is not working, groups are automatically moved out of this drive upon reception of this status
    reserved 4;
    FAULTY = 5; // drive is expected to become BROKEN soon, new groups are not created, old groups are asynchronously moved out from this drive
    TO_BE_REMOVED = 6; // same as INACTIVE, but drive is counted in fault model as not working
}

enum EDecommitStatus {
    DECOMMIT_UNSET = 0; // unset status -- missing optional field
    DECOMMIT_NONE = 1; // no decomission
    DECOMMIT_PENDING = 2; // drive is going to be removed soon, but SelfHeal logic would not remove it automatically
    DECOMMIT_IMMINENT = 3; // drive is going to be settled automatically
    DECOMMIT_REJECTED = 4; // drive is working as usual, but decommitted slots are not placed here
}

// set by CMS
message TMaintenanceStatus {
    enum E {
        NOT_SET = 0;                        // unset status, default value
        NO_REQUEST = 1;                     // no active maintenance request
        LONG_TERM_MAINTENANCE_PLANNED = 2;  // maintenance requested, VDisks should be moved asynchronously from PDisk
        NO_NEW_VDISKS = 3;                  // no new VDisks should be allocated on this PDisk, but existing ones are not moved
    }
}

message TGroupStatus {
    enum E {
        UNKNOWN = 0; // group status is unknown (default value)
        FULL = 1; // all VDisks of the group are READY for specific period of time
        PARTIAL = 2; // some of VDisks are operational, but group is not yet DEGRADED
        DEGRADED = 3; // group is DEGRADED -- one random failure may lead to group loss (but may not lead too)
        DISINTEGRATED = 4; // group is not available for operation
    }
}

message TDriveLifeStage {
    enum E {
        FREE = 0; // disk drive has been seen on a node, but is not added to BSC yet
        ADDED_BY_DSTOOL = 1; // disk drive has been added to BSC
        REMOVED_BY_DSTOOL = 2; // disk drive has been removed from BSC
    }
}

message TSerialManagementStage {
    enum E {
        DISCOVER_SERIAL = 0;
        CHECK_SERIAL = 1;
        ONLY_SERIAL = 2;
    }
}
