PY3TEST()

PEERDIR(
    contrib/python/flex
    contrib/python/pytest-localserver
    contrib/python/factory-boy
    contrib/python/responses
    contrib/python/mock
    contrib/python/falcon
    contrib/python/tornado
)

PY_SRCS(
    NAMESPACE tests
    utils.py
    factories.py
)

TEST_SRCS(
    __init__.py
    cli/__init__.py
    cli/test_command_line_interface.py
    conftest.py
    core/test_decorators.py
    core/test_empty_sentinal.py
    core/test_error_dict.py
    core/test_error_list.py
    core/test_example_schemas.py
    core/test_format_validators.py
    core/test_load_source.py
    core/test_match_request_path_to_api_path.py
    core/test_parameter_utils.py
    core/test_path_utils.py
    core/test_request_response_objects.py
    core/test_utils.py
    core/utils/__init__.py
    core/utils/test_pluralize.py
    decorators/__init__.py
    decorators/test_pull_keys_from_object.py
    decorators/test_skip_if_any_empty.py
    decorators/test_skip_if_empty.py
    http/__init__.py
    http/test_request_data_property.py
    http/test_request_normalization.py
    http/test_response_data_propery.py
    http/test_response_normalization.py
    loading/__init__.py
    loading/common/__init__.py
    loading/common/test_external_docs_validator.py
    loading/common/test_reference_object_validation.py
    loading/definition/__init__.py
    loading/definition/parameters/__init__.py
    loading/definition/parameters/single/__init__.py
    loading/definition/parameters/single/test_collection_format.py
    loading/definition/parameters/single/test_default_validation.py
    loading/definition/parameters/single/test_description_validation.py
    loading/definition/parameters/single/test_in_validation.py
    loading/definition/parameters/single/test_items_validation.py
    loading/definition/parameters/single/test_name_validation.py
    loading/definition/parameters/single/test_type_validation.py
    loading/definition/responses/__init__.py
    loading/definition/responses/headers/__init__.py
    loading/definition/responses/headers/single/__init__.py
    loading/definition/responses/headers/single/test_collection_format_validation.py
    loading/definition/responses/headers/single/test_description_validation.py
    loading/definition/responses/headers/single/test_items_validation.py
    loading/definition/responses/headers/single/test_schema_validation.py
    loading/definition/responses/headers/single/test_type_validation.py
    loading/definition/responses/headers/test_multi_header_validation.py
    loading/definition/responses/single/__init__.py
    loading/definition/responses/single/test_schema_validation.py
    loading/definition/responses/test_responses_validation.py
    loading/definition/schema/__init__.py
    loading/definition/schema/test_default.py
    loading/definition/schema/test_enum.py
    loading/definition/schema/test_format.py
    loading/definition/schema/test_items.py
    loading/definition/schema/test_min_and_max_items.py
    loading/definition/schema/test_min_and_max_length.py
    loading/definition/schema/test_min_and_max_properties.py
    loading/definition/schema/test_minimum_and_maximum_validation.py
    loading/definition/schema/test_multiple_of_validation.py
    loading/definition/schema/test_pattern.py
    loading/definition/schema/test_properties.py
    loading/definition/schema/test_read_only.py
    loading/definition/schema/test_ref.py
    loading/definition/schema/test_required.py
    loading/definition/schema/test_schema_validator.py
    loading/definition/schema/test_title.py
    loading/definition/schema/test_type.py
    loading/definition/schema/test_unique_items.py
    loading/definition/test_parameters_validation.py
    loading/definition/test_reference_validation.py
    loading/schema/__init__.py
    loading/schema/paths/__init__.py
    loading/schema/paths/operation/__init__.py
    loading/schema/paths/operation/responses/__init__.py
    loading/schema/paths/operation/responses/schema/__init__.py
    loading/schema/paths/operation/responses/schema/test_external_docs_validation.py
    loading/schema/paths/operation/responses/schema/test_reference_validation.py
    loading/schema/paths/operation/responses/test_response_validation.py
    loading/schema/paths/operation/responses/test_schema_validation.py
    loading/schema/paths/operation/test_consumes_validation.py
    loading/schema/paths/operation/test_external_docs_validation.py
    loading/schema/paths/operation/test_parameters_validation.py
    loading/schema/paths/operation/test_produces_validation.py
    loading/schema/paths/operation/test_responses_validation.py
    loading/schema/paths/operation/test_tags_validation.py
    loading/schema/paths/test_operation_validation.py
    loading/schema/test_base_path_validation.py
    loading/schema/test_host_validation.py
    loading/schema/test_info_validation.py
    loading/schema/test_mimetype_validation.py
    loading/schema/test_paths_validation.py
    loading/schema/test_produces_and_consumes_validation.py
    loading/schema/test_schemes_validation.py
    loading/schema/test_swagger_validation.py
    test_assertion_utils.py
    validation/api_call/__init__.py
    validation/api_call/test_api_call_validation.py
    validation/headers/__init__.py
    validation/headers/test_header_type_casting.py
    validation/headers/test_response_header_validation.py
    validation/operation/__init__.py
    validation/operation/test_consumes_validation.py
    validation/operation/test_parameter_validation.py
    validation/parameter/__init__.py
    validation/parameter/test_enum_validation.py
    validation/parameter/test_format_validation.py
    validation/parameter/test_items_validation.py
    validation/parameter/test_min_max_items_validation.py
    validation/parameter/test_min_max_length_validation.py
    validation/parameter/test_minimum_and_maximum_validation.py
    validation/parameter/test_multiple_of_validation.py
    validation/parameter/test_parameter_type_casting.py
    validation/parameter/test_path_parameter_extraction.py
    validation/parameter/test_pattern_validation.py
    validation/parameter/test_required_validation.py
    validation/parameter/test_schema_validation.py
    validation/parameter/test_type_validation.py
    validation/parameter/test_unique_items_validation.py
    validation/path/__init__.py
    validation/path/test_validate_path_to_api_path.py
    validation/request/__init__.py
    validation/request/test_request_body_parameter_validation.py
    validation/request/test_request_content_type_validation.py
    validation/request/test_request_header_validation.py
    validation/request/test_request_method_validation.py
    validation/request/test_request_parameter_validation.py
    validation/request/test_request_path_validation.py
    validation/request/test_request_query_parameter_validation.py
    validation/response/__init__.py
    validation/response/test_produces_validation.py
    validation/response/test_response_content_type_validation.py
    validation/response/test_response_header_validation.py
    validation/response/test_response_method_validation.py
    validation/response/test_response_path_validation.py
    validation/response/test_response_reference.py
    validation/response/test_response_status_code_validation.py
    validation/response/test_schema_validation.py
    validation/schema/__init__.py
    validation/schema/test_additional_properties_validation.py
    validation/schema/test_allof_validation.py
    validation/schema/test_anyof_validation.py
    validation/schema/test_enum_validation.py
    validation/schema/test_format_validation.py
    validation/schema/test_items_validation.py
    validation/schema/test_min_and_max_length_validation.py
    validation/schema/test_min_max_items_validation.py
    validation/schema/test_min_max_properties_validation.py
    validation/schema/test_minimum_and_maximum_validation.py
    validation/schema/test_multiple_of_validation.py
    validation/schema/test_pattern_validation.py
    validation/schema/test_properties_validation.py
    validation/schema/test_ref_validation.py
    validation/schema/test_required_validation.py
    validation/schema/test_type_validation.py
    validation/schema/test_unique_items_validation.py
    validation/utils/__init__.py
)

DATA(
    arcadia/contrib/python/flex/tests
)

RESOURCE(
    schemas/cli-test-invalid-schema.yaml            schemas/cli-test-invalid-schema.yaml
    schemas/cli-test-valid-schema.yaml              schemas/cli-test-valid-schema.yaml
    schemas/httpbin.yaml                            schemas/httpbin.yaml
    schemas/polymorphism.yaml                       schemas/polymorphism.yaml
)

NO_LINT()

END()
