# Generated by devtools/yamaker.

PY3_LIBRARY()

LICENSE(Apache-2.0)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(1.18.0)

PEERDIR(
    contrib/libs/onnx
    contrib/libs/onnx/proto
    contrib/libs/pybind11
    contrib/libs/python
    contrib/python/numpy
    contrib/python/typing-extensions
)

IF (USE_VANILLA_PROTOC)
    PEERDIR(
        contrib/libs/protobuf_std
    )
ELSE()
    PEERDIR(
        contrib/libs/protobuf
    )
ENDIF()

ADDINCL(
    contrib/libs/onnx
)

NO_COMPILER_WARNINGS()

NO_LINT()

CFLAGS(
    -DONNX_ML=1
    -DONNX_NAMESPACE=onnx
)

SRCDIR(contrib/libs/onnx/onnx)

SRCS(
    cpp2py_export.cc
)

PY_REGISTER(
    onnx.onnx_cpp2py_export
)

PY_SRCS(
    NAMESPACE onnx
    __init__.py
    _custom_element_types.py
    checker.py
    compose.py
    defs/__init__.py
    external_data_helper.py
    gen_proto.py
    helper.py
    hub.py
    inliner.py
    mapping.py
    model_container.py
    numpy_helper.py
    onnx_cpp2py_export/__init__.pyi
    onnx_cpp2py_export/checker.pyi
    onnx_cpp2py_export/defs.pyi
    onnx_cpp2py_export/inliner.pyi
    onnx_cpp2py_export/parser.pyi
    onnx_cpp2py_export/printer.pyi
    onnx_cpp2py_export/shape_inference.pyi
    onnx_cpp2py_export/version_converter.pyi
    onnx_data_pb.py
    onnx_operators_pb.py
    onnx_pb.py
    parser.py
    printer.py
    serialization.py
    shape_inference.py
    subbyte.py
    utils.py
    version.py
    version_converter.py
)

END()
