items:
- name: Deployment preparation
  href: deployment-preparation.md
- name: Configuration V1
  href: deployment-configuration-v1.md
- name: Configuration V2
  href: deployment-configuration-v2.md
