# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(1.0.2)

LICENSE(MIT)

PEERDIR(
    contrib/python/pytest
    contrib/python/vcrpy
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    pytest_vcr.py
)

RESOURCE_FILES(
    PREFIX contrib/python/pytest-vcr/
    .dist-info/METADATA
    .dist-info/entry_points.txt
    .dist-info/top_level.txt
)

END()
