/// Only edit the `.in` file, as it is the source for autogeneration by CMake

const char * auto_config_build[]
{
    "VERSION_FULL", "ClickHouse 25.3.15.1",
    "VERSION_DESCRIBE", "v25.3.15.1-lts",
    "VERSION_INTEGER", "25003015",
    "SYSTEM", "Linux",
    "VERSION_GITHASH", "84d6b30ad528e77d787ab7a2437406c1e2a5887a",
    "VERSION_REVISION", "54510",
    "BUILD_TYPE", "MinSizeRel",
    "SYSTEM_PROCESSOR", "x86_64",
    "CMAKE_VERSION", "4.1.2",
    "C_COMPILER", "/var/empty/clang-wrapper-19.1.7/bin/clang",
    "C_COMPILER_VERSION", "19.1.7",
    "CXX_COMPILER", "/var/empty/clang-wrapper-19.1.7/bin/clang++",
    "CXX_COMPILER_VERSION", "19.1.7",
    "C_FLAGS", " --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=.=. -falign-functions=32 -mbranches-within-32B-boundaries -ffp-contract=off  -fdiagnostics-absolute-paths -Wframe-larger-than=65536 -Weverything -Wpedantic -Wvla-cxx-extension -Wno-return-type-c-linkage -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-unsafe-buffer-usage -Wno-switch-default -Os -DNDEBUG",
    "CXX_FLAGS", "-fno-integrated-cc1 --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=.=. -falign-functions=32 -mbranches-within-32B-boundaries -ffp-contract=off  -fdiagnostics-absolute-paths -fstrict-vtable-pointers -Wall -Wextra -Wframe-larger-than=65536 -Weverything -Wpedantic -Wvla-cxx-extension -Wno-return-type-c-linkage -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-unsafe-buffer-usage -Wno-switch-default -Os -DNDEBUG",
    "LINK_FLAGS", " --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-x86_64 --ld-path=/var/empty/lld-21.1.2/bin/ld.lld -Wl,--no-export-dynamic -Wl,--gc-sections -Wl,--build-id=sha1 -no-pie -Wl,-no-pie ",
    "BUILD_COMPILE_DEFINITIONS", "",
    "USE_EMBEDDED_COMPILER", "",
    "USE_GLIBC_COMPATIBILITY", "OFF",
    "USE_JEMALLOC", "",
    "USE_ICU", "1",
    "USE_H3", "1",
    "USE_MYSQL", "",
    "USE_RDKAFKA", "",
    "USE_CAPNP", "",
    "USE_BASE64", "1",
    "USE_HDFS", "",
    "USE_SNAPPY", "1",
    "USE_PARQUET", "",
    "USE_PROTOBUF", "",
    "USE_BROTLI", "",
    "USE_SSL", "1",
    "OPENSSL_VERSION", "",
    "OPENSSL_IS_BORING_SSL", "",
    "USE_VECTORSCAN", "",
    "USE_SIMDJSON", "1",
    "USE_GRPC", "",
    "USE_LDAP", "",
    "TZDATA_VERSION", "2024a",
    "USE_KRB5", "",
    "USE_FILELOG", "1",
    "USE_BZIP2", "",
    "USE_AMQPCPP", "",
    "USE_ROCKSDB", "",
    "USE_NURAFT", "",
    "USE_NLP", "",
    "USE_LIBURING", "",
    "USE_SQLITE", "",
    "USE_LIBPQXX", "",
    "USE_AZURE_BLOB_STORAGE", "",
    "USE_AWS_S3", "1",
    "USE_CASSANDRA", "",
    "USE_YAML_CPP", "OFF",
    "USE_SENTRY", "OFF",
    "USE_DATASKETCHES", "",
    "USE_AVRO", "1",
    "USE_ARROW", "",
    "USE_ORC", "",
    "USE_MSGPACK", "1",
    "USE_QPL", "",
    "USE_QATLIB", "",
    "USE_DELTA_KERNEL_RS", "",
    "CLICKHOUSE_CLOUD", "0",
    "GIT_HASH", "",
    "GIT_BRANCH", R"IRjaNsZIL9Yh7FQ4()IRjaNsZIL9Yh7FQ4",
    "GIT_DATE", "",
    "GIT_COMMIT_SUBJECT", R"Gi17KJMlbGCjErEN()Gi17KJMlbGCjErEN",

    nullptr, nullptr
};
