# Generated by devtools/yamaker from nixpkgs 24.05.

LIBRARY()

LICENSE(BSL-1.0)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(1.90.0)

ORIGINAL_SOURCE(https://github.com/boostorg/lockfree/archive/boost-1.90.0.tar.gz)

PEERDIR(
    contrib/restricted/boost/align
    contrib/restricted/boost/assert
    contrib/restricted/boost/atomic
    contrib/restricted/boost/config
    contrib/restricted/boost/core
    contrib/restricted/boost/parameter
    contrib/restricted/boost/predef
    contrib/restricted/boost/static_assert
    contrib/restricted/boost/utility
)

ADDINCL(
    GLOBAL contrib/restricted/boost/lockfree/include
)

NO_COMPILER_WARNINGS()

NO_UTIL()

END()
