---
apiVersion: ydb.tech/v1alpha1
kind: Storage
metadata:
  name: {{ storage_name }}
  namespace: {{ storage_namespace }}
  annotations:
    ydb.tech/node-claim: {{ nodeclaim_name }}.{{ nodeclaim_namespace }}
spec:
  image:
    name: cr.yandex/crpl7ipeu79oseqhcgn2/ydb:23.2.9
    pullPolicy: IfNotPresent
  nodes: 8
  domain: Root
  hostNetwork: true
  dataStore: []
  erasure: block-4-2
  configuration: |
    static_erasure: block-4-2

    # host_configs:
    #   section will be filled automatically if not specified
    #   https://a.yandex-team.ru/arcadia/kikimr/tools/node-claim-operator/controller/controllers/storage/webhooks.py?rev=r12042066#L79  # noqa

    # hosts:
    #   section will be filled automatically if not specified
    #   https://a.yandex-team.ru/arcadia/kikimr/tools/node-claim-operator/controller/controllers/storage/webhooks.py?rev=r12042066#L80  # noqa

    # blob_storage_config:
    #   section will be filled automatically if not specified
    #   https://a.yandex-team.ru/arcadia/kikimr/tools/node-claim-operator/controller/controllers/storage/webhooks.py?rev=r12042066#L81  # noqa

    domains_config:
      domain:
      - name: Root
        storage_pool_types:
        - kind: ssd                     # please double check this field with disk kind on your selected nodes
          pool_config:
            box_id: '1'
            erasure_species: block-4-2
            kind: ssd
            pdisk_filter:
            - property:
              - {type: SSD}             # please double check this field with disk kind on your selected nodes
            vdisk_kind: Default
      state_storage:
      - ring:
          node: [1, 2, 3, 4, 5, 6, 7, 8]
          nto_select: 5
        ssid: 1

    channel_profile_config:
      profile:
        - channel:
            - erasure_species: block-4-2
              pdisk_category: 1
              storage_pool_kind: ssd    # please double check this field with disk kind on your selected nodes
            - erasure_species: block-4-2
              pdisk_category: 1
              storage_pool_kind: ssd    # please double check this field with disk kind on your selected nodes
            - erasure_species: block-4-2
              pdisk_category: 1
              storage_pool_kind: ssd    # please double check this field with disk kind on your selected nodes
          profile_id: 0

    actor_system_config:
      batch_executor: 2
      io_executor: 3
      executor:
      - name: System
        spin_threshold: 0
        threads: 8
        type: BASIC
      - name: User
        spin_threshold: 0
        threads: 14
        type: BASIC
      - name: Batch
        spin_threshold: 0
        threads: 4
        type: BASIC
      - name: IO
        threads: 2
        time_per_mailbox_micro_secs: 100
        type: IO
      - name: IC
        spin_threshold: 10
        threads: 4
        time_per_mailbox_micro_secs: 100
        type: BASIC
      scheduler:
        progress_threshold: 10000
        resolution: 64
        spin_threshold: 0
      service_executor:
      - executor_id: 4
        service_name: Interconnect
      sys_executor: 0
      user_executor: 1

    grpc_config:
      port: 2135

