GO_LIBRARY()
IF (TRUE)
    SRCS(
        atob.go
        atoc.go
        atof.go
        atoi.go
        bytealg.go
        ctoa.go
        decimal.go
        doc.go
        eisel_lemire.go
        ftoa.go
        ftoaryu.go
        isprint.go
        itoa.go
        quote.go
    )
ENDIF()
END()
