# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(3.6.0)

LICENSE(BSD-2-Clause)

PEERDIR(
    contrib/libs/xxhash
)

ADDINCL(
    contrib/libs/xxhash
)

NO_COMPILER_WARNINGS()

NO_LINT()

SRCS(
    _xxhash.c
)

PY_REGISTER(
    xxhash._xxhash
)

PY_SRCS(
    TOP_LEVEL
    xxhash/__init__.py
    xxhash/__init__.pyi
    xxhash/version.py
)

RESOURCE_FILES(
    PREFIX contrib/python/xxhash/
    .dist-info/METADATA
    .dist-info/top_level.txt
    xxhash/py.typed
)

END()

RECURSE_FOR_TESTS(
    tests
)
