# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(2024.8.26)

LICENSE(MIT)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    ordlookup/__init__.py
    ordlookup/oleaut32.py
    ordlookup/ws2_32.py
    ordlookup/wsock32.py
    pefile.py
    peutils.py
)

RESOURCE_FILES(
    PREFIX contrib/python/pefile/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
