# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(68.1)

LICENSE(BSD-3-Clause)

PEERDIR(
    contrib/python/Pillow
    contrib/python/cffi
    contrib/python/cssselect2
    contrib/python/fonttools
    contrib/python/pydyf
    contrib/python/pyphen
    contrib/python/tinycss2
    contrib/python/tinyhtml5
    contrib/python/weasyprint/symbols
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    weasyprint/__init__.py
    weasyprint/__main__.py
    weasyprint/anchors.py
    weasyprint/css/__init__.py
    weasyprint/css/computed_values.py
    weasyprint/css/counters.py
    weasyprint/css/functions.py
    weasyprint/css/media_queries.py
    weasyprint/css/properties.py
    weasyprint/css/targets.py
    weasyprint/css/tokens.py
    weasyprint/css/units.py
    weasyprint/css/validation/__init__.py
    weasyprint/css/validation/descriptors.py
    weasyprint/css/validation/expanders.py
    weasyprint/css/validation/properties.py
    weasyprint/document.py
    weasyprint/draw/__init__.py
    weasyprint/draw/border.py
    weasyprint/draw/color.py
    weasyprint/draw/text.py
    weasyprint/formatting_structure/boxes.py
    weasyprint/formatting_structure/build.py
    weasyprint/html.py
    weasyprint/images.py
    weasyprint/layout/__init__.py
    weasyprint/layout/absolute.py
    weasyprint/layout/background.py
    weasyprint/layout/block.py
    weasyprint/layout/column.py
    weasyprint/layout/flex.py
    weasyprint/layout/float.py
    weasyprint/layout/grid.py
    weasyprint/layout/inline.py
    weasyprint/layout/leader.py
    weasyprint/layout/min_max.py
    weasyprint/layout/page.py
    weasyprint/layout/percent.py
    weasyprint/layout/preferred.py
    weasyprint/layout/replaced.py
    weasyprint/layout/table.py
    weasyprint/logger.py
    weasyprint/matrix.py
    weasyprint/pdf/__init__.py
    weasyprint/pdf/anchors.py
    weasyprint/pdf/debug.py
    weasyprint/pdf/fonts.py
    weasyprint/pdf/metadata.py
    weasyprint/pdf/pdfa.py
    weasyprint/pdf/pdfua.py
    weasyprint/pdf/pdfx.py
    weasyprint/pdf/stream.py
    weasyprint/pdf/tags.py
    weasyprint/stacking.py
    weasyprint/svg/__init__.py
    weasyprint/svg/bounding_box.py
    weasyprint/svg/css.py
    weasyprint/svg/defs.py
    weasyprint/svg/images.py
    weasyprint/svg/path.py
    weasyprint/svg/shapes.py
    weasyprint/svg/text.py
    weasyprint/svg/utils.py
    weasyprint/text/constants.py
    weasyprint/text/ffi.py
    weasyprint/text/fonts.py
    weasyprint/text/line_break.py
    weasyprint/urls.py
)

RESOURCE_FILES(
    PREFIX contrib/python/weasyprint/
    .dist-info/METADATA
    .dist-info/entry_points.txt
    weasyprint/css/html5_ph.css
    weasyprint/css/html5_ua.css
    weasyprint/css/html5_ua_form.css
    weasyprint/pdf/sRGB2014.icc
)

END()

RECURSE(
    symbols
)
