#pragma once

#define HAVE_ARPA_INET_H
#define HAVE_FCNTL_H
#define HAVE_INTTYPES_H
#define HAVE_NETDB_H
#define HAVE_NETINET_IN_H
#define HAVE_PTHREAD_H
#define HAVE_STDINT_H
#define HAVE_SYS_IOCTL_H
#define HAVE_SYS_POLL_H
#define HAVE_SYS_SOCKET_H
#define HAVE_SYS_STAT_H
#define HAVE_SYS_TIME_H
#define HAVE_SYS_UN_H
#define HAVE_UNISTD_H

#define PACKAGE_VERSION "0.10.0-dev"

#define ARITHMETIC_RIGHT_SHIFT 1
#define SIGNED_RIGHT_SHIFT_IS 1
#define USE_STD_THREAD 1
