# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(1.5.1)

LICENSE(MIT)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    widget_tweaks/__init__.py
    widget_tweaks/models.py
    widget_tweaks/templatetags/__init__.py
    widget_tweaks/templatetags/widget_tweaks.py
)

RESOURCE_FILES(
    PREFIX contrib/python/django-widget-tweaks/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
