# Generated by devtools/yamaker from nixpkgs 24.05.

LIBRARY()

LICENSE(
    "(Apache-2.0 OR MIT)" AND
    Apache-2.0 AND
    CC0-1.0 AND
    Public-Domain
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(20190702)

ORIGINAL_SOURCE(https://github.com/P-H-C/phc-winner-argon2/archive/20190702.tar.gz)

ADDINCL(
    contrib/deprecated/argon2/include
    contrib/deprecated/argon2/src
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

CFLAGS(
    -DA2_VISCTL=1
    -Dblake2b=_argon2_blake2b
    -Dblake2b_init=_argon2_blake2b_init
    -Dblake2b_init_key=_argon2_blake2b_init_key
    -Dblake2b_init_param=_argon2_blake2b_init_param
    -Dblake2b_final=_argon2_blake2b_final
    -Dblake2b_update=_argon2_blake2b_update
)

SRCS(
    src/argon2.c
    src/blake2/blake2b.c
    src/core.c
    src/encoding.c
    src/thread.c
)

IF (ARCH_X86_64)
    SRCS(
        src/opt.c
    )
ELSE()
    SRCS(
        src/ref.c
    )
ENDIF()

END()
