#pragma once

#include "curl_config-linux.h"

#undef CURL_CA_BUNDLE
#undef CURL_CA_FALLBACK
#undef CURL_CA_PATH
#undef HAVE_ACCEPT4
#undef HAVE_ALARM
#undef HAVE_ARPA_INET_H
#undef HAVE_ATOMIC
#undef HAVE_BASENAME
#undef HAVE_BROTLI_DECODE_H
#undef HAVE_CLOCK_GETTIME_MONOTONIC
#undef HAVE_CLOCK_GETTIME_MONOTONIC_RAW
#undef HAVE_DECL_FSEEKO
#undef HAVE_DIRENT_H
#undef HAVE_DLFCN_H
#undef HAVE_EVENTFD
#undef HAVE_FCNTL
#undef HAVE_FCNTL_O_NONBLOCK
#undef HAVE_FNMATCH
#undef HAVE_FSEEKO
#undef HAVE_FSETXATTR
#undef HAVE_FSETXATTR_5
#undef HAVE_FTRUNCATE
#undef HAVE_GETADDRINFO_THREADSAFE
#undef HAVE_GETEUID
#undef HAVE_GETHOSTBYNAME_R
#undef HAVE_GETHOSTBYNAME_R_6
#undef HAVE_GETIFADDRS
#undef HAVE_GETPPID
#undef HAVE_GETPWUID
#undef HAVE_GETPWUID_R
#undef HAVE_GETRLIMIT
#undef HAVE_GETTIMEOFDAY
#undef HAVE_GLIBC_STRERROR_R
#undef HAVE_GMTIME_R
#undef HAVE_IFADDRS_H
#undef HAVE_INET_NTOP
#undef HAVE_INTTYPES_H
#undef HAVE_IOCTL_FIONBIO
#undef HAVE_IOCTL_SIOCGIFADDR
#undef HAVE_LIBBROTLIDEC
#undef HAVE_LIBGEN_H
#undef HAVE_LIBSSH2
#undef HAVE_LINUX_TCP_H
#undef HAVE_MEMRCHR
#undef HAVE_MSG_NOSIGNAL
#undef HAVE_NETDB_H
#undef HAVE_NETINET_IN_H
#undef HAVE_NETINET_TCP_H
#undef HAVE_NETINET_UDP_H
#undef HAVE_NET_IF_H
#undef HAVE_OPENDIR
#undef HAVE_PIPE
#undef HAVE_PIPE2
#undef HAVE_POLL
#undef HAVE_POLL_H
#undef HAVE_PWD_H
#undef HAVE_SA_FAMILY_T
#undef HAVE_SCHED_YIELD
#undef HAVE_SENDMMSG
#undef HAVE_SENDMSG
#undef HAVE_SIGACTION
#undef HAVE_SIGINTERRUPT
#undef HAVE_SIGSETJMP
#undef HAVE_SNPRINTF
#undef HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID
#undef HAVE_SOCKETPAIR
#undef HAVE_SSL_SET0_WBIO
#undef HAVE_STDATOMIC_H
#undef HAVE_STDINT_H
#undef HAVE_STDIO_H
#undef HAVE_STRCASECMP
#undef HAVE_STRERROR_R
#undef HAVE_STRINGS_H
#undef HAVE_SUSECONDS_T
#undef HAVE_SYS_IOCTL_H
#undef HAVE_SYS_PARAM_H
#undef HAVE_SYS_POLL_H
#undef HAVE_SYS_RESOURCE_H
#undef HAVE_SYS_SELECT_H
#undef HAVE_SYS_UN_H
#undef HAVE_SYS_XATTR_H
#undef HAVE_TERMIOS_H
#undef HAVE_TERMIO_H
#undef HAVE_UNISTD_H
#undef HAVE_UTIMES
#undef HAVE_UTIME_H
#undef HAVE_WRITABLE_ARGV
#undef HAVE_ZSTD
#undef HAVE_ZSTD_H
#undef LT_OBJDIR
#undef PACKAGE
#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_URL
#undef PACKAGE_VERSION
#undef SIZEOF_CURL_SOCKET_T
#undef USE_LIBSSH2
#undef USE_UNIX_SOCKETS
#undef VERSION

#undef CURL_EXTERN_SYMBOL
#define CURL_EXTERN_SYMBOL

#undef CURL_OS
#define CURL_OS "Windows"

#undef HAVE_CLOSESOCKET
#define HAVE_CLOSESOCKET 1

#undef HAVE_IOCTLSOCKET
#define HAVE_IOCTLSOCKET 1

#undef HAVE_IOCTLSOCKET_FIONBIO
#define HAVE_IOCTLSOCKET_FIONBIO 1

#undef HAVE_IO_H
#define HAVE_IO_H 1

#undef HAVE_SETMODE
#define HAVE_SETMODE 1

#undef HAVE_STRICMP
#define HAVE_STRICMP 1

#undef HAVE_SYS_UTIME_H
#define HAVE_SYS_UTIME_H 1

#undef SIZEOF_OFF_T
#define SIZEOF_OFF_T 4

#undef SIZEOF_TIME_T
#define SIZEOF_TIME_T 8

#undef USE_WIN32_LARGE_FILES
#define USE_WIN32_LARGE_FILES 1

#undef ssize_t
#define ssize_t int64_t
