generic:
  mlock: false

  logging:
    stderr: false

  server:
    http_port: 8788
    https_port: 8789
    ca_cert_file: path/to/ca.crt
    ssl_cert_file: path/to/ssl.crt

  auth:
    token_file: path/to/tokenator_config

    # Optional for federated credentials flow.
    # Requires: access_service_type: "nebius_v1"
    federated_creds:
      k8s_token_path: /var/run/secrets/tokens/k8s-jwt
      token_service_endpoint: "grpcs://token-service.private-api.nebius.cloud:443"
      service_account_id: "ajep..."

  access_service_type: "nebius_v1"

meta:
  meta_api_endpoint: grpc://lb.ydb-ui.ydb.nemax.nebiuscloud.net:2135
  meta_database: /nemax_global/ydb-ui
  meta_database_token_name: "meta-token"
