items:
- name: Обзор
  href: index.md
- name: Первоначальное развёртывание
  href: initial-deployment.md
- name: Подготовка виртуальных машин с Terraform
  href: preparing-vms-with-terraform.md
- name: Перезапуск
  href: restart.md
- name: Обновление конфигурации
  href: update-config.md
- name: Наблюдаемость
  include:
    mode: link
    path: observability/toc_p.yaml