LIBRARY()

LICENSE(BSD-3-Clause)

VERSION(1.0)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

ORIGINAL_SOURCE(https://www.netlib.org/blas/)

NO_COMPILER_WARNINGS()

IF (HAVE_MKL)
    PEERDIR(
        contrib/libs/intel/mkl
    )
ELSE()
    CFLAGS(
        -DADD_
        -DNO_BLAS_WRAP
    )
    PEERDIR(
        ADDINCL contrib/libs/libf2c
    )
    ADDINCL(
        contrib/libs/cblas/include
    )
    SRCS(
        caxpy.c
        ccopy.c
        cdotc.c
        cdotu.c
        cgbmv.c
        cgemm.c
        cgemv.c
        cgerc.c
        cgeru.c
        chbmv.c
        chemm.c
        chemv.c
        cher.c
        cher2.c
        cher2k.c
        cherk.c
        chpmv.c
        chpr.c
        chpr2.c
        crotg.c
        cscal.c
        csrot.c
        csscal.c
        cswap.c
        csymm.c
        csyr2k.c
        csyrk.c
        ctbmv.c
        ctbsv.c
        ctpmv.c
        ctpsv.c
        ctrmm.c
        ctrmv.c
        ctrsm.c
        ctrsv.c
        dasum.c
        daxpy.c
        dcabs1.c
        dcopy.c
        ddot.c
        dgbmv.c
        dgemm.c
        dgemv.c
        dger.c
        dnrm2.c
        drot.c
        drotg.c
        drotm.c
        drotmg.c
        dsbmv.c
        dscal.c
        dsdot.c
        dspmv.c
        dspr.c
        dspr2.c
        dswap.c
        dsymm.c
        dsymv.c
        dsyr.c
        dsyr2.c
        dsyr2k.c
        dsyrk.c
        dtbmv.c
        dtbsv.c
        dtpmv.c
        dtpsv.c
        dtrmm.c
        dtrmv.c
        dtrsm.c
        dtrsv.c
        dzasum.c
        dznrm2.c
        icamax.c
        idamax.c
        isamax.c
        izamax.c
        lsame.c
        sasum.c
        saxpy.c
        scabs1.c
        scasum.c
        scnrm2.c
        scopy.c
        sdot.c
        sdsdot.c
        sgbmv.c
        sgemm.c
        sgemv.c
        sger.c
        snrm2.c
        srot.c
        srotg.c
        srotm.c
        srotmg.c
        ssbmv.c
        sscal.c
        sspmv.c
        sspr.c
        sspr2.c
        sswap.c
        ssymm.c
        ssymv.c
        ssyr.c
        ssyr2.c
        ssyr2k.c
        ssyrk.c
        stbmv.c
        stbsv.c
        stpmv.c
        stpsv.c
        strmm.c
        strmv.c
        strsm.c
        strsv.c
        xerbla.c
        xerbla_array.c
        zaxpy.c
        zcopy.c
        zdotc.c
        zdotu.c
        zdrot.c
        zdscal.c
        zgbmv.c
        zgemm.c
        zgemv.c
        zgerc.c
        zgeru.c
        zhbmv.c
        zhemm.c
        zhemv.c
        zher.c
        zher2.c
        zher2k.c
        zherk.c
        zhpmv.c
        zhpr.c
        zhpr2.c
        zrotg.c
        zscal.c
        zswap.c
        zsymm.c
        zsyr2k.c
        zsyrk.c
        ztbmv.c
        ztbsv.c
        ztpmv.c
        ztpsv.c
        ztrmm.c
        ztrmv.c
        ztrsm.c
        ztrsv.c
        src/cblas_caxpy.c
        src/cblas_ccopy.c
        src/cblas_cdotc_sub.c
        src/cblas_cdotu_sub.c
        src/cblas_cgbmv.c
        src/cblas_cgemm.c
        src/cblas_cgemv.c
        src/cblas_cgerc.c
        src/cblas_cgeru.c
        src/cblas_chbmv.c
        src/cblas_chemm.c
        src/cblas_chemv.c
        src/cblas_cher.c
        src/cblas_cher2.c
        src/cblas_cher2k.c
        src/cblas_cherk.c
        src/cblas_chpmv.c
        src/cblas_chpr.c
        src/cblas_chpr2.c
        src/cblas_cscal.c
        src/cblas_csscal.c
        src/cblas_cswap.c
        src/cblas_csymm.c
        src/cblas_csyr2k.c
        src/cblas_csyrk.c
        src/cblas_ctbmv.c
        src/cblas_ctbsv.c
        src/cblas_ctpmv.c
        src/cblas_ctpsv.c
        src/cblas_ctrmm.c
        src/cblas_ctrmv.c
        src/cblas_ctrsm.c
        src/cblas_ctrsv.c
        src/cblas_dasum.c
        src/cblas_daxpy.c
        src/cblas_dcopy.c
        src/cblas_ddot.c
        src/cblas_dgbmv.c
        src/cblas_dgemm.c
        src/cblas_dgemv.c
        src/cblas_dger.c
        src/cblas_dnrm2.c
        src/cblas_drot.c
        src/cblas_drotg.c
        src/cblas_drotm.c
        src/cblas_drotmg.c
        src/cblas_dsbmv.c
        src/cblas_dscal.c
        src/cblas_dsdot.c
        src/cblas_dspmv.c
        src/cblas_dspr.c
        src/cblas_dspr2.c
        src/cblas_dswap.c
        src/cblas_dsymm.c
        src/cblas_dsymv.c
        src/cblas_dsyr.c
        src/cblas_dsyr2.c
        src/cblas_dsyr2k.c
        src/cblas_dsyrk.c
        src/cblas_dtbmv.c
        src/cblas_dtbsv.c
        src/cblas_dtpmv.c
        src/cblas_dtpsv.c
        src/cblas_dtrmm.c
        src/cblas_dtrmv.c
        src/cblas_dtrsm.c
        src/cblas_dtrsv.c
        src/cblas_dzasum.c
        src/cblas_dznrm2.c
        src/cblas_globals.c
        src/cblas_icamax.c
        src/cblas_idamax.c
        src/cblas_isamax.c
        src/cblas_izamax.c
        src/cblas_sasum.c
        src/cblas_saxpy.c
        src/cblas_scasum.c
        src/cblas_scnrm2.c
        src/cblas_scopy.c
        src/cblas_sdot.c
        src/cblas_sdsdot.c
        src/cblas_sgbmv.c
        src/cblas_sgemm.c
        src/cblas_sgemv.c
        src/cblas_sger.c
        src/cblas_snrm2.c
        src/cblas_srot.c
        src/cblas_srotg.c
        src/cblas_srotm.c
        src/cblas_srotmg.c
        src/cblas_ssbmv.c
        src/cblas_sscal.c
        src/cblas_sspmv.c
        src/cblas_sspr.c
        src/cblas_sspr2.c
        src/cblas_sswap.c
        src/cblas_ssymm.c
        src/cblas_ssymv.c
        src/cblas_ssyr.c
        src/cblas_ssyr2.c
        src/cblas_ssyr2k.c
        src/cblas_ssyrk.c
        src/cblas_stbmv.c
        src/cblas_stbsv.c
        src/cblas_stpmv.c
        src/cblas_stpsv.c
        src/cblas_strmm.c
        src/cblas_strmv.c
        src/cblas_strsm.c
        src/cblas_strsv.c
        src/cblas_xerbla.c
        src/cblas_zaxpy.c
        src/cblas_zcopy.c
        src/cblas_zdotc_sub.c
        src/cblas_zdotu_sub.c
        src/cblas_zdscal.c
        src/cblas_zgbmv.c
        src/cblas_zgemm.c
        src/cblas_zgemv.c
        src/cblas_zgerc.c
        src/cblas_zgeru.c
        src/cblas_zhbmv.c
        src/cblas_zhemm.c
        src/cblas_zhemv.c
        src/cblas_zher.c
        src/cblas_zher2.c
        src/cblas_zher2k.c
        src/cblas_zherk.c
        src/cblas_zhpmv.c
        src/cblas_zhpr.c
        src/cblas_zhpr2.c
        src/cblas_zscal.c
        src/cblas_zswap.c
        src/cblas_zsymm.c
        src/cblas_zsyr2k.c
        src/cblas_zsyrk.c
        src/cblas_ztbmv.c
        src/cblas_ztbsv.c
        src/cblas_ztpmv.c
        src/cblas_ztpsv.c
        src/cblas_ztrmm.c
        src/cblas_ztrmv.c
        src/cblas_ztrsm.c
        src/cblas_ztrsv.c
        src/cdotcsub.c
        src/cdotusub.c
        src/dasumsub.c
        src/ddotsub.c
        src/dnrm2sub.c
        src/dsdotsub.c
        src/dzasumsub.c
        src/dznrm2sub.c
        src/icamaxsub.c
        src/idamaxsub.c
        src/isamaxsub.c
        src/izamaxsub.c
        src/sasumsub.c
        src/scasumsub.c
        src/scnrm2sub.c
        src/sdotsub.c
        src/sdsdotsub.c
        src/snrm2sub.c
        src/xerbla.c
        src/zdotcsub.c
        src/zdotusub.c
    )
ENDIF()

END()
