# Generated by devtools/yamaker (pypi).

PY2_LIBRARY()

VERSION(0.8.10)

LICENSE(MIT)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    tabulate.py
)

RESOURCE_FILES(
    PREFIX contrib/python/tabulate/py2/
    .dist-info/METADATA
    .dist-info/entry_points.txt
    .dist-info/top_level.txt
)

END()
