# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(1.4.0)

LICENSE(MIT)

PEERDIR(
    contrib/python/beautifulsoup4
    contrib/python/requests
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    wikipedia/__init__.py
    wikipedia/exceptions.py
    wikipedia/util.py
    wikipedia/wikipedia.py
)

RESOURCE_FILES(
    PREFIX contrib/python/wikipedia/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
