# Generated by devtools/yamaker (pypi).

PY2_LIBRARY()

SUBSCRIBER(g:python-contrib)

VERSION(1.5)

LICENSE(MIT)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    blinker/__init__.py
    blinker/_saferef.py
    blinker/_utilities.py
    blinker/base.py
)

RESOURCE_FILES(
    PREFIX contrib/python/blinker/py2/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
