# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

SUBSCRIBER(g:cpp-contrib)

VERSION(20.1.4)

PEERDIR(
    contrib/libs/llvm20
    contrib/libs/llvm20/lib/Support
)

ADDINCL(
    contrib/libs/llvm20/lib/TableGen
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    DetailedRecordsBackend.cpp
    Error.cpp
    JSONBackend.cpp
    Main.cpp
    Parser.cpp
    Record.cpp
    SetTheory.cpp
    StringMatcher.cpp
    TGLexer.cpp
    TGParser.cpp
    TGTimer.cpp
    TableGenBackend.cpp
    TableGenBackendSkeleton.cpp
)

END()
