# Generated by devtools/yamaker from nixpkgs 24.05.

LIBRARY()

LICENSE(
    BSL-1.0 AND
    Public-Domain
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(2.3.2)

ORIGINAL_SOURCE(https://github.com/apolukhin/pfr_non_boost/archive/2.3.2.tar.gz)

ADDINCL(
    GLOBAL contrib/libs/pfr/include
)

END()
