PY3_LIBRARY()

PY_SRCS(
    __init__.py
    actors_core.py
    cli.py
    cluster_templates.py
    cluster_templates_ui.py
    common.py
    config.py
    distributed_sessions.py
    distributed_plan.py
    distributed_builder_ui.py
    distributed_worker.py
    distributed_workload.py
    distributed_artifacts.py
    distributed_runtime.py
    distributed_telemetry.py
    distributed_reports.py
    distributed_coordinator.py
    import_results.py
    hosts.py
    federation.py
    load_control.py
    local_ydb.py
    local_ydb_workloads.py
    linux_telemetry.py
    ydb_telemetry.py
    runner.py
    process_recovery.py
    results.py
    run_index.py
    system_info.py
    topology.py
    web.py
)

PEERDIR(
    contrib/python/grpcio
    contrib/python/PyYAML
    ydb/core/protos
    ydb/public/api/grpc
    ydb/public/api/protos
    ydb/tools/ydb_bench/benchmarks
)

END()
