PY3TEST()

SIZE(MEDIUM)

FORK_TESTS()

PEERDIR(
    contrib/python/networkx
    contrib/python/numpy
    contrib/python/scipy
    contrib/python/sympy
    contrib/python/pandas
    contrib/python/matplotlib
    contrib/python/lxml
)

NO_LINT()

SRCDIR(contrib/python/networkx/py3)

PY_SRCS(
    TOP_LEVEL
    networkx/classes/tests/dispatch_interface.py
)

TEST_SRCS(
    networkx/algorithms/approximation/tests/__init__.py
    networkx/algorithms/approximation/tests/test_approx_clust_coeff.py
    networkx/algorithms/approximation/tests/test_clique.py
    networkx/algorithms/approximation/tests/test_connectivity.py
    networkx/algorithms/approximation/tests/test_distance_measures.py
    networkx/algorithms/approximation/tests/test_dominating_set.py
    networkx/algorithms/approximation/tests/test_kcomponents.py
    networkx/algorithms/approximation/tests/test_matching.py
    networkx/algorithms/approximation/tests/test_maxcut.py
    networkx/algorithms/approximation/tests/test_ramsey.py
    networkx/algorithms/approximation/tests/test_steinertree.py
    networkx/algorithms/approximation/tests/test_traveling_salesman.py
    networkx/algorithms/approximation/tests/test_treewidth.py
    networkx/algorithms/approximation/tests/test_vertex_cover.py
    networkx/algorithms/assortativity/tests/__init__.py
    networkx/algorithms/assortativity/tests/base_test.py
    networkx/algorithms/assortativity/tests/test_connectivity.py
    networkx/algorithms/assortativity/tests/test_correlation.py
    networkx/algorithms/assortativity/tests/test_mixing.py
    networkx/algorithms/assortativity/tests/test_neighbor_degree.py
    networkx/algorithms/assortativity/tests/test_pairs.py
    networkx/algorithms/bipartite/tests/__init__.py
    networkx/algorithms/bipartite/tests/test_basic.py
    networkx/algorithms/bipartite/tests/test_centrality.py
    networkx/algorithms/bipartite/tests/test_cluster.py
    networkx/algorithms/bipartite/tests/test_covering.py
    networkx/algorithms/bipartite/tests/test_edgelist.py
    networkx/algorithms/bipartite/tests/test_extendability.py
    networkx/algorithms/bipartite/tests/test_generators.py
    networkx/algorithms/bipartite/tests/test_matching.py
    networkx/algorithms/bipartite/tests/test_matrix.py
    networkx/algorithms/bipartite/tests/test_project.py
    networkx/algorithms/bipartite/tests/test_redundancy.py
    networkx/algorithms/bipartite/tests/test_spectral_bipartivity.py
    networkx/algorithms/centrality/tests/__init__.py
    networkx/algorithms/centrality/tests/test_betweenness_centrality.py
    networkx/algorithms/centrality/tests/test_betweenness_centrality_subset.py
    networkx/algorithms/centrality/tests/test_closeness_centrality.py
    networkx/algorithms/centrality/tests/test_current_flow_betweenness_centrality.py
    networkx/algorithms/centrality/tests/test_current_flow_betweenness_centrality_subset.py
    networkx/algorithms/centrality/tests/test_current_flow_closeness.py
    networkx/algorithms/centrality/tests/test_degree_centrality.py
    networkx/algorithms/centrality/tests/test_dispersion.py
    networkx/algorithms/centrality/tests/test_eigenvector_centrality.py
    networkx/algorithms/centrality/tests/test_group.py
    networkx/algorithms/centrality/tests/test_harmonic_centrality.py
    networkx/algorithms/centrality/tests/test_katz_centrality.py
    networkx/algorithms/centrality/tests/test_laplacian_centrality.py
    networkx/algorithms/centrality/tests/test_load_centrality.py
    networkx/algorithms/centrality/tests/test_percolation_centrality.py
    networkx/algorithms/centrality/tests/test_reaching.py
    networkx/algorithms/centrality/tests/test_second_order_centrality.py
    networkx/algorithms/centrality/tests/test_subgraph.py
    networkx/algorithms/centrality/tests/test_trophic.py
    networkx/algorithms/centrality/tests/test_voterank.py
    networkx/algorithms/coloring/tests/__init__.py
    networkx/algorithms/coloring/tests/test_coloring.py
    networkx/algorithms/community/tests/__init__.py
    networkx/algorithms/community/tests/test_asyn_fluid.py
    networkx/algorithms/community/tests/test_centrality.py
    networkx/algorithms/community/tests/test_divisive.py
    networkx/algorithms/community/tests/test_kclique.py
    networkx/algorithms/community/tests/test_kernighan_lin.py
    networkx/algorithms/community/tests/test_label_propagation.py
    networkx/algorithms/community/tests/test_louvain.py
    networkx/algorithms/community/tests/test_lukes.py
    networkx/algorithms/community/tests/test_modularity_max.py
    networkx/algorithms/community/tests/test_quality.py
    networkx/algorithms/community/tests/test_utils.py
    networkx/algorithms/components/tests/__init__.py
    networkx/algorithms/components/tests/test_attracting.py
    networkx/algorithms/components/tests/test_biconnected.py
    networkx/algorithms/components/tests/test_connected.py
    networkx/algorithms/components/tests/test_semiconnected.py
    networkx/algorithms/components/tests/test_strongly_connected.py
    networkx/algorithms/components/tests/test_weakly_connected.py
    networkx/algorithms/connectivity/tests/__init__.py
    networkx/algorithms/connectivity/tests/test_connectivity.py
    networkx/algorithms/connectivity/tests/test_cuts.py
    networkx/algorithms/connectivity/tests/test_disjoint_paths.py
    networkx/algorithms/connectivity/tests/test_edge_augmentation.py
    networkx/algorithms/connectivity/tests/test_edge_kcomponents.py
    networkx/algorithms/connectivity/tests/test_kcomponents.py
    networkx/algorithms/connectivity/tests/test_kcutsets.py
    networkx/algorithms/connectivity/tests/test_stoer_wagner.py
    networkx/algorithms/flow/tests/__init__.py
    networkx/algorithms/flow/tests/test_gomory_hu.py
    networkx/algorithms/flow/tests/test_maxflow.py
    networkx/algorithms/flow/tests/test_maxflow_large_graph.py
    networkx/algorithms/flow/tests/test_mincost.py
    networkx/algorithms/flow/tests/test_networksimplex.py
    networkx/algorithms/isomorphism/tests/__init__.py
    networkx/algorithms/isomorphism/tests/test_ismags.py
    networkx/algorithms/isomorphism/tests/test_isomorphism.py
    networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
    networkx/algorithms/isomorphism/tests/test_match_helpers.py
    networkx/algorithms/isomorphism/tests/test_temporalisomorphvf2.py
    networkx/algorithms/isomorphism/tests/test_tree_isomorphism.py
    networkx/algorithms/isomorphism/tests/test_vf2pp.py
    networkx/algorithms/isomorphism/tests/test_vf2pp_helpers.py
    networkx/algorithms/isomorphism/tests/test_vf2userfunc.py
    networkx/algorithms/link_analysis/tests/__init__.py
    networkx/algorithms/link_analysis/tests/test_hits.py
    networkx/algorithms/link_analysis/tests/test_pagerank.py
    networkx/algorithms/minors/tests/test_contraction.py
    networkx/algorithms/operators/tests/__init__.py
    networkx/algorithms/operators/tests/test_all.py
    networkx/algorithms/operators/tests/test_binary.py
    networkx/algorithms/operators/tests/test_product.py
    networkx/algorithms/operators/tests/test_unary.py
    networkx/algorithms/shortest_paths/tests/__init__.py
    networkx/algorithms/shortest_paths/tests/test_astar.py
    networkx/algorithms/shortest_paths/tests/test_dense.py
    networkx/algorithms/shortest_paths/tests/test_dense_numpy.py
    networkx/algorithms/shortest_paths/tests/test_generic.py
    networkx/algorithms/shortest_paths/tests/test_unweighted.py
    networkx/algorithms/shortest_paths/tests/test_weighted.py
    networkx/algorithms/tests/__init__.py
    networkx/algorithms/tests/test_asteroidal.py
    networkx/algorithms/tests/test_boundary.py
    networkx/algorithms/tests/test_bridges.py
    networkx/algorithms/tests/test_broadcasting.py
    networkx/algorithms/tests/test_chains.py
    networkx/algorithms/tests/test_chordal.py
    networkx/algorithms/tests/test_clique.py
    networkx/algorithms/tests/test_cluster.py
    networkx/algorithms/tests/test_communicability.py
    networkx/algorithms/tests/test_core.py
    networkx/algorithms/tests/test_covering.py
    networkx/algorithms/tests/test_cuts.py
    networkx/algorithms/tests/test_cycles.py
    networkx/algorithms/tests/test_d_separation.py
    networkx/algorithms/tests/test_dag.py
    networkx/algorithms/tests/test_distance_measures.py
    networkx/algorithms/tests/test_distance_regular.py
    networkx/algorithms/tests/test_dominance.py
    networkx/algorithms/tests/test_dominating.py
    networkx/algorithms/tests/test_efficiency.py
    networkx/algorithms/tests/test_euler.py
    networkx/algorithms/tests/test_graph_hashing.py
    networkx/algorithms/tests/test_graphical.py
    networkx/algorithms/tests/test_hierarchy.py
    networkx/algorithms/tests/test_hybrid.py
    networkx/algorithms/tests/test_isolate.py
    networkx/algorithms/tests/test_link_prediction.py
    networkx/algorithms/tests/test_lowest_common_ancestors.py
    networkx/algorithms/tests/test_matching.py
    networkx/algorithms/tests/test_max_weight_clique.py
    networkx/algorithms/tests/test_mis.py
    networkx/algorithms/tests/test_moral.py
    networkx/algorithms/tests/test_node_classification.py
    networkx/algorithms/tests/test_non_randomness.py
    networkx/algorithms/tests/test_planar_drawing.py
    networkx/algorithms/tests/test_planarity.py
    networkx/algorithms/tests/test_polynomials.py
    networkx/algorithms/tests/test_reciprocity.py
    networkx/algorithms/tests/test_regular.py
    networkx/algorithms/tests/test_richclub.py
    networkx/algorithms/tests/test_similarity.py
    networkx/algorithms/tests/test_simple_paths.py
    networkx/algorithms/tests/test_smallworld.py
    networkx/algorithms/tests/test_smetric.py
    networkx/algorithms/tests/test_sparsifiers.py
    networkx/algorithms/tests/test_structuralholes.py
    networkx/algorithms/tests/test_summarization.py
    networkx/algorithms/tests/test_swap.py
    networkx/algorithms/tests/test_threshold.py
    networkx/algorithms/tests/test_time_dependent.py
    networkx/algorithms/tests/test_tournament.py
    networkx/algorithms/tests/test_triads.py
    networkx/algorithms/tests/test_vitality.py
    networkx/algorithms/tests/test_voronoi.py
    networkx/algorithms/tests/test_walks.py
    networkx/algorithms/tests/test_wiener.py
    networkx/algorithms/traversal/tests/__init__.py
    networkx/algorithms/traversal/tests/test_beamsearch.py
    networkx/algorithms/traversal/tests/test_bfs.py
    networkx/algorithms/traversal/tests/test_dfs.py
    networkx/algorithms/traversal/tests/test_edgebfs.py
    networkx/algorithms/traversal/tests/test_edgedfs.py
    networkx/algorithms/tree/tests/__init__.py
    networkx/algorithms/tree/tests/test_branchings.py
    networkx/algorithms/tree/tests/test_coding.py
    networkx/algorithms/tree/tests/test_decomposition.py
    networkx/algorithms/tree/tests/test_mst.py
    networkx/algorithms/tree/tests/test_operations.py
    networkx/algorithms/tree/tests/test_recognition.py
    networkx/classes/tests/__init__.py
    networkx/classes/tests/historical_tests.py
    networkx/classes/tests/test_coreviews.py
    networkx/classes/tests/test_digraph.py
    networkx/classes/tests/test_digraph_historical.py
    networkx/classes/tests/test_filters.py
    networkx/classes/tests/test_function.py
    networkx/classes/tests/test_graph.py
    networkx/classes/tests/test_graph_historical.py
    networkx/classes/tests/test_graphviews.py
    networkx/classes/tests/test_multidigraph.py
    networkx/classes/tests/test_multigraph.py
    networkx/classes/tests/test_reportviews.py
    networkx/classes/tests/test_special.py
    networkx/classes/tests/test_subgraphviews.py
    networkx/conftest.py
    networkx/drawing/tests/__init__.py
    networkx/drawing/tests/test_agraph.py
    networkx/drawing/tests/test_latex.py
    networkx/drawing/tests/test_layout.py
    networkx/drawing/tests/test_pydot.py
    networkx/drawing/tests/test_pylab.py
    networkx/generators/tests/__init__.py
    networkx/generators/tests/test_atlas.py
    networkx/generators/tests/test_classic.py
    networkx/generators/tests/test_cographs.py
    networkx/generators/tests/test_community.py
    networkx/generators/tests/test_degree_seq.py
    networkx/generators/tests/test_directed.py
    networkx/generators/tests/test_duplication.py
    networkx/generators/tests/test_ego.py
    networkx/generators/tests/test_expanders.py
    networkx/generators/tests/test_geometric.py
    networkx/generators/tests/test_harary_graph.py
    networkx/generators/tests/test_internet_as_graphs.py
    networkx/generators/tests/test_intersection.py
    networkx/generators/tests/test_interval_graph.py
    networkx/generators/tests/test_joint_degree_seq.py
    networkx/generators/tests/test_lattice.py
    networkx/generators/tests/test_line.py
    networkx/generators/tests/test_mycielski.py
    networkx/generators/tests/test_nonisomorphic_trees.py
    networkx/generators/tests/test_random_clustered.py
    networkx/generators/tests/test_random_graphs.py
    networkx/generators/tests/test_small.py
    networkx/generators/tests/test_spectral_graph_forge.py
    networkx/generators/tests/test_stochastic.py
    networkx/generators/tests/test_sudoku.py
    networkx/generators/tests/test_time_series.py
    networkx/generators/tests/test_trees.py
    networkx/generators/tests/test_triads.py
    networkx/linalg/tests/__init__.py
    networkx/linalg/tests/test_algebraic_connectivity.py
    networkx/linalg/tests/test_attrmatrix.py
    networkx/linalg/tests/test_bethehessian.py
    networkx/linalg/tests/test_graphmatrix.py
    networkx/linalg/tests/test_laplacian.py
    networkx/linalg/tests/test_modularity.py
    networkx/linalg/tests/test_spectrum.py
    networkx/readwrite/json_graph/tests/__init__.py
    networkx/readwrite/json_graph/tests/test_adjacency.py
    networkx/readwrite/json_graph/tests/test_cytoscape.py
    networkx/readwrite/json_graph/tests/test_node_link.py
    networkx/readwrite/json_graph/tests/test_tree.py
    networkx/readwrite/tests/__init__.py
    networkx/readwrite/tests/test_adjlist.py
    networkx/readwrite/tests/test_edgelist.py
    networkx/readwrite/tests/test_gexf.py
    networkx/readwrite/tests/test_gml.py
    networkx/readwrite/tests/test_graph6.py
    networkx/readwrite/tests/test_graphml.py
    networkx/readwrite/tests/test_leda.py
    networkx/readwrite/tests/test_p2g.py
    networkx/readwrite/tests/test_pajek.py
    networkx/readwrite/tests/test_sparse6.py
    networkx/readwrite/tests/test_text.py
    networkx/tests/__init__.py
    networkx/tests/test_all_random_functions.py
    networkx/tests/test_convert.py
    networkx/tests/test_convert_numpy.py
    networkx/tests/test_convert_pandas.py
    networkx/tests/test_convert_scipy.py
    networkx/tests/test_exceptions.py
    networkx/tests/test_import.py
    networkx/tests/test_lazy_imports.py
    networkx/tests/test_relabel.py
    networkx/utils/tests/__init__.py
    networkx/utils/tests/test__init.py
    networkx/utils/tests/test_backends.py
    networkx/utils/tests/test_config.py
    networkx/utils/tests/test_decorators.py
    networkx/utils/tests/test_heaps.py
    networkx/utils/tests/test_mapped_queue.py
    networkx/utils/tests/test_misc.py
    networkx/utils/tests/test_random_sequence.py
    networkx/utils/tests/test_rcm.py
    networkx/utils/tests/test_unionfind.py
)

RESOURCE_FILES(
    PREFIX contrib/python/networkx/py3/
    networkx/algorithms/flow/tests/gl1.gpickle.bz2
    networkx/algorithms/flow/tests/gw1.gpickle.bz2
    networkx/algorithms/flow/tests/netgen-2.gpickle.bz2
    networkx/algorithms/flow/tests/wlm3.gpickle.bz2
    networkx/algorithms/isomorphism/tests/iso_r01_s80.A99
    networkx/algorithms/isomorphism/tests/iso_r01_s80.B99
    networkx/algorithms/isomorphism/tests/si2_b06_m200.A99
    networkx/algorithms/isomorphism/tests/si2_b06_m200.B99
    networkx/drawing/tests/baseline/test_house_with_colors.png
)

END()
