
if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
  set(YASM_FLAGS -f elf64 -D UNIX -D _x86_64_ -D_YASM_ -g dwarf2)
  set(RAGEL_FLAGS -L -I ${YDB_SDK_SOURCE_DIR}/)
endif()

if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
  set(RAGEL_FLAGS -L -I ${YDB_SDK_SOURCE_DIR}/)
endif()

if(CMAKE_SYSTEM_NAME STREQUAL "Darwin" AND CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
  set(YASM_FLAGS -f macho64 -D DARWIN -D UNIX -D _x86_64_ -D_YASM_)
  set(RAGEL_FLAGS -L -I ${YDB_SDK_SOURCE_DIR}/)
endif()

if(CMAKE_SYSTEM_NAME STREQUAL "Darwin" AND CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64")
  set(RAGEL_FLAGS -L -I ${YDB_SDK_SOURCE_DIR}/)
endif()

if(WIN32 AND CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64")
  set(YASM_FLAGS -f win64 -D WIN64 -D _x86_64_ -D_YASM_)
  set(RAGEL_FLAGS -L -I ${YDB_SDK_SOURCE_DIR}/)
endif()

