name: Release documentation

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: diplodoc-platform/docs-release-action@v1
        with:
          revision: "${{ github.sha }}"
          project-name: ${{ secrets.DOCS_PROJECT_NAME }}
          src-root: ${{ vars.SRC_ROOT }}
          storage-bucket: ${{ secrets.DOCS_AWS_BUCKET }}
          storage-endpoint: ${{ vars.DOCS_AWS_ENDPOINT }}
          storage-access-key-id: ${{ secrets.DOCS_AWS_KEY_ID }}
          storage-secret-access-key: ${{ secrets.DOCS_AWS_SECRET_ACCESS_KEY }}
          storage-region: ${{ vars.DOCS_AWS_REGION }}
          shared-storage-bucket: true
