PY3_LIBRARY()

VERSION(86.0.4240.5)

LICENSE(BSD-3-Clause)

PEERDIR(
    contrib/python/six
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    grit/__init__.py
    grit/clique.py
    grit/constants.py
    grit/exception.py
    grit/extern/__init__.py
    grit/extern/BogoFP.py
    grit/extern/FP.py
    grit/extern/tclib.py
    grit/format/__init__.py
    grit/format/android_xml.py
    grit/format/c_format.py
    grit/format/chrome_messages_json.py
    grit/format/data_pack.py
    grit/format/gen_predetermined_ids.py
    grit/format/gzip_string.py
    grit/format/html_inline.py
    grit/format/minifier.py
    grit/format/policy_templates_json.py
    grit/format/rc.py
    grit/format/rc_header.py
    grit/format/resource_map.py
    grit/gather/__init__.py
    grit/gather/admin_template.py
    grit/gather/chrome_html.py
    grit/gather/chrome_scaled_image.py
    grit/gather/chrome_scaled_image_exceptions.py
    grit/gather/interface.py
    grit/gather/json_loader.py
    grit/gather/policy_json.py
    grit/gather/rc.py
    grit/gather/regexp.py
    grit/gather/skeleton_gatherer.py
    grit/gather/tr_html.py
    grit/gather/txt.py
    grit/grd_reader.py
    grit/grit_runner.py
    grit/lazy_re.py
    grit/node/__init__.py
    grit/node/base.py
    grit/node/brotli_util.py
    grit/node/empty.py
    grit/node/include.py
    grit/node/mapping.py
    grit/node/message.py
    grit/node/misc.py
    grit/node/mock_brotli.py
    grit/node/node_io.py
    grit/node/structure.py
    grit/node/variant.py
    grit/pseudo.py
    grit/pseudo_rtl.py
    grit/shortcuts.py
    grit/tclib.py
    grit/tool/__init__.py
    grit/tool/android2grd.py
    grit/tool/build.py
    grit/tool/buildinfo.py
    grit/tool/count.py
    grit/tool/diff_structures.py
    grit/tool/interface.py
    grit/tool/menu_from_parts.py
    grit/tool/newgrd.py
    grit/tool/postprocess_interface.py
    grit/tool/preprocess_interface.py
    grit/tool/rc2grd.py
    grit/tool/resize.py
    grit/tool/test.py
    grit/tool/transl2tc.py
    grit/tool/unit.py
    grit/tool/xmb.py
    grit/util.py
    grit/xtb_reader.py
)

END()

RECURSE_FOR_TESTS(
    tests
)