# Generated by devtools/yamaker from nixpkgs 22.05.

LIBRARY()

LICENSE(
    BSL-1.0 AND
    GPL-1.0-or-later
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

OWNER(
    g:cpp-contrib
    g:taxi-common
)

VERSION(1.81.0)

ORIGINAL_SOURCE(https://github.com/boostorg/assign/archive/boost-1.81.0.tar.gz)

PEERDIR(
    contrib/restricted/boost/array
    contrib/restricted/boost/config
    contrib/restricted/boost/core
    contrib/restricted/boost/move
    contrib/restricted/boost/mpl
    contrib/restricted/boost/preprocessor
    contrib/restricted/boost/ptr_container
    contrib/restricted/boost/range
    contrib/restricted/boost/static_assert
    contrib/restricted/boost/throw_exception
    contrib/restricted/boost/tuple
    contrib/restricted/boost/type_traits
)

ADDINCL(
    GLOBAL contrib/restricted/boost/assign/include
)

NO_COMPILER_WARNINGS()

NO_UTIL()

END()
