# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(1.39.1)

LICENSE(Apache-2.0)

PEERDIR(
    contrib/libs/googleapis-common-protos
    contrib/libs/opentelemetry-proto
    contrib/python/opentelemetry-api
    contrib/python/opentelemetry-exporter-otlp-proto-common
    contrib/python/opentelemetry-sdk
    contrib/python/requests
    contrib/python/typing-extensions
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    opentelemetry/exporter/otlp/proto/http/__init__.py
    opentelemetry/exporter/otlp/proto/http/_common/__init__.py
    opentelemetry/exporter/otlp/proto/http/_log_exporter/__init__.py
    opentelemetry/exporter/otlp/proto/http/metric_exporter/__init__.py
    opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py
    opentelemetry/exporter/otlp/proto/http/trace_exporter/encoder/__init__.py
    opentelemetry/exporter/otlp/proto/http/version/__init__.py
)

RESOURCE_FILES(
    PREFIX contrib/python/opentelemetry-exporter-otlp-proto-http/
    .dist-info/METADATA
    .dist-info/entry_points.txt
    opentelemetry/exporter/otlp/proto/http/py.typed
)

END()
