# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(2.1.0)

LICENSE(MIT)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    iso8601/__init__.py
    iso8601/iso8601.py
)

RESOURCE_FILES(
    PREFIX contrib/python/iso8601/py3/
    .dist-info/METADATA
    .dist-info/top_level.txt
    iso8601/py.typed
)

END()

RECURSE_FOR_TESTS(
    tests
)
