# Generated by devtools/yamaker.

LIBRARY()

WITHOUT_LICENSE_TEXTS()

VERSION(1.2.2)

LICENSE(BSD-3-Clause)

ADDINCL(
    contrib/libs/libwebp/dsp
    contrib/libs/libwebp/webp
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

CFLAGS(
    -DHAVE_CONFIG_H
)

SRCDIR(contrib/libs/libwebp/dsp)

SRCS(
    alpha_processing_neon.c
    dec_neon.c
    filters_neon.c
    lossless_neon.c
    rescaler_neon.c
    upsampling_neon.c
    yuv_neon.c
)

END()
