SqlCore {
    ExtendedTranslationFlags {
        Name: "AnsiOrderByLimitInUnionAll"
    }
    ExtendedTranslationFlags {
        Name: "DisableCoalesceJoinKeysOnQualifiedAll"
    }
    ExtendedTranslationFlags {
        Name: "AnsiRankForNullableKeys"
    }
    ExtendedTranslationFlags {
        Name: "DisableAnsiOptionalAs"
    }
    ExtendedTranslationFlags {
        Name: "FlexibleTypes"
    }
    ExtendedTranslationFlags {
        Name: "CompactNamedExprs"
    }
    ExtendedTranslationFlags {
        Name: "Antlr4"
    }
    ExtendedTranslationFlags {
        Name: "DistinctOverWindow"
    }
    ExtendedTranslationFlags {
        Name: "DisableUnorderedResult"
    }
}

YqlCore {
    Flags {
        Name: "DisableYsonCastToString"
    }
    Flags {
        Name: "EnableConstraintCheck"
        Args: ["Distinct","Unique"]
    }
    Flags {
        Name: "UseCanonicalLibrarySuffix"
    }
}
