SqlCore {
    ExtendedTranslationFlags: {
        Name: "FlexibleTypes"
    }
    ExtendedTranslationFlags: {
        Name: "DisableAnsiOptionalAs"
    }
    ExtendedTranslationFlags: {
        Name: "EmitAggApply"
    }
}

YqlCore {
    Flags {
        Name: "DisableYsonCastToString"
    }
    Flags {
        Name: "UseBlocks"
    }
}
