# Generated by devtools/yamaker.

LIBRARY()

WITHOUT_LICENSE_TEXTS()

VERSION(4.15.2)

LICENSE(MIT)

ADDINCL(
    contrib/libs/z3-solver/src
    contrib/libs/z3-solver/src/util
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -D_EXTERNAL_RELEASE
    -D_MP_INTERNAL
)

SRCS(
    algebraic_numbers.cpp
    polynomial.cpp
    polynomial_cache.cpp
    rpolynomial.cpp
    sexpr2upolynomial.cpp
    upolynomial.cpp
    upolynomial_factorization.cpp
)

END()
