# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class ScribeResourceExhaustedErrorPayload(UncheckedBaseModel):
    """
    Payload for resource exhausted errors.
    """

    message_type: typing.Literal["resource_exhausted"] = pydantic.Field(default="resource_exhausted")
    """
    The message type identifier.
    """

    error: str = pydantic.Field()
    """
    Resource exhausted error details.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
