LIBRARY()

PEERDIR(
    library/cpp/streams/bzip2
    ydb/core/base
    ydb/core/blobstorage/base
    ydb/core/blobstorage/groupinfo
    ydb/core/blobstorage/pdisk
    ydb/core/blobstorage/vdisk/chunk_keeper
    ydb/core/blobstorage/vdisk/common
    ydb/core/blobstorage/vdisk/huge
    ydb/core/blobstorage/vdisk/hulldb/barriers
    ydb/core/blobstorage/vdisk/hulldb/base
    ydb/core/blobstorage/vdisk/synclog
    ydb/core/util
)

SRCS(
    defs.h
    assimilation.cpp
    assimilation.h
    query_barrier.cpp
    query_base.h
    query_dumpdb.h
    query_extr.cpp
    query_public.cpp
    query_public.h
    query_range.cpp
    query_readactor.cpp
    query_readactor.h
    query_readbatch.cpp
    query_readbatch.h
    query_spacereport.cpp
    query_spacereport_scan.cpp
    query_spacereport_scan.h
    query_spacetracker.h
    query_statalgo.h
    query_stat_yield.h
    query_statdb.cpp
    query_statdb.h
    query_statdb_stream.cpp
    query_statdb_stream.h
    query_stathuge.cpp
    query_stathuge.h
    query_stattablet.cpp
    query_stattablet.h
    query_stream.h
)

END()

RECURSE_FOR_TESTS(
    ut
)
