items:
- name: Системные требования
  href: system-requirements.md
- name: Настройки CPU для production
  href: cpu-production-settings.md
- name: Планирование ёмкости хранилища
  href: capacity-planning.md
- name: Версионирование
  href: versioning.md
- name: Обслуживание
  href: maintenance-without-downtime.md
- name: SelfHeal
  href: selfheal.md
  items:
  - name: SelfHeal хранилища
    href: selfheal-storage.md
  - name: SelfHeal State Storage
    href: selfheal-state-storage.md
- name: Аутентификация и авторизация узлов баз данных
  href: node-authorization.md
