LIBRARY()

SRCS(
    yql_aggregate_expander.cpp
    yql_callable_transform.cpp
    yql_callable_transform.h
    yql_cost_function.cpp
    yql_data_provider.h
    yql_default_valid_value.cpp
    yql_default_valid_value.h
    yql_execution.cpp
    yql_execution.h
    yql_expr_constraint.cpp
    yql_expr_constraint.h
    yql_expr_csee.cpp
    yql_expr_csee.h
    yql_expr_optimize.cpp
    yql_expr_optimize.h
    yql_expr_type_annotation.cpp
    yql_expr_type_annotation.h
    yql_func_stack.cpp
    yql_func_stack.h
    yql_gc_transformer.cpp
    yql_gc_transformer.h
    yql_graph_transformer.cpp
    yql_graph_transformer.h
    yql_holding_file_storage.cpp
    yql_holding_file_storage.h
    yql_join.cpp
    yql_join.h
    yql_library_compiler.cpp
    yql_opt_hopping.cpp
    yql_opt_match_recognize.cpp
    yql_opt_match_recognize.h
    yql_opt_proposed_by_data.cpp
    yql_opt_proposed_by_data.h
    yql_opt_range.cpp
    yql_opt_range.h
    yql_opt_rewrite_io.cpp
    yql_opt_rewrite_io.h
    yql_opt_utils.cpp
    yql_opt_utils.h
    yql_opt_window.cpp
    yql_opt_window.h
    yql_statistics.cpp
    yql_type_annotation.cpp
    yql_type_annotation.h
    yql_type_helpers.cpp
    yql_type_helpers.h
    yql_udf_index.cpp
    yql_udf_index.h
    yql_udf_index_package_set.cpp
    yql_udf_index_package_set.h
    yql_udf_resolver.cpp
    yql_udf_resolver.h
    yql_user_data.cpp
    yql_user_data.h
    yql_user_data_storage.cpp
    yql_user_data_storage.h
)

PEERDIR(
    library/cpp/enumbitset
    library/cpp/random_provider
    library/cpp/threading/future
    library/cpp/time_provider
    library/cpp/type_info/tz
    library/cpp/yson
    library/cpp/yson/node
    yql/essentials/ast
    yql/essentials/core/file_storage
    yql/essentials/core/sql_types
    yql/essentials/core/credentials
    yql/essentials/core/url_lister/interface
    yql/essentials/core/url_preprocessing/interface
    yql/essentials/minikql
    yql/essentials/minikql/jsonpath/parser
    yql/essentials/core/minsketch
    yql/essentials/core/histogram
    yql/essentials/protos
    yql/essentials/public/udf
    yql/essentials/public/langver
    yql/essentials/sql/settings
    yql/essentials/sql
    yql/essentials/utils
    yql/essentials/utils/log
    yql/essentials/core/expr_nodes
    yql/essentials/providers/common/proto
)

GENERATE_ENUM_SERIALIZATION(yql_data_provider.h)

GENERATE_ENUM_SERIALIZATION(yql_user_data.h)

GENERATE_ENUM_SERIALIZATION(yql_type_annotation.h)

GENERATE_ENUM_SERIALIZATION(yql_cost_function.h)

YQL_LAST_ABI_VERSION()

END()

RECURSE(
    cbo
    credentials
    dq_expr_nodes
    dq_integration
    dqs_expr_nodes
    file_storage
    issue
    langver
    minsketch
    pg_ext
    pg_settings
    sql_types
    url_lister
    url_preprocessing
    user_data
    arrow_kernels
    common_opt
    expr_nodes
    expr_nodes_gen
    extract_predicate
    facade
    peephole_opt
    qplayer
    services
    type_ann
    url_lister
    url_preprocessing
)

RECURSE_FOR_TESTS(ut)
