self: super: with self; rec {
  version = "2.16.0";

  # Released tarball contains autogenerated language files which repository snapshot doesn't
  src = fetchurl {
    url = "https://fontconfig.org/release/fontconfig-${version}.tar.xz";
    hash = "sha256-ajPcVVzJuosQyvdpWHjvE07rNtCvNmBB9jmx2ptu0iA=";
  };

  patches = [];

  configureFlags = [
    "--build=x86_64-pc-linux-gnu"
    "--disable-nls"
  ];
}
