from typing import Any

class CoreV1EndpointPort:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, app_protocol: str | None = None, name: str | None = None, port: int | None = None, protocol: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def app_protocol(self) -> str: ...
    @app_protocol.setter
    def app_protocol(self, app_protocol: str) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, port: int) -> None: ...
    @property
    def protocol(self) -> str: ...
    @protocol.setter
    def protocol(self, protocol: str) -> None: ...
