from typing import Any

class StorageV1TokenRequest:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, audience: str | None = None, expiration_seconds: int | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def audience(self) -> str: ...
    @audience.setter
    def audience(self, audience: str) -> None: ...
    @property
    def expiration_seconds(self) -> int: ...
    @expiration_seconds.setter
    def expiration_seconds(self, expiration_seconds: int) -> None: ...
