from kubernetes_asyncio.client.models import V1LabelSelector
from typing import Any

class V1AggregationRule:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, cluster_role_selectors: list[V1LabelSelector] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def cluster_role_selectors(self) -> list[V1LabelSelector]: ...
    @cluster_role_selectors.setter
    def cluster_role_selectors(self, cluster_role_selectors: list[V1LabelSelector]) -> None: ...
