from typing import Any

class V1AzureDiskVolumeSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, caching_mode: str | None = None, disk_name: str | None = None, disk_uri: str | None = None, fs_type: str | None = None, kind: str | None = None, read_only: bool | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def caching_mode(self) -> str: ...
    @caching_mode.setter
    def caching_mode(self, caching_mode: str) -> None: ...
    @property
    def disk_name(self) -> str: ...
    @disk_name.setter
    def disk_name(self, disk_name: str) -> None: ...
    @property
    def disk_uri(self) -> str: ...
    @disk_uri.setter
    def disk_uri(self, disk_uri: str) -> None: ...
    @property
    def fs_type(self) -> str: ...
    @fs_type.setter
    def fs_type(self, fs_type: str) -> None: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    @property
    def read_only(self) -> bool: ...
    @read_only.setter
    def read_only(self, read_only: bool) -> None: ...
