from typing import Any

class V1AuditAnnotation:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, key: str | None = None, value_expression: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def key(self) -> str: ...
    @key.setter
    def key(self, key: str) -> None: ...
    @property
    def value_expression(self) -> str: ...
    @value_expression.setter
    def value_expression(self, value_expression: str) -> None: ...
