from typing import Any

class V1AttachedVolume:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, device_path: str | None = None, name: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def device_path(self) -> str: ...
    @device_path.setter
    def device_path(self, device_path: str) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
