from kubernetes_asyncio.client.models import V1LinuxContainerUser
from typing import Any

class V1ContainerUser:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, linux: V1LinuxContainerUser | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def linux(self) -> V1LinuxContainerUser: ...
    @linux.setter
    def linux(self, linux: V1LinuxContainerUser) -> None: ...
