from datetime import datetime
from typing import Any

class V1ContainerStateRunning:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, started_at: datetime | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def started_at(self) -> datetime: ...
    @started_at.setter
    def started_at(self, started_at: datetime) -> None: ...
