from kubernetes_asyncio.client.models import V1LabelSelector
from kubernetes_asyncio.client.models import V1ObjectMeta
from typing import Any

class V1CSIStorageCapacity:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, api_version: str | None = None, capacity: str | None = None, kind: str | None = None, maximum_volume_size: str | None = None, metadata: V1ObjectMeta | None = None, node_topology: V1LabelSelector | None = None, storage_class_name: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def api_version(self) -> str: ...
    @api_version.setter
    def api_version(self, api_version: str) -> None: ...
    @property
    def capacity(self) -> str: ...
    @capacity.setter
    def capacity(self, capacity: str) -> None: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    @property
    def maximum_volume_size(self) -> str: ...
    @maximum_volume_size.setter
    def maximum_volume_size(self, maximum_volume_size: str) -> None: ...
    @property
    def metadata(self) -> V1ObjectMeta: ...
    @metadata.setter
    def metadata(self, metadata: V1ObjectMeta) -> None: ...
    @property
    def node_topology(self) -> V1LabelSelector: ...
    @node_topology.setter
    def node_topology(self, node_topology: V1LabelSelector) -> None: ...
    @property
    def storage_class_name(self) -> str: ...
    @storage_class_name.setter
    def storage_class_name(self, storage_class_name: str) -> None: ...
