from typing import Any

class V1CertificateSigningRequestSpec:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, expiration_seconds: int | None = None, extra: dict[str, list[str]] | None = None, groups: list[str] | None = None, request: str | None = None, signer_name: str | None = None, uid: str | None = None, usages: list[str] | None = None, username: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def expiration_seconds(self) -> int: ...
    @expiration_seconds.setter
    def expiration_seconds(self, expiration_seconds: int) -> None: ...
    @property
    def extra(self) -> dict[str, list[str]]: ...
    @extra.setter
    def extra(self, extra: dict[str, list[str]]) -> None: ...
    @property
    def groups(self) -> list[str]: ...
    @groups.setter
    def groups(self, groups: list[str]) -> None: ...
    @property
    def request(self) -> str: ...
    @request.setter
    def request(self, request: str) -> None: ...
    @property
    def signer_name(self) -> str: ...
    @signer_name.setter
    def signer_name(self, signer_name: str) -> None: ...
    @property
    def uid(self) -> str: ...
    @uid.setter
    def uid(self, uid: str) -> None: ...
    @property
    def usages(self) -> list[str]: ...
    @usages.setter
    def usages(self, usages: list[str]) -> None: ...
    @property
    def username(self) -> str: ...
    @username.setter
    def username(self, username: str) -> None: ...
