from kubernetes_asyncio.client.models import V1ObjectMeta
from typing import Any

class V1ControllerRevision:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, api_version: str | None = None, data: Any | None = None, kind: str | None = None, metadata: V1ObjectMeta | None = None, revision: int | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def api_version(self) -> str: ...
    @api_version.setter
    def api_version(self, api_version: str) -> None: ...
    @property
    def data(self) -> Any: ...
    @data.setter
    def data(self, data: Any) -> None: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    @property
    def metadata(self) -> V1ObjectMeta: ...
    @metadata.setter
    def metadata(self, metadata: V1ObjectMeta) -> None: ...
    @property
    def revision(self) -> int: ...
    @revision.setter
    def revision(self, revision: int) -> None: ...
