from typing import Any

class V1ContainerExtendedResourceRequest:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, container_name: str | None = None, request_name: str | None = None, resource_name: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def container_name(self) -> str: ...
    @container_name.setter
    def container_name(self, container_name: str) -> None: ...
    @property
    def request_name(self) -> str: ...
    @request_name.setter
    def request_name(self, request_name: str) -> None: ...
    @property
    def resource_name(self) -> str: ...
    @resource_name.setter
    def resource_name(self, resource_name: str) -> None: ...
