from kubernetes_asyncio.client.models import V1LabelSelector
from typing import Any

class V1ClusterTrustBundleProjection:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, label_selector: V1LabelSelector | None = None, name: str | None = None, optional: bool | None = None, path: str | None = None, signer_name: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def label_selector(self) -> V1LabelSelector: ...
    @label_selector.setter
    def label_selector(self, label_selector: V1LabelSelector) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def optional(self) -> bool: ...
    @optional.setter
    def optional(self, optional: bool) -> None: ...
    @property
    def path(self) -> str: ...
    @path.setter
    def path(self, path: str) -> None: ...
    @property
    def signer_name(self) -> str: ...
    @signer_name.setter
    def signer_name(self, signer_name: str) -> None: ...
