from typing import Any

class V1ConfigMapNodeConfigSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, kubelet_config_key: str | None = None, name: str | None = None, namespace: str | None = None, resource_version: str | None = None, uid: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def kubelet_config_key(self) -> str: ...
    @kubelet_config_key.setter
    def kubelet_config_key(self, kubelet_config_key: str) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def namespace(self) -> str: ...
    @namespace.setter
    def namespace(self, namespace: str) -> None: ...
    @property
    def resource_version(self) -> str: ...
    @resource_version.setter
    def resource_version(self, resource_version: str) -> None: ...
    @property
    def uid(self) -> str: ...
    @uid.setter
    def uid(self, uid: str) -> None: ...
