from typing import Any

class V1CapacityRequirements:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, requests: dict[str, str] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def requests(self) -> dict[str, str]: ...
    @requests.setter
    def requests(self, requests: dict[str, str]) -> None: ...
