from kubernetes_asyncio.client.models import V1DeploymentCondition
from typing import Any

class V1DeploymentStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, available_replicas: int | None = None, collision_count: int | None = None, conditions: list[V1DeploymentCondition] | None = None, observed_generation: int | None = None, ready_replicas: int | None = None, replicas: int | None = None, terminating_replicas: int | None = None, unavailable_replicas: int | None = None, updated_replicas: int | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def available_replicas(self) -> int: ...
    @available_replicas.setter
    def available_replicas(self, available_replicas: int) -> None: ...
    @property
    def collision_count(self) -> int: ...
    @collision_count.setter
    def collision_count(self, collision_count: int) -> None: ...
    @property
    def conditions(self) -> list[V1DeploymentCondition]: ...
    @conditions.setter
    def conditions(self, conditions: list[V1DeploymentCondition]) -> None: ...
    @property
    def observed_generation(self) -> int: ...
    @observed_generation.setter
    def observed_generation(self, observed_generation: int) -> None: ...
    @property
    def ready_replicas(self) -> int: ...
    @ready_replicas.setter
    def ready_replicas(self, ready_replicas: int) -> None: ...
    @property
    def replicas(self) -> int: ...
    @replicas.setter
    def replicas(self, replicas: int) -> None: ...
    @property
    def terminating_replicas(self) -> int: ...
    @terminating_replicas.setter
    def terminating_replicas(self, terminating_replicas: int) -> None: ...
    @property
    def unavailable_replicas(self) -> int: ...
    @unavailable_replicas.setter
    def unavailable_replicas(self, unavailable_replicas: int) -> None: ...
    @property
    def updated_replicas(self) -> int: ...
    @updated_replicas.setter
    def updated_replicas(self, updated_replicas: int) -> None: ...
