from kubernetes_asyncio.client.models import V1CapacityRequirements
from kubernetes_asyncio.client.models import V1DeviceSelector
from kubernetes_asyncio.client.models import V1DeviceToleration
from typing import Any

class V1DeviceSubRequest:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, allocation_mode: str | None = None, capacity: V1CapacityRequirements | None = None, count: int | None = None, device_class_name: str | None = None, name: str | None = None, selectors: list[V1DeviceSelector] | None = None, tolerations: list[V1DeviceToleration] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def allocation_mode(self) -> str: ...
    @allocation_mode.setter
    def allocation_mode(self, allocation_mode: str) -> None: ...
    @property
    def capacity(self) -> V1CapacityRequirements: ...
    @capacity.setter
    def capacity(self, capacity: V1CapacityRequirements) -> None: ...
    @property
    def count(self) -> int: ...
    @count.setter
    def count(self, count: int) -> None: ...
    @property
    def device_class_name(self) -> str: ...
    @device_class_name.setter
    def device_class_name(self, device_class_name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def selectors(self) -> list[V1DeviceSelector]: ...
    @selectors.setter
    def selectors(self, selectors: list[V1DeviceSelector]) -> None: ...
    @property
    def tolerations(self) -> list[V1DeviceToleration]: ...
    @tolerations.setter
    def tolerations(self, tolerations: list[V1DeviceToleration]) -> None: ...
