from kubernetes_asyncio.client.models import V1DownwardAPIVolumeFile
from typing import Any

class V1DownwardAPIVolumeSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, default_mode: int | None = None, items: list[V1DownwardAPIVolumeFile] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def default_mode(self) -> int: ...
    @default_mode.setter
    def default_mode(self, default_mode: int) -> None: ...
    @property
    def items(self) -> list[V1DownwardAPIVolumeFile]: ...
    @items.setter
    def items(self, items: list[V1DownwardAPIVolumeFile]) -> None: ...
