from kubernetes_asyncio.client.models import V1ObjectFieldSelector
from kubernetes_asyncio.client.models import V1ResourceFieldSelector
from typing import Any

class V1DownwardAPIVolumeFile:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, field_ref: V1ObjectFieldSelector | None = None, mode: int | None = None, path: str | None = None, resource_field_ref: V1ResourceFieldSelector | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def field_ref(self) -> V1ObjectFieldSelector: ...
    @field_ref.setter
    def field_ref(self, field_ref: V1ObjectFieldSelector) -> None: ...
    @property
    def mode(self) -> int: ...
    @mode.setter
    def mode(self, mode: int) -> None: ...
    @property
    def path(self) -> str: ...
    @path.setter
    def path(self, path: str) -> None: ...
    @property
    def resource_field_ref(self) -> V1ResourceFieldSelector: ...
    @resource_field_ref.setter
    def resource_field_ref(self, resource_field_ref: V1ResourceFieldSelector) -> None: ...
