from kubernetes_asyncio.client.models import V1EnvVarSource
from typing import Any

class V1EnvVar:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, name: str | None = None, value: str | None = None, value_from: V1EnvVarSource | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...
    @property
    def value_from(self) -> V1EnvVarSource: ...
    @value_from.setter
    def value_from(self, value_from: V1EnvVarSource) -> None: ...
