from kubernetes_asyncio.client.models import V1PersistentVolumeClaimTemplate
from typing import Any

class V1EphemeralVolumeSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, volume_claim_template: V1PersistentVolumeClaimTemplate | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def volume_claim_template(self) -> V1PersistentVolumeClaimTemplate: ...
    @volume_claim_template.setter
    def volume_claim_template(self, volume_claim_template: V1PersistentVolumeClaimTemplate) -> None: ...
