from kubernetes_asyncio.client.models import DiscoveryV1EndpointPort
from kubernetes_asyncio.client.models import V1Endpoint
from kubernetes_asyncio.client.models import V1ObjectMeta
from typing import Any

class V1EndpointSlice:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, address_type: str | None = None, api_version: str | None = None, endpoints: list[V1Endpoint] | None = None, kind: str | None = None, metadata: V1ObjectMeta | None = None, ports: list[DiscoveryV1EndpointPort] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def address_type(self) -> str: ...
    @address_type.setter
    def address_type(self, address_type: str) -> None: ...
    @property
    def api_version(self) -> str: ...
    @api_version.setter
    def api_version(self, api_version: str) -> None: ...
    @property
    def endpoints(self) -> list[V1Endpoint]: ...
    @endpoints.setter
    def endpoints(self, endpoints: list[V1Endpoint]) -> None: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    @property
    def metadata(self) -> V1ObjectMeta: ...
    @metadata.setter
    def metadata(self, metadata: V1ObjectMeta) -> None: ...
    @property
    def ports(self) -> list[DiscoveryV1EndpointPort]: ...
    @ports.setter
    def ports(self, ports: list[DiscoveryV1EndpointPort]) -> None: ...
