from typing import Any

class V1ExpressionWarning:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, field_ref: str | None = None, warning: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def field_ref(self) -> str: ...
    @field_ref.setter
    def field_ref(self, field_ref: str) -> None: ...
    @property
    def warning(self) -> str: ...
    @warning.setter
    def warning(self, warning: str) -> None: ...
