from kubernetes_asyncio.client.models import V1SecretReference
from typing import Any

class V1FlexPersistentVolumeSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, driver: str | None = None, fs_type: str | None = None, options: dict[str, str] | None = None, read_only: bool | None = None, secret_ref: V1SecretReference | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def driver(self) -> str: ...
    @driver.setter
    def driver(self, driver: str) -> None: ...
    @property
    def fs_type(self) -> str: ...
    @fs_type.setter
    def fs_type(self, fs_type: str) -> None: ...
    @property
    def options(self) -> dict[str, str]: ...
    @options.setter
    def options(self, options: dict[str, str]) -> None: ...
    @property
    def read_only(self) -> bool: ...
    @read_only.setter
    def read_only(self, read_only: bool) -> None: ...
    @property
    def secret_ref(self) -> V1SecretReference: ...
    @secret_ref.setter
    def secret_ref(self, secret_ref: V1SecretReference) -> None: ...
