from typing import Any

class V1GRPCAction:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, port: int | None = None, service: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, port: int) -> None: ...
    @property
    def service(self) -> str: ...
    @service.setter
    def service(self, service: str) -> None: ...
