from kubernetes_asyncio.client.models import V1HTTPIngressPath
from typing import Any

class V1HTTPIngressRuleValue:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, paths: list[V1HTTPIngressPath] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def paths(self) -> list[V1HTTPIngressPath]: ...
    @paths.setter
    def paths(self, paths: list[V1HTTPIngressPath]) -> None: ...
