from kubernetes_asyncio.client.models import V1ServiceBackendPort
from typing import Any

class V1IngressServiceBackend:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, name: str | None = None, port: V1ServiceBackendPort | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def port(self) -> V1ServiceBackendPort: ...
    @port.setter
    def port(self, port: V1ServiceBackendPort) -> None: ...
