from typing import Any

class V1ImageVolumeSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, pull_policy: str | None = None, reference: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def pull_policy(self) -> str: ...
    @pull_policy.setter
    def pull_policy(self, pull_policy: str) -> None: ...
    @property
    def reference(self) -> str: ...
    @reference.setter
    def reference(self, reference: str) -> None: ...
