from typing import Any

class V1IngressTLS:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, hosts: list[str] | None = None, secret_name: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def hosts(self) -> list[str]: ...
    @hosts.setter
    def hosts(self, hosts: list[str]) -> None: ...
    @property
    def secret_name(self) -> str: ...
    @secret_name.setter
    def secret_name(self, secret_name: str) -> None: ...
