from typing import Any

class V1ModifyVolumeStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, status: str | None = None, target_volume_attributes_class_name: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def status(self) -> str: ...
    @status.setter
    def status(self, status: str) -> None: ...
    @property
    def target_volume_attributes_class_name(self) -> str: ...
    @target_volume_attributes_class_name.setter
    def target_volume_attributes_class_name(self, target_volume_attributes_class_name: str) -> None: ...
