from typing import Any

class V1MatchCondition:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, expression: str | None = None, name: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def expression(self) -> str: ...
    @expression.setter
    def expression(self, expression: str) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
