from typing import Any

class V1NFSVolumeSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, path: str | None = None, read_only: bool | None = None, server: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def path(self) -> str: ...
    @path.setter
    def path(self, path: str) -> None: ...
    @property
    def read_only(self) -> bool: ...
    @read_only.setter
    def read_only(self, read_only: bool) -> None: ...
    @property
    def server(self) -> str: ...
    @server.setter
    def server(self, server: str) -> None: ...
