from typing import Any

class V1NetworkPolicyPort:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, end_port: int | None = None, port: Any | None = None, protocol: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def end_port(self) -> int: ...
    @end_port.setter
    def end_port(self, end_port: int) -> None: ...
    @property
    def port(self) -> Any: ...
    @port.setter
    def port(self, port: Any) -> None: ...
    @property
    def protocol(self) -> str: ...
    @protocol.setter
    def protocol(self, protocol: str) -> None: ...
