from typing import Any

class V1ObjectFieldSelector:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, api_version: str | None = None, field_path: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def api_version(self) -> str: ...
    @api_version.setter
    def api_version(self, api_version: str) -> None: ...
    @property
    def field_path(self) -> str: ...
    @field_path.setter
    def field_path(self, field_path: str) -> None: ...
