from typing import Any

class V1OpaqueDeviceConfiguration:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, driver: str | None = None, parameters: Any | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def driver(self) -> str: ...
    @driver.setter
    def driver(self, driver: str) -> None: ...
    @property
    def parameters(self) -> Any: ...
    @parameters.setter
    def parameters(self, parameters: Any) -> None: ...
