from kubernetes_asyncio.client.models import V1PodFailurePolicyRule
from typing import Any

class V1PodFailurePolicy:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, rules: list[V1PodFailurePolicyRule] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def rules(self) -> list[V1PodFailurePolicyRule]: ...
    @rules.setter
    def rules(self, rules: list[V1PodFailurePolicyRule]) -> None: ...
