from typing import Any

class V1Preconditions:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, resource_version: str | None = None, uid: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def resource_version(self) -> str: ...
    @resource_version.setter
    def resource_version(self, resource_version: str) -> None: ...
    @property
    def uid(self) -> str: ...
    @uid.setter
    def uid(self, uid: str) -> None: ...
