from kubernetes_asyncio.client.models import V1ObjectMeta
from typing import Any

class V1PriorityClass:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, api_version: str | None = None, description: str | None = None, global_default: bool | None = None, kind: str | None = None, metadata: V1ObjectMeta | None = None, preemption_policy: str | None = None, value: int | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def api_version(self) -> str: ...
    @api_version.setter
    def api_version(self, api_version: str) -> None: ...
    @property
    def description(self) -> str: ...
    @description.setter
    def description(self, description: str) -> None: ...
    @property
    def global_default(self) -> bool: ...
    @global_default.setter
    def global_default(self, global_default: bool) -> None: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    @property
    def metadata(self) -> V1ObjectMeta: ...
    @metadata.setter
    def metadata(self, metadata: V1ObjectMeta) -> None: ...
    @property
    def preemption_policy(self) -> str: ...
    @preemption_policy.setter
    def preemption_policy(self, preemption_policy: str) -> None: ...
    @property
    def value(self) -> int: ...
    @value.setter
    def value(self, value: int) -> None: ...
