from typing import Any

class V1PortStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, error: str | None = None, port: int | None = None, protocol: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def error(self) -> str: ...
    @error.setter
    def error(self, error: str) -> None: ...
    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, port: int) -> None: ...
    @property
    def protocol(self) -> str: ...
    @protocol.setter
    def protocol(self, protocol: str) -> None: ...
