from datetime import datetime
from typing import Any

class V1PersistentVolumeStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, last_phase_transition_time: datetime | None = None, message: str | None = None, phase: str | None = None, reason: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def last_phase_transition_time(self) -> datetime: ...
    @last_phase_transition_time.setter
    def last_phase_transition_time(self, last_phase_transition_time: datetime) -> None: ...
    @property
    def message(self) -> str: ...
    @message.setter
    def message(self, message: str) -> None: ...
    @property
    def phase(self) -> str: ...
    @phase.setter
    def phase(self, phase: str) -> None: ...
    @property
    def reason(self) -> str: ...
    @reason.setter
    def reason(self, reason: str) -> None: ...
