from typing import Any

class V1PersistentVolumeClaimVolumeSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, claim_name: str | None = None, read_only: bool | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def claim_name(self) -> str: ...
    @claim_name.setter
    def claim_name(self, claim_name: str) -> None: ...
    @property
    def read_only(self) -> bool: ...
    @read_only.setter
    def read_only(self, read_only: bool) -> None: ...
