from typing import Any

class V1RollingUpdateStatefulSetStrategy:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, max_unavailable: Any | None = None, partition: int | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def max_unavailable(self) -> Any: ...
    @max_unavailable.setter
    def max_unavailable(self, max_unavailable: Any) -> None: ...
    @property
    def partition(self) -> int: ...
    @partition.setter
    def partition(self, partition: int) -> None: ...
