from typing import Any

class V1ResourceFieldSelector:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, container_name: str | None = None, divisor: str | None = None, resource: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def container_name(self) -> str: ...
    @container_name.setter
    def container_name(self, container_name: str) -> None: ...
    @property
    def divisor(self) -> str: ...
    @divisor.setter
    def divisor(self, divisor: str) -> None: ...
    @property
    def resource(self) -> str: ...
    @resource.setter
    def resource(self, resource: str) -> None: ...
