from typing import Any

class V1ResourceHealth:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, health: str | None = None, resource_id: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def health(self) -> str: ...
    @health.setter
    def health(self, health: str) -> None: ...
    @property
    def resource_id(self) -> str: ...
    @resource_id.setter
    def resource_id(self, resource_id: str) -> None: ...
