from typing import Any

class V1RollingUpdateDaemonSet:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, max_surge: Any | None = None, max_unavailable: Any | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def max_surge(self) -> Any: ...
    @max_surge.setter
    def max_surge(self, max_surge: Any) -> None: ...
    @property
    def max_unavailable(self) -> Any: ...
    @max_unavailable.setter
    def max_unavailable(self, max_unavailable: Any) -> None: ...
