from kubernetes_asyncio.client.models import V1ObjectMeta
from kubernetes_asyncio.client.models import V1Overhead
from kubernetes_asyncio.client.models import V1Scheduling
from typing import Any

class V1RuntimeClass:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, api_version: str | None = None, handler: str | None = None, kind: str | None = None, metadata: V1ObjectMeta | None = None, overhead: V1Overhead | None = None, scheduling: V1Scheduling | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def api_version(self) -> str: ...
    @api_version.setter
    def api_version(self, api_version: str) -> None: ...
    @property
    def handler(self) -> str: ...
    @handler.setter
    def handler(self, handler: str) -> None: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    @property
    def metadata(self) -> V1ObjectMeta: ...
    @metadata.setter
    def metadata(self, metadata: V1ObjectMeta) -> None: ...
    @property
    def overhead(self) -> V1Overhead: ...
    @overhead.setter
    def overhead(self, overhead: V1Overhead) -> None: ...
    @property
    def scheduling(self) -> V1Scheduling: ...
    @scheduling.setter
    def scheduling(self, scheduling: V1Scheduling) -> None: ...
