from typing import Any

class V1StatefulSetPersistentVolumeClaimRetentionPolicy:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, when_deleted: str | None = None, when_scaled: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def when_deleted(self) -> str: ...
    @when_deleted.setter
    def when_deleted(self, when_deleted: str) -> None: ...
    @property
    def when_scaled(self) -> str: ...
    @when_scaled.setter
    def when_scaled(self, when_scaled: str) -> None: ...
