from typing import Any

class V1ServiceCIDRSpec:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, cidrs: list[str] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def cidrs(self) -> list[str]: ...
    @cidrs.setter
    def cidrs(self, cidrs: list[str]) -> None: ...
