from typing import Any

class V1SelectableField:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, json_path: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def json_path(self) -> str: ...
    @json_path.setter
    def json_path(self, json_path: str) -> None: ...
