from kubernetes_asyncio.client.models import V1ScopedResourceSelectorRequirement
from typing import Any

class V1ScopeSelector:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, match_expressions: list[V1ScopedResourceSelectorRequirement] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def match_expressions(self) -> list[V1ScopedResourceSelectorRequirement]: ...
    @match_expressions.setter
    def match_expressions(self, match_expressions: list[V1ScopedResourceSelectorRequirement]) -> None: ...
