from kubernetes_asyncio.client.models import V1RollingUpdateStatefulSetStrategy
from typing import Any

class V1StatefulSetUpdateStrategy:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, rolling_update: V1RollingUpdateStatefulSetStrategy | None = None, type: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def rolling_update(self) -> V1RollingUpdateStatefulSetStrategy: ...
    @rolling_update.setter
    def rolling_update(self, rolling_update: V1RollingUpdateStatefulSetStrategy) -> None: ...
    @property
    def type(self) -> str: ...
    @type.setter
    def type(self, type: str) -> None: ...
