from kubernetes_asyncio.client.models import V1KeyToPath
from typing import Any

class V1SecretProjection:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, items: list[V1KeyToPath] | None = None, name: str | None = None, optional: bool | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def items(self) -> list[V1KeyToPath]: ...
    @items.setter
    def items(self, items: list[V1KeyToPath]) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def optional(self) -> bool: ...
    @optional.setter
    def optional(self, optional: bool) -> None: ...
