from kubernetes_asyncio.client.models import V1KeyToPath
from typing import Any

class V1SecretVolumeSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, default_mode: int | None = None, items: list[V1KeyToPath] | None = None, optional: bool | None = None, secret_name: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def default_mode(self) -> int: ...
    @default_mode.setter
    def default_mode(self, default_mode: int) -> None: ...
    @property
    def items(self) -> list[V1KeyToPath]: ...
    @items.setter
    def items(self, items: list[V1KeyToPath]) -> None: ...
    @property
    def optional(self) -> bool: ...
    @optional.setter
    def optional(self, optional: bool) -> None: ...
    @property
    def secret_name(self) -> str: ...
    @secret_name.setter
    def secret_name(self, secret_name: str) -> None: ...
