from kubernetes_asyncio.client.models import V1StatefulSetCondition
from typing import Any

class V1StatefulSetStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, available_replicas: int | None = None, collision_count: int | None = None, conditions: list[V1StatefulSetCondition] | None = None, current_replicas: int | None = None, current_revision: str | None = None, observed_generation: int | None = None, ready_replicas: int | None = None, replicas: int | None = None, update_revision: str | None = None, updated_replicas: int | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def available_replicas(self) -> int: ...
    @available_replicas.setter
    def available_replicas(self, available_replicas: int) -> None: ...
    @property
    def collision_count(self) -> int: ...
    @collision_count.setter
    def collision_count(self, collision_count: int) -> None: ...
    @property
    def conditions(self) -> list[V1StatefulSetCondition]: ...
    @conditions.setter
    def conditions(self, conditions: list[V1StatefulSetCondition]) -> None: ...
    @property
    def current_replicas(self) -> int: ...
    @current_replicas.setter
    def current_replicas(self, current_replicas: int) -> None: ...
    @property
    def current_revision(self) -> str: ...
    @current_revision.setter
    def current_revision(self, current_revision: str) -> None: ...
    @property
    def observed_generation(self) -> int: ...
    @observed_generation.setter
    def observed_generation(self, observed_generation: int) -> None: ...
    @property
    def ready_replicas(self) -> int: ...
    @ready_replicas.setter
    def ready_replicas(self, ready_replicas: int) -> None: ...
    @property
    def replicas(self) -> int: ...
    @replicas.setter
    def replicas(self, replicas: int) -> None: ...
    @property
    def update_revision(self) -> str: ...
    @update_revision.setter
    def update_revision(self, update_revision: str) -> None: ...
    @property
    def updated_replicas(self) -> int: ...
    @updated_replicas.setter
    def updated_replicas(self, updated_replicas: int) -> None: ...
