from kubernetes_asyncio.client.models import V1ObjectMeta
from typing import Any

class V1Secret:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, api_version: str | None = None, data: dict[str, str] | None = None, immutable: bool | None = None, kind: str | None = None, metadata: V1ObjectMeta | None = None, string_data: dict[str, str] | None = None, type: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def api_version(self) -> str: ...
    @api_version.setter
    def api_version(self, api_version: str) -> None: ...
    @property
    def data(self) -> dict[str, str]: ...
    @data.setter
    def data(self, data: dict[str, str]) -> None: ...
    @property
    def immutable(self) -> bool: ...
    @immutable.setter
    def immutable(self, immutable: bool) -> None: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    @property
    def metadata(self) -> V1ObjectMeta: ...
    @metadata.setter
    def metadata(self, metadata: V1ObjectMeta) -> None: ...
    @property
    def string_data(self) -> dict[str, str]: ...
    @string_data.setter
    def string_data(self, string_data: dict[str, str]) -> None: ...
    @property
    def type(self) -> str: ...
    @type.setter
    def type(self, type: str) -> None: ...
