from kubernetes_asyncio.client.models import V1LabelSelector
from typing import Any

class V1TopologySpreadConstraint:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, label_selector: V1LabelSelector | None = None, match_label_keys: list[str] | None = None, max_skew: int | None = None, min_domains: int | None = None, node_affinity_policy: str | None = None, node_taints_policy: str | None = None, topology_key: str | None = None, when_unsatisfiable: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def label_selector(self) -> V1LabelSelector: ...
    @label_selector.setter
    def label_selector(self, label_selector: V1LabelSelector) -> None: ...
    @property
    def match_label_keys(self) -> list[str]: ...
    @match_label_keys.setter
    def match_label_keys(self, match_label_keys: list[str]) -> None: ...
    @property
    def max_skew(self) -> int: ...
    @max_skew.setter
    def max_skew(self, max_skew: int) -> None: ...
    @property
    def min_domains(self) -> int: ...
    @min_domains.setter
    def min_domains(self, min_domains: int) -> None: ...
    @property
    def node_affinity_policy(self) -> str: ...
    @node_affinity_policy.setter
    def node_affinity_policy(self, node_affinity_policy: str) -> None: ...
    @property
    def node_taints_policy(self) -> str: ...
    @node_taints_policy.setter
    def node_taints_policy(self, node_taints_policy: str) -> None: ...
    @property
    def topology_key(self) -> str: ...
    @topology_key.setter
    def topology_key(self, topology_key: str) -> None: ...
    @property
    def when_unsatisfiable(self) -> str: ...
    @when_unsatisfiable.setter
    def when_unsatisfiable(self, when_unsatisfiable: str) -> None: ...
