from kubernetes_asyncio.client.models import V1TopologySelectorLabelRequirement
from typing import Any

class V1TopologySelectorTerm:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, match_label_expressions: list[V1TopologySelectorLabelRequirement] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def match_label_expressions(self) -> list[V1TopologySelectorLabelRequirement]: ...
    @match_label_expressions.setter
    def match_label_expressions(self, match_label_expressions: list[V1TopologySelectorLabelRequirement]) -> None: ...
