from kubernetes_asyncio.client.models import V1UserInfo
from typing import Any

class V1TokenReviewStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, audiences: list[str] | None = None, authenticated: bool | None = None, error: str | None = None, user: V1UserInfo | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def audiences(self) -> list[str]: ...
    @audiences.setter
    def audiences(self, audiences: list[str]) -> None: ...
    @property
    def authenticated(self) -> bool: ...
    @authenticated.setter
    def authenticated(self, authenticated: bool) -> None: ...
    @property
    def error(self) -> str: ...
    @error.setter
    def error(self, error: str) -> None: ...
    @property
    def user(self) -> V1UserInfo: ...
    @user.setter
    def user(self, user: V1UserInfo) -> None: ...
