from kubernetes_asyncio.client.models import V1AuditAnnotation
from kubernetes_asyncio.client.models import V1MatchCondition
from kubernetes_asyncio.client.models import V1MatchResources
from kubernetes_asyncio.client.models import V1ParamKind
from kubernetes_asyncio.client.models import V1Validation
from kubernetes_asyncio.client.models import V1Variable
from typing import Any

class V1ValidatingAdmissionPolicySpec:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, audit_annotations: list[V1AuditAnnotation] | None = None, failure_policy: str | None = None, match_conditions: list[V1MatchCondition] | None = None, match_constraints: V1MatchResources | None = None, param_kind: V1ParamKind | None = None, validations: list[V1Validation] | None = None, variables: list[V1Variable] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def audit_annotations(self) -> list[V1AuditAnnotation]: ...
    @audit_annotations.setter
    def audit_annotations(self, audit_annotations: list[V1AuditAnnotation]) -> None: ...
    @property
    def failure_policy(self) -> str: ...
    @failure_policy.setter
    def failure_policy(self, failure_policy: str) -> None: ...
    @property
    def match_conditions(self) -> list[V1MatchCondition]: ...
    @match_conditions.setter
    def match_conditions(self, match_conditions: list[V1MatchCondition]) -> None: ...
    @property
    def match_constraints(self) -> V1MatchResources: ...
    @match_constraints.setter
    def match_constraints(self, match_constraints: V1MatchResources) -> None: ...
    @property
    def param_kind(self) -> V1ParamKind: ...
    @param_kind.setter
    def param_kind(self, param_kind: V1ParamKind) -> None: ...
    @property
    def validations(self) -> list[V1Validation]: ...
    @validations.setter
    def validations(self, validations: list[V1Validation]) -> None: ...
    @property
    def variables(self) -> list[V1Variable]: ...
    @variables.setter
    def variables(self, variables: list[V1Variable]) -> None: ...
