from typing import Any

class V1VolumeMountStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, mount_path: str | None = None, name: str | None = None, read_only: bool | None = None, recursive_read_only: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def mount_path(self) -> str: ...
    @mount_path.setter
    def mount_path(self, mount_path: str) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def read_only(self) -> bool: ...
    @read_only.setter
    def read_only(self, read_only: bool) -> None: ...
    @property
    def recursive_read_only(self) -> str: ...
    @recursive_read_only.setter
    def recursive_read_only(self, recursive_read_only: str) -> None: ...
