from datetime import datetime
from typing import Any

class V1alpha3DeviceTaint:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, effect: str | None = None, key: str | None = None, time_added: datetime | None = None, value: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def effect(self) -> str: ...
    @effect.setter
    def effect(self, effect: str) -> None: ...
    @property
    def key(self) -> str: ...
    @key.setter
    def key(self, key: str) -> None: ...
    @property
    def time_added(self) -> datetime: ...
    @time_added.setter
    def time_added(self, time_added: datetime) -> None: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...
