from kubernetes_asyncio.client.models import V1alpha1MatchCondition
from kubernetes_asyncio.client.models import V1alpha1MatchResources
from kubernetes_asyncio.client.models import V1alpha1Mutation
from kubernetes_asyncio.client.models import V1alpha1ParamKind
from kubernetes_asyncio.client.models import V1alpha1Variable
from typing import Any

class V1alpha1MutatingAdmissionPolicySpec:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, failure_policy: str | None = None, match_conditions: list[V1alpha1MatchCondition] | None = None, match_constraints: V1alpha1MatchResources | None = None, mutations: list[V1alpha1Mutation] | None = None, param_kind: V1alpha1ParamKind | None = None, reinvocation_policy: str | None = None, variables: list[V1alpha1Variable] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def failure_policy(self) -> str: ...
    @failure_policy.setter
    def failure_policy(self, failure_policy: str) -> None: ...
    @property
    def match_conditions(self) -> list[V1alpha1MatchCondition]: ...
    @match_conditions.setter
    def match_conditions(self, match_conditions: list[V1alpha1MatchCondition]) -> None: ...
    @property
    def match_constraints(self) -> V1alpha1MatchResources: ...
    @match_constraints.setter
    def match_constraints(self, match_constraints: V1alpha1MatchResources) -> None: ...
    @property
    def mutations(self) -> list[V1alpha1Mutation]: ...
    @mutations.setter
    def mutations(self, mutations: list[V1alpha1Mutation]) -> None: ...
    @property
    def param_kind(self) -> V1alpha1ParamKind: ...
    @param_kind.setter
    def param_kind(self, param_kind: V1alpha1ParamKind) -> None: ...
    @property
    def reinvocation_policy(self) -> str: ...
    @reinvocation_policy.setter
    def reinvocation_policy(self, reinvocation_policy: str) -> None: ...
    @property
    def variables(self) -> list[V1alpha1Variable]: ...
    @variables.setter
    def variables(self, variables: list[V1alpha1Variable]) -> None: ...
