from kubernetes_asyncio.client.models import V1alpha1GangSchedulingPolicy
from typing import Any

class V1alpha1PodGroupPolicy:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, basic: Any | None = None, gang: V1alpha1GangSchedulingPolicy | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def basic(self) -> Any: ...
    @basic.setter
    def basic(self, basic: Any) -> None: ...
    @property
    def gang(self) -> V1alpha1GangSchedulingPolicy: ...
    @gang.setter
    def gang(self, gang: V1alpha1GangSchedulingPolicy) -> None: ...
