from kubernetes_asyncio.client.models import V1GroupResource
from typing import Any

class V1beta1StorageVersionMigrationSpec:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, resource: V1GroupResource | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def resource(self) -> V1GroupResource: ...
    @resource.setter
    def resource(self, resource: V1GroupResource) -> None: ...
