from kubernetes_asyncio.client.models import V1beta2OpaqueDeviceConfiguration
from typing import Any

class V1beta2DeviceAllocationConfiguration:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, opaque: V1beta2OpaqueDeviceConfiguration | None = None, requests: list[str] | None = None, source: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def opaque(self) -> V1beta2OpaqueDeviceConfiguration: ...
    @opaque.setter
    def opaque(self, opaque: V1beta2OpaqueDeviceConfiguration) -> None: ...
    @property
    def requests(self) -> list[str]: ...
    @requests.setter
    def requests(self, requests: list[str]) -> None: ...
    @property
    def source(self) -> str: ...
    @source.setter
    def source(self, source: str) -> None: ...
