from kubernetes_asyncio.client.models import V1beta2CapacityRequestPolicy
from typing import Any

class V1beta2DeviceCapacity:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, request_policy: V1beta2CapacityRequestPolicy | None = None, value: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def request_policy(self) -> V1beta2CapacityRequestPolicy: ...
    @request_policy.setter
    def request_policy(self, request_policy: V1beta2CapacityRequestPolicy) -> None: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...
