from kubernetes_asyncio.client.models import IoK8sApimachineryPkgApisMetaV1GroupVersionKind
from typing import Any

class V2APISubresourceDiscovery:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, subresource: str | None = None, response_kind: IoK8sApimachineryPkgApisMetaV1GroupVersionKind | None = None, accepted_types: list[IoK8sApimachineryPkgApisMetaV1GroupVersionKind] | None = None, verbs: list[str] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def accepted_types(self) -> list[IoK8sApimachineryPkgApisMetaV1GroupVersionKind]: ...
    @accepted_types.setter
    def accepted_types(self, accepted_types: list[IoK8sApimachineryPkgApisMetaV1GroupVersionKind]) -> None: ...
    @property
    def response_kind(self) -> IoK8sApimachineryPkgApisMetaV1GroupVersionKind: ...
    @response_kind.setter
    def response_kind(self, response_kind: IoK8sApimachineryPkgApisMetaV1GroupVersionKind) -> None: ...
    @property
    def subresource(self) -> str: ...
    @subresource.setter
    def subresource(self, subresource: str) -> None: ...
    @property
    def verbs(self) -> list[str]: ...
    @verbs.setter
    def verbs(self, verbs: list[str]) -> None: ...
