from datetime import datetime
from kubernetes_asyncio.client.models import V2HorizontalPodAutoscalerCondition
from kubernetes_asyncio.client.models import V2MetricStatus
from typing import Any

class V2HorizontalPodAutoscalerStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, conditions: list[V2HorizontalPodAutoscalerCondition] | None = None, current_metrics: list[V2MetricStatus] | None = None, current_replicas: int | None = None, desired_replicas: int | None = None, last_scale_time: datetime | None = None, observed_generation: int | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def conditions(self) -> list[V2HorizontalPodAutoscalerCondition]: ...
    @conditions.setter
    def conditions(self, conditions: list[V2HorizontalPodAutoscalerCondition]) -> None: ...
    @property
    def current_metrics(self) -> list[V2MetricStatus]: ...
    @current_metrics.setter
    def current_metrics(self, current_metrics: list[V2MetricStatus]) -> None: ...
    @property
    def current_replicas(self) -> int: ...
    @current_replicas.setter
    def current_replicas(self, current_replicas: int) -> None: ...
    @property
    def desired_replicas(self) -> int: ...
    @desired_replicas.setter
    def desired_replicas(self, desired_replicas: int) -> None: ...
    @property
    def last_scale_time(self) -> datetime: ...
    @last_scale_time.setter
    def last_scale_time(self, last_scale_time: datetime) -> None: ...
    @property
    def observed_generation(self) -> int: ...
    @observed_generation.setter
    def observed_generation(self, observed_generation: int) -> None: ...
