from kubernetes_asyncio.client.models import V2CrossVersionObjectReference
from kubernetes_asyncio.client.models import V2HorizontalPodAutoscalerBehavior
from kubernetes_asyncio.client.models import V2MetricSpec
from typing import Any

class V2HorizontalPodAutoscalerSpec:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, behavior: V2HorizontalPodAutoscalerBehavior | None = None, max_replicas: int | None = None, metrics: list[V2MetricSpec] | None = None, min_replicas: int | None = None, scale_target_ref: V2CrossVersionObjectReference | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def behavior(self) -> V2HorizontalPodAutoscalerBehavior: ...
    @behavior.setter
    def behavior(self, behavior: V2HorizontalPodAutoscalerBehavior) -> None: ...
    @property
    def max_replicas(self) -> int: ...
    @max_replicas.setter
    def max_replicas(self, max_replicas: int) -> None: ...
    @property
    def metrics(self) -> list[V2MetricSpec]: ...
    @metrics.setter
    def metrics(self, metrics: list[V2MetricSpec]) -> None: ...
    @property
    def min_replicas(self) -> int: ...
    @min_replicas.setter
    def min_replicas(self, min_replicas: int) -> None: ...
    @property
    def scale_target_ref(self) -> V2CrossVersionObjectReference: ...
    @scale_target_ref.setter
    def scale_target_ref(self, scale_target_ref: V2CrossVersionObjectReference) -> None: ...
