from typing import Any

class V2MetricTarget:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, average_utilization: int | None = None, average_value: str | None = None, type: str | None = None, value: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def average_utilization(self) -> int: ...
    @average_utilization.setter
    def average_utilization(self, average_utilization: int) -> None: ...
    @property
    def average_value(self) -> str: ...
    @average_value.setter
    def average_value(self, average_value: str) -> None: ...
    @property
    def type(self) -> str: ...
    @type.setter
    def type(self, type: str) -> None: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...
