from kubernetes_asyncio.client.models import V2beta1APIResourceDiscovery
from typing import Any

class V2beta1APIVersionDiscovery:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, version: str | None = None, resources: list[V2beta1APIResourceDiscovery] | None = None, freshness: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def freshness(self) -> str: ...
    @freshness.setter
    def freshness(self, freshness: str) -> None: ...
    @property
    def resources(self) -> list[V2beta1APIResourceDiscovery]: ...
    @resources.setter
    def resources(self, resources: list[V2beta1APIResourceDiscovery]) -> None: ...
    @property
    def version(self) -> str: ...
    @version.setter
    def version(self, version: str) -> None: ...
