__title__ = "murmurhash"
__version__ = "1.0.15"
__summary__ = "Cython bindings for MurmurHash"
__uri__ = "https://github.com/explosion/murmurhash"
__author__ = "Explosion"
__email__ = "contact@explosion.ai"
__license__ = "MIT"
