# Generated by devtools/yamaker from nixpkgs 22.11.

LIBRARY()

LICENSE(Zlib)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(1.2.13)

ORIGINAL_SOURCE(https://www.zlib.net/fossils/zlib-1.2.13.tar.gz)

OPENSOURCE_EXPORT_REPLACEMENT(
    CMAKE
    ZLIB
    CMAKE_TARGET
    ZLIB::ZLIB
    CONAN
    zlib/1.2.13
)

ADDINCL(
    GLOBAL contrib/libs/zlib/include
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

NO_SANITIZE_HEADERS()

IF (NOT MSVC)
    CFLAGS(
        -DHAVE_HIDDEN
    )
ENDIF()

SRCS(
    adler32.c
    compress.c
    crc32.c
    deflate.c
    gzclose.c
    gzlib.c
    gzread.c
    gzwrite.c
    infback.c
    inffast.c
    inflate.c
    inftrees.c
    trees.c
    uncompr.c
    zutil.c
)

END()
