PY3TEST()

PEERDIR(
    contrib/python/Cartopy
    contrib/python/pykdtree
)

NO_LINT()

DATA(
    arcadia/contrib/python/Cartopy/cartopy/tests
)

SRCDIR(contrib/python/Cartopy)

PY_SRCS(
    TOP_LEVEL
    cartopy/tests/conftest.py
    cartopy/tests/mpl/conftest.py
)

TEST_SRCS(
    cartopy/tests/__init__.py
    cartopy/tests/crs/__init__.py
    cartopy/tests/crs/helpers.py
    cartopy/tests/crs/test_aitoff.py
    cartopy/tests/crs/test_albers_equal_area.py
    cartopy/tests/crs/test_azimuthal_equidistant.py
    cartopy/tests/crs/test_eckert.py
    cartopy/tests/crs/test_equal_earth.py
    cartopy/tests/crs/test_equidistant_conic.py
    cartopy/tests/crs/test_geostationary.py
    cartopy/tests/crs/test_gnomonic.py
    cartopy/tests/crs/test_hammer.py
    cartopy/tests/crs/test_interrupted_goode_homolosine.py
    cartopy/tests/crs/test_lambert_azimuthal_equal_area.py
    cartopy/tests/crs/test_lambert_conformal.py
    cartopy/tests/crs/test_mercator.py
    cartopy/tests/crs/test_miller.py
    cartopy/tests/crs/test_mollweide.py
    cartopy/tests/crs/test_nearside_perspective.py
    cartopy/tests/crs/test_oblique_mercator.py
    cartopy/tests/crs/test_orthographic.py
    cartopy/tests/crs/test_robinson.py
    cartopy/tests/crs/test_rotated_geodetic.py
    cartopy/tests/crs/test_rotated_pole.py
    cartopy/tests/crs/test_sinusoidal.py
    cartopy/tests/crs/test_spilhaus.py
    cartopy/tests/crs/test_stereographic.py
    cartopy/tests/crs/test_transverse_mercator.py
    cartopy/tests/crs/test_utm.py
    cartopy/tests/feature/__init__.py
    cartopy/tests/feature/test_nightshade.py
    cartopy/tests/io/__init__.py
    #cartopy/tests/io/test_downloaders.py
    cartopy/tests/io/test_ogc_clients.py
    #cartopy/tests/io/test_srtm.py
    cartopy/tests/mpl/__init__.py
    #cartopy/tests/mpl/test_axes.py
    cartopy/tests/mpl/test_boundary.py
    #cartopy/tests/mpl/test_caching.py
    cartopy/tests/mpl/test_contour.py
    #cartopy/tests/mpl/test_crs.py
    #cartopy/tests/mpl/test_examples.py
    cartopy/tests/mpl/test_feature_artist.py
    #cartopy/tests/mpl/test_features.py
    #cartopy/tests/mpl/test_gridliner.py
    #cartopy/tests/mpl/test_images.py
    #cartopy/tests/mpl/test_img_transform.py
    #cartopy/tests/mpl/test_mpl_integration.py
    #cartopy/tests/mpl/test_nightshade.py
    cartopy/tests/mpl/test_path.py
    cartopy/tests/mpl/test_plots.py
    cartopy/tests/mpl/test_pseudo_color.py
    cartopy/tests/mpl/test_quiver.py
    cartopy/tests/mpl/test_set_extent.py
    #cartopy/tests/mpl/test_shapely_to_mpl.py
    cartopy/tests/mpl/test_style.py
    cartopy/tests/mpl/test_ticker.py
    #cartopy/tests/mpl/test_ticks.py
    cartopy/tests/mpl/test_web_services.py
    #cartopy/tests/test_coastline.py
    cartopy/tests/test_coding_standards.py
    cartopy/tests/test_crs.py
    cartopy/tests/test_crs_transform_vectors.py
    cartopy/tests/test_features.py
    cartopy/tests/test_geodesic.py
    #cartopy/tests/test_img_nest.py
    cartopy/tests/test_img_tiles.py
    cartopy/tests/test_img_transform.py
    cartopy/tests/test_line_string.py
    cartopy/tests/test_linear_ring.py
    cartopy/tests/test_polygon.py
    #cartopy/tests/test_shapereader.py
    cartopy/tests/test_util.py
    cartopy/tests/test_vector_transform.py
)

END()
