RECURSE(
    client/draft
    client/draft/ut
    client/extensions
    client/helpers
    client/impl/ydb_endpoints
    client/impl/ydb_endpoints/ut
    client/impl/ydb_internal/common
    client/impl/ydb_internal/db_driver_state
    client/impl/ydb_internal/grpc_connections
    client/impl/ydb_internal/logger
    client/impl/ydb_internal/make_request
    client/impl/ydb_internal/plain_status
    client/impl/ydb_internal/thread_pool
    client/impl/ydb_internal/value_helpers
    client/impl/ydb_stats
    client/resources
    client/ydb_common_client
    client/ydb_common_client/impl
    client/ydb_coordination
    client/ydb_coordination/ut
    client/ydb_datastreams
    client/ydb_discovery
    client/ydb_driver
    client/ydb_driver/ut
    client/ydb_export
    client/ydb_extension
    client/ydb_federated_topic
    client/ydb_federated_topic/impl
    client/ydb_federated_topic/ut
    client/ydb_import
    client/ydb_operation
    client/ydb_params
    client/ydb_params/ut
    client/ydb_persqueue_core
    client/ydb_persqueue_public
    client/ydb_persqueue_public/impl
    client/ydb_persqueue_public/ut
    client/ydb_persqueue_public/ut/ut_utils
    client/ydb_persqueue_public/ut/with_offset_ranges_mode_ut
    client/ydb_proto
    client/ydb_query
    client/ydb_rate_limiter
    client/ydb_result
    client/ydb_result/ut
    client/ydb_scheme
    client/ydb_table
    client/ydb_table/impl
    client/ydb_table/query_stats
    client/ydb_topic
    client/ydb_topic/codecs
    client/ydb_topic/impl
    client/ydb_topic/ut
    client/ydb_types
    client/ydb_types/credentials
    client/ydb_types/exceptions
    client/ydb_types/fatal_error_handlers
    client/ydb_types/operation
    client/ydb_types/status
    client/ydb_value
    client/ydb_value/ut
    examples
)
