__author__ = "Jared Forsyth, Fabio Caccamo"
__copyright__ = "Copyright (c) 2013-present Jared Forsyth / Fabio Caccamo"
__description__ = "color field for django models with a nice color-picker in the admin."
__email__ = "jared@jaredforsyth.com, fabio.caccamo@gmail.com"
__license__ = "MIT"
__title__ = "django-colorfield"
__version__ = "0.14.0"
