# Generated by devtools/yamaker from nixpkgs 22.05.

LIBRARY()

LICENSE(Apache-2.0)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(0.1.14)

ORIGINAL_SOURCE(https://github.com/awslabs/aws-checksums/archive/v0.1.14.tar.gz)

PEERDIR(
    contrib/restricted/aws/aws-c-common
)

ADDINCL(
    GLOBAL contrib/restricted/aws/aws-checksums/include
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

CFLAGS(
    -DAWS_CHECKSUMS_USE_IMPORT_EXPORT
    -DAWS_COMMON_USE_IMPORT_EXPORT
    -DHAVE_SYSCONF
)

IF (BUILD_TYPE == "DEBUG")
    CFLAGS(
        -DDEBUG_BUILD
    )
ENDIF()

SRCS(
    source/crc.c
    source/crc_sw.c
    source/intel/asm/crc32c_sse42_asm.c
)

END()
