// Stub header for building pdfium without Chromium's partition_alloc.
#ifndef PARTITION_ALLOC_PARTITION_ALLOC_BUILDFLAGS_H_
#define PARTITION_ALLOC_PARTITION_ALLOC_BUILDFLAGS_H_

#define BUILDFLAG_INTERNAL_USE_PARTITION_ALLOC() 0
#define BUILDFLAG_INTERNAL_USE_PARTITION_ALLOC_AS_MALLOC() 0
#define BUILDFLAG_INTERNAL_ENABLE_BACKUP_REF_PTR_SUPPORT() 0
#define BUILDFLAG_INTERNAL_ENABLE_RAW_PTR_EXCLUSION() 0
#define BUILDFLAG_INTERNAL_PA_ENABLE_MTE_CHECKED_PTR_SUPPORT() 0
#define BUILDFLAG_INTERNAL_FORCIBLY_ENABLE_BACKUP_REF_PTR_IN_ALL_PROCESSES() 0
#define BUILDFLAG_INTERNAL_ENABLE_BACKUP_REF_PTR_INSTANCE_TRACER() 0
#define BUILDFLAG_INTERNAL_ENABLE_BACKUP_REF_PTR_SLOW_CHECKS() 0
#define BUILDFLAG_INTERNAL_RAW_PTR_ZERO_ON_CONSTRUCT() 0
#define BUILDFLAG_INTERNAL_RAW_PTR_ZERO_ON_MOVE() 0
#define BUILDFLAG_INTERNAL_RAW_PTR_ZERO_ON_DESTRUCT() 0

#endif
