# Generated by devtools/yamaker from nixpkgs 22.11.

LIBRARY()

LICENSE(BSL-1.0)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(1.86.0)

ORIGINAL_SOURCE(https://github.com/boostorg/iostreams/archive/boost-1.86.0.tar.gz)

PEERDIR(
    contrib/libs/libbz2
    contrib/libs/lzma
    contrib/libs/zlib
    contrib/libs/zstd
    contrib/restricted/boost/assert
    contrib/restricted/boost/config
    contrib/restricted/boost/core
    contrib/restricted/boost/detail
    contrib/restricted/boost/function
    contrib/restricted/boost/integer
    contrib/restricted/boost/iterator
    contrib/restricted/boost/mpl
    contrib/restricted/boost/numeric_conversion
    contrib/restricted/boost/preprocessor
    contrib/restricted/boost/random
    contrib/restricted/boost/range
    contrib/restricted/boost/regex
    contrib/restricted/boost/smart_ptr
    contrib/restricted/boost/static_assert
    contrib/restricted/boost/throw_exception
    contrib/restricted/boost/type_traits
    contrib/restricted/boost/utility
)

ADDINCL(
    GLOBAL contrib/restricted/boost/iostreams/include
    contrib/libs/libbz2
    contrib/libs/zstd/include
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DBOOST_IOSTREAMS_USE_DEPRECATED
)

IF (DYNAMIC_BOOST)
    CFLAGS(
        GLOBAL -DBOOST_IOSTREAMS_DYN_LINK
    )
ENDIF()

SRCS(
    src/bzip2.cpp
    src/file_descriptor.cpp
    src/gzip.cpp
    src/lzma.cpp
    src/mapped_file.cpp
    src/zlib.cpp
    src/zstd.cpp
)

END()
