# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(0.1.2)

LICENSE(MIT)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    mdurl/__init__.py
    mdurl/_decode.py
    mdurl/_encode.py
    mdurl/_format.py
    mdurl/_parse.py
    mdurl/_url.py
)

RESOURCE_FILES(
    PREFIX contrib/python/mdurl/
    .dist-info/METADATA
    mdurl/py.typed
)

END()
