syntax = "proto3";

import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/common/common.proto";
import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/common/ydb_operation.proto";

package NLogBroker.NAdmin;

option cc_enable_arenas = true;
option go_package = "a.yandex-team.ru/logbroker/public/api/admin;logbroker_admin";

message ExecuteModifyCommandsRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    repeated SingleModifyRequest actions = 2;
    string comment = 3;
    repeated Prerequisite prerequisites = 4;
    string token = 111;
}

message Prerequisite {
    message SpeedQuota {
        NLogBroker.ClusterKey cluster = 1;
        uint64 bytes_speed_per_sec = 2;
    }

    message Condition {
        oneof condition {
            SpeedQuota rolling_dc_write_quota = 1;
        }
    }

    NLogBroker.Path path = 1;
    NLogBroker.IntOrDefaultValue validate_abc_id = 2;
    repeated Condition conditions = 3;
}

message SingleModifyRequest {
    oneof request {
        CreateAccountRequest create_account = 71;
        CreateDirectoryRequest create_directory = 1;
        CreateTopicRequest create_topic = 2;
        CreateConsumerRequest create_consumer = 3;
        CreateReadRuleRequest create_read_rule = 4;
        CreateAccountTemplateRequest create_account_template = 70;
        CreateTopicTemplateRequest create_topic_template = 72;
        CreateConsumerTemplateRequest create_consumer_template = 73;
        CreateClusterRequest create_cluster = 74;
        CreateYtConsumerRequest create_yt_consumer = 75;
        CreateYdbConsumerRequest create_ydb_consumer = 76;
        CreateShadowClusterRequest create_shadow_cluster = 77;
        CreateRemoteMirrorRuleRequest create_remote_mirror_rule = 78;

        UpdateAccountRateLimitRequest update_account_rate_limit = 98;
        UpdateDirectoryRequest update_directory = 10;
        UpdateTopicRequest update_topic = 11;
        UpdateConsumerRequest update_consumer = 12;
        UpdateReadRuleRequest update_read_rule = 13;
        UpdateRemoteMirrorRuleRequest update_remote_mirror_rule = 14;

        UpdateAccountTemplateRequest update_account_template = 80;
        UpdateAccountRequest update_account = 81;
        UpdateTopicTemplateRequest update_topic_template = 82;
        UpdateConsumerTemplateRequest update_consumer_template = 83;
        UpdateClusterRequest update_cluster = 84;
        UpdateYtConsumerRequest update_yt_consumer = 85;
        UpdateShadowClusterRequest update_shadow_cluster = 86;

        SetAccountRateLimitRequest set_account_rate_limit = 99;
        SetDirectoryRateLimitRequest set_directory_rate_limit = 40;
        SetTopicRateLimitRequest set_topic_rate_limit = 41;
        SetConsumerRateLimitRequest set_consumer_rate_limit = 42;
        SetMetadataRequest set_metadata = 60;

        RemoveClusterRequest remove_cluster = 94;
        RemoveAccountRequest remove_account = 91;
        RemoveDirectoryRequest remove_directory = 20;
        RemoveTopicRequest remove_topic = 21;
        RemoveConsumerRequest remove_consumer = 22;
        RemoveReadRuleRequest remove_read_rule = 23;
        RemoveDirectoryRateLimitRequest remove_directory_rate_limit = 50;
        RemoveTopicRateLimitRequest remove_topic_rate_limit = 51;
        RemoveConsumerRateLimitRequest remove_consumer_rate_limit = 52;
        RemoveMetadataRequest remove_metadata = 61;
        RemoveAccountTemplateRequest remove_account_template = 90;
        RemoveTopicTemplateRequest remove_topic_template = 92;
        RemoveConsumerTemplateRequest remove_consumer_template = 93;
        RemoveYtConsumerRequest remove_yt_consumer = 95;
        RemoveYdbConsumerRequest remove_ydb_consumer = 96;
        RemoveRemoteMirrorRuleRequest remove_remote_mirror_rule = 97;

        GrantPermissionsRequest grant_permissions = 30;
        RevokePermissionsRequest revoke_permissions = 31;
        SetPermissionsRequest set_permissions = 32;
        ChangeOwnerRequest change_owner = 33;

        AlterAllTopicsRequest alter_all_topics = 62;
        SwitchAccountToDatabaseRequest switch_account_to_database = 63;
    }
}

message DescribeClusterRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string name = 2;
    string token = 111;
}

message DescribeClusterResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message DescribeClusterResult {
    string name = 1;
    NLogBroker.ClusterProperties properties = 2;
    NLogBroker.ClusterAdminProperties admin_properties = 3;
    uint64 creation_time_ms = 20;
    uint64 modification_time_ms = 21;
    string created_by = 22;
    string modified_by = 23;
}

message DescribePathRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    NLogBroker.Path path = 2;
    string token = 111;
}

message DescribePathResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message DescribePathResult {
    NLogBroker.Path path = 1;
    oneof result {
        DescribeAccountResult account = 2;
        DescribeDirectoryResult directory = 3;
        DescribeTopicResult topic = 4;
        DescribeConsumerResult consumer = 5;
    }
    uint64 creation_time_ms = 20;
    uint64 modification_time_ms = 21;
    string created_by = 22;
    string modified_by = 23;
}

message DescribeAccountResult {
    string name = 1;
    string parent_template = 2;
    NLogBroker.AccountProperties properties = 3;
    NLogBroker.AccountAdminProperties admin_properties = 10;
    NLogBroker.QuotaUsageProperties quota_usage = 8;
    NLogBroker.AdminQuotaUsageProperties admin_quota_usage = 9;
    repeated NLogBroker.AccountRateLimitProperties account_rate_limits = 14;
    repeated NLogBroker.DirectoryRateLimitProperties rate_limits = 4;
    repeated NLogBroker.Permissions permissions = 5;
    repeated NLogBroker.Permissions effective_permissions = 13;
    repeated NLogBroker.Metadata metadata = 7;
    bool is_related_to_caller = 11;
    string owner = 12;
}

message DescribeDirectoryResult {
    NLogBroker.DirectoryProperties properties = 1;
    NLogBroker.DirectoryAdminProperties admin_properties = 8;
    repeated NLogBroker.DirectoryRateLimitProperties rate_limits = 2;
    repeated NLogBroker.InheritedDirectoryRateLimit inherited_rate_limits = 3;
    repeated NLogBroker.Permissions permissions = 4;
    repeated NLogBroker.Permissions effective_permissions = 5;
    repeated NLogBroker.Metadata metadata = 7;
    string owner = 9;
    uint32 children_count = 10;
}

message DescribeTopicResult {
    message Consumer {
        string path = 1;
        repeated NLogBroker.TopicInstance instances = 2;
    }

    NLogBroker.TopicProperties properties = 1;
    NLogBroker.TopicAdminProperties admin_properties = 2;
    string parent_template = 3;
    repeated NLogBroker.TopicRateLimitProperties rate_limits = 4;
    repeated NLogBroker.InheritedDirectoryRateLimit inherited_rate_limits = 5;
    repeated NLogBroker.Permissions permissions = 6;
    repeated NLogBroker.Permissions effective_permissions = 7;
    repeated NLogBroker.ReadRuleAdmin read_rules = 10;
    repeated NLogBroker.Metadata metadata = 11;
    string owner = 12;
    repeated NLogBroker.TopicInstance instances = 13;
    repeated Consumer consumers = 14;
    repeated NLogBroker.RemoteMirrorRuleAdmin remote_mirror_rules = 15;
}

message DescribeConsumerResult {
    message Topic {
        string path = 1;
        repeated NLogBroker.TopicInstance instances = 2;
    }

    NLogBroker.ConsumerProperties properties = 1;
    NLogBroker.ConsumerAdminProperties admin_properties = 10;
    string parent_template = 2;
    repeated NLogBroker.ConsumerRateLimitProperties rate_limits = 3;
    repeated NLogBroker.InheritedDirectoryRateLimit inherited_rate_limits = 4;
    repeated NLogBroker.Permissions permissions = 5;
    repeated NLogBroker.Permissions effective_permissions = 6;
    repeated NLogBroker.ReadRuleAdmin read_rules = 8;
    repeated NLogBroker.Metadata metadata = 9;
    string owner = 11;
    repeated Topic topics = 12;
}

message DescribeYtConsumerRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    NLogBroker.Path path = 2;
    string token = 111;
}

message DescribeYtConsumerResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message DescribeYtConsumerResult {
    NLogBroker.Path path = 1;
    NLogBroker.YtConsumerProperties properties = 3;
    uint64 creation_time_ms = 20;
    uint64 modification_time_ms = 21;
    string created_by = 22;
    string modified_by = 23;
}

message DescribeYdbConsumerRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    NLogBroker.Path path = 2;
    string token = 111;
}

message DescribeYdbConsumerResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message DescribeYdbConsumerResult {
    NLogBroker.Path path = 1;
    uint64 creation_time_ms = 20;
    uint64 modification_time_ms = 21;
    string created_by = 22;
    string modified_by = 23;
}

message DescribeAccountTemplateRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string name = 2;
    string token = 111;
}

message DescribeAccountTemplateResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message DescribeAccountTemplateResult {
    string name = 1;
    NLogBroker.AccountProperties properties = 2;
    NLogBroker.AccountAdminProperties admin_properties = 3;
    uint64 creation_time_ms = 20;
    uint64 modification_time_ms = 21;
    string created_by = 22;
    string modified_by = 23;
}

message DescribeTopicTemplateRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string name = 2;
    string token = 111;
}

message DescribeTopicTemplateResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message DescribeTopicTemplateResult {
    string name = 1;
    NLogBroker.TopicProperties properties = 2;
    NLogBroker.TopicAdminProperties admin_properties = 3;
    uint64 creation_time_ms = 20;
    uint64 modification_time_ms = 21;
    string created_by = 22;
    string modified_by = 23;
}

message DescribeConsumerTemplateRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string name = 2;
    string token = 111;
}

message DescribeConsumerTemplateResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message DescribeConsumerTemplateResult {
    string name = 1;
    NLogBroker.ConsumerProperties properties = 2;
    NLogBroker.ConsumerAdminProperties admin_properties = 3;
    uint64 creation_time_ms = 20;
    uint64 modification_time_ms = 21;
    string created_by = 22;
    string modified_by = 23;
}

message ListClustersRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string token = 111;
}

message ListClustersResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message ListClustersResult {
    repeated string names = 1;
}

message ListAccountsRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string token = 111;
}

message ListAccountsResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message ListAccountsResult {
    repeated string names = 1;
}

message ListAccountsAndDescribeRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    bool extended_information = 2;
    repeated NLogBroker.ListFilter filter = 3;
    string token = 111;
}

message ListAccountsAndDescribeResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message ListAccountsAndDescribeResult {
    repeated NLogBroker.BasicDescribeAccountResult accounts = 1;
}

message ListDirectoryRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    NLogBroker.Path path = 2;
    string token = 111;
}

message ListDirectoryResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message ListDirectoryResult {
    NLogBroker.Path path = 1;
    NLogBroker.Entry self = 2;
    repeated NLogBroker.Entry children = 3;
}

message ListYtConsumersRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string token = 111;
}

message ListYtConsumersResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message ListYtConsumersResult {
    repeated string names = 1;
}

message ListYdbConsumersRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string token = 111;
}

message ListYdbConsumersResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message ListYdbConsumersResult {
    repeated string names = 1;
}

message ListAccountTemplatesRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string token = 111;
}

message ListAccountTemplatesResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message ListAccountTemplatesResult {
    repeated string names = 1;
}

message ListTopicTemplatesRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string token = 111;
}

message ListTopicTemplatesResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message ListTopicTemplatesResult {
    repeated string names = 1;
}

message ListConsumerTemplatesRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string token = 111;
}

message ListConsumerTemplatesResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message ListConsumerTemplatesResult {
    repeated string names = 1;
}

message CreateClusterRequest {
    string name = 1;
    NLogBroker.ClusterProperties properties = 2;
    NLogBroker.ClusterAdminProperties admin_properties = 3;
}

message CreateShadowClusterRequest {
    string name = 1;
    string shadow_for = 2;
    NLogBroker.ClusterProperties properties = 3;
    NLogBroker.ClusterAdminProperties admin_properties = 4;
}

message CreateAccountRequest {
    string name = 1;
    string parent_template = 2;
    NLogBroker.AccountProperties properties = 3;
    NLogBroker.AccountAdminProperties admin_properties = 4;
    NLogBroker.BoolOrDefaultValue validate_accounts_count = 5;
}

message CreateDirectoryRequest {
    NLogBroker.Path path = 1;
    NLogBroker.DirectoryProperties properties = 2;
    NLogBroker.DirectoryAdminProperties admin_properties = 3;
}

message CreateTopicRequest {
    NLogBroker.Path path = 1;
    string parent_template = 2;
    NLogBroker.TopicProperties properties = 3;
    NLogBroker.TopicAdminProperties admin_properties = 4;
}

message CreateConsumerRequest {
    NLogBroker.Path path = 1;
    string parent_template = 2;
    NLogBroker.ConsumerProperties properties = 3;
    NLogBroker.ConsumerAdminProperties admin_properties = 4;
}

message CreateReadRuleRequest {
    NLogBroker.ReadRuleKey read_rule = 1;
    NLogBroker.ReadRuleProperties properties = 2;
    NLogBroker.ReadRuleAdminProperties admin_properties = 3;
}

message CreateRemoteMirrorRuleRequest {
    NLogBroker.RemoteMirrorRuleKey remote_mirror_rule = 1;
    NLogBroker.RemoteMirrorRuleProperties properties = 2;
    NLogBroker.RemoteMirrorRuleAdminProperties admin_properties = 3;
}

message CreateYtConsumerRequest {
    NLogBroker.Path path = 1;
    string parent_template = 2;
    NLogBroker.ConsumerProperties consumer_properties = 3;
    NLogBroker.ConsumerAdminProperties consumer_admin_properties = 5;
    NLogBroker.YtConsumerProperties yt_consumer_properties = 4;
}

message CreateYdbConsumerRequest {
    NLogBroker.Path path = 1;
    string parent_template = 2;
    NLogBroker.ConsumerProperties consumer_properties = 3;
    NLogBroker.ConsumerAdminProperties consumer_admin_properties = 5;
}

message CreateAccountTemplateRequest {
    string name = 1;
    NLogBroker.AccountProperties properties = 2;
    NLogBroker.AccountAdminProperties admin_properties = 3;
}

message CreateTopicTemplateRequest {
    string name = 1;
    NLogBroker.TopicProperties properties = 2;
    NLogBroker.TopicAdminProperties admin_properties = 3;
}

message CreateConsumerTemplateRequest {
    string name = 1;
    NLogBroker.ConsumerProperties properties = 2;
    NLogBroker.ConsumerAdminProperties admin_properties = 3;
}

message UpdateClusterRequest {
    string name = 1;
    NLogBroker.ClusterProperties properties = 2;
    NLogBroker.ClusterAdminProperties admin_properties = 3;
}

message UpdateShadowClusterRequest {
    string name = 1;
    string shadow_for = 2;
    NLogBroker.ClusterProperties properties = 3;
    NLogBroker.ClusterAdminProperties admin_properties = 4;
}

message UpdateAccountRequest {
    string name = 1;
    NLogBroker.AccountProperties properties = 2;
    NLogBroker.AccountAdminProperties admin_properties = 3;
}

message UpdateDirectoryRequest {
    NLogBroker.Path path = 1;
    NLogBroker.DirectoryProperties properties = 2;
    NLogBroker.DirectoryAdminProperties admin_properties = 3;
}

message UpdateTopicRequest {
    NLogBroker.Path path = 1;
    NLogBroker.TopicProperties properties = 2;
    NLogBroker.TopicAdminProperties admin_properties = 3;
}

message UpdateConsumerRequest {
    NLogBroker.Path path = 1;
    NLogBroker.ConsumerProperties properties = 2;
    NLogBroker.ConsumerAdminProperties admin_properties = 3;
}

message UpdateReadRuleRequest {
    NLogBroker.ReadRuleKey read_rule = 1;
    NLogBroker.ReadRuleProperties properties = 2;
    NLogBroker.ReadRuleAdminProperties admin_properties = 3;
}

message UpdateYtConsumerRequest {
    NLogBroker.Path path = 1;
    NLogBroker.YtConsumerProperties properties = 2;
}

message UpdateAccountTemplateRequest {
    string name = 1;
    NLogBroker.AccountProperties properties = 2;
    NLogBroker.AccountAdminProperties admin_properties = 3;
}

message UpdateTopicTemplateRequest {
    string name = 1;
    NLogBroker.TopicProperties properties = 2;
    NLogBroker.TopicAdminProperties admin_properties = 3;
}

message UpdateConsumerTemplateRequest {
    string name = 1;
    NLogBroker.ConsumerProperties properties = 2;
    NLogBroker.ConsumerAdminProperties admin_properties = 3;
}

message UpdateRemoteMirrorRuleRequest {
    NLogBroker.RemoteMirrorRuleKey remote_mirror_rule = 1;
    NLogBroker.RemoteMirrorRuleProperties properties = 2;
    NLogBroker.RemoteMirrorRuleAdminProperties admin_properties = 3;
}

message UpdateAccountRateLimitRequest {
    NLogBroker.Path path = 1;
    NLogBroker.AccountRateLimitProperties rate_limit = 2;
}

message SetAccountRateLimitRequest {
    NLogBroker.Path path = 1;
    NLogBroker.AccountRateLimitProperties rate_limit = 2;
}

message SetDirectoryRateLimitRequest {
    NLogBroker.Path path = 1;
    NLogBroker.DirectoryRateLimitProperties rate_limit = 2;
}

message SetTopicRateLimitRequest {
    NLogBroker.Path path = 1;
    NLogBroker.TopicRateLimitProperties rate_limit = 2;
}

message SetConsumerRateLimitRequest {
    NLogBroker.Path path = 1;
    NLogBroker.ConsumerRateLimitProperties rate_limit = 2;
}

message SetMetadataRequest {
    NLogBroker.Path path = 1;
    NLogBroker.Metadata metadata = 2;
}

message RemoveClusterRequest {
    string name = 1;
}

message RemoveAccountRequest {
    string name = 1;
}

message RemoveDirectoryRequest {
    NLogBroker.Path path = 1;
}

message RemoveTopicRequest {
    NLogBroker.Path path = 1;
}

message RemoveConsumerRequest {
    NLogBroker.Path path = 1;
}

message RemoveReadRuleRequest {
    NLogBroker.ReadRuleKey read_rule = 1;
}

message RemoveRemoteMirrorRuleRequest {
    NLogBroker.RemoteMirrorRuleKey remote_mirror_rule = 1;
}

message RemoveYtConsumerRequest {
    NLogBroker.Path path = 1;
}

message RemoveYdbConsumerRequest {
    NLogBroker.Path path = 1;
}

message RemoveDirectoryRateLimitRequest {
    NLogBroker.ClusterKey cluster = 2;
    NLogBroker.Path path = 1;
}

message RemoveTopicRateLimitRequest {
    NLogBroker.ClusterKey cluster = 2;
    NLogBroker.Path path = 1;
}

message RemoveConsumerRateLimitRequest {
    NLogBroker.ClusterKey cluster = 2;
    NLogBroker.Path path = 1;
}

message RemoveMetadataRequest {
    NLogBroker.Path path = 1;
    string key = 2;
}

message RemoveAccountTemplateRequest {
    string name = 1;
}

message RemoveTopicTemplateRequest {
    string name = 1;
}

message RemoveConsumerTemplateRequest {
    string name = 1;
}

message GrantPermissionsRequest {
    NLogBroker.Path path = 1;
    repeated NLogBroker.Permissions permissions = 2;
}

message RevokePermissionsRequest {
    NLogBroker.Path path = 1;
    repeated NLogBroker.Permissions permissions = 2;
}

message SetPermissionsRequest {
    NLogBroker.Path path = 1;
    repeated NLogBroker.Permissions permissions = 2;
}

message ChangeOwnerRequest {
    NLogBroker.Path path = 1;
    string owner = 2;
}

message SwitchAccountToDatabaseRequest {
    string name = 1;
}

message AlterAllTopicsRequest {
}

message GetCurrentVersionRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    uint64 desired_version = 2;
}

message GetCurrentVersionResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message GetCurrentVersionResult {
    uint64 version = 1;
    uint64 current_version = 2;
}

message GetBackendVersionsRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
}

message GetBackendVersionsResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message GetBackendVersionsResult {
    message BackendVersion {
        string name = 1;
        uint64 version = 2;
    }
    repeated BackendVersion backend_versions = 1;
}

message GetCommandsLogRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    uint64 start_version = 2;
    uint32 logs_count = 3;
}

message GetCommandsLogResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message GetCommandsLogResult {
    message TLogEntry {
        uint64 version = 1;
        ExecuteModifyCommandsRequest request = 2;
    }
    repeated TLogEntry log_enties = 1;
}
