PY2_LIBRARY()

LICENSE(MIT)

VERSION(20.3.0)

NO_CHECK_IMPORTS(
    twisted.*
)

PEERDIR(
    contrib/python/Automat
    contrib/python/attrs
    contrib/python/constantly
    contrib/python/hyperlink
    contrib/python/incremental
    contrib/python/pyOpenSSL
    contrib/python/Twisted/py2/twisted/python
    contrib/python/zope.interface
)

NO_LINT()

NO_COMPILER_WARNINGS()

PY_SRCS(
    TOP_LEVEL
    twisted/__init__.py
    twisted/_threads/__init__.py
    twisted/_threads/_convenience.py
    twisted/_threads/_ithreads.py
    twisted/_threads/_memory.py
    twisted/_threads/_pool.py
    twisted/_threads/_team.py
    twisted/_threads/_threadworker.py
    twisted/_version.py
    twisted/application/__init__.py
    twisted/application/app.py
    twisted/application/internet.py
    twisted/application/reactors.py
    twisted/application/runner/__init__.py
    twisted/application/runner/_exit.py
    twisted/application/runner/_pidfile.py
    twisted/application/runner/_runner.py
    twisted/application/service.py
    twisted/application/strports.py
    twisted/application/twist/__init__.py
    twisted/application/twist/_options.py
    twisted/application/twist/_twist.py
    twisted/conch/__init__.py
    twisted/conch/avatar.py
    twisted/conch/checkers.py
    twisted/conch/client/__init__.py
    twisted/conch/client/agent.py
    twisted/conch/client/connect.py
    twisted/conch/client/default.py
    twisted/conch/client/direct.py
    twisted/conch/client/knownhosts.py
    twisted/conch/client/options.py
    twisted/conch/endpoints.py
    twisted/conch/error.py
    twisted/conch/insults/__init__.py
    twisted/conch/insults/helper.py
    twisted/conch/insults/insults.py
    twisted/conch/insults/text.py
    twisted/conch/insults/window.py
    twisted/conch/interfaces.py
    twisted/conch/ls.py
    twisted/conch/manhole.py
    twisted/conch/manhole_ssh.py
    twisted/conch/manhole_tap.py
    twisted/conch/mixin.py
    twisted/conch/openssh_compat/__init__.py
    twisted/conch/openssh_compat/factory.py
    twisted/conch/openssh_compat/primes.py
    twisted/conch/recvline.py
    twisted/conch/ssh/__init__.py
    twisted/conch/ssh/_kex.py
    twisted/conch/ssh/address.py
    twisted/conch/ssh/agent.py
    twisted/conch/ssh/channel.py
    twisted/conch/ssh/common.py
    twisted/conch/ssh/connection.py
    twisted/conch/ssh/factory.py
    twisted/conch/ssh/filetransfer.py
    twisted/conch/ssh/forwarding.py
    twisted/conch/ssh/keys.py
    twisted/conch/ssh/service.py
    twisted/conch/ssh/session.py
    twisted/conch/ssh/sexpy.py
    twisted/conch/ssh/transport.py
    twisted/conch/ssh/userauth.py
    twisted/conch/stdio.py
    twisted/conch/tap.py
    twisted/conch/telnet.py
    twisted/conch/ttymodes.py
    twisted/conch/ui/__init__.py
    twisted/conch/ui/ansi.py
    twisted/conch/ui/tkvt100.py
    twisted/conch/unix.py
    twisted/copyright.py
    twisted/cred/__init__.py
    twisted/cred/_digest.py
    twisted/cred/checkers.py
    twisted/cred/credentials.py
    twisted/cred/error.py
    twisted/cred/portal.py
    twisted/cred/strcred.py
    twisted/enterprise/__init__.py
    twisted/enterprise/adbapi.py
    twisted/internet/__init__.py
    twisted/internet/_baseprocess.py
    twisted/internet/_dumbwin32proc.py
    twisted/internet/_glibbase.py
    twisted/internet/_idna.py
    twisted/internet/_newtls.py
    twisted/internet/_pollingfile.py
    twisted/internet/_posixserialport.py
    twisted/internet/_posixstdio.py
    twisted/internet/_producer_helpers.py
    twisted/internet/_resolver.py
    twisted/internet/_signals.py
    twisted/internet/_sslverify.py
    twisted/internet/_threadedselect.py
    twisted/internet/_win32serialport.py
    twisted/internet/_win32stdio.py
    twisted/internet/abstract.py
    twisted/internet/address.py
    twisted/internet/asyncioreactor.py
    twisted/internet/base.py
    twisted/internet/cfreactor.py
    twisted/internet/default.py
    twisted/internet/defer.py
    twisted/internet/endpoints.py
    twisted/internet/epollreactor.py
    twisted/internet/error.py
    twisted/internet/fdesc.py
    twisted/internet/gireactor.py
    twisted/internet/glib2reactor.py
    twisted/internet/gtk2reactor.py
    twisted/internet/gtk3reactor.py
    twisted/internet/inotify.py
    twisted/internet/interfaces.py
    twisted/internet/iocpreactor/__init__.py
    twisted/internet/iocpreactor/abstract.py
    twisted/internet/iocpreactor/const.py
    twisted/internet/iocpreactor/interfaces.py
    twisted/internet/iocpreactor/reactor.py
    twisted/internet/iocpreactor/setup.py
    twisted/internet/iocpreactor/tcp.py
    twisted/internet/iocpreactor/udp.py
    twisted/internet/kqreactor.py
    twisted/internet/main.py
    twisted/internet/pollreactor.py
    twisted/internet/posixbase.py
    twisted/internet/process.py
    twisted/internet/protocol.py
    twisted/internet/pyuisupport.py
    twisted/internet/reactor.py
    twisted/internet/selectreactor.py
    twisted/internet/serialport.py
    twisted/internet/ssl.py
    twisted/internet/stdio.py
    twisted/internet/task.py
    twisted/internet/tcp.py
    twisted/internet/testing.py
    twisted/internet/threads.py
    twisted/internet/tksupport.py
    twisted/internet/udp.py
    twisted/internet/unix.py
    twisted/internet/utils.py
    twisted/internet/win32eventreactor.py
    twisted/internet/wxreactor.py
    twisted/internet/wxsupport.py
    twisted/logger/__init__.py
    twisted/logger/_buffer.py
    twisted/logger/_capture.py
    twisted/logger/_file.py
    twisted/logger/_filter.py
    twisted/logger/_flatten.py
    twisted/logger/_format.py
    twisted/logger/_global.py
    twisted/logger/_io.py
    twisted/logger/_json.py
    twisted/logger/_legacy.py
    twisted/logger/_levels.py
    twisted/logger/_logger.py
    twisted/logger/_observer.py
    twisted/logger/_stdlib.py
    twisted/logger/_util.py
    twisted/mail/__init__.py
    twisted/mail/_cred.py
    twisted/mail/_except.py
    twisted/mail/alias.py
    twisted/mail/bounce.py
    twisted/mail/imap4.py
    twisted/mail/interfaces.py
    twisted/mail/mail.py
    twisted/mail/maildir.py
    twisted/mail/pb.py
    twisted/mail/pop3.py
    twisted/mail/pop3client.py
    twisted/mail/protocols.py
    twisted/mail/relay.py
    twisted/mail/relaymanager.py
    twisted/mail/smtp.py
    twisted/mail/tap.py
    twisted/names/__init__.py
    twisted/names/_rfc1982.py
    twisted/names/authority.py
    twisted/names/cache.py
    twisted/names/client.py
    twisted/names/common.py
    twisted/names/dns.py
    twisted/names/error.py
    twisted/names/hosts.py
    twisted/names/resolve.py
    twisted/names/root.py
    twisted/names/secondary.py
    twisted/names/server.py
    twisted/names/srvconnect.py
    twisted/names/tap.py
    twisted/news/__init__.py
    twisted/news/database.py
    twisted/news/news.py
    twisted/news/nntp.py
    twisted/news/tap.py
    twisted/pair/__init__.py
    twisted/pair/ethernet.py
    twisted/pair/ip.py
    twisted/pair/raw.py
    twisted/pair/rawudp.py
    twisted/pair/testing.py
    twisted/pair/tuntap.py
    twisted/persisted/__init__.py
    twisted/persisted/aot.py
    twisted/persisted/crefutil.py
    twisted/persisted/dirdbm.py
    twisted/persisted/sob.py
    twisted/persisted/styles.py
    twisted/plugin.py
    twisted/plugins/__init__.py
    twisted/plugins/cred_anonymous.py
    twisted/plugins/cred_file.py
    twisted/plugins/cred_memory.py
    twisted/plugins/cred_sshkeys.py
    twisted/plugins/cred_unix.py
    twisted/plugins/twisted_conch.py
    twisted/plugins/twisted_core.py
    twisted/plugins/twisted_ftp.py
    twisted/plugins/twisted_inet.py
    twisted/plugins/twisted_mail.py
    twisted/plugins/twisted_names.py
    twisted/plugins/twisted_news.py
    twisted/plugins/twisted_portforward.py
    twisted/plugins/twisted_reactors.py
    twisted/plugins/twisted_runner.py
    twisted/plugins/twisted_socks.py
    twisted/plugins/twisted_trial.py
    twisted/plugins/twisted_web.py
    twisted/plugins/twisted_words.py
    twisted/positioning/__init__.py
    twisted/positioning/_sentence.py
    twisted/positioning/base.py
    twisted/positioning/ipositioning.py
    twisted/positioning/nmea.py
    twisted/protocols/__init__.py
    twisted/protocols/amp.py
    twisted/protocols/basic.py
    twisted/protocols/dict.py
    twisted/protocols/finger.py
    twisted/protocols/ftp.py
    twisted/protocols/haproxy/__init__.py
    twisted/protocols/haproxy/_exceptions.py
    twisted/protocols/haproxy/_info.py
    twisted/protocols/haproxy/_interfaces.py
    twisted/protocols/haproxy/_parser.py
    twisted/protocols/haproxy/_v1parser.py
    twisted/protocols/haproxy/_v2parser.py
    twisted/protocols/haproxy/_wrapper.py
    twisted/protocols/htb.py
    twisted/protocols/ident.py
    twisted/protocols/loopback.py
    twisted/protocols/memcache.py
    twisted/protocols/pcp.py
    twisted/protocols/policies.py
    twisted/protocols/portforward.py
    twisted/protocols/postfix.py
    twisted/protocols/shoutcast.py
    twisted/protocols/sip.py
    twisted/protocols/socks.py
    twisted/protocols/stateful.py
    twisted/protocols/tls.py
    twisted/protocols/wire.py
    twisted/python/__init__.py
    twisted/python/_appdirs.py
    twisted/python/_inotify.py
    twisted/python/_pydoctor.py
    twisted/python/_release.py
    twisted/python/_setup.py
    twisted/python/_shellcomp.py
    twisted/python/_textattributes.py
    twisted/python/_tzhelper.py
    twisted/python/_url.py
    twisted/python/constants.py
    twisted/python/context.py
    twisted/python/failure.py
    twisted/python/fakepwd.py
    twisted/python/finalize.py
    twisted/python/formmethod.py
    twisted/python/hook.py
    twisted/python/htmlizer.py
    twisted/python/lockfile.py
    twisted/python/log.py
    twisted/python/logfile.py
    twisted/python/monkey.py
    twisted/python/procutils.py
    twisted/python/randbytes.py
    twisted/python/rebuild.py
    twisted/python/release.py
    twisted/python/roots.py
    twisted/python/sendmsg.py
    twisted/python/shortcut.py
    twisted/python/syslog.py
    twisted/python/systemd.py
    twisted/python/text.py
    twisted/python/threadable.py
    twisted/python/threadpool.py
    twisted/python/url.py
    twisted/python/urlpath.py
    twisted/python/usage.py
    twisted/python/versions.py
    twisted/python/zipstream.py
    twisted/runner/__init__.py
    twisted/runner/inetd.py
    twisted/runner/inetdconf.py
    twisted/runner/inetdtap.py
    twisted/runner/procmon.py
    twisted/runner/procmontap.py
    twisted/scripts/__init__.py
    twisted/scripts/_twistd_unix.py
    twisted/scripts/_twistw.py
    twisted/scripts/htmlizer.py
    twisted/scripts/trial.py
    twisted/scripts/twistd.py
    twisted/spread/__init__.py
    twisted/spread/banana.py
    twisted/spread/flavors.py
    twisted/spread/interfaces.py
    twisted/spread/jelly.py
    twisted/spread/pb.py
    twisted/spread/publish.py
    twisted/spread/util.py
    twisted/tap/__init__.py
    twisted/tap/ftp.py
    twisted/tap/portforward.py
    twisted/tap/socks.py
    twisted/trial/__init__.py
    twisted/trial/__main__.py
    twisted/trial/_asyncrunner.py
    twisted/trial/_asynctest.py
    twisted/trial/_dist/__init__.py
    twisted/trial/_dist/distreporter.py
    twisted/trial/_dist/disttrial.py
    twisted/trial/_dist/managercommands.py
    twisted/trial/_dist/options.py
    twisted/trial/_dist/worker.py
    twisted/trial/_dist/workercommands.py
    twisted/trial/_dist/workerreporter.py
    twisted/trial/_dist/workertrial.py
    twisted/trial/_synctest.py
    twisted/trial/itrial.py
    twisted/trial/reporter.py
    twisted/trial/runner.py
    twisted/trial/unittest.py
    twisted/trial/util.py
    twisted/web/__init__.py
    twisted/web/_auth/__init__.py
    twisted/web/_auth/basic.py
    twisted/web/_auth/digest.py
    twisted/web/_auth/wrapper.py
    twisted/web/_element.py
    twisted/web/_flatten.py
    twisted/web/_http2.py
    twisted/web/_newclient.py
    twisted/web/_responses.py
    twisted/web/_stan.py
    twisted/web/client.py
    twisted/web/demo.py
    twisted/web/distrib.py
    twisted/web/domhelpers.py
    twisted/web/error.py
    twisted/web/guard.py
    twisted/web/html.py
    twisted/web/http.py
    twisted/web/http_headers.py
    twisted/web/iweb.py
    twisted/web/microdom.py
    twisted/web/proxy.py
    twisted/web/resource.py
    twisted/web/rewrite.py
    twisted/web/script.py
    twisted/web/server.py
    twisted/web/soap.py
    twisted/web/static.py
    twisted/web/sux.py
    twisted/web/tap.py
    twisted/web/template.py
    twisted/web/test/requesthelper.py
    twisted/web/twcgi.py
    twisted/web/util.py
    twisted/web/vhost.py
    twisted/web/wsgi.py
    twisted/web/xmlrpc.py
    twisted/words/__init__.py
    twisted/words/ewords.py
    twisted/words/im/__init__.py
    twisted/words/im/baseaccount.py
    twisted/words/im/basechat.py
    twisted/words/im/basesupport.py
    twisted/words/im/interfaces.py
    twisted/words/im/ircsupport.py
    twisted/words/im/locals.py
    twisted/words/im/pbsupport.py
    twisted/words/iwords.py
    twisted/words/protocols/__init__.py
    twisted/words/protocols/irc.py
    twisted/words/protocols/jabber/__init__.py
    twisted/words/protocols/jabber/client.py
    twisted/words/protocols/jabber/component.py
    twisted/words/protocols/jabber/error.py
    twisted/words/protocols/jabber/ijabber.py
    twisted/words/protocols/jabber/jid.py
    twisted/words/protocols/jabber/jstrports.py
    twisted/words/protocols/jabber/sasl.py
    twisted/words/protocols/jabber/sasl_mechanisms.py
    twisted/words/protocols/jabber/xmlstream.py
    twisted/words/protocols/jabber/xmpp_stringprep.py
    twisted/words/service.py
    twisted/words/tap.py
    twisted/words/xish/__init__.py
    twisted/words/xish/domish.py
    twisted/words/xish/utility.py
    twisted/words/xish/xmlstream.py
    twisted/words/xish/xpath.py
    twisted/words/xish/xpathparser.py
    twisted/words/xmpproutertap.py
)

IF (OS_WINDOWS)
    SRCS(
        twisted/internet/iocpreactor/iocpsupport/iocpsupport.c
        twisted/internet/iocpreactor/iocpsupport/winsock_pointers.c
    )

    PY_REGISTER(iocpsupport)
ELSE()
    SRCS(
        twisted/python/_sendmsg.c
    )

    PY_REGISTER(_sendmsg)
ENDIF ()

RESOURCE_FILES(
    PREFIX contrib/python/Twisted/py2/
    .dist-info/METADATA
    .dist-info/entry_points.txt
    .dist-info/top_level.txt
)

END()
