# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(0.70.19)

LICENSE(BSD-3-Clause)

PEERDIR(
    contrib/python/dill
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    _multiprocess/__init__.py
    multiprocess/__info__.py
    multiprocess/__init__.py
    multiprocess/connection.py
    multiprocess/context.py
    multiprocess/dummy/__init__.py
    multiprocess/dummy/connection.py
    multiprocess/forkserver.py
    multiprocess/heap.py
    multiprocess/managers.py
    multiprocess/pool.py
    multiprocess/popen_fork.py
    multiprocess/popen_forkserver.py
    multiprocess/popen_spawn_posix.py
    multiprocess/popen_spawn_win32.py
    multiprocess/process.py
    multiprocess/queues.py
    multiprocess/reduction.py
    multiprocess/resource_sharer.py
    multiprocess/resource_tracker.py
    multiprocess/shared_memory.py
    multiprocess/sharedctypes.py
    multiprocess/spawn.py
    multiprocess/synchronize.py
    multiprocess/util.py
)

RESOURCE_FILES(
    PREFIX contrib/python/multiprocess/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
