LIBRARY()

RESOURCE(
    api/css/print.css /mvp/content/api/css/print.css
    api/css/reset.css /mvp/content/api/css/reset.css
    api/css/screen.css /mvp/content/api/css/screen.css
    api/css/style.css /mvp/content/api/css/style.css
    api/css/typography.css /mvp/content/api/css/typography.css
    api/fonts/DroidSans-Bold.ttf /mvp/content/api/fonts/DroidSans-Bold.ttf
    api/fonts/DroidSans.ttf /mvp/content/api/fonts/DroidSans.ttf
    api/images/collapse.gif /mvp/content/api/images/collapse.gif
    api/images/expand.gif /mvp/content/api/images/expand.gif
    api/images/explorer_icons.png /mvp/content/api/images/explorer_icons.png
    api/images/favicon-16x16.png /mvp/content/api/images/favicon-16x16.png
    api/images/favicon-32x32.png /mvp/content/api/images/favicon-32x32.png
    api/images/favicon.ico /mvp/content/api/images/favicon.ico
    api/images/logo_small.png /mvp/content/api/images/logo_small.png
    api/images/throbber.gif /mvp/content/api/images/throbber.gif
    api/index.html /mvp/content/api/index.html
    api/lang/ca.js /mvp/content/api/lang/ca.js
    api/lang/en.js /mvp/content/api/lang/en.js
    api/lang/es.js /mvp/content/api/lang/es.js
    api/lang/fr.js /mvp/content/api/lang/fr.js
    api/lang/geo.js /mvp/content/api/lang/geo.js
    api/lang/it.js /mvp/content/api/lang/it.js
    api/lang/ja.js /mvp/content/api/lang/ja.js
    api/lang/ko-kr.js /mvp/content/api/lang/ko-kr.js
    api/lang/pl.js /mvp/content/api/lang/pl.js
    api/lang/pt.js /mvp/content/api/lang/pt.js
    api/lang/ru.js /mvp/content/api/lang/ru.js
    api/lang/tr.js /mvp/content/api/lang/tr.js
    api/lang/translator.js /mvp/content/api/lang/translator.js
    api/lang/zh-cn.js /mvp/content/api/lang/zh-cn.js
    api/lib/backbone-min.js /mvp/content/api/lib/backbone-min.js
    api/lib/es5-shim.js /mvp/content/api/lib/es5-shim.js
    api/lib/handlebars-4.0.5.js /mvp/content/api/lib/handlebars-4.0.5.js
    api/lib/highlight.9.1.0.pack.js /mvp/content/api/lib/highlight.9.1.0.pack.js
    api/lib/highlight.9.1.0.pack_extended.js /mvp/content/api/lib/highlight.9.1.0.pack_extended.js
    api/lib/jquery-1.8.0.min.js /mvp/content/api/lib/jquery-1.8.0.min.js
    api/lib/jquery.ba-bbq.min.js /mvp/content/api/lib/jquery.ba-bbq.min.js
    api/lib/jquery.slideto.min.js /mvp/content/api/lib/jquery.slideto.min.js
    api/lib/jquery.wiggle.min.js /mvp/content/api/lib/jquery.wiggle.min.js
    api/lib/js-yaml.min.js /mvp/content/api/lib/js-yaml.min.js
    api/lib/jsoneditor.min.js /mvp/content/api/lib/jsoneditor.min.js
    api/lib/lodash.min.js /mvp/content/api/lib/lodash.min.js
    api/lib/marked.js /mvp/content/api/lib/marked.js
    api/lib/object-assign-pollyfill.js /mvp/content/api/lib/object-assign-pollyfill.js
    api/lib/sanitize-html.min.js /mvp/content/api/lib/sanitize-html.min.js
    api/lib/swagger-oauth.js /mvp/content/api/lib/swagger-oauth.js
    api/swagger-ui.min.js /mvp/content/api/swagger-ui.min.js
    api/index.html /mvp/api/index.html
    api/schemes/logbroker/operation.json /mvp/content/api/schemes/logbroker/operation.json
    api/schemes/logbroker/error.json /mvp/content/api/schemes/logbroker/error.json
    api/schemes/logbroker/status.json /mvp/content/api/schemes/logbroker/status.json
    api/schemes/logbroker/io_average_speed.json /mvp/content/api/schemes/logbroker/io_average_speed.json
    api/schemes/logbroker/topic_instance.json /mvp/content/api/schemes/logbroker/topic_instance.json
    api/schemes/logbroker/installations.json /mvp/content/api/schemes/logbroker/installations.json
    api/schemes/logbroker/describe.json /mvp/content/api/schemes/logbroker/describe.json
    api/schemes/logbroker/list.json /mvp/content/api/schemes/logbroker/list.json
    api/schemes/logbroker/describe_dynamic.json /mvp/content/api/schemes/logbroker/describe_dynamic.json
    api/schemes/logbroker/list_dynamic.json /mvp/content/api/schemes/logbroker/list_dynamic.json
    api/schemes/logbroker/list_topic_partitions_dynamic.json /mvp/content/api/schemes/logbroker/list_topic_partitions_dynamic.json
    api/schemes/logbroker/modify.json /mvp/content/api/schemes/logbroker/modify.json
    api/schemes/logbroker/poll.json /mvp/content/api/schemes/logbroker/poll.json
    api/schemes/logbroker/path.json /mvp/content/api/schemes/logbroker/path.json
    api/schemes/logbroker/int_or_default_value.json /mvp/content/api/schemes/logbroker/int_or_default_value.json
    api/schemes/logbroker/bool_or_default_value.json /mvp/content/api/schemes/logbroker/bool_or_default_value.json
    api/schemes/logbroker/string_or_default_value.json /mvp/content/api/schemes/logbroker/string_or_default_value.json
    api/schemes/logbroker/string_array_or_default_value.json /mvp/content/api/schemes/logbroker/string_array_or_default_value.json
    api/schemes/logbroker/cluster_key.json /mvp/content/api/schemes/logbroker/cluster_key.json
    api/schemes/logbroker/read_rule_key.json /mvp/content/api/schemes/logbroker/read_rule_key.json
    api/schemes/logbroker/permissions.json /mvp/content/api/schemes/logbroker/permissions.json
    api/schemes/logbroker/directory_properties.json /mvp/content/api/schemes/logbroker/directory_properties.json
    api/schemes/logbroker/topic_properties.json /mvp/content/api/schemes/logbroker/topic_properties.json
    api/schemes/logbroker/consumer_properties.json /mvp/content/api/schemes/logbroker/consumer_properties.json
    api/schemes/logbroker/list_yt_deliveries.json /mvp/content/api/schemes/logbroker/list_yt_deliveries.json
    api/schemes/rtmr/accounts.json /mvp/content/api/schemes/rtmr/accounts.json
    api/schemes/rtmr/pools.json /mvp/content/api/schemes/rtmr/pools.json
    api/schemes/rtmr/tasks.json /mvp/content/api/schemes/rtmr/tasks.json
    api/schemes/rtmr/operations.json /mvp/content/api/schemes/rtmr/operations.json
    api/schemes/rtmr/sources.json /mvp/content/api/schemes/rtmr/sources.json
    api/schemes/rtmr/sinks.json /mvp/content/api/schemes/rtmr/sinks.json
    api/schemes/rtmr/tables.json /mvp/content/api/schemes/rtmr/tables.json
    api/schemes/rtmr/views.json /mvp/content/api/schemes/rtmr/views.json
    api/schemes/rtmr/installations.json /mvp/content/api/schemes/rtmr/installations.json
    api/schemes/rtmr/table.json /mvp/content/api/schemes/rtmr/table.json
    api/schemes/rtmr/operation.json /mvp/content/api/schemes/rtmr/operation.json
    api/schemes/rtmr/table_preview.json /mvp/content/api/schemes/rtmr/table_preview.json
    api/schemes/rtmr/operation_preview.json /mvp/content/api/schemes/rtmr/operation_preview.json
    api/schemes/rtmr/data.json /mvp/content/api/schemes/rtmr/data.json
    api/schemes/rtmr/graph.json /mvp/content/api/schemes/rtmr/graph.json
    api/schemes/rtmr/task_graph.json /mvp/content/api/schemes/rtmr/task_graph.json
    api/schemes/rtmr/task.json /mvp/content/api/schemes/rtmr/task.json
    api/schemes/rtmr/vla-sources.json /mvp/content/api/schemes/rtmr/vla-sources.json # TODO: remove it when api/sources handler will be ready
    api/schemes/rtmr/man-sources.json /mvp/content/api/schemes/rtmr/man-sources.json # TODO: remove it when api/sources handler will be ready
    api/schemes/yds/get_records.json /mvp/content/api/schemes/yds/get_records.json
    api/schemes/yds/list_shards.json /mvp/content/api/schemes/yds/list_shards.json
    api/schemes/yds/create_datastream.json /mvp/content/api/schemes/yds/create_datastream.json
    api/schemes/yds/create_datastream_consumer.json /mvp/content/api/schemes/yds/create_datastream_consumer.json
    api/schemes/yds/datastream.json /mvp/content/api/schemes/yds/datastream.json
    api/schemes/yds/datastream_consumer.json /mvp/content/api/schemes/yds/datastream_consumer.json
    api/schemes/yds/datastream_consumers.json /mvp/content/api/schemes/yds/datastream_consumers.json
    api/schemes/yds/datastreams.json /mvp/content/api/schemes/yds/datastreams.json
    api/schemes/yds/describe_consumer.json /mvp/content/api/schemes/yds/describe_consumer.json
    api/schemes/yds/put_datastream_records.json /mvp/content/api/schemes/yds/put_datastream_records.json
    api/schemes/yds/simulate_datastream.json /mvp/content/api/schemes/yds/simulate_datastream.json
)

END()
