RECURSE(
    draft
    draft/ut
    extensions
    helpers
    impl/ydb_endpoints
    impl/ydb_endpoints/ut
    impl/ydb_internal/common
    impl/ydb_internal/db_driver_state
    impl/ydb_internal/grpc_connections
    impl/ydb_internal/logger
    impl/ydb_internal/make_request
    impl/ydb_internal/plain_status
    impl/ydb_internal/thread_pool
    impl/ydb_internal/value_helpers
    impl/ydb_stats
    resources
    ydb_common_client
    ydb_common_client/impl
    ydb_coordination
    ydb_coordination/ut
    ydb_datastreams
    ydb_debug
    ydb_discovery
    ydb_driver
    ydb_driver/ut
    ydb_export
    ydb_extension
    ydb_federated_topic
    ydb_federated_topic/impl
    ydb_import
    ydb_operation
    ydb_params
    ydb_persqueue_core
    ydb_persqueue_public
    ydb_persqueue_public/impl
    ydb_proto
    ydb_query
    ydb_rate_limiter
    ydb_result
    ydb_result/ut
    ydb_scheme
    ydb_table
    ydb_table/impl
    ydb_table/query_stats
    ydb_topic
    ydb_topic/codecs
    ydb_topic/impl
    ydb_types
    ydb_types/credentials
    ydb_types/exceptions
    ydb_types/fatal_error_handlers
    ydb_types/operation
    ydb_types/status
    ydb_value
)
