#pragma once

#include "config-linux.h"

#undef UWSGI_CAP

#undef UWSGI_EVENT_FILEMONITOR_USE_INOTIFY
#define UWSGI_EVENT_FILEMONITOR_USE_KQUEUE

#undef UWSGI_EVENT_TIMER_USE_TIMERFD
#define UWSGI_EVENT_TIMER_USE_KQUEUE

#undef UWSGI_EVENT_USE_EPOLL
#define UWSGI_EVENT_USE_KQUEUE

#undef UWSGI_LOCK_USE_MUTEX
#define UWSGI_LOCK_USE_OSX_SPINLOCK

#define UWSGI_UUID
