from typing import Any, Optional

class _EventMeta(type):
    def __init__(cls, classname, bases, dict_) -> None: ...

class Events(metaclass=_EventMeta): ...

class dispatcher(object):
    dispatch_cls: Any = ...
    events: Any = ...
    def __init__(self, events) -> None: ...
    def __get__(self, obj, cls): ...
