__all__ = ["Listener"]

class _SocketContainer: ...

class _ConnectionBase:
    def __del__(self) -> None: ...
    def close(self) -> None: ...

class PipeConnection(_ConnectionBase): ...
class Connection(_ConnectionBase): ...

class Listener:
    def __init__(
        self,
        backlog: int = ...,
    ) -> None: ...
    def close(self) -> None: ...

class SocketListener:
    def close(self) -> None: ...

class ConnectionWrapper: ...
class XmlListener(Listener): ...
