from logging import Logger, _Level

__all__ = [
    "SUBDEBUG",
    "SUBWARNING",
    "debug",
    "get_logger",
    "info",
    "log_to_stderr",
    "sub_debug",
    "sub_warning",
]

SUBDEBUG: int
SUBWARNING: int

def sub_debug(msg: str, *args: object, **kwargs: object) -> None: ...
def debug(msg: str, *args: object, **kwargs: object) -> None: ...
def info(msg: str, *args: object, **kwargs: object) -> None: ...
def sub_warning(msg: str, *args: object, **kwargs: object) -> None: ...
def warning(msg: str, *args: object, **kwargs: object) -> None: ...
def get_logger() -> Logger: ...
def log_to_stderr(level: _Level | None = ...) -> Logger: ...
