LIBRARY()

SRCS(
    audit_log.cpp
    audit_dml_operations.cpp
    db_metadata_cache.h
    grpc_endpoint_publish_actor.cpp
    grpc_helper.cpp
    grpc_mon.cpp
    grpc_publisher_service_actor.cpp
    grpc_request_proxy.cpp
    grpc_request_proxy_simple.cpp
    local_rate_limiter.cpp
    operation_helpers.cpp
    resolve_local_db_table.cpp
    rpc_alter_coordination_node.cpp
    rpc_alter_table.cpp
    rpc_backup.cpp
    rpc_begin_transaction.cpp
    rpc_calls.cpp
    rpc_cancel_operation.cpp
    rpc_cms.cpp
    rpc_commit_transaction.cpp
    rpc_dynamic_config.cpp
    rpc_copy_table.cpp
    rpc_copy_tables.cpp
    rpc_export.cpp
    rpc_create_coordination_node.cpp
    rpc_create_table.cpp
    rpc_describe_coordination_node.cpp
    rpc_describe_path.cpp
    rpc_describe_table.cpp
    rpc_describe_table_options.cpp
    rpc_drop_coordination_node.cpp
    rpc_drop_table.cpp
    rpc_discovery.cpp
    rpc_execute_data_query.cpp
    rpc_execute_scheme_query.cpp
    rpc_execute_yql_script.cpp
    rpc_explain_yql_script.cpp
    rpc_explain_data_query.cpp
    rpc_forget_operation.cpp
    rpc_fq_internal.cpp
    rpc_fq.cpp
    rpc_get_operation.cpp
    rpc_get_shard_locations.cpp
    rpc_import.cpp
    rpc_import_data.cpp
    rpc_keep_alive.cpp
    rpc_keyvalue.cpp
    rpc_kh_describe.cpp
    rpc_kh_snapshots.cpp
    rpc_kqp_base.cpp
    rpc_list_operations.cpp
    rpc_login.cpp
    rpc_load_rows.cpp
    rpc_log_store.cpp
    rpc_node_registration.cpp
    rpc_maintenance.cpp
    rpc_make_directory.cpp
    rpc_modify_permissions.cpp
    rpc_monitoring.cpp
    rpc_prepare_data_query.cpp
    rpc_rate_limiter_api.cpp
    rpc_read_columns.cpp
    rpc_read_table.cpp
    rpc_read_rows.cpp
    rpc_remove_directory.cpp
    rpc_rename_tables.cpp
    rpc_replication.cpp
    rpc_rollback_transaction.cpp
    rpc_scheme_base.cpp
    rpc_stream_execute_scan_query.cpp
    rpc_stream_execute_yql_script.cpp
    rpc_whoami.cpp
    rpc_object_storage.cpp
    table_settings.cpp

    rpc_common/rpc_common_kqp_session.cpp

    query/rpc_execute_query.cpp
    query/rpc_execute_script.cpp
    query/rpc_fetch_script_results.cpp
    query/rpc_attach_session.cpp
    query/rpc_kqp_tx.cpp
    query/service_query.h

    ydb_over_fq/create_session.cpp
    ydb_over_fq/describe_table.cpp
    ydb_over_fq/execute_data_query.cpp
    ydb_over_fq/explain_data_query.cpp
    ydb_over_fq/keep_alive.cpp
    ydb_over_fq/list_directory.cpp
)

PEERDIR(
    contrib/libs/xxhash
    library/cpp/cgiparam
    library/cpp/digest/old_crc
    ydb/core/actorlib_impl
    ydb/core/audit
    ydb/core/base
    ydb/core/control
    ydb/core/discovery
    ydb/core/engine
    ydb/core/formats
    ydb/core/fq/libs/events
    ydb/core/fq/libs/control_plane_proxy/events
    ydb/core/grpc_services/base
    ydb/core/grpc_services/counters
    ydb/core/grpc_services/local_rpc
    ydb/core/grpc_services/cancelation
    ydb/core/health_check
    ydb/core/io_formats/ydb_dump
    ydb/core/kesus/tablet
    ydb/core/kqp/common
    ydb/core/kqp/session_actor
    ydb/core/protos
    ydb/core/scheme
    ydb/core/sys_view
    ydb/core/tx
    ydb/core/tx/datashard
    ydb/core/tx/sharding
    ydb/core/tx/data_events
    ydb/core/tx/schemeshard/olap/bg_tasks/events
    ydb/core/util
    ydb/core/ydb_convert
    ydb/core/security
    ydb/core/security/ldap_auth_provider
    ydb/library/aclib
    ydb/library/binary_json
    ydb/library/dynumber
    ydb/library/mkql_proto
    ydb/library/persqueue/topic_parser
    ydb/library/yql/parser/pg_wrapper/interface
    ydb/library/yql/public/types
    ydb/library/yql/public/issue
    ydb/library/services
    ydb/public/api/grpc/draft
    ydb/public/api/protos
    ydb/public/lib/fq
    ydb/public/lib/operation_id
    ydb/public/sdk/cpp/client/resources
    ydb/services/ext_index/common
)

YQL_LAST_ABI_VERSION()

END()

RECURSE(
    base
    counters
    local_rpc
    tablet
)

RECURSE_FOR_TESTS(
    ut
)
