from typing import Any, Optional

class UnevaluatableError(Exception): ...

class EvaluatorCompiler(object):
    target_cls: Any = ...
    def __init__(self, target_cls: Optional[Any] = ...) -> None: ...
    def process(self, clause): ...
    def visit_grouping(self, clause): ...
    def visit_null(self, clause): ...
    def visit_false(self, clause): ...
    def visit_true(self, clause): ...
    def visit_column(self, clause): ...
    def visit_clauselist(self, clause): ...
    def visit_binary(self, clause): ...
    def visit_unary(self, clause): ...
    def visit_bindparam(self, clause): ...
