from typing import Any, Optional

def instances(query, cursor, context): ...
def merge_result(query, iterator, load: bool = ...): ...
def get_from_identity(session, key, passive): ...
def load_on_ident(query, key, refresh_state: Optional[Any] = ..., lockmode: Optional[Any] = ...,
                  only_load_props: Optional[Any] = ...): ...
def load_scalar_attributes(mapper, state, attribute_names): ...
