# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

PROVIDES(ujson)

VERSION(1.35)

LICENSE(BSD-3-Clause)

ADDINCL(
    contrib/deprecated/python/ujson/py3/lib
    contrib/deprecated/python/ujson/py3/python
)

NO_COMPILER_WARNINGS()

NO_LINT()

NO_UTIL()

SRCS(
    lib/ultrajsondec.c
    lib/ultrajsonenc.c
    python/JSONtoObj.c
    python/objToJSON.c
    python/ujson.c
)

PY_REGISTER(
    ujson
)

PY_SRCS(
    TOP_LEVEL
    ujson.pyi
)

RESOURCE_FILES(
    PREFIX contrib/deprecated/python/ujson/py3/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
