PY3TEST()

SIZE(MEDIUM)

FORK_TESTS()

PEERDIR(
    contrib/python/mock
    contrib/python/hypothesis
    contrib/python/spacy
)

DATA(
    arcadia/contrib/python/spacy/spacy/tests/tokenizer
)

SRCDIR(contrib/python/spacy)

TEST_SRCS(
    spacy/tests/__init__.py
    spacy/tests/conftest.py
    spacy/tests/doc/__init__.py
    spacy/tests/doc/test_add_entities.py
    spacy/tests/doc/test_array.py
    spacy/tests/doc/test_creation.py
    spacy/tests/doc/test_doc_api.py
    spacy/tests/doc/test_graph.py
    spacy/tests/doc/test_json_doc_conversion.py
    spacy/tests/doc/test_morphanalysis.py
    spacy/tests/doc/test_pickle_doc.py
    spacy/tests/doc/test_retokenize_merge.py
    spacy/tests/doc/test_retokenize_split.py
    spacy/tests/doc/test_span.py
    spacy/tests/doc/test_span_group.py
    spacy/tests/doc/test_token_api.py
    spacy/tests/doc/test_underscore.py
    #spacy/tests/enable_gpu.py
    spacy/tests/lang/__init__.py
    spacy/tests/lang/af/__init__.py
    spacy/tests/lang/af/test_text.py
    spacy/tests/lang/af/test_tokenizer.py
    spacy/tests/lang/am/__init__.py
    spacy/tests/lang/am/test_exception.py
    spacy/tests/lang/am/test_text.py
    spacy/tests/lang/ar/__init__.py
    spacy/tests/lang/ar/test_exceptions.py
    spacy/tests/lang/ar/test_text.py
    spacy/tests/lang/bn/__init__.py
    spacy/tests/lang/bn/test_tokenizer.py
    spacy/tests/lang/ca/__init__.py
    spacy/tests/lang/ca/test_exception.py
    spacy/tests/lang/ca/test_prefix_suffix_infix.py
    spacy/tests/lang/ca/test_text.py
    spacy/tests/lang/cs/__init__.py
    spacy/tests/lang/cs/test_text.py
    spacy/tests/lang/da/__init__.py
    spacy/tests/lang/da/test_exceptions.py
    spacy/tests/lang/da/test_noun_chunks.py
    spacy/tests/lang/da/test_prefix_suffix_infix.py
    spacy/tests/lang/da/test_text.py
    spacy/tests/lang/de/__init__.py
    spacy/tests/lang/de/test_exceptions.py
    spacy/tests/lang/de/test_noun_chunks.py
    spacy/tests/lang/de/test_parser.py
    spacy/tests/lang/de/test_prefix_suffix_infix.py
    spacy/tests/lang/de/test_text.py
    spacy/tests/lang/dsb/__init__.py
    spacy/tests/lang/dsb/test_text.py
    spacy/tests/lang/dsb/test_tokenizer.py
    spacy/tests/lang/el/__init__.py
    spacy/tests/lang/el/test_exception.py
    spacy/tests/lang/el/test_noun_chunks.py
    spacy/tests/lang/el/test_text.py
    spacy/tests/lang/en/__init__.py
    spacy/tests/lang/en/test_customized_tokenizer.py
    spacy/tests/lang/en/test_exceptions.py
    spacy/tests/lang/en/test_indices.py
    spacy/tests/lang/en/test_noun_chunks.py
    spacy/tests/lang/en/test_parser.py
    spacy/tests/lang/en/test_prefix_suffix_infix.py
    spacy/tests/lang/en/test_punct.py
    spacy/tests/lang/en/test_sbd.py
    spacy/tests/lang/en/test_text.py
    spacy/tests/lang/en/test_tokenizer.py
    spacy/tests/lang/es/__init__.py
    spacy/tests/lang/es/test_exception.py
    spacy/tests/lang/es/test_noun_chunks.py
    spacy/tests/lang/es/test_text.py
    spacy/tests/lang/et/__init__.py
    spacy/tests/lang/et/test_text.py
    spacy/tests/lang/et/test_tokenizer.py
    spacy/tests/lang/eu/__init__.py
    spacy/tests/lang/eu/test_text.py
    spacy/tests/lang/fa/__init__.py
    spacy/tests/lang/fa/test_noun_chunks.py
    spacy/tests/lang/fi/__init__.py
    spacy/tests/lang/fi/test_noun_chunks.py
    spacy/tests/lang/fi/test_text.py
    spacy/tests/lang/fi/test_tokenizer.py
    spacy/tests/lang/fo/__init__.py
    spacy/tests/lang/fo/test_tokenizer.py
    spacy/tests/lang/fr/__init__.py
    spacy/tests/lang/fr/test_exceptions.py
    spacy/tests/lang/fr/test_noun_chunks.py
    spacy/tests/lang/fr/test_prefix_suffix_infix.py
    spacy/tests/lang/fr/test_text.py
    spacy/tests/lang/ga/__init__.py
    spacy/tests/lang/ga/test_tokenizer.py
    spacy/tests/lang/grc/__init__.py
    spacy/tests/lang/grc/test_text.py
    spacy/tests/lang/grc/test_tokenizer.py
    spacy/tests/lang/gu/__init__.py
    spacy/tests/lang/gu/test_text.py
    spacy/tests/lang/he/__init__.py
    spacy/tests/lang/he/test_tokenizer.py
    spacy/tests/lang/hi/__init__.py
    spacy/tests/lang/hi/test_lex_attrs.py
    spacy/tests/lang/hi/test_text.py
    spacy/tests/lang/hr/__init__.py
    spacy/tests/lang/hr/test_text.py
    spacy/tests/lang/hr/test_tokenizer.py
    spacy/tests/lang/hsb/__init__.py
    spacy/tests/lang/hsb/test_text.py
    spacy/tests/lang/hsb/test_tokenizer.py
    spacy/tests/lang/hu/__init__.py
    spacy/tests/lang/hu/test_tokenizer.py
    spacy/tests/lang/hy/__init__.py
    spacy/tests/lang/hy/test_text.py
    spacy/tests/lang/hy/test_tokenizer.py
    spacy/tests/lang/id/__init__.py
    spacy/tests/lang/id/test_noun_chunks.py
    spacy/tests/lang/id/test_prefix_suffix_infix.py
    spacy/tests/lang/id/test_text.py
    spacy/tests/lang/is/__init__.py
    spacy/tests/lang/is/test_text.py
    spacy/tests/lang/is/test_tokenizer.py
    spacy/tests/lang/it/__init__.py
    spacy/tests/lang/it/test_noun_chunks.py
    spacy/tests/lang/it/test_prefix_suffix_infix.py
    spacy/tests/lang/it/test_stopwords.py
    spacy/tests/lang/it/test_text.py
    spacy/tests/lang/ja/__init__.py
    spacy/tests/lang/ja/test_lemmatization.py
    spacy/tests/lang/ja/test_morphologizer_factory.py
    spacy/tests/lang/ja/test_serialize.py
    spacy/tests/lang/ja/test_tokenizer.py
    spacy/tests/lang/ko/__init__.py
    spacy/tests/lang/ko/test_lemmatization.py
    spacy/tests/lang/ko/test_serialize.py
    spacy/tests/lang/ko/test_tokenizer.py
    spacy/tests/lang/ky/__init__.py
    spacy/tests/lang/ky/test_tokenizer.py
    spacy/tests/lang/la/__init__.py
    spacy/tests/lang/la/test_exception.py
    spacy/tests/lang/la/test_noun_chunks.py
    spacy/tests/lang/la/test_text.py
    spacy/tests/lang/lb/__init__.py
    spacy/tests/lang/lb/test_exceptions.py
    spacy/tests/lang/lb/test_prefix_suffix_infix.py
    spacy/tests/lang/lb/test_text.py
    spacy/tests/lang/lg/__init__.py
    spacy/tests/lang/lg/test_tokenizer.py
    spacy/tests/lang/lt/__init__.py
    spacy/tests/lang/lt/test_text.py
    spacy/tests/lang/lv/__init__.py
    spacy/tests/lang/lv/test_text.py
    spacy/tests/lang/lv/test_tokenizer.py
    spacy/tests/lang/mk/__init__.py
    spacy/tests/lang/mk/test_text.py
    spacy/tests/lang/ml/__init__.py
    spacy/tests/lang/ml/test_text.py
    spacy/tests/lang/ms/__init__.py
    spacy/tests/lang/ms/test_noun_chunks.py
    spacy/tests/lang/ms/test_prefix_suffix_infix.py
    spacy/tests/lang/ms/test_text.py
    spacy/tests/lang/nb/__init__.py
    spacy/tests/lang/nb/test_noun_chunks.py
    spacy/tests/lang/nb/test_tokenizer.py
    spacy/tests/lang/ne/__init__.py
    spacy/tests/lang/ne/test_text.py
    spacy/tests/lang/nl/__init__.py
    spacy/tests/lang/nl/test_noun_chunks.py
    spacy/tests/lang/nl/test_text.py
    spacy/tests/lang/nn/__init__.py
    spacy/tests/lang/nn/test_tokenizer.py
    spacy/tests/lang/pl/__init__.py
    spacy/tests/lang/pl/test_text.py
    spacy/tests/lang/pl/test_tokenizer.py
    spacy/tests/lang/pt/__init__.py
    spacy/tests/lang/pt/test_noun_chunks.py
    spacy/tests/lang/pt/test_text.py
    spacy/tests/lang/ro/__init__.py
    spacy/tests/lang/ro/test_tokenizer.py
    spacy/tests/lang/ru/__init__.py
    spacy/tests/lang/ru/test_exceptions.py
    spacy/tests/lang/ru/test_lemmatizer.py
    spacy/tests/lang/ru/test_text.py
    spacy/tests/lang/ru/test_tokenizer.py
    spacy/tests/lang/sa/__init__.py
    spacy/tests/lang/sa/test_text.py
    spacy/tests/lang/sk/__init__.py
    spacy/tests/lang/sk/test_text.py
    spacy/tests/lang/sk/test_tokenizer.py
    spacy/tests/lang/sl/__init__.py
    spacy/tests/lang/sl/test_text.py
    spacy/tests/lang/sl/test_tokenizer.py
    spacy/tests/lang/sq/__init__.py
    spacy/tests/lang/sq/test_text.py
    spacy/tests/lang/sq/test_tokenizer.py
    spacy/tests/lang/sr/__init__.py
    spacy/tests/lang/sr/test_exceptions.py
    spacy/tests/lang/sr/test_tokenizer.py
    spacy/tests/lang/sv/__init__.py
    spacy/tests/lang/sv/test_exceptions.py
    spacy/tests/lang/sv/test_lex_attrs.py
    spacy/tests/lang/sv/test_noun_chunks.py
    spacy/tests/lang/sv/test_prefix_suffix_infix.py
    spacy/tests/lang/sv/test_text.py
    spacy/tests/lang/sv/test_tokenizer.py
    spacy/tests/lang/ta/__init__.py
    spacy/tests/lang/ta/test_text.py
    spacy/tests/lang/ta/test_tokenizer.py
    spacy/tests/lang/test_attrs.py
    spacy/tests/lang/test_initialize.py
    spacy/tests/lang/test_lemmatizers.py
    spacy/tests/lang/th/__init__.py
    spacy/tests/lang/th/test_serialize.py
    spacy/tests/lang/th/test_tokenizer.py
    spacy/tests/lang/ti/__init__.py
    spacy/tests/lang/ti/test_exception.py
    spacy/tests/lang/ti/test_text.py
    spacy/tests/lang/tl/__init__.py
    spacy/tests/lang/tl/test_indices.py
    spacy/tests/lang/tl/test_punct.py
    spacy/tests/lang/tl/test_text.py
    spacy/tests/lang/tr/__init__.py
    spacy/tests/lang/tr/test_noun_chunks.py
    spacy/tests/lang/tr/test_parser.py
    spacy/tests/lang/tr/test_text.py
    spacy/tests/lang/tr/test_tokenizer.py
    spacy/tests/lang/tt/__init__.py
    spacy/tests/lang/tt/test_tokenizer.py
    spacy/tests/lang/uk/__init__.py
    spacy/tests/lang/uk/test_lemmatizer.py
    spacy/tests/lang/uk/test_tokenizer.py
    spacy/tests/lang/uk/test_tokenizer_exc.py
    spacy/tests/lang/ur/__init__.py
    spacy/tests/lang/ur/test_prefix_suffix_infix.py
    spacy/tests/lang/ur/test_text.py
    spacy/tests/lang/vi/__init__.py
    spacy/tests/lang/vi/test_serialize.py
    spacy/tests/lang/vi/test_tokenizer.py
    spacy/tests/lang/xx/__init__.py
    spacy/tests/lang/xx/test_text.py
    spacy/tests/lang/xx/test_tokenizer.py
    spacy/tests/lang/yo/__init__.py
    spacy/tests/lang/yo/test_text.py
    spacy/tests/lang/zh/__init__.py
    spacy/tests/lang/zh/test_serialize.py
    spacy/tests/lang/zh/test_text.py
    spacy/tests/lang/zh/test_tokenizer.py
    spacy/tests/matcher/__init__.py
    spacy/tests/matcher/test_dependency_matcher.py
    spacy/tests/matcher/test_levenshtein.py
    spacy/tests/matcher/test_matcher_api.py
    spacy/tests/matcher/test_matcher_logic.py
    spacy/tests/matcher/test_pattern_validation.py
    spacy/tests/matcher/test_phrase_matcher.py
    spacy/tests/morphology/__init__.py
    spacy/tests/morphology/test_morph_converters.py
    spacy/tests/morphology/test_morph_features.py
    spacy/tests/morphology/test_morph_pickle.py
    spacy/tests/package/__init__.py
    #spacy/tests/package/test_requirements.py
    spacy/tests/parser/__init__.py
    spacy/tests/parser/test_add_label.py
    spacy/tests/parser/test_arc_eager_oracle.py
    spacy/tests/parser/test_ner.py
    spacy/tests/parser/test_neural_parser.py
    #spacy/tests/parser/test_nn_beam.py
    spacy/tests/parser/test_nonproj.py
    spacy/tests/parser/test_parse.py
    spacy/tests/parser/test_parse_navigate.py
    spacy/tests/parser/test_preset_sbd.py
    spacy/tests/parser/test_space_attachment.py
    spacy/tests/parser/test_state.py
    spacy/tests/pipeline/__init__.py
    spacy/tests/pipeline/test_analysis.py
    spacy/tests/pipeline/test_annotates_on_update.py
    spacy/tests/pipeline/test_attributeruler.py
    spacy/tests/pipeline/test_edit_tree_lemmatizer.py
    spacy/tests/pipeline/test_entity_linker.py
    spacy/tests/pipeline/test_entity_ruler.py
    spacy/tests/pipeline/test_functions.py
    spacy/tests/pipeline/test_initialize.py
    spacy/tests/pipeline/test_lemmatizer.py
    spacy/tests/pipeline/test_models.py
    spacy/tests/pipeline/test_morphologizer.py
    spacy/tests/pipeline/test_pipe_factories.py
    spacy/tests/pipeline/test_pipe_methods.py
    spacy/tests/pipeline/test_sentencizer.py
    spacy/tests/pipeline/test_senter.py
    spacy/tests/pipeline/test_span_finder.py
    spacy/tests/pipeline/test_span_ruler.py
    spacy/tests/pipeline/test_spancat.py
    spacy/tests/pipeline/test_tagger.py
    spacy/tests/pipeline/test_textcat.py
    spacy/tests/pipeline/test_tok2vec.py
    spacy/tests/serialize/__init__.py
    spacy/tests/serialize/test_resource_warning.py
    spacy/tests/serialize/test_serialize_config.py
    spacy/tests/serialize/test_serialize_doc.py
    spacy/tests/serialize/test_serialize_docbin.py
    spacy/tests/serialize/test_serialize_extension_attrs.py
    spacy/tests/serialize/test_serialize_kb.py
    spacy/tests/serialize/test_serialize_language.py
    spacy/tests/serialize/test_serialize_pipeline.py
    spacy/tests/serialize/test_serialize_span_groups.py
    spacy/tests/serialize/test_serialize_tokenizer.py
    spacy/tests/serialize/test_serialize_vocab_strings.py
    spacy/tests/test_architectures.py
    #spacy/tests/test_cli.py
    #spacy/tests/test_cli_app.py
    spacy/tests/test_displacy.py
    spacy/tests/test_errors.py
    spacy/tests/test_language.py
    spacy/tests/test_misc.py
    spacy/tests/test_models.py
    spacy/tests/test_pickles.py
    spacy/tests/test_scorer.py
    spacy/tests/test_ty.py
    spacy/tests/tok2vec.py
    spacy/tests/tokenizer/__init__.py
    spacy/tests/tokenizer/test_exceptions.py
    spacy/tests/tokenizer/test_explain.py
    spacy/tests/tokenizer/test_naughty_strings.py
    spacy/tests/tokenizer/test_tokenizer.py
    spacy/tests/tokenizer/test_urls.py
    spacy/tests/tokenizer/test_whitespace.py
    spacy/tests/training/__init__.py
    spacy/tests/training/test_augmenters.py
    spacy/tests/training/test_corpus.py
    spacy/tests/training/test_logger.py
    spacy/tests/training/test_new_example.py
    spacy/tests/training/test_readers.py
    spacy/tests/training/test_rehearse.py
    spacy/tests/training/test_training.py
    spacy/tests/util.py
    spacy/tests/vocab_vectors/__init__.py
    spacy/tests/vocab_vectors/test_lexeme.py
    spacy/tests/vocab_vectors/test_lookups.py
    spacy/tests/vocab_vectors/test_similarity.py
    spacy/tests/vocab_vectors/test_stringstore.py
    spacy/tests/vocab_vectors/test_vectors.py
    spacy/tests/vocab_vectors/test_vocab_api.py
)

NO_LINT()

END()
