# Generated by devtools/yamaker from nixpkgs 24.05.

LIBRARY()

LICENSE(BSD-3-Clause)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(2026-02-26)

ORIGINAL_SOURCE(https://github.com/mreineck/pocketfft/archive/8187407446316c3d16f15e5395dabd4b22f4fec7.tar.gz)

END()
