# Generated by devtools/yamaker.

LIBRARY()

VERSION(4.0.1)

LICENSE(BSD-3-Clause-Open-MPI)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

PEERDIR(
    contrib/libs/hwloc/hwloc
    contrib/libs/libevent
)

ADDINCL(
    contrib/libs/openmpi
    contrib/libs/openmpi/ompi/include
    contrib/libs/openmpi/ompi/mca/coll/sync
    contrib/libs/openmpi/opal/include
    contrib/libs/openmpi/orte/include
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(-DHAVE_CONFIG_H)

SRCS(
    coll_sync_bcast.c
    coll_sync_component.c
    coll_sync_exscan.c
    coll_sync_gather.c
    coll_sync_gatherv.c
    coll_sync_module.c
    coll_sync_reduce.c
    coll_sync_reduce_scatter.c
    coll_sync_scan.c
    coll_sync_scatter.c
    coll_sync_scatterv.c
)

END()
