- name: ensure YC_TOKEN variable exists
  ansible.builtin.assert:
    that:
      - lookup('env', 'YC_TOKEN') != ''
    msg: |
      Please set YC_TOKEN environment variable, example: export YC_TOKEN=$(yc --profile ydbtech iam create-token)

- name: get htpasswd content
  delegate_to: 127.0.0.1
  become: false
  ansible.builtin.uri:
    url: "https://payload.lockbox.api.cloud.yandex.net/lockbox/v1/secrets/{{ bazel_remote_htpasswd_lockbox_secret_id }}/payload"
    headers:
      Authorization: "Bearer {{ lookup('env', 'YC_TOKEN') }}"
  register: htpasswd
  check_mode: no

- name: extract htpasswd content
  ansible.builtin.set_fact:
    htpasswd_content: "{{ (htpasswd.json.entries | items2dict('key', 'textValue')).htpasswd  }}"

- name: create htpasswd
  ansible.builtin.copy:
    dest: /home/bazel-remote/htpasswd
    content: "{{ htpasswd_content }}"
    mode: 0600
    owner: bazel-remote
    group: bazel-remote
