LIBRARY()

SET(yql_grammar ${ARCADIA_ROOT}/${MODDIR}/YQL.g4)

SET(GRAMMAR_STRING_CORE_SINGLE "\"~(QUOTE_SINGLE | BACKSLASH) | (BACKSLASH .)\"")
SET(GRAMMAR_STRING_CORE_DOUBLE "\"~(QUOTE_DOUBLE | BACKSLASH) | (BACKSLASH .)\"")
SET(GRAMMAR_MULTILINE_COMMENT_CORE       "\".\"")

IF(EXPORT_CMAKE)
    MANUAL_GENERATION(${yql_grammar})
ELSE()
    CONFIGURE_FILE(${ARCADIA_ROOT}/ydb/library/yql/sql/v1/SQLv1.g.in ${yql_grammar})
ENDIF()

RUN_ANTLR4_CPP(${yql_grammar})

END()
