RECURSE(
    bsconfig
    draft
    extensions
    helpers
    impl/ydb_endpoints
    impl/ydb_internal/common
    impl/ydb_internal/db_driver_state
    impl/ydb_internal/grpc_connections
    impl/ydb_internal/logger
    impl/ydb_internal/make_request
    impl/ydb_internal/plain_status
    impl/ydb_internal/thread_pool
    impl/ydb_internal/value_helpers
    impl/ydb_stats
    resources
    cms
    common_client
    common_client/impl
    coordination
    datastreams
    debug
    discovery
    driver
    export
    extension_common
    federated_topic
    federated_topic/impl
    import
    operation
    params
    persqueue_public
    persqueue_public/impl
    proto
    query
    query/impl
    rate_limiter
    result
    scheme
    table
    table/impl
    table/query_stats
    topic
    topic/codecs
    topic/impl
    types
    types/credentials
    types/exceptions
    types/fatal_error_handlers
    types/operation
    types/status
    value
)
