import shelve
from threading import Thread
from typing import NamedTuple

from billiard.context import Process
from typing_extensions import override

__all__ = [
    "PersistentScheduler",
    "ScheduleEntry",
    "Scheduler",
    "SchedulingError",
    "Service",
]

class event_t(NamedTuple): ...
class SchedulingError(Exception): ...
class BeatLazyFunc: ...

class ScheduleEntry:
    total_run_count: int

class Scheduler:
    Entry = ScheduleEntry
    def setup_schedule(self) -> None: ...
    def sync(self) -> None: ...
    def close(self) -> None: ...

class PersistentScheduler(Scheduler):
    persistence = shelve
    @override
    def setup_schedule(self) -> None: ...
    @override
    def sync(self) -> None: ...
    @override
    def close(self) -> None: ...

class Service:
    scheduler_cls = PersistentScheduler
    def start(self, embedded_process: bool = ...) -> None: ...
    def sync(self) -> None: ...
    def stop(self, wait: bool = ...) -> None: ...
    def get_scheduler(
        self, lazy: bool = ..., extension_namespace: str = ...
    ) -> Scheduler: ...
    @property
    def scheduler(self) -> Scheduler: ...

class _Threaded(Thread):
    daemon: bool
    name: str
    @override
    def run(self) -> None: ...
    def stop(self) -> None: ...

class _Process(Process):
    name: str
    @override
    def run(self) -> None: ...
    def stop(self) -> None: ...
