name: test-python
description: Run functional Python tests
inputs:
  log_suffix:
    required: true
    type: string
  test_label_regexp:
    required: false
    type: string
  aws_key_id:
    required: true
    type: string
  aws_key_value: 
    required: true
    type: string
  aws_bucket:
    required: true
    type: string
    
runs:
  using: "composite"
  steps:
  - name: Test
    shell: bash
    run: |
      export source_root=$(pwd)
      export build_root=$(pwd)/../build/
      mkdir -p ../artifacts
      rm -rf ../artifacts/*
      source ${source_root}/ydb/tests/oss/launch/prepare.sh

      echo "Stdout log (gzip archive): https://storage.yandexcloud.net/ydb-tech-ci/${{ github.repository }}/${{github.workflow}}/${{ github.run_id }}/${{inputs.log_suffix}}-${{inputs.sanitizer}}-stdout.gz" >> $GITHUB_STEP_SUMMARY
      cd ${source_root}/ydb/tests/functional/
      bad_suites=$(grep -Eo 'ignore=[a-zA-Z_-]*' pytest.ini | sed 's/ignore=//g')
      suites=""
      for suite in $(echo */ | sed 's/\///g'); do
        suite_find=$(echo $bad_suites | grep "$suite")
        if [[ $suite_find == '' ]]; then
            suites+=$suite;
            suites+=$'\n'
        fi
      done
      if [[ ${{inputs.test_label_regexp}} != '' ]]; then
        suites=${{inputs.test_label_regexp}}
      fi
      echo -n "$suites" | parallel -j32 --group "pytest -o junit_logging=log -o junit_log_passing_tests=False \
        -v --junit-xml=${source_root}/ydb/tests/functional/test-results/xml/{}/res.xml {}" | \
        sed -e 's/\x1b\[[0-9;]*m//g' | \
        tee >(gzip --stdout > ${source_root}/../artifacts/${{inputs.log_suffix}}-stdout.gz) | \
        tee -a $GITHUB_STEP_SUMMARY
  - name: Upload S3
    uses: shallwefootball/s3-upload-action@master
    if: always()
    with:
      aws_key_id: ${{inputs.aws_key_id}}
      aws_secret_access_key: ${{inputs.aws_key_value}}
      aws_bucket: ${{inputs.aws_bucket}}
      source_dir: ../artifacts
      destination_dir: '${{ github.repository }}/${{github.workflow}}/${{ github.run_id }}'
      endpoint: https://storage.yandexcloud.net
