# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(1.17.3)

LICENSE(Apache-2.0)

NO_COMPILER_WARNINGS()

NO_LINT()

CFLAGS(
    -DANNOYLIB_MULTITHREADED_BUILD
)

SRCS(
    src/annoymodule.cc
)

PY_REGISTER(
    annoy.annoylib
)

PY_SRCS(
    TOP_LEVEL
    annoy/__init__.py
    annoy/__init__.pyi
)

RESOURCE_FILES(
    PREFIX contrib/python/annoy/
    .dist-info/METADATA
    .dist-info/top_level.txt
    annoy/py.typed
)

END()

RECURSE_FOR_TESTS(
    tests
)
