# Generated by devtools/yamaker.

INCLUDE(${ARCADIA_ROOT}/build/platform/clang/arch.cmake)

LIBRARY(clang_rt.scudo_standalone_cxx${CLANG_RT_SUFFIX})

LICENSE(
    Apache-2.0 AND
    Apache-2.0 WITH LLVM-exception AND
    MIT AND
    NCSA
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

SUBSCRIBER(g:cpp-contrib)

ADDINCL(
    contrib/libs/clang14-rt/lib
    contrib/libs/clang14-rt/lib/scudo/standalone/include
)

NO_COMPILER_WARNINGS()

NO_UTIL()

NO_SANITIZE()

CFLAGS(
    -DGWP_ASAN_HOOKS
    -fcommon
    -fno-exceptions
    -fno-lto
    -fno-omit-frame-pointer
    -fvisibility=hidden
)

SRCDIR(contrib/libs/clang14-rt/lib/scudo/standalone)

SRCS(
    wrappers_cpp.cpp
)

END()
