#define WAVM_ENABLE_RUNTIME 1
#define WAVM_ENABLE_STATIC_LINKING 0
#define WAVM_ENABLE_ASAN 0
#define WAVM_ENABLE_UBSAN 0
#define WAVM_ENABLE_TSAN 0
#define WAVM_ENABLE_LIBFUZZER 0
#define WAVM_ENABLE_RELEASE_ASSERTS 0
#define WAVM_ENABLE_UNWIND 1
