#include <ydb/core/persqueue/common/percentiles.h>

#include <library/cpp/testing/unittest/registar.h>

namespace NKikimr::NPQ {

Y_UNIT_TEST_SUITE(TPercentilesTest) {

Y_UNIT_TEST(FastLatencyTables) {
    UNIT_ASSERT_VALUES_EQUAL(FAST_LATENCY_INTERVALS.size(), 13u);
    UNIT_ASSERT_VALUES_EQUAL(FAST_LATENCY_MS_INTERVALS.size(), 13u);
    UNIT_ASSERT_VALUES_EQUAL(FAST_LATENCY_BOUNDS.size(), 13u);
    UNIT_ASSERT_VALUES_EQUAL(FAST_LATENCY_INTERVALS.front().first, 0u);
    UNIT_ASSERT_VALUES_EQUAL(FAST_LATENCY_INTERVALS.front().second, "0");
    UNIT_ASSERT_VALUES_EQUAL(FAST_LATENCY_MS_INTERVALS.front().second, "0ms");
    UNIT_ASSERT_VALUES_EQUAL(FAST_LATENCY_BOUNDS.front(), 0.0);
    UNIT_ASSERT_VALUES_EQUAL(FAST_LATENCY_RANGES[12].RangeName, "9999999");
}

Y_UNIT_TEST(SlowLatencyTables) {
    UNIT_ASSERT_VALUES_EQUAL(SLOW_LATENCY_INTERVALS.size(), 14u);
    UNIT_ASSERT_VALUES_EQUAL(SLOW_LATENCY_MS_INTERVALS.size(), 14u);
    UNIT_ASSERT_VALUES_EQUAL(SLOW_LATENCY_BOUNDS.size(), 14u);
    UNIT_ASSERT_VALUES_EQUAL(SLOW_LATENCY_INTERVALS.front().first, 10u);
    UNIT_ASSERT_VALUES_EQUAL(SLOW_LATENCY_MS_INTERVALS.back().second, "9999999ms");
}

Y_UNIT_TEST(SizeTables) {
    UNIT_ASSERT_VALUES_EQUAL(SIZE_INTERVALS.size(), 14u);
    UNIT_ASSERT_VALUES_EQUAL(SIZE_KB_INTERVALS.size(), 14u);
    UNIT_ASSERT_VALUES_EQUAL(SIZE_RANGES[0].RangeVal, 1024u);
    UNIT_ASSERT_VALUES_EQUAL(SIZE_INTERVALS.front().second, "1024");
    UNIT_ASSERT_VALUES_EQUAL(SIZE_KB_INTERVALS.front().second, "1kb");
    UNIT_ASSERT_VALUES_EQUAL(SIZE_KB_INTERVALS.back().second, "999999999kb");
}

Y_UNIT_TEST(MlpLocksTables) {
    UNIT_ASSERT_VALUES_EQUAL(MLP_LOCKS_BOUNDS.size(), 10u);
    UNIT_ASSERT_VALUES_EQUAL(MLP_LOCKS_RANGES[0].RangeVal, 1u);
    UNIT_ASSERT_VALUES_EQUAL(MLP_LOCKS_RANGES[9].RangeName, "1000");
    UNIT_ASSERT_VALUES_EQUAL(MLP_LOCKS_BOUNDS.back(), 1000.0);
}

} // Y_UNIT_TEST_SUITE(TPercentilesTest)

} // namespace NKikimr::NPQ
