#ifndef PANGO_FEATURES_H
#define PANGO_FEATURES_H

#define PANGO_VERSION_MAJOR 1
#define PANGO_VERSION_MINOR 55
#define PANGO_VERSION_MICRO 5

#define PANGO_VERSION_STRING "1.55.5"

#endif /* PANGO_FEATURES_H */
