syntax = "proto3";

import "ydb/core/nbs/nbs1_compat_api/cloud/blockstore/public/api/protos/headers.proto";
import "ydb/core/nbs/cloud/storage/core/protos/error.proto";

package NYdb.NBS.NNbs1CompatApi.NBlockStore.NProto;

option go_package = "github.com/ydb-platform/ydb/ydb/core/nbs/nbs1_compat_api/cloud/blockstore/public/api/protos";

////////////////////////////////////////////////////////////////////////////////
// Health-check request/response

message TPingRequest
{
    // Optional request headers.
    THeaders Headers = 1;
}

message TPingResponse
{
    // Optional error, set only if error happened.
    NYdb.NBS.NProto.TError Error = 1;

    // Most recent stats, will be used for load balancing
    uint64 LastByteCount = 2;
    uint64 LastRequestCount = 3;
}
