# Generated by devtools/yamaker. 
 
LIBRARY() 
 
OWNER(g:cpp-contrib) 
 
LICENSE(Apache-2.0) 
 
LICENSE_TEXTS(.yandex_meta/licenses.list.txt) 
 
PEERDIR( 
    contrib/libs/grpc/grpc 
    contrib/libs/grpc/grpc++ 
    contrib/libs/grpc/src/core/lib 
    contrib/libs/grpc/third_party/address_sorting 
    contrib/libs/grpc/third_party/upb 
    contrib/libs/openssl 
) 
 
ADDINCL( 
    GLOBAL contrib/libs/grpc/include 
    ${ARCADIA_BUILD_ROOT}/contrib/libs/grpc 
    contrib/libs/grpc 
    contrib/libs/grpc/src/core/ext/upb-generated 
    contrib/libs/grpc/third_party/upb 
) 
 
NO_COMPILER_WARNINGS() 
 
IF (OS_LINUX OR OS_DARWIN) 
    CFLAGS( 
        -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 
    ) 
ENDIF() 
 
SRCS( 
    alts_context.cc 
    alts_util.cc 
) 
 
END() 
