items:
- name: Первоначальное развертывание
  href: initial-deployment.md
- name: Настройка SSO
  href: sso.md
- name: Настройка резервного копирования в S3
  href: s3-backups.md
- name: Настройка ИИ-ассистента
  href: ai-assistant.md
