GO_LIBRARY()
IF (OS_DARWIN AND ARCH_ARM64 OR OS_DARWIN AND ARCH_X86_64 OR OS_LINUX AND ARCH_AARCH64 OR OS_LINUX AND ARCH_X86_64)
    SRCS(
		allocs.go
		benchmark.go
		cover.go
		example.go
		fuzz.go
		match.go
		newcover.go
		run_example.go
		testing.go
		testing_other.go
    )
ELSEIF (OS_WINDOWS AND ARCH_X86_64)
    SRCS(
		allocs.go
		benchmark.go
		cover.go
		example.go
		fuzz.go
		match.go
		newcover.go
		run_example.go
		testing.go
		testing_windows.go
    )
ENDIF()
END()
