---
apiVersion: ydb.tech/v1alpha1
kind: Database
metadata:
  name: {{ database_name }}
  namespace: {{ database_namespace }}
  annotations:
    ydb.tech/node-claim: {{ nodeclaim_name }}.{{ nodeclaim_namespace }}
spec:
  image:
    name: cr.yandex/crpl7ipeu79oseqhcgn2/ydb:23.2.9
    pullPolicy: IfNotPresent
  nodes: 3
  domain: Root
  resources:
    storageUnits:
      - count: 1
        unitKind: ssd    # please double check this field with disk kind on your selected nodes
  storageClusterRef:
    name: {{ storage_name }}

