apiVersion: batch/v1
kind: Job
metadata:
  name: ydbd-obl-job-{{ nodeclaim_name }}-{{ node_name.split('.')[0] }}
  namespace: {{ namespace_name }}
  annotations:
    ydb.tech/node-claim: {{ nodeclaim_name }}.{{ namespace_name }}
spec:
  template:
    metadata:
      annotations:
        ydb.tech/node-claim: {{ nodeclaim_name }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: "{{ node_name }}"
      tolerations:
      - key: "ydb.tech/node-claim"
        value: "{{ nodeclaim_name }}.{{ namespace_name }}"
        effect: "NoSchedule"
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
      containers:
      - name: ydbd-obliterate
        image: {{ ydb_image }}
        imagePullPolicy: Always
        # Obliterate function doesn't sync the disk after the operation, so we need to do it manually
        # We don't have such problem on baremetal, because ydbd running in the same namespace witqh obliterate
        command:
          - 'sh'
          - '-c'
          - 'find /dev/disk/ -path "*/by-partlabel/kikimr_*" -exec /opt/ydb/bin/ydbd admin bs disk obliterate {} \; && sync'
        resources:
          limits:
            ydb-disk-manager/hostdev: '1'
          requests:
            ydb-disk-manager/hostdev: '1'
        securityContext:
          capabilities:
            add: ["SYS_RAWIO"]
      restartPolicy: Never