# ClickHouse uses non-standard naming for poco libraries,
# hence we have to duplicate provides.pbtxt with alternative naming
p { x: "_poco_crypto" peerdir: "contrib/libs/poco/Crypto" }
p { x: "_poco_data" peerdir: "contrib/libs/poco/Data" }
p { x: "_poco_foundation" peerdir: "contrib/libs/poco/Foundation" }
p { x: "_poco_json" peerdir: "contrib/libs/poco/JSON" }
p { x: "_poco_mongodb" peerdir: "contrib/libs/poco/MongoDB" }
p { x: "_poco_net" peerdir: "contrib/libs/poco/Net"}
p { x: "_poco_net_ssl" peerdir: "contrib/libs/poco/NetSSL_OpenSSL" }
p { x: "_poco_redis" peerdir: "contrib/libs/poco/Redis" }
p { x: "_poco_util" peerdir: "contrib/libs/poco/Util" }
p { x: "_poco_xml" peerdir: "contrib/libs/poco/XML" }

# base64 in ClickHouse referes to https://github.com/powturbo/Turbo-Base64
# but the name is too common to be put into projects/provides.pbtxt
p { x: "base64" pi: "contrib/restricted/turbo_base64" }

# ClickHouse uses fixed version of cityhash (1.0.2)
p { x: "cityhash" pi: "contrib/restricted/cityhash-1.0.2" }

# consistent-hashing is internal project of Yandex
p { x: "consistent-hashing" pi: "library/cpp/consistent_hashing" }

# ClickHouse uses copy-pasted function readpassphrase() from libc_compat
p { x: "readpassphrase" peerdir: "contrib/libs/libc_compat" }

# yamaker could not properly resolve needed boost libs by includes,
# so add peerdir to all boost-libs used in ClickHouse when boost is used
p {
    x: "boost"
    peerdir: "contrib/restricted/boost/circular_buffer"
    peerdir: "contrib/restricted/boost/container_hash"
    peerdir: "contrib/restricted/boost/context"
    peerdir: "contrib/restricted/boost/convert"
    peerdir: "contrib/restricted/boost/dynamic_bitset"
    peerdir: "contrib/restricted/boost/geometry"
    peerdir: "contrib/restricted/boost/heap"
    peerdir: "contrib/restricted/boost/multi_index"
    peerdir: "contrib/restricted/boost/program_options"
}

# ClickHouse uses custom addincl to croaring/include/roaring.
p { x: "roaring" peerdir: "contrib/libs/croaring" addincl: "contrib/libs/croaring/include/roaring" }

# Pseudo-libraries which imitate API of some clickhouse dependencies.
p { x: "h3_compat" pi: "library/cpp/clickhouse_deps/h3_compat" }
p { x: "incbin_stub" pi: "library/cpp/clickhouse_deps/incbin_stub"}
p { x: "re2_st_stub" peerdir: "library/cpp/clickhouse_deps/re2_st_stub" }

# Contribs in arcadia that are used only in ClickHouse.
# They may contain the exact version used in ClickHouse (incl. unstable/patched version)
# to simplify ClickHouse update in arcadia.
p { x: "morton-nd" peerdir: "contrib/restricted/clickhouse-deps/morton-nd" }

# TODO(dakovalkov): We use ClickHouse's version of replxx and it should be in
# contrib/restricted/clickhouse-deps, but ydb has already added another dependency.
p { x: "replxx" peerdir: "contrib/restricted/patched/replxx" }

p { x: "pocketfft" pi: "contrib/libs/pocketfft" }
