# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(2.4.0)

LICENSE(Apache-2.0)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    absl/__init__.py
    absl/app.py
    absl/app.pyi
    absl/command_name.py
    absl/flags/__init__.py
    absl/flags/_argument_parser.py
    absl/flags/_defines.py
    absl/flags/_exceptions.py
    absl/flags/_flag.py
    absl/flags/_flagvalues.py
    absl/flags/_helpers.py
    absl/flags/_validators.py
    absl/flags/_validators_classes.py
    absl/flags/argparse_flags.py
    absl/logging/__init__.py
    absl/logging/__init__.pyi
    absl/logging/converter.py
    absl/testing/__init__.py
    absl/testing/_bazelize_command.py
    absl/testing/_pretty_print_reporter.py
    absl/testing/absltest.py
    absl/testing/flagsaver.py
    absl/testing/parameterized.py
    absl/testing/xml_reporter.py
)

RESOURCE_FILES(
    PREFIX contrib/python/absl-py/py3/
    .dist-info/METADATA
    .dist-info/top_level.txt
    absl/py.typed
)

END()
