items:
- name: Обзор
  href: index.md
- name: Полное и инкрементальное резервное копирование
  href: full-and-incremental-backups.md
- name: Резервное копирование и восстановление через NFS
  href: nfs-backups.md
