from collections.abc import Callable

from typing_extensions import Buffer

def crc32c_cython(data: Buffer) -> int: ...
def decode_varint_cython(buffer: bytearray, pos: int) -> tuple[int, int]: ...
def encode_varint_cython(value: int, write: Callable[[int], None]) -> int: ...
def size_of_varint_cython(value: int) -> int: ...
