# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(0.6.0)

LICENSE(BSD-3-Clause)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    gast/__init__.py
    gast/ast2.py
    gast/ast3.py
    gast/astn.py
    gast/gast.py
    gast/unparser.py
    gast/version.py
)

RESOURCE_FILES(
    PREFIX contrib/python/gast/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
