# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(14.6.0)

LICENSE(MIT)

PEERDIR(
    contrib/python/marshmallow
    contrib/python/python-dotenv
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    environs/__init__.py
    environs/exceptions.py
    environs/fields.py
    environs/types.py
)

RESOURCE_FILES(
    PREFIX contrib/python/environs/
    .dist-info/METADATA
    .dist-info/top_level.txt
    environs/py.typed
)

END()
