GO_LIBRARY()
IF (OS_DARWIN AND ARCH_ARM64 AND RACE OR OS_DARWIN AND ARCH_X86_64 AND RACE OR OS_LINUX AND ARCH_AARCH64 AND RACE OR OS_LINUX AND ARCH_X86_64 AND RACE OR OS_WINDOWS AND ARCH_X86_64 AND RACE)
    SRCS(
		doc.go
		race.s
		type.go
		value.go
    )
ELSEIF (OS_DARWIN AND ARCH_ARM64 AND NOT RACE OR OS_DARWIN AND ARCH_X86_64 AND NOT RACE OR OS_LINUX AND ARCH_AARCH64 AND NOT RACE OR OS_LINUX AND ARCH_X86_64 AND NOT RACE OR OS_WINDOWS AND ARCH_X86_64 AND NOT RACE)
    SRCS(
		asm.s
		doc.go
		type.go
		value.go
    )
ENDIF()
END()
