LIBRARY()

SRCS(
    actor.cpp
    change_message_visibility.cpp
    config.cpp
    consumer_attributes.cpp
    create_queue.cpp
    delete_message.cpp
    delete_queue.cpp
    error.cpp
    get_queue_attributes.cpp
    get_queue_url.cpp
    limits.cpp
    list_queues.cpp
    purge_queue.cpp
    receipt.cpp
    receive_message.cpp
    send_message.cpp
    set_queue_attributes.cpp
    sqs_topic_proxy.cpp
    statuses.cpp
    utils.cpp
)

PEERDIR(
    ydb/library/grpc/server
    ydb/core/base
    ydb/core/client/server
    ydb/core/grpc_services
    ydb/core/mind
    ydb/public/api/grpc
    ydb/public/api/grpc/draft
    ydb/public/sdk/cpp/src/library/operation_id
    ydb/public/sdk/cpp/src/client/resources
    ydb/services/datastreams/codes
    ydb/services/lib/actors
    ydb/services/lib/sharding
    ydb/services/persqueue_v1
    ydb/services/sqs_topic/queue_url
    ydb/services/sqs_topic/queue_url/holder
    ydb/services/sqs_topic/protos/receipt
    ydb/services/ydb
    ydb/core/persqueue/public/describer
    ydb/core/persqueue/public/mlp
    ydb/core/ymq/attributes
    ydb/core/ymq/base
    ydb/core/ymq/error
    library/cpp/json
)

END()

RECURSE(
    protos
    queue_url
)
