/* postgres can not */
/* syntax version 1 */
SELECT
    key,
    FIRST_VALUE(key) RESPECT NULLS OVER w1,
    FIRST_VALUE(key) IGNORE NULLS OVER w1,
    LAST_VALUE(key) OVER w1,
    LAST_VALUE(key) IGNORE NULLS OVER w1,
    FIRST_VALUE(NULL) RESPECT NULLS OVER w1,
    FIRST_VALUE(NULL) IGNORE NULLS OVER w1,
    LAST_VALUE(NULL) OVER w1,
    LAST_VALUE(NULL) IGNORE NULLS OVER w1,
    subkey
FROM plato.Input
WINDOW
    w1 AS (
        ORDER BY
            subkey
        ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    )
ORDER BY
    subkey;
