PY2_LIBRARY()

LICENSE(Apache-2.0)

VERSION(3.4.5)

PEERDIR(
    contrib/deprecated/python/singledispatch
    contrib/python/six
)

NO_LINT()
NO_CHECK_IMPORTS(
    nltk.*
)

PY_SRCS(
    TOP_LEVEL
    nltk/__init__.py
    nltk/app/__init__.py
    nltk/app/chartparser_app.py
    nltk/app/chunkparser_app.py
    nltk/app/collocations_app.py
    nltk/app/concordance_app.py
    nltk/app/nemo_app.py
    nltk/app/rdparser_app.py
    nltk/app/srparser_app.py
    nltk/app/wordfreq_app.py
    nltk/app/wordnet_app.py
    nltk/book.py
    nltk/ccg/__init__.py
    nltk/ccg/api.py
    nltk/ccg/chart.py
    nltk/ccg/combinator.py
    nltk/ccg/lexicon.py
    nltk/ccg/logic.py
    nltk/chat/__init__.py
    nltk/chat/eliza.py
    nltk/chat/iesha.py
    nltk/chat/rude.py
    nltk/chat/suntsu.py
    nltk/chat/util.py
    nltk/chat/zen.py
    nltk/chunk/__init__.py
    nltk/chunk/api.py
    nltk/chunk/named_entity.py
    nltk/chunk/regexp.py
    nltk/chunk/util.py
    nltk/classify/__init__.py
    nltk/classify/api.py
    nltk/classify/decisiontree.py
    nltk/classify/maxent.py
    nltk/classify/megam.py
    nltk/classify/naivebayes.py
    nltk/classify/positivenaivebayes.py
    nltk/classify/rte_classify.py
    nltk/classify/scikitlearn.py
    nltk/classify/senna.py
    nltk/classify/svm.py
    nltk/classify/tadm.py
    nltk/classify/textcat.py
    nltk/classify/util.py
    nltk/classify/weka.py
    nltk/cluster/__init__.py
    nltk/cluster/api.py
    nltk/cluster/em.py
    nltk/cluster/gaac.py
    nltk/cluster/kmeans.py
    nltk/cluster/util.py
    nltk/collections.py
    nltk/collocations.py
    nltk/compat.py
    nltk/corpus/__init__.py
    nltk/corpus/europarl_raw.py
    nltk/corpus/reader/__init__.py
    nltk/corpus/reader/aligned.py
    nltk/corpus/reader/api.py
    nltk/corpus/reader/bnc.py
    nltk/corpus/reader/bracket_parse.py
    nltk/corpus/reader/categorized_sents.py
    nltk/corpus/reader/chasen.py
    nltk/corpus/reader/childes.py
    nltk/corpus/reader/chunked.py
    nltk/corpus/reader/cmudict.py
    nltk/corpus/reader/comparative_sents.py
    nltk/corpus/reader/conll.py
    nltk/corpus/reader/crubadan.py
    nltk/corpus/reader/dependency.py
    nltk/corpus/reader/framenet.py
    nltk/corpus/reader/ieer.py
    nltk/corpus/reader/indian.py
    nltk/corpus/reader/ipipan.py
    nltk/corpus/reader/knbc.py
    nltk/corpus/reader/lin.py
    nltk/corpus/reader/mte.py
    nltk/corpus/reader/nkjp.py
    nltk/corpus/reader/nombank.py
    nltk/corpus/reader/nps_chat.py
    nltk/corpus/reader/opinion_lexicon.py
    nltk/corpus/reader/panlex_lite.py
    nltk/corpus/reader/panlex_swadesh.py
    nltk/corpus/reader/pl196x.py
    nltk/corpus/reader/plaintext.py
    nltk/corpus/reader/ppattach.py
    nltk/corpus/reader/propbank.py
    nltk/corpus/reader/pros_cons.py
    nltk/corpus/reader/reviews.py
    nltk/corpus/reader/rte.py
    nltk/corpus/reader/semcor.py
    nltk/corpus/reader/senseval.py
    nltk/corpus/reader/sentiwordnet.py
    nltk/corpus/reader/sinica_treebank.py
    nltk/corpus/reader/string_category.py
    nltk/corpus/reader/switchboard.py
    nltk/corpus/reader/tagged.py
    nltk/corpus/reader/timit.py
    nltk/corpus/reader/toolbox.py
    nltk/corpus/reader/twitter.py
    nltk/corpus/reader/udhr.py
    nltk/corpus/reader/util.py
    nltk/corpus/reader/verbnet.py
    nltk/corpus/reader/wordlist.py
    nltk/corpus/reader/wordnet.py
    nltk/corpus/reader/xmldocs.py
    nltk/corpus/reader/ycoe.py
    nltk/corpus/util.py
    nltk/data.py
    nltk/decorators.py
    nltk/downloader.py
    nltk/draw/__init__.py
    nltk/draw/cfg.py
    nltk/draw/dispersion.py
    nltk/draw/table.py
    nltk/draw/tree.py
    nltk/draw/util.py
    nltk/featstruct.py
    nltk/grammar.py
    nltk/help.py
    nltk/inference/__init__.py
    nltk/inference/api.py
    nltk/inference/discourse.py
    nltk/inference/mace.py
    nltk/inference/nonmonotonic.py
    nltk/inference/prover9.py
    nltk/inference/resolution.py
    nltk/inference/tableau.py
    nltk/internals.py
    nltk/jsontags.py
    nltk/lazyimport.py
    nltk/lm/__init__.py
    nltk/lm/api.py
    nltk/lm/counter.py
    nltk/lm/models.py
    nltk/lm/preprocessing.py
    nltk/lm/smoothing.py
    nltk/lm/util.py
    nltk/lm/vocabulary.py
    nltk/metrics/__init__.py
    nltk/metrics/agreement.py
    nltk/metrics/aline.py
    nltk/metrics/association.py
    nltk/metrics/confusionmatrix.py
    nltk/metrics/distance.py
    nltk/metrics/paice.py
    nltk/metrics/scores.py
    nltk/metrics/segmentation.py
    nltk/metrics/spearman.py
    nltk/misc/__init__.py
    nltk/misc/babelfish.py
    nltk/misc/chomsky.py
    nltk/misc/minimalset.py
    nltk/misc/sort.py
    nltk/misc/wordfinder.py
    nltk/parse/__init__.py
    nltk/parse/api.py
    nltk/parse/bllip.py
    nltk/parse/chart.py
    nltk/parse/corenlp.py
    nltk/parse/dependencygraph.py
    nltk/parse/earleychart.py
    nltk/parse/evaluate.py
    nltk/parse/featurechart.py
    nltk/parse/generate.py
    nltk/parse/malt.py
    nltk/parse/nonprojectivedependencyparser.py
    nltk/parse/pchart.py
    nltk/parse/projectivedependencyparser.py
    nltk/parse/recursivedescent.py
    nltk/parse/shiftreduce.py
    nltk/parse/stanford.py
    nltk/parse/transitionparser.py
    nltk/parse/util.py
    nltk/parse/viterbi.py
    nltk/probability.py
    nltk/sem/__init__.py
    nltk/sem/boxer.py
    nltk/sem/chat80.py
    nltk/sem/cooper_storage.py
    nltk/sem/drt.py
    nltk/sem/drt_glue_demo.py
    nltk/sem/evaluate.py
    nltk/sem/glue.py
    nltk/sem/hole.py
    nltk/sem/lfg.py
    nltk/sem/linearlogic.py
    nltk/sem/logic.py
    nltk/sem/relextract.py
    nltk/sem/skolemize.py
    nltk/sem/util.py
    nltk/sentiment/__init__.py
    nltk/sentiment/sentiment_analyzer.py
    nltk/sentiment/util.py
    nltk/sentiment/vader.py
    nltk/stem/__init__.py
    nltk/stem/api.py
    nltk/stem/arlstem.py
    nltk/stem/cistem.py
    nltk/stem/isri.py
    nltk/stem/lancaster.py
    nltk/stem/porter.py
    nltk/stem/regexp.py
    nltk/stem/rslp.py
    nltk/stem/snowball.py
    nltk/stem/util.py
    nltk/stem/wordnet.py
    nltk/tag/__init__.py
    nltk/tag/api.py
    nltk/tag/brill.py
    nltk/tag/brill_trainer.py
    nltk/tag/crf.py
    nltk/tag/hmm.py
    nltk/tag/hunpos.py
    nltk/tag/mapping.py
    nltk/tag/perceptron.py
    nltk/tag/senna.py
    nltk/tag/sequential.py
    nltk/tag/stanford.py
    nltk/tag/tnt.py
    nltk/tag/util.py
    nltk/tbl/__init__.py
    nltk/tbl/api.py
    nltk/tbl/demo.py
    nltk/tbl/erroranalysis.py
    nltk/tbl/feature.py
    nltk/tbl/rule.py
    nltk/tbl/template.py
    nltk/text.py
    nltk/tgrep.py
    nltk/tokenize/__init__.py
    nltk/tokenize/api.py
    nltk/tokenize/casual.py
    nltk/tokenize/mwe.py
    nltk/tokenize/nist.py
    nltk/tokenize/punkt.py
    nltk/tokenize/regexp.py
    nltk/tokenize/repp.py
    nltk/tokenize/sexpr.py
    nltk/tokenize/simple.py
    nltk/tokenize/sonority_sequencing.py
    nltk/tokenize/stanford.py
    nltk/tokenize/stanford_segmenter.py
    nltk/tokenize/texttiling.py
    nltk/tokenize/toktok.py
    nltk/tokenize/treebank.py
    nltk/tokenize/util.py
    nltk/toolbox.py
    nltk/translate/__init__.py
    nltk/translate/api.py
    nltk/translate/bleu_score.py
    nltk/translate/chrf_score.py
    nltk/translate/gale_church.py
    nltk/translate/gdfa.py
    nltk/translate/gleu_score.py
    nltk/translate/ibm1.py
    nltk/translate/ibm2.py
    nltk/translate/ibm3.py
    nltk/translate/ibm4.py
    nltk/translate/ibm5.py
    nltk/translate/ibm_model.py
    nltk/translate/meteor_score.py
    nltk/translate/metrics.py
    nltk/translate/nist_score.py
    nltk/translate/phrase_based.py
    nltk/translate/ribes_score.py
    nltk/translate/stack_decoder.py
    nltk/tree.py
    nltk/treeprettyprinter.py
    nltk/treetransforms.py
    nltk/twitter/__init__.py
    nltk/twitter/api.py
    nltk/twitter/common.py
    nltk/twitter/twitter_demo.py
    nltk/twitter/twitterclient.py
    nltk/twitter/util.py
    nltk/util.py
    nltk/wsd.py
)

RESOURCE_FILES(
    PREFIX contrib/python/nltk/py2/
    .dist-info/METADATA
    .dist-info/top_level.txt
    nltk/VERSION
)

END()
