RECURSE_ROOT_RELATIVE(
    ydb/library/yql/minikql/benchmark
    ydb/library/yql/minikql/jsonpath/benchmark
    ydb/library/yql/minikql/perf/alloc
    ydb/library/yql/minikql/perf/mt_param
    ydb/library/yql/minikql/perf/packer
    ydb/library/yql/minikql/perf/param
    ydb/library/yql/minikql/perf/presort
    ydb/library/yql/sql/v1/perf
)
