RECURSE_ROOT_RELATIVE(
    yql/essentials/minikql/benchmark
    yql/essentials/minikql/jsonpath/benchmark
    yql/essentials/minikql/perf/alloc
    yql/essentials/minikql/perf/mt_param
    yql/essentials/minikql/perf/packer
    yql/essentials/minikql/perf/param
    yql/essentials/minikql/perf/presort
    yql/essentials/sql/v1/perf
)
