[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", 
            "pybind11", 
            "pyomo", 
            "wheel"]  # PEP 508 specifications.

build-backend = "setuptools.build_meta"

[tool.cibuildwheel.macos]
     repair-wheel-command = [
         "DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH delocate-listdeps {wheel}",
         "DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}"
     ]