static_erasure: none
host_configs:
- drive:
  - path: /tmp/pdisk.data
    type: SSD
  host_config_id: 1
hosts:
- host: localhost
  host_config_id: 1
  port: 19001
  walle_location:
    body: 1
    data_center: '1'
    rack: '1'
domains_config:
  domain:
  - name: Root
    storage_pool_types:
    - kind: ssd
      pool_config:
        box_id: 1
        erasure_species: none
        kind: ssd
        pdisk_filter:
        - property:
          - type: SSD
        vdisk_kind: Default
  state_storage:
  - ring:
      node:
      - 1
      nto_select: 1
    ssid: 1
table_service_config:
  sql_version: 1
actor_system_config:
  executor:
  - name: System
    spin_threshold: 0
    threads: 2
    type: BASIC
  - name: User
    spin_threshold: 0
    threads: 3
    type: BASIC
  - name: Batch
    spin_threshold: 0
    threads: 2
    type: BASIC
  - name: IO
    threads: 1
    time_per_mailbox_micro_secs: 100
    type: IO
  - name: IC
    spin_threshold: 10
    threads: 1
    time_per_mailbox_micro_secs: 100
    type: BASIC
  scheduler:
    progress_threshold: 10000
    resolution: 256
    spin_threshold: 0
blob_storage_config:
  service_set:
    groups:
    - erasure_species: none
      rings:
      - fail_domains:
        - vdisk_locations:
          - node_id: 1
            path: /tmp/pdisk.data
            pdisk_category: SSD
channel_profile_config:
  profile:
  - channel:
    - erasure_species: none
      pdisk_category: 0
      storage_pool_kind: ssd
    - erasure_species: none
      pdisk_category: 0
      storage_pool_kind: ssd
    - erasure_species: none
      pdisk_category: 0
      storage_pool_kind: ssd
    profile_id: 0
