# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(0.7.3)

LICENSE(MIT)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    loguru/__init__.py
    loguru/__init__.pyi
    loguru/_asyncio_loop.py
    loguru/_better_exceptions.py
    loguru/_colorama.py
    loguru/_colorizer.py
    loguru/_contextvars.py
    loguru/_ctime_functions.py
    loguru/_datetime.py
    loguru/_defaults.py
    loguru/_error_interceptor.py
    loguru/_file_sink.py
    loguru/_filters.py
    loguru/_get_frame.py
    loguru/_handler.py
    loguru/_locks_machinery.py
    loguru/_logger.py
    loguru/_recattrs.py
    loguru/_simple_sinks.py
    loguru/_string_parsers.py
)

RESOURCE_FILES(
    PREFIX contrib/python/loguru/
    .dist-info/METADATA
    .dist-info/top_level.txt
    loguru/py.typed
)

END()
