LIBRARY()

SRCS(
    auth.cpp
    actor_activity_names.cpp
    appdata.cpp
    backtrace.cpp
    board_lookup.cpp
    board_publish.cpp
    board_replica.cpp
    bridge.cpp
    blobstorage.cpp
    blobstorage_grouptype.cpp
    blobstorage_relevance.cpp
    boot_type.cpp
    counters.cpp
    domain.cpp
    event_filter.cpp
    feature_flags_service.cpp
    fulltext.cpp
    group_stat.cpp
    kmeans_clusters.cpp
    local_user_token.cpp
    localdb.cpp
    logoblob.cpp
    path.cpp
    pool_stats_collector.cpp
    row_version.cpp
    services_assert.cpp
    statestorage.cpp
    statestorage_event_filter.cpp
    statestorage_guardian.cpp
    statestorage_monitoring.cpp
    statestorage_proxy.cpp
    statestorage_replica.cpp
    storage_pools.cpp
    subdomain.cpp
    table_index.cpp
    tablet.cpp
    tablet_dev_ui_mon_access.cpp
    tablet_killer.cpp
    tablet_status_checker.cpp
    traceid.cpp
    tx_processing.cpp
    wilson_tracing_control.cpp
    json_index.cpp
)

PEERDIR(
    contrib/libs/snowball
    ydb/library/actors/core
    ydb/library/actors/helpers
    ydb/library/actors/interconnect
    ydb/library/actors/protos
    ydb/library/actors/wilson
    ydb/library/aclib
    library/cpp/deprecated/enum_codegen
    library/cpp/dot_product
    library/cpp/l1_distance
    library/cpp/l2_distance
    library/cpp/logger
    library/cpp/lwtrace
    library/cpp/lwtrace/mon
    library/cpp/random_provider
    library/cpp/time_provider
    ydb/core/audit/audit_config
    ydb/core/base/generated
    ydb/core/base/services
    ydb/core/control/lib
    ydb/core/debug
    ydb/core/erasure
    ydb/core/graph/api
    ydb/core/jaeger_tracing
    ydb/core/protos
    ydb/core/protos/out
    ydb/library/aclib
    ydb/library/login
    ydb/library/pdisk_io
    ydb/library/pretty_types_print/protobuf
    ydb/library/ydb_issue
    ydb/public/api/protos/out
    yql/essentials/minikql
    yql/essentials/types/binary_json
    library/cpp/deprecated/atomic
)

YQL_LAST_ABI_VERSION()

IF (NOT OS_WINDOWS)
PEERDIR(
    library/cpp/dwarf_backtrace
)
ENDIF()

GENERATE_ENUM_SERIALIZATION(boot_type.h)
GENERATE_ENUM_SERIALIZATION(memory_controller_iface.h)

END()

RECURSE(
    generated
)

RECURSE_FOR_TESTS(
    ut
    ut_auth
    ut_board_subscriber
)
