# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(2.2.0)

LICENSE(Apache-2.0)

PEERDIR(
    contrib/python/aiohttp
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    aiohttp_sse/__init__.py
    aiohttp_sse/helpers.py
)

RESOURCE_FILES(
    PREFIX contrib/python/aiohttp-sse/
    .dist-info/METADATA
    .dist-info/top_level.txt
    aiohttp_sse/py.typed
)

END()

RECURSE_FOR_TESTS(
    tests
)
