# Generated by devtools/yamaker.

LIBRARY()

VERSION(8.0.1)

LICENSE(NCSA)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

PEERDIR(
    contrib/libs/llvm8/include
    contrib/libs/llvm8/lib/BinaryFormat
    contrib/libs/llvm8/lib/Bitcode/Reader
    contrib/libs/llvm8/lib/IR
    contrib/libs/llvm8/lib/MC
    contrib/libs/llvm8/lib/MC/MCParser
    contrib/libs/llvm8/lib/Support
)

ADDINCL(
    contrib/libs/llvm8/include
    ${ARCADIA_BUILD_ROOT}/contrib/libs/llvm8/include
    contrib/libs/llvm8/lib/Object
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    Archive.cpp
    ArchiveWriter.cpp
    Binary.cpp
    COFFImportFile.cpp
    COFFModuleDefinition.cpp
    COFFObjectFile.cpp
    Decompressor.cpp
    ELF.cpp
    ELFObjectFile.cpp
    Error.cpp
    IRObjectFile.cpp
    IRSymtab.cpp
    MachOObjectFile.cpp
    MachOUniversal.cpp
    ModuleSymbolTable.cpp
    Object.cpp
    ObjectFile.cpp
    RecordStreamer.cpp
    SymbolSize.cpp
    SymbolicFile.cpp
    WasmObjectFile.cpp
    WindowsResource.cpp
)

END()
