# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(1.6.0)

LICENSE(Apache-2.0)

PEERDIR(
    contrib/python/psutil
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    portpicker.py
)

RESOURCE_FILES(
    PREFIX contrib/python/portpicker/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
