syntax = "proto3";

package NLogBroker;

option cc_enable_arenas = true;
option java_package = "com.yandex.logbroker";
option go_package = "a.yandex-team.ru/logbroker/public/api/common;logbroker_common";

import "google/protobuf/descriptor.proto";

message Limit {
    message Range {
        uint32 min = 1;
        uint32 max = 2;
    }

    oneof kind {
        Range range = 1;
        uint32 lt = 2;
        uint32 le = 3;
        uint32 eq = 4;
        uint32 ge = 5;
        uint32 gt = 6;
    }
}

message MapKey {
    Limit length = 1;
    string value = 2;
}

extend google.protobuf.FieldOptions {
    bool required = 787650;
    Limit size = 787651;
    Limit length = 787652;
    MapKey map_key = 787653;
    string value = 787654;
}
