syntax = "proto3";

package NLogBroker.Issue;

option cc_enable_arenas = true;
option java_package = "com.yandex.logbroker";
option go_package = "a.yandex-team.ru/logbroker/public/api/common;logbroker_common";

message IssueMessage {
    message Position {
        uint32 row = 1;
        uint32 column = 2;
        string file = 3;
    }

    Position position = 1;
    string message = 2;
    Position end_position = 3;
    uint32 issue_code = 4;
    uint32 severity = 5;
    repeated IssueMessage issues = 6;
}
