syntax = "proto3";

import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/common/common.proto";
import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/common/ydb_operation.proto";

package NLogBroker;

option cc_enable_arenas = true;
option go_package = "a.yandex-team.ru/logbroker/public/api/protos;logbroker";

message ExecuteModifyCommandsRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    repeated SingleModifyRequest actions = 2;
    string comment = 3;
    string token = 111;
}

message SingleModifyRequest {
    oneof request {
        CreateDirectoryRequest create_directory = 1;
        CreateTopicRequest create_topic = 2;
        CreateConsumerRequest create_consumer = 3;
        CreateReadRuleRequest create_read_rule = 4;
        CreateAccountRequest create_account = 5;
        CreateRemoteMirrorRuleRequest create_remote_mirror_rule = 6;

        UpdateDirectoryRequest update_directory = 10;
        UpdateTopicRequest update_topic = 11;
        UpdateConsumerRequest update_consumer = 12;
        UpdateAccountRequest update_account = 14;
        UpdateRemoteMirrorRuleRequest update_remote_mirror_rule = 15;

        SetDirectoryRateLimitRequest set_directory_rate_limit = 40;
        SetTopicRateLimitRequest set_topic_rate_limit = 41;
        SetConsumerRateLimitRequest set_consumer_rate_limit = 42;
        SetMetadataRequest set_metadata = 60;

        RemoveDirectoryRequest remove_directory = 20;
        RemoveTopicRequest remove_topic = 21;
        RemoveConsumerRequest remove_consumer = 22;
        RemoveReadRuleRequest remove_read_rule = 23;
        RemoveDirectoryRateLimitRequest remove_directory_rate_limit = 50;
        RemoveTopicRateLimitRequest remove_topic_rate_limit = 51;
        RemoveConsumerRateLimitRequest remove_consumer_rate_limit = 52;
        RemoveMetadataRequest remove_metadata = 61;
        RemoveRemoteMirrorRuleRequest remove_remote_mirror_rule = 62;

        GrantPermissionsRequest grant_permissions = 30;
        RevokePermissionsRequest revoke_permissions = 31;
        SetPermissionsRequest set_permissions = 32;
        ChangeOwnerRequest change_owner = 33;

        AddTopicToYtDeliveryRequest add_topic_to_yt_delivery = 70;
        RemoveTopicFromYtDeliveryRequest remove_topic_from_yt_delivery = 71;
    }
}

message DescribeClusterRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string name = 2;
    string token = 111;
}

message DescribeClusterResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message DescribeClusterResult {
    string name = 1;
    NLogBroker.ClusterProperties properties = 2;
}

message DescribePathRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    NLogBroker.Path path = 2;
    string token = 111;
}

message DescribePathResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message DescribePathResult {
    NLogBroker.Path path = 1;
    oneof result {
        DescribeAccountResult account = 2;
        DescribeDirectoryResult directory = 3;
        DescribeTopicResult topic = 4;
        DescribeConsumerResult consumer = 5;
    }
    uint64 creation_time_ms = 20;
    uint64 modification_time_ms = 21;
    string created_by = 22;
    string modified_by = 23;
}

message DescribeAccountResult {
    string name = 1;
    NLogBroker.AccountProperties properties = 2;
    NLogBroker.QuotaUsageProperties quota_usage = 8;
    repeated NLogBroker.AccountRateLimitProperties account_rate_limits = 11;
    repeated NLogBroker.DirectoryRateLimitProperties rate_limits = 3;
    repeated NLogBroker.Permissions permissions = 4;
    repeated NLogBroker.Permissions effective_permissions = 5;
    repeated NLogBroker.Metadata metadata = 7;
    bool is_related_to_caller = 9;
    string owner = 10;
}

message DescribeDirectoryResult {
    NLogBroker.DirectoryProperties properties = 1;
    repeated NLogBroker.DirectoryRateLimitProperties rate_limits = 2;
    repeated NLogBroker.InheritedDirectoryRateLimit inherited_rate_limits = 3;
    repeated NLogBroker.Permissions permissions = 4;
    repeated NLogBroker.Permissions effective_permissions = 5;
    repeated NLogBroker.Metadata metadata = 7;
    string owner = 8;
    uint32 children_count = 9;
}

message DescribeTopicResult {
    message Consumer {
        string path = 1;
        repeated NLogBroker.TopicInstance instances = 2;
    }

    NLogBroker.TopicProperties properties = 1;
    NLogBroker.TopicAdminProperties admin_properties = 2;
    repeated NLogBroker.TopicRateLimitProperties rate_limits = 3;
    repeated NLogBroker.InheritedDirectoryRateLimit inherited_rate_limits = 4;
    repeated NLogBroker.Permissions permissions = 5;
    repeated NLogBroker.Permissions effective_permissions = 6;
    repeated NLogBroker.ReadRule read_rules = 9;
    repeated NLogBroker.Metadata metadata = 10;
    string owner = 11;
    repeated NLogBroker.TopicInstance instances = 12;
    repeated Consumer consumers = 13;
    repeated string yt_deliveries = 14;
    bool addition_to_yt_delivery_allowed = 15;
    bool removal_from_yt_delivery_allowed = 16;
    repeated NLogBroker.RemoteMirrorRuleAdmin remote_mirror_rules = 17;
}

message DescribeConsumerResult {
    message Topic {
        string path = 1;
        repeated NLogBroker.TopicInstance instances = 2;
    }

    NLogBroker.ConsumerProperties properties = 1;
    repeated NLogBroker.ConsumerRateLimitProperties rate_limits = 2;
    repeated NLogBroker.InheritedDirectoryRateLimit inherited_rate_limits = 3;
    repeated NLogBroker.Permissions permissions = 4;
    repeated NLogBroker.Permissions effective_permissions = 5;
    repeated NLogBroker.ReadRule read_rules = 7;
    repeated NLogBroker.Metadata metadata = 8;
    string owner = 9;
    repeated Topic topics = 10;
}

message ListClustersRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string token = 111;
}

message ListClustersResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message ListClustersResult {
    repeated string names = 1;
}

message ListAccountsRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    string token = 111;
}

message ListAccountsResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message ListAccountsResult {
    repeated string names = 1;
}

message ListDirectoryRequest {
    NLogBroker.Operations.OperationParams operation_params = 1;
    NLogBroker.Path path = 2;
    string token = 111;
}

message ListDirectoryResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message ListDirectoryResult {
    NLogBroker.Path path = 1;
    NLogBroker.Entry self = 2;
    repeated NLogBroker.Entry children = 3;
}

message CreateAccountRequest {
    string name = 1;
    string abc_service = 2;
    string responsible = 3;
    uint32 abc_id = 4;
    string monitoring_project_id = 5;
}

message CreateDirectoryRequest {
    NLogBroker.Path path = 1;
    NLogBroker.DirectoryProperties properties = 2;
}

message CreateTopicRequest {
    NLogBroker.Path path = 1;
    NLogBroker.TopicProperties properties = 2;
}

message CreateConsumerRequest {
    NLogBroker.Path path = 1;
    NLogBroker.ConsumerProperties properties = 3;
}

message CreateReadRuleRequest {
    NLogBroker.ReadRuleKey read_rule = 1;
    NLogBroker.ReadRuleProperties properties = 2;
}

message CreateRemoteMirrorRuleRequest {
    NLogBroker.RemoteMirrorRuleKey remote_mirror_rule = 1;
    NLogBroker.RemoteMirrorRuleProperties properties = 2;
}

message UpdateAccountRequest {
    string name = 1;
    string abc_service = 2;
    string responsible = 3;
    uint32 abc_id = 4;
    string monitoring_project_id = 5;
}

message UpdateDirectoryRequest {
    NLogBroker.Path path = 1;
    NLogBroker.DirectoryProperties properties = 2;
}

message UpdateTopicRequest {
    NLogBroker.Path path = 1;
    NLogBroker.TopicProperties properties = 2;
}

message UpdateConsumerRequest {
    NLogBroker.Path path = 1;
    NLogBroker.ConsumerProperties properties = 2;
}

message UpdateReadRuleRequest {
    NLogBroker.ReadRuleKey read_rule = 1;
    NLogBroker.ReadRuleProperties properties = 2;
}

message UpdateRemoteMirrorRuleRequest {
    NLogBroker.RemoteMirrorRuleKey remote_mirror_rule = 1;
    NLogBroker.RemoteMirrorRuleProperties properties = 2;
}

message SetDirectoryRateLimitRequest {
    NLogBroker.Path path = 1;
    NLogBroker.DirectoryRateLimitProperties rate_limit = 2;
}

message SetTopicRateLimitRequest {
    NLogBroker.Path path = 1;
    NLogBroker.TopicRateLimitProperties rate_limit = 2;
}

message SetConsumerRateLimitRequest {
    NLogBroker.Path path = 1;
    NLogBroker.ConsumerRateLimitProperties rate_limit = 2;
}

message SetMetadataRequest {
    NLogBroker.Path path = 1;
    NLogBroker.Metadata metadata = 2;
}

message RemoveDirectoryRequest {
    NLogBroker.Path path = 1;
}

message RemoveTopicRequest {
    NLogBroker.Path path = 1;
}

message RemoveConsumerRequest {
    NLogBroker.Path path = 1;
}

message RemoveReadRuleRequest {
    NLogBroker.ReadRuleKey read_rule = 1;
}

message RemoveRemoteMirrorRuleRequest {
    NLogBroker.RemoteMirrorRuleKey remote_mirror_rule = 1;
}

message RemoveDirectoryRateLimitRequest {
    NLogBroker.ClusterKey cluster = 2;
    NLogBroker.Path path = 1;
}

message RemoveTopicRateLimitRequest {
    NLogBroker.ClusterKey cluster = 2;
    NLogBroker.Path path = 1;
}

message RemoveConsumerRateLimitRequest {
    NLogBroker.ClusterKey cluster = 2;
    NLogBroker.Path path = 1;
}

message RemoveMetadataRequest {
    NLogBroker.Path path = 1;
    string key = 2;
}

message GrantPermissionsRequest {
    NLogBroker.Path path = 1;
    repeated NLogBroker.Permissions permissions = 2;
}

message RevokePermissionsRequest {
    NLogBroker.Path path = 1;
    repeated NLogBroker.Permissions permissions = 2;
}

message SetPermissionsRequest {
    NLogBroker.Path path = 1;
    repeated NLogBroker.Permissions permissions = 2;
}

message ChangeOwnerRequest {
    NLogBroker.Path path = 1;
    string owner = 2;
}

message ListYtDeliveriesRequest {
    string token = 1;
}

message ListYtDeliveriesResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message YtDelivery {
    string path = 1;
    string destination = 2;
    bool addition_allowed = 3;
}

message ListYtDeliveriesResult {
    repeated YtDelivery deliveries = 1;
}

message AddTopicToYtDeliveryRequest {
    string topic = 1;
    string delivery = 2;
}

message RemoveTopicFromYtDeliveryRequest {
    string topic = 1;
    string delivery = 2;
}
