#include "env.h"

const std::initializer_list<ui32> TEnvironmentSetup::DebugLogComponents{
//    NKikimrServices::BS_CONTROLLER,
//    NKikimrServices::BS_SELFHEAL,
//    NKikimrServices::BS_PDISK,
//    NKikimrServices::BS_SKELETON,
//    NKikimrServices::BS_HULLCOMP,
//    NKikimrServices::BS_HULLRECS,
//    NKikimrServices::BS_HULLHUGE,
//    NKikimrServices::BS_REPL,
//    NKikimrServices::BS_SYNCER,
//    NKikimrServices::BS_SYNCLOG,
//    NKikimrServices::BS_SYNCJOB,
//    NKikimrServices::BS_QUEUE,
//    NKikimrServices::BS_VDISK_GET,
//    NKikimrServices::BS_VDISK_PATCH,
//    NKikimrServices::BS_VDISK_PUT,
//    NKikimrServices::BS_VDISK_OTHER,
//    NKikimrServices::BS_VDISK_SCRUB,
//    NKikimrServices::BS_PROXY,
//    NKikimrServices::BS_PROXY_RANGE,
//    NKikimrServices::BS_PROXY_GET,
//    NKikimrServices::BS_PROXY_PUT,
//    NKikimrServices::BS_PROXY_PATCH,
//    NKikimrServices::BS_PROXY_INDEXRESTOREGET,
//    NKikimrServices::BS_PROXY_STATUS,
    NActorsServices::TEST,
//    NKikimrServices::BLOB_DEPOT,
//    NKikimrServices::BLOB_DEPOT_AGENT,
//    NKikimrServices::HIVE,
//    NKikimrServices::LOCAL,
//    NActorsServices::INTERCONNECT,
//    NActorsServices::INTERCONNECT_SESSION,
//    NKikimrServices::BS_VDISK_BALANCING,
};
