# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(0.31.2)

LICENSE(MIT)

PEERDIR(
    contrib/python/marshmallow
    contrib/python/mongoengine
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    marshmallow_mongoengine/__init__.py
    marshmallow_mongoengine/conversion/__init__.py
    marshmallow_mongoengine/conversion/fields.py
    marshmallow_mongoengine/conversion/params.py
    marshmallow_mongoengine/convert.py
    marshmallow_mongoengine/exceptions.py
    marshmallow_mongoengine/fields.py
    marshmallow_mongoengine/schema.py
)

RESOURCE_FILES(
    PREFIX contrib/python/marshmallow-mongoengine/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()

RECURSE_FOR_TESTS(
    tests
)
