name: "validate-pr-description"

runs:
  using: "composite"
  steps:
    - name: Run validation script
      id: validate
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PR_BODY: ${{ inputs.pr_body}}
      run: |
        python3 -m pip install PyGithub
        echo "$PR_BODY" | python3 ${{ github.action_path }}/validate_pr_description.py

inputs:
  pr_body:
    description: "The body of the pull request."
    required: true

outputs:
  status:
    description: "The status of the PR description validation."
    value: ${{ steps.validate.outcome }}

files:
  - validate_pr_description.py
