# Generated by devtools/yamaker.

LIBRARY()

VERSION(8.0.1)

LICENSE(NCSA)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

PEERDIR(
    contrib/libs/llvm8/lib/MC
    contrib/libs/llvm8/lib/Support
)

ADDINCL(
    contrib/libs/llvm8/include
    contrib/libs/llvm8/lib/MC/MCParser
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    AsmLexer.cpp
    AsmParser.cpp
    COFFAsmParser.cpp
    DarwinAsmParser.cpp
    ELFAsmParser.cpp
    MCAsmLexer.cpp
    MCAsmParser.cpp
    MCAsmParserExtension.cpp
    MCTargetAsmParser.cpp
    WasmAsmParser.cpp
)

END()
