RECURSE(
    auth
    bg_tasks
    cms
    datastreams
    deprecated/persqueue_v0
    deprecated/persqueue_v0/api
    discovery
    dynamic_config
    ext_index
    fq
    kesus
    keyvalue
    lib
    local_discovery
    maintenance
    metadata
    monitoring
    persqueue_cluster_discovery
    persqueue_v1
    rate_limiter
    ydb
)
