{
 "title": "DataShard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": { "query": "label_values(database)" } }
  ]
 },
 "panels": [
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MiniKQL program size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_MiniKQLProgramSize{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Result size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_TxResultSize{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "RowRead rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_EngineHostRowReads{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "RowRead bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_EngineHostRowReadBytes{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "RangeRead rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_EngineHostRangeReadRows{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "RangeRead bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_EngineHostRangeReadBytes{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "RowUpdate rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_EngineHostRowUpdates{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "RowUpdate bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_EngineHostRowUpdateBytes{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "RowErase rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_EngineHostRowErases{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "RowErase bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_EngineHostRowEraseBytes{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "BulkUpsert rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_UploadRows{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "BulkUpsert bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_UploadRowsBytes{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Scanned rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_ScannedRows{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "Scanned bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_ScannedBytes{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "ReadColumns rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_ReadColumnsRows{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "ReadColumns bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_ReadColumnsBytes{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  { "title": "Compactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Compaction bytes read",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(tablets_CompactionBytesRead{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Compaction bytes written",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(tablets_CompactionBytesWritten{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Compaction queue sizes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(tablets_EnqueuedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen0\"})",
     "legendFormat": "gen0"
    },
    {
     "expr": "sum(tablets_EnqueuedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen1\"})",
     "legendFormat": "gen1"
    },
    {
     "expr": "sum(tablets_EnqueuedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen2\"})",
     "legendFormat": "gen2"
    },
    {
     "expr": "sum(tablets_EnqueuedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen3\"})",
     "legendFormat": "gen3"
    }
   ]
  },
  {
   "title": "Compactions in fly",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum(tablets_InFlyTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen0\"})",
     "legendFormat": "gen0"
    },
    {
     "expr": "sum(tablets_InFlyTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen1\"})",
     "legendFormat": "gen1"
    },
    {
     "expr": "sum(tablets_InFlyTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen2\"})",
     "legendFormat": "gen2"
    },
    {
     "expr": "sum(tablets_InFlyTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen3\"})",
     "legendFormat": "gen3"
    }
   ]
  },
  {
   "title": "Compactions finished",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(tablets_FinishedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen0\"}[1m]))",
     "legendFormat": "gen0"
    },
    {
     "expr": "sum(rate(tablets_FinishedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen1\"}[1m]))",
     "legendFormat": "gen1"
    },
    {
     "expr": "sum(rate(tablets_FinishedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen2\"}[1m]))",
     "legendFormat": "gen2"
    },
    {
     "expr": "sum(rate(tablets_EnqueuedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen3\"}[1m]))",
     "legendFormat": "gen3"
    }
   ]
  },
  { "title": "Readsets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Readset received count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_ReadsetReceivedCount{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Readset received size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_ReadsetReceivedSize{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Readset sent count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_ReadsetSentCount{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Readset sent size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_ReadsetSentSize{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Acks sent",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_AckSent{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Acks sent delayed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DataShard_AckSentDelayed{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Loaded blocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"tablets_DataShard_.+_LoadedBlocks\"}, \"name_label\", \"$1\", \"__name__\", \"tablets_DataShard_(.+)_LoadedBlocks\")[1m:]))",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Touched blocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"tablets_DataShard_.+_TouchedBlocks\"}, \"name_label\", \"$1\", \"__name__\", \"tablets_DataShard_(.+)_TouchedBlocks\")[1m:]))",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Read bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"tablets_DataShard_.+_ReadBytes\"}, \"name_label\", \"$1\", \"__name__\", \"tablets_DataShard_(.+)_ReadBytes\")[1m:]))",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Written bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "sum(rate(tablets_DbRedoWrittenBytes{database=\"$database\",container=\"ydb-dynamic\"}[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "max TxCompleteLag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "max(tablets_MAX_DataShard_TxCompleteLag_{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "max TxCompleteLag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "max(tablets_MAX_DataShard_TxCompleteLag_{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "ImmediateTxInFly",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "sum(tablets_SUM_DataShard_ImmediateTxInFly_{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "count"
    }
   ]
  }
 ]
}