PY3_LIBRARY()

LICENSE(MIT)

VERSION(2.0.0a1)

PEERDIR(
    contrib/deprecated/python/celery
    contrib/python/django-braces
    contrib/deprecated/python/django-celery-beat
    contrib/deprecated/python/django-celery-results
    contrib/python/django-environ
    contrib/python/django-model-utils
    contrib/python/django-widget-tweaks
    contrib/python/docutils
    contrib/python/natsort
    contrib/python/netaddr
    contrib/python/packaging
    contrib/python/psycopg2
    contrib/python/redis
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    localshop/__init__.py
    localshop/apps/__init__.py
    localshop/apps/accounts/__init__.py
    localshop/apps/accounts/admin.py
    localshop/apps/accounts/auth_urls.py
    localshop/apps/accounts/forms.py
    localshop/apps/accounts/migrations/0001_initial.py
    localshop/apps/accounts/migrations/0002_migrate_users.py
    localshop/apps/accounts/migrations/0003_migrate_credentials.py
    localshop/apps/accounts/migrations/0004_auto_20171116_2112.py
    localshop/apps/accounts/migrations/__init__.py
    localshop/apps/accounts/models.py
    localshop/apps/accounts/urls.py
    localshop/apps/accounts/views.py
    localshop/apps/dashboard/__init__.py
    localshop/apps/dashboard/forms.py
    localshop/apps/dashboard/urls.py
    localshop/apps/dashboard/views/__init__.py
    localshop/apps/dashboard/views/cidr.py
    localshop/apps/dashboard/views/credentials.py
    localshop/apps/dashboard/views/misc.py
    localshop/apps/dashboard/views/package.py
    localshop/apps/dashboard/views/repository.py
    localshop/apps/packages/__init__.py
    localshop/apps/packages/admin.py
    localshop/apps/packages/forms.py
    localshop/apps/packages/migrations/0001_initial.py
    localshop/apps/packages/migrations/0002_repository.py
    localshop/apps/packages/migrations/0003_default_repo.py
    localshop/apps/packages/migrations/0004_auto_20150517_1612.py
    localshop/apps/packages/migrations/0005_auto_20150525_1931.py
    localshop/apps/packages/migrations/0006_repository_upstream_pypi_url.py
    localshop/apps/packages/migrations/0007_normalize_names.py
    localshop/apps/packages/migrations/0008_requires_python.py
    localshop/apps/packages/migrations/0009_auto_20150909_2245.py
    localshop/apps/packages/migrations/0010_auto_20171116_2112.py
    localshop/apps/packages/migrations/0011_package_name.py
    localshop/apps/packages/migrations/0012_releasefile_python_version_max_length.py
    localshop/apps/packages/migrations/0013_releasefile_fields_max_length.py
    localshop/apps/packages/migrations/0014_releasefile_upload_time.py
    localshop/apps/packages/migrations/0015_trusted_packages.py
    localshop/apps/packages/migrations/__init__.py
    localshop/apps/packages/mixins.py
    localshop/apps/packages/models.py
    localshop/apps/packages/pypi.py
    localshop/apps/packages/tasks.py
    localshop/apps/packages/tests/test_views.py
    localshop/apps/packages/urls.py
    localshop/apps/packages/utils.py
    localshop/apps/packages/views.py
    localshop/apps/packages/xmlrpc.py
    localshop/apps/permissions/__init__.py
    localshop/apps/permissions/admin.py
    localshop/apps/permissions/migrations/0001_initial.py
    localshop/apps/permissions/migrations/0001_squashed_0002_remove_userena.py
    localshop/apps/permissions/migrations/0002_auto_20150517_1857.py
    localshop/apps/permissions/migrations/0002_remove_userena.py
    localshop/apps/permissions/migrations/0003_auto_20171116_2112.py
    localshop/apps/permissions/migrations/__init__.py
    localshop/apps/permissions/mixins.py
    localshop/apps/permissions/models.py
    localshop/apps/permissions/utils.py
    localshop/celery.py
    localshop/http.py
    localshop/management/__init__.py
    localshop/management/commands/__init__.py
    localshop/management/commands/create_default_user.py
    localshop/management/commands/init.py
    localshop/management/commands/repository_refresh.py
    localshop/runner.py
    localshop/settings/__init__.py
    localshop/settings/defaults.py
    localshop/templatetags/__init__.py
    localshop/templatetags/forms.py
    localshop/templatetags/permission_tags.py
    localshop/urls.py
    localshop/utils.py
    localshop/views.py
    localshop/wsgi.py
)

RESOURCE_FILES(
    PREFIX contrib/python/localshop/
    .dist-info/METADATA
    .dist-info/entry_points.txt
    .dist-info/top_level.txt
    localshop/static/localshop/css/main.css
    localshop/static/localshop/css/main.css.map
    localshop/static/localshop/fonts/glyphicons-halflings-regular.eot
    localshop/static/localshop/fonts/glyphicons-halflings-regular.svg
    localshop/static/localshop/fonts/glyphicons-halflings-regular.ttf
    localshop/static/localshop/fonts/glyphicons-halflings-regular.woff
    localshop/static/localshop/fonts/glyphicons-halflings-regular.woff2
    localshop/static/localshop/js/bootstrap.min.js
    localshop/static/localshop/js/jquery-2.1.4.min.js
    localshop/static/localshop/less/bootstrap/alerts.less
    localshop/static/localshop/less/bootstrap/badges.less
    localshop/static/localshop/less/bootstrap/bootstrap.less
    localshop/static/localshop/less/bootstrap/breadcrumbs.less
    localshop/static/localshop/less/bootstrap/button-groups.less
    localshop/static/localshop/less/bootstrap/buttons.less
    localshop/static/localshop/less/bootstrap/carousel.less
    localshop/static/localshop/less/bootstrap/close.less
    localshop/static/localshop/less/bootstrap/code.less
    localshop/static/localshop/less/bootstrap/component-animations.less
    localshop/static/localshop/less/bootstrap/dropdowns.less
    localshop/static/localshop/less/bootstrap/forms.less
    localshop/static/localshop/less/bootstrap/glyphicons.less
    localshop/static/localshop/less/bootstrap/grid.less
    localshop/static/localshop/less/bootstrap/input-groups.less
    localshop/static/localshop/less/bootstrap/jumbotron.less
    localshop/static/localshop/less/bootstrap/labels.less
    localshop/static/localshop/less/bootstrap/list-group.less
    localshop/static/localshop/less/bootstrap/media.less
    localshop/static/localshop/less/bootstrap/mixins.less
    localshop/static/localshop/less/bootstrap/mixins/alerts.less
    localshop/static/localshop/less/bootstrap/mixins/background-variant.less
    localshop/static/localshop/less/bootstrap/mixins/border-radius.less
    localshop/static/localshop/less/bootstrap/mixins/buttons.less
    localshop/static/localshop/less/bootstrap/mixins/center-block.less
    localshop/static/localshop/less/bootstrap/mixins/clearfix.less
    localshop/static/localshop/less/bootstrap/mixins/forms.less
    localshop/static/localshop/less/bootstrap/mixins/gradients.less
    localshop/static/localshop/less/bootstrap/mixins/grid-framework.less
    localshop/static/localshop/less/bootstrap/mixins/grid.less
    localshop/static/localshop/less/bootstrap/mixins/hide-text.less
    localshop/static/localshop/less/bootstrap/mixins/image.less
    localshop/static/localshop/less/bootstrap/mixins/labels.less
    localshop/static/localshop/less/bootstrap/mixins/list-group.less
    localshop/static/localshop/less/bootstrap/mixins/nav-divider.less
    localshop/static/localshop/less/bootstrap/mixins/nav-vertical-align.less
    localshop/static/localshop/less/bootstrap/mixins/opacity.less
    localshop/static/localshop/less/bootstrap/mixins/pagination.less
    localshop/static/localshop/less/bootstrap/mixins/panels.less
    localshop/static/localshop/less/bootstrap/mixins/progress-bar.less
    localshop/static/localshop/less/bootstrap/mixins/reset-filter.less
    localshop/static/localshop/less/bootstrap/mixins/resize.less
    localshop/static/localshop/less/bootstrap/mixins/responsive-visibility.less
    localshop/static/localshop/less/bootstrap/mixins/size.less
    localshop/static/localshop/less/bootstrap/mixins/tab-focus.less
    localshop/static/localshop/less/bootstrap/mixins/table-row.less
    localshop/static/localshop/less/bootstrap/mixins/text-emphasis.less
    localshop/static/localshop/less/bootstrap/mixins/text-overflow.less
    localshop/static/localshop/less/bootstrap/mixins/vendor-prefixes.less
    localshop/static/localshop/less/bootstrap/modals.less
    localshop/static/localshop/less/bootstrap/navbar.less
    localshop/static/localshop/less/bootstrap/navs.less
    localshop/static/localshop/less/bootstrap/normalize.less
    localshop/static/localshop/less/bootstrap/pager.less
    localshop/static/localshop/less/bootstrap/pagination.less
    localshop/static/localshop/less/bootstrap/panels.less
    localshop/static/localshop/less/bootstrap/popovers.less
    localshop/static/localshop/less/bootstrap/print.less
    localshop/static/localshop/less/bootstrap/progress-bars.less
    localshop/static/localshop/less/bootstrap/responsive-embed.less
    localshop/static/localshop/less/bootstrap/responsive-utilities.less
    localshop/static/localshop/less/bootstrap/scaffolding.less
    localshop/static/localshop/less/bootstrap/tables.less
    localshop/static/localshop/less/bootstrap/theme.less
    localshop/static/localshop/less/bootstrap/thumbnails.less
    localshop/static/localshop/less/bootstrap/tooltip.less
    localshop/static/localshop/less/bootstrap/type.less
    localshop/static/localshop/less/bootstrap/utilities.less
    localshop/static/localshop/less/bootstrap/variables.less
    localshop/static/localshop/less/bootstrap/wells.less
    localshop/static/localshop/less/custom.less
    localshop/static/localshop/less/main.less
    localshop/templates/403.html
    localshop/templates/404.html
    localshop/templates/500.html
    localshop/templates/accounts/accesskey_confirm_delete.html
    localshop/templates/accounts/accesskey_form.html
    localshop/templates/accounts/accesskey_list.html
    localshop/templates/accounts/base.html
    localshop/templates/accounts/profile.html
    localshop/templates/accounts/team_confirm_delete.html
    localshop/templates/accounts/team_detail.html
    localshop/templates/accounts/team_form.html
    localshop/templates/accounts/team_list.html
    localshop/templates/dashboard/index.html
    localshop/templates/dashboard/package_detail.html
    localshop/templates/dashboard/repository_create.html
    localshop/templates/dashboard/repository_detail.html
    localshop/templates/dashboard/repository_settings/base.html
    localshop/templates/dashboard/repository_settings/cidr_confirm_delete.html
    localshop/templates/dashboard/repository_settings/cidr_form.html
    localshop/templates/dashboard/repository_settings/cidr_list.html
    localshop/templates/dashboard/repository_settings/credential_confirm_delete.html
    localshop/templates/dashboard/repository_settings/credential_form.html
    localshop/templates/dashboard/repository_settings/credential_list.html
    localshop/templates/dashboard/repository_settings/delete.html
    localshop/templates/dashboard/repository_settings/edit.html
    localshop/templates/dashboard/repository_settings/teams.html
    localshop/templates/layout.base.html
    localshop/templates/layout.main.html
    localshop/templates/packages/package_list.html
    localshop/templates/packages/simple_package_detail.html
    localshop/templates/packages/simple_package_list.html
    localshop/templates/partial/_form_field.html
    localshop/templates/partial/_form_fields.html
    localshop/templates/registration/logged_out.html
    localshop/templates/registration/login.html
    localshop/templates/registration/password_change_done.html
    localshop/templates/registration/password_change_form.html
    localshop/templates/registration/password_reset_complete.html
    localshop/templates/registration/password_reset_confirm.html
    localshop/templates/registration/password_reset_done.html
    localshop/templates/registration/password_reset_form.html
)

END()
