# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(0.60b1)

LICENSE(Apache-2.0)

PEERDIR(
    contrib/python/opentelemetry-api
    contrib/python/opentelemetry-instrumentation
    contrib/python/opentelemetry-instrumentation-wsgi
    contrib/python/opentelemetry-semantic-conventions
    contrib/python/opentelemetry-util-http
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    opentelemetry/instrumentation/django/__init__.py
    opentelemetry/instrumentation/django/environment_variables.py
    opentelemetry/instrumentation/django/middleware/__init__.py
    opentelemetry/instrumentation/django/middleware/otel_middleware.py
    opentelemetry/instrumentation/django/middleware/sqlcommenter_middleware.py
    opentelemetry/instrumentation/django/package.py
    opentelemetry/instrumentation/django/version.py
)

RESOURCE_FILES(
    PREFIX contrib/python/opentelemetry-instrumentation-django/
    .dist-info/METADATA
    .dist-info/entry_points.txt
)

END()
