# Generated by devtools/yamaker (pypi).

PY2_LIBRARY()

VERSION(3.1.7)

LICENSE(Apache-2.0)

PEERDIR(
    contrib/python/cffi
    contrib/python/six
)

ADDINCL(
    contrib/python/bcrypt/py2/_csrc
)

NO_COMPILER_WARNINGS()

NO_LINT()

SRCS(
    _csrc/bcrypt.c
    _csrc/bcrypt_pbkdf.c
    _csrc/blf.c
    _csrc/sha2.c
    _csrc/timingsafe_bcmp.c
)

PY_REGISTER(
    bcrypt._bcrypt
)

PY_SRCS(
    TOP_LEVEL
    bcrypt/__about__.py
    bcrypt/__init__.py
)

RUN_PROGRAM(
    contrib/python/cffi/py2/gen build_bcrypt.py:ffi bcrypt._bcrypt.cffi.py2.c
    IN build_bcrypt.py
    OUT bcrypt._bcrypt.cffi.py2.c
    OUTPUT_INCLUDES pycabcrypt.h
)

RESOURCE_FILES(
    PREFIX contrib/python/bcrypt/py2/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()

RECURSE_FOR_TESTS(
    tests
)
