version: '3.4'
services:
  trino:
    hostname: trino
    image: 'trinodb/trino@sha256:49aa7230aaa00b92d54842b2f0cafc1f5ec5f228e77b4bc45b3d65f9fa94c45f'
    volumes:
      - ./trino/catalog:/etc/trino/catalog:ro
    ports:
      - '8080'

  # This job creates the "datalake" bucket on Minio
  trino-job:
    image: 'trinodb/trino@sha256:49aa7230aaa00b92d54842b2f0cafc1f5ec5f228e77b4bc45b3d65f9fa94c45f'
    container_name: trino-job
    volumes:
    - ./scripts:/scripts
    command: |
      /bin/bash /scripts/bootstrap.bash
    depends_on:
      - trino

  # HMS backend database
  metastore_db:
    image: postgres@sha256:00e6ed9967881099ce9e552be567537d0bb47c990dacb43229cc9494bfddd8a0
    hostname: metastore_db
    container_name: metastore_db
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore

  # Hive metastore service (HMS)
  hive-metastore:
    privileged: true
    container_name: hive-metastore
    hostname: hive-metastore
    image: 'starburstdata/hive@sha256:a84bdd96b6148b2991939a7f33df47da7456369657e637179d7ce6fa08d4c2fd'
    ports:
      - '9083' # Metastore Thrift
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3://datalake/
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
    depends_on:
      - metastore_db

  # MinIO object storage
  minio:
    hostname: minio
    image: 'minio/minio@sha256:1a3debf2408bde1f33b49cd70af245eb2173c5897a2e6bf99d7934005cd14537'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"

  # This job creates the "datalake" bucket on Minio
  mc-job:
    image: 'minio/mc@sha256:57267ad9b94e2dd17e0f480ea4d0d3df42c53804dbdaff0ca1e2124a93695bf9'
    container_name: mc-job
    entrypoint: |
      /bin/bash -c "
      sleep 5;
      /usr/bin/mc config --quiet host add myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb --quiet myminio/datalake
      "
    depends_on:
      - minio
