# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(0.2.0)

LICENSE(MIT)

PEERDIR(
    contrib/python/numpy
    contrib/python/scipy
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    sobol_seq/__init__.py
    sobol_seq/sobol_seq-not_tested.py
    sobol_seq/sobol_seq.py
)

RESOURCE_FILES(
    PREFIX contrib/python/sobol-seq/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()

RECURSE_FOR_TESTS(
    tests
)
