/* syntax version 1 */
/* postgres can not */
select
    ListHasItems([]),
    Yql::Filter([],($x)->{return $x}),
    Yql::Map([],($x)->{return $x*2}),
    Yql::FlatMap([],($x)->{return Just($x*2)}),    
    Yql::OrderedFilter([],($x)->{return $x}),
    Yql::OrderedMap([],($x)->{return $x*2}),
    Yql::OrderedFlatMap([],($x)->{return Just($x*2)}),    
    ListFilter([],($x)->{return $x}),
    ListMap([],($x)->{return $x*2}),
    ListFlatMap([],($x)->{return Just($x*2)}),    
    ListCollect([]),
    ListSort([]),
    ListReverse([]),
    ListEnumerate([]),
    ListSkip([], 1),
    ListTake([], 1),
    ListIndexOf([], 1),
    ListUniq([]),
    ListAny([]),
    ListAll([]),
    ListHas([],1),
    ListHead([]),
    ListLast([]),
    ListMin([]),
    ListMax([]),
    ListSum([]),
    ListAvg([]),

    ListHasItems(Just([])),
    ListFilter(Just([]),($x)->{return $x}),
    ListMap(Just([]),($x)->{return $x*2}),
    ListFlatMap(Just([]),($x)->{return Just($x*2)}),    
    ListCollect(Just([])),
    ListSort(Just([])),    
    ListReverse(Just([])),    
    ListEnumerate(Just([])),
    ListSkip(Just([]), 1),
    ListTake(Just([]), 1),
    ListUniq(Just([])),
    ListAny(Just([])),
    ListAll(Just([])),
    ListHas(Just([]),1),
    ListHead(Just([])),
    ListLast(Just([])),
    ListMin(Just([])),
    ListMax(Just([])),
    ListSum(Just([])),
    ListAvg(Just([])),

