SELECT ListFromRange(1, 3),
       ListFromRange(1, Just(3)),
       ListFromRange(Just(1), Just(3)),
       ListFromRange(1, 3, 1),
       ListFromRange(1, 3, Just(1)),
       ListFromRange(1, 3, Nothing(Int32?)),
       ListFromRange(1, Just(3), Just(1)),
       ListFromRange(1.2, 3.2),
       ListFromRange(1.2, Just(3.2)),
       ListFromRange(Just(1.2), Just(3.2)),
       ListFromRange(1, Just(3.2)),
       ListFromRange(1, Nothing(Uint64?)),
       ListFromRange(1.2, Just(3.2), 0.4),
       ListFromRange(1.2, 3.2, Just(0.4)),
       ListFromRange(Just(1.2), 3.2, Just(0.4)),
       ListFromRange(1.2, 3.2, Nothing(Double?)),
       ListFromRange(1, Just(1.2), Null),
       ListFromRange(Just(1), Null, Null),
       ListFromRange(1, 1.2, Null),
       ListFromRange(1, Null, Null),
       ListFromRange(Null, Null, Null),
       ListFromRange(Interval("PT1S"), Interval("PT1S")),
       ListFromRange(Interval("PT1M"), Just(Interval("PT1M"))),
       ListFromRange(Interval("PT1M"), Interval("PT2M"), Just(Interval("PT10S"))),
       ListFromRange(Interval("PT1S"), Interval("PT1M"), Null),
       ListFromRange(Interval("PT1S"), Interval("PT4S"), Nothing(Interval?));
