# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(1.3.0)

LICENSE(MIT AND Public-Domain AND Unlicense)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    html5tagger/__init__.py
    html5tagger/builder.py
    html5tagger/document.py
    html5tagger/html5.py
    html5tagger/makebuilder.py
    html5tagger/util.py
)

RESOURCE_FILES(
    PREFIX contrib/python/html5tagger/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
