RECURSE_FOR_TESTS(
    ut_auditsettings
    ut_background_cleaning
    ut_backup
    ut_backup_collection
    ut_backup_collection_reboots
    ut_base
    ut_base_reboots
    ut_bsvolume
    ut_bsvolume_reboots
    ut_cdc_stream
    ut_cdc_stream_reboots
    ut_column_build
    ut_column_build_reboots
    ut_compaction
    ut_consistent_copy_tables
    ut_continuous_backup
    ut_continuous_backup_reboots
    ut_shred
    ut_shred_reboots
    ut_export
    ut_export_reboots_s3
    ut_external_data_source
    ut_external_data_source_reboots
    ut_external_table
    ut_external_table_reboots
    ut_extsubdomain
    ut_extsubdomain_reboots
    ut_failure_injection
    ut_filestore_reboots
    ut_incremental_restore
    ut_incremental_restore_reboots
    ut_index
    ut_index_build
    ut_index_build_reboots
    ut_login
    ut_login_large
    ut_move
    ut_move_reboots
    ut_olap
    ut_olap_reboots
    ut_partition_stats
    ut_pq_reboots
    ut_reboots
    ut_replication
    ut_replication_reboots
    ut_resource_pool
    ut_resource_pool_reboots
    ut_restore
    ut_rtmr
    ut_rtmr_reboots
    ut_ru_calculator
    ut_sequence
    ut_sequence_reboots
    ut_serverless
    ut_serverless_reboots
    ut_split_merge
    ut_split_merge_reboots
    ut_secret
    ut_secret_reboots
    ut_stats
    ut_streaming_query
    ut_streaming_query_reboots
    ut_subdomain
    ut_subdomain_reboots
    ut_system_names
    ut_sysview
    ut_sysview_reboots
    ut_topic_splitmerge
    ut_topic_set_boundaries
    ut_transfer
    ut_truncate_table_reboots
    ut_truncate_table_simple
    ut_ttl
    ut_user_attributes
    ut_user_attributes_reboots
    ut_vector_index_build_reboots
    ut_view
)

LIBRARY()

SRCS(
    defs.h
    operation_queue_timer.h
    schemeshard.cpp
    schemeshard__background_cleaning.cpp
    schemeshard__background_compaction.cpp
    schemeshard__backup_collection_common.cpp
    schemeshard__borrowed_compaction.cpp
    schemeshard__clean_pathes.cpp
    schemeshard__conditional_erase.cpp
    schemeshard__shred_manager.cpp
    schemeshard__delete_tablet_reply.cpp
    schemeshard__describe_scheme.cpp
    schemeshard__find_subdomain_path_id.cpp
    schemeshard__fix_bad_paths.cpp
    schemeshard__init.cpp
    schemeshard__init_populator.cpp
    schemeshard__init_root.cpp
    schemeshard__init_schema.cpp
    schemeshard__list_users.cpp
    schemeshard__login.cpp
    schemeshard__login_finalize.cpp
    schemeshard__make_access_database_no_inheritable.cpp
    schemeshard__monitoring.cpp
    schemeshard__notify.cpp
    schemeshard__op_traits.h
    schemeshard__operation.cpp
    schemeshard__operation.h
    schemeshard__op_traits.cpp
    schemeshard__op_traits.h
    schemeshard__operation_alter_bsv.cpp
    schemeshard__operation_alter_cdc_stream.cpp
    schemeshard__operation_alter_continuous_backup.cpp
    schemeshard__operation_alter_external_data_source.cpp
    schemeshard__operation_alter_external_table.cpp
    schemeshard__operation_alter_extsubdomain.cpp
    schemeshard__operation_alter_fs.cpp
    schemeshard__operation_alter_index.cpp
    schemeshard__operation_alter_kesus.cpp
    schemeshard__operation_alter_login.cpp
    schemeshard__operation_alter_pq.cpp
    schemeshard__operation_alter_replication.cpp
    schemeshard__operation_alter_resource_pool.cpp
    schemeshard__operation_alter_secret.cpp
    schemeshard__operation_alter_sequence.cpp
    schemeshard__operation_alter_solomon.cpp
    schemeshard__operation_alter_streaming_query.cpp
    schemeshard__operation_alter_subdomain.cpp
    schemeshard__operation_alter_table.cpp
    schemeshard__operation_alter_user_attrs.cpp
    schemeshard__operation_apply_build_index.cpp
    schemeshard__operation_assign_bsv.cpp
    schemeshard__operation_backup_backup_collection.cpp
    schemeshard__operation_backup_incremental_backup_collection.cpp
    schemeshard__operation_blob_depot.cpp
    schemeshard__operation_cancel_tx.cpp
    schemeshard__operation_change_path_state.cpp
    schemeshard__operation_common.cpp
    schemeshard__operation_common.h
    schemeshard__operation_common_bsv.cpp
    schemeshard__operation_common_cdc_stream.cpp
    schemeshard__operation_common_external_data_source.cpp
    schemeshard__operation_common_external_table.cpp
    schemeshard__operation_common_pq.cpp
    schemeshard__operation_common_resource_pool.cpp
    schemeshard__operation_common_subdomain.cpp
    schemeshard__operation_common_subdomain.h
    schemeshard__operation_consistent_copy_tables.cpp
    schemeshard__operation_copy_sequence.cpp
    schemeshard__operation_copy_table.cpp
    schemeshard__operation_create_backup.cpp
    schemeshard__operation_create_backup_collection.cpp
    schemeshard__operation_create_bsv.cpp
    schemeshard__operation_create_build_index.cpp
    schemeshard__operation_create_cdc_stream.cpp
    schemeshard__operation_create_continuous_backup.cpp
    schemeshard__operation_create_external_data_source.cpp
    schemeshard__operation_create_external_table.cpp
    schemeshard__operation_create_extsubdomain.cpp
    schemeshard__operation_create_fs.cpp
    schemeshard__operation_create_index.cpp
    schemeshard__operation_create_indexed_table.cpp
    schemeshard__operation_create_kesus.cpp
    schemeshard__operation_create_lock.cpp
    schemeshard__operation_create_pq.cpp
    schemeshard__operation_create_replication.cpp
    schemeshard__operation_create_resource_pool.cpp
    schemeshard__operation_create_restore.cpp
    schemeshard__operation_create_secret.cpp
    schemeshard__operation_create_restore_incremental_backup.cpp
    schemeshard__operation_incremental_restore_finalize.cpp
    schemeshard__operation_create_rtmr.cpp
    schemeshard__operation_create_sequence.cpp
    schemeshard__operation_create_solomon.cpp
    schemeshard__operation_create_streaming_query.cpp
    schemeshard__operation_create_subdomain.cpp
    schemeshard__operation_create_sysview.cpp
    schemeshard__operation_create_table.cpp
    schemeshard__operation_create_view.cpp
    schemeshard__operation_db_changes.cpp
    schemeshard__operation_drop_backup_collection.cpp
    schemeshard__operation_drop_bsv.cpp
    schemeshard__operation_drop_cdc_stream.cpp
    schemeshard__operation_drop_continuous_backup.cpp
    schemeshard__operation_drop_external_data_source.cpp
    schemeshard__operation_drop_external_table.cpp
    schemeshard__operation_drop_extsubdomain.cpp
    schemeshard__operation_drop_fs.cpp
    schemeshard__operation_drop_index.cpp
    schemeshard__operation_drop_indexed_table.cpp
    schemeshard__operation_drop_kesus.cpp
    schemeshard__operation_drop_lock.cpp
    schemeshard__operation_drop_pq.cpp
    schemeshard__operation_drop_replication.cpp
    schemeshard__operation_drop_resource_pool.cpp
    schemeshard__operation_drop_secret.cpp
    schemeshard__operation_drop_sequence.cpp
    schemeshard__operation_drop_solomon.cpp
    schemeshard__operation_drop_streaming_query.cpp
    schemeshard__operation_drop_subdomain.cpp
    schemeshard__operation_drop_sysview.cpp
    schemeshard__operation_drop_table.cpp
    schemeshard__operation_drop_unsafe.cpp
    schemeshard__operation_drop_view.cpp
    schemeshard__operation_finalize_build_index.cpp
    schemeshard__operation_initiate_build_index.cpp
    schemeshard__operation_just_reject.cpp
    schemeshard__operation_memory_changes.cpp
    schemeshard__operation_mkdir.cpp
    schemeshard__operation_modify_acl.cpp
    schemeshard__operation_move_index.cpp
    schemeshard__operation_move_sequence.cpp
    schemeshard__operation_move_table.cpp
    schemeshard__operation_move_table_index.cpp
    schemeshard__operation_move_tables.cpp
    schemeshard__operation_part.cpp
    schemeshard__operation_part.h
    schemeshard__operation_restore_backup_collection.cpp
    schemeshard__operation_rmdir.cpp
    schemeshard__operation_rotate_cdc_stream.cpp
    schemeshard__operation_side_effects.cpp
    schemeshard__operation_side_effects.h
    schemeshard__operation_split_merge.cpp
    schemeshard__operation_truncate_table.cpp
    schemeshard__operation_upgrade_subdomain.cpp
    schemeshard__pq_stats.cpp
    schemeshard__publish_to_scheme_board.cpp
    schemeshard__root_shred_manager.cpp
    schemeshard__serverless_storage_billing.cpp
    schemeshard__state_changed_reply.cpp
    schemeshard__sync_update_tenants.cpp
    schemeshard__table_stats.cpp
    schemeshard__table_stats_histogram.cpp
    schemeshard__tenant_shred_manager.cpp
    schemeshard__unmark_restore_tables.cpp
    schemeshard__upgrade_access_database.cpp
    schemeshard__upgrade_schema.cpp
    schemeshard_audit_log.cpp
    schemeshard_audit_log_fragment.cpp
    schemeshard_backup.cpp
    schemeshard_backup_incremental__forget.cpp
    schemeshard_backup_incremental__get.cpp
    schemeshard_backup_incremental__list.cpp
    schemeshard_backup_incremental__progress.cpp
    schemeshard_restore_incremental__forget.cpp
    schemeshard_forced_compaction__create.cpp
    schemeshard_forced_compaction__progress.cpp
    schemeshard_forced_compaction.cpp
    schemeshard_restore_incremental__get.cpp
    schemeshard_restore_incremental__list.cpp
    schemeshard_bg_tasks__list.cpp
    schemeshard_billing_helpers.cpp
    schemeshard_build_index.cpp
    schemeshard_build_index_helpers.cpp
    schemeshard_build_index__cancel.cpp
    schemeshard_build_index__create.cpp
    schemeshard_build_index__forget.cpp
    schemeshard_build_index__get.cpp
    schemeshard_build_index__list.cpp
    schemeshard_build_index__progress.cpp
    schemeshard_build_index_tx_base.cpp
    schemeshard_cdc_stream_common.cpp
    schemeshard_cdc_stream_scan.cpp
    schemeshard_continuous_backup_cleaner.cpp
    schemeshard_incremental_restore_scan.cpp
    schemeshard_domain_links.cpp
    schemeshard_domain_links.h
    schemeshard_effective_acl.cpp
    schemeshard_effective_acl.h
    schemeshard_scheme_builders.cpp
    schemeshard_scheme_builders.h
    schemeshard_export.cpp
    schemeshard_export__cancel.cpp
    schemeshard_export__create.cpp
    schemeshard_export__forget.cpp
    schemeshard_export__get.cpp
    schemeshard_export__list.cpp
    schemeshard_export_helpers.cpp
    schemeshard_export_flow_proposals.cpp
    schemeshard_identificators.cpp
    schemeshard_impl.cpp
    schemeshard_impl.h
    schemeshard_import.cpp
    schemeshard_import_helpers.cpp
    schemeshard_import__cancel.cpp
    schemeshard_import__create.cpp
    schemeshard_import__forget.cpp
    schemeshard_import__get.cpp
    schemeshard_import__list.cpp
    schemeshard_import_flow_proposals.cpp
    schemeshard_import_scheme_query_executor.cpp
    schemeshard_index_build_info.cpp
    schemeshard_index_build_info.h
    schemeshard_index_utils.cpp
    schemeshard_index_utils.h
    schemeshard_info_types.cpp
    schemeshard_info_types.h
    schemeshard_login_helper.cpp
    schemeshard_login_helper.h
    schemeshard_path.cpp
    schemeshard_path.h
    schemeshard_path_describer.cpp
    schemeshard_path_element.cpp
    schemeshard_path_element.h
    schemeshard_pq_helpers.h
    schemeshard_schema.h
    schemeshard_self_pinger.cpp
    schemeshard_self_pinger.h
    schemeshard_shard_deleter.cpp
    schemeshard_shard_deleter.h
    schemeshard_subop_state_types.cpp
    schemeshard_subop_state_types.h
    schemeshard_subop_types.cpp
    schemeshard_subop_types.h
    schemeshard_svp_migration.cpp
    schemeshard_svp_migration.h
    schemeshard_system_names.cpp
    schemeshard_system_names.h
    schemeshard_sysviews_update.cpp
    schemeshard_tx_infly.cpp
    schemeshard_tx_infly.h
    schemeshard_types.cpp
    schemeshard_types.h
    schemeshard_user_attr_limits.h
    schemeshard_validate_ttl.cpp
    schemeshard_xxport__helpers.cpp
    user_attributes.cpp
    schemeshard__operation_create_set_constraint.cpp
    schemeshard__operation_create_set_constraint_check.cpp
    schemeshard__operation_create_set_constraint_finalize.cpp
    schemeshard__operation_create_set_constraint_lock.cpp
)

GENERATE_ENUM_SERIALIZATION(schemeshard_subop_state_types.h)

GENERATE_ENUM_SERIALIZATION(schemeshard_info_types.h)

GENERATE_ENUM_SERIALIZATION(schemeshard_index_build_info.h)

GENERATE_ENUM_SERIALIZATION(schemeshard_types.h)

GENERATE_ENUM_SERIALIZATION(operation_queue_timer.h)

PEERDIR(
    contrib/libs/protobuf
    library/cpp/deprecated/enum_codegen
    library/cpp/html/pcdata
    library/cpp/json
    library/cpp/protobuf/json
    library/cpp/regex/pcre
    ydb/core/actorlib_impl
    ydb/core/audit
    ydb/core/base
    ydb/core/backup/regexp
    ydb/core/blob_depot
    ydb/core/blobstorage/base
    ydb/core/blockstore/core
    ydb/core/engine
    ydb/core/engine/minikql
    ydb/core/external_sources
    ydb/core/filestore/core
    ydb/core/kesus/tablet
    ydb/core/keyvalue
    ydb/core/keyvalue/protos
    ydb/core/metering
    ydb/core/persqueue/events
    ydb/core/persqueue/public
    ydb/core/persqueue/public/partition_index_generator
    ydb/core/persqueue/public/partition_key_range
    ydb/core/persqueue/writer
    ydb/core/protos
    ydb/core/resource_pools
    ydb/core/scheme
    ydb/core/statistics
    ydb/core/sys_view/common
    ydb/core/sys_view/partition_stats
    ydb/core/tablet
    ydb/core/tablet_flat
    ydb/core/tx
    ydb/core/tx/datashard
    ydb/core/tx/schemeshard/common
    ydb/core/tx/schemeshard/generated
    ydb/core/tx/schemeshard/olap
    ydb/core/tx/scheme_board
    ydb/core/tx/tx_allocator_client
    ydb/core/util
    ydb/core/wrappers
    ydb/core/ydb_convert
    ydb/library/aclib
    ydb/library/aclib/protos
    ydb/library/login
    ydb/library/login/protos
    ydb/library/protobuf_printer
    ydb/public/lib/ydb_cli/dump/files
    ydb/public/lib/ydb_cli/dump/util
    yql/essentials/minikql
    yql/essentials/providers/common/proto
    ydb/services/bg_tasks
    ydb/core/tx/columnshard/bg_tasks/manager
    ydb/core/tx/tiering/tier
)

YQL_LAST_ABI_VERSION()

IF (OS_WINDOWS)
    SRCS(
        schemeshard_export_uploaders_fallback.cpp
        schemeshard_import_getters_fallback.cpp
    )
ELSE()
    SRCS(
        schemeshard_export_uploaders.cpp
        schemeshard_import_getters.cpp
    )
ENDIF()

END()
