PY2TEST()

PEERDIR(
    contrib/python/beautifulsoup4
    contrib/python/soupsieve
)

TEST_SRCS(
    __init__.py
    test_api.py
    test_bs4_cases.py
    test_extra/__init__.py
    test_extra/test_attribute.py
    test_extra/test_contains.py
    test_extra/test_custom.py
    test_level1/__init__.py
    test_level1/test_active.py
    test_level1/test_at_rule.py
    test_level1/test_class.py
    test_level1/test_comments.py
    test_level1/test_descendant.py
    test_level1/test_escapes.py
    test_level1/test_id.py
    test_level1/test_link.py
    test_level1/test_list.py
    test_level1/test_pseudo_class.py
    test_level1/test_pseudo_element.py
    test_level1/test_type.py
    test_level1/test_visited.py
    test_level2/__init__.py
    test_level2/test_attribute.py
    test_level2/test_child.py
    test_level2/test_first_child.py
    test_level2/test_focus.py
    test_level2/test_hover.py
    test_level2/test_lang.py
    test_level2/test_next_sibling.py
    test_level2/test_universal_type.py
    test_level3/__init__.py
    test_level3/test_attribute.py
    test_level3/test_checked.py
    test_level3/test_disabled.py
    test_level3/test_empty.py
    test_level3/test_enabled.py
    test_level3/test_first_of_type.py
    test_level3/test_last_child.py
    test_level3/test_last_of_type.py
    test_level3/test_namespace.py
    test_level3/test_not.py
    test_level3/test_nth_child.py
    test_level3/test_nth_last_child.py
    test_level3/test_nth_last_of_type.py
    test_level3/test_nth_of_type.py
    test_level3/test_only_child.py
    test_level3/test_only_of_type.py
    test_level3/test_root.py
    test_level3/test_subsequent_sibling.py
    test_level3/test_target.py
    test_level4/__init__.py
    test_level4/test_any_link.py
    test_level4/test_attribute.py
    test_level4/test_current.py
    test_level4/test_default.py
    test_level4/test_defined.py
    test_level4/test_dir.py
    test_level4/test_focus_visible.py
    test_level4/test_focus_within.py
    test_level4/test_future.py
    test_level4/test_has.py
    test_level4/test_host.py
    test_level4/test_host_context.py
    test_level4/test_in_range.py
    test_level4/test_indeterminate.py
    test_level4/test_is.py
    test_level4/test_lang.py
    test_level4/test_local_link.py
    test_level4/test_matches.py
    test_level4/test_not.py
    test_level4/test_nth_child.py
    test_level4/test_optional.py
    test_level4/test_out_of_range.py
    test_level4/test_past.py
    test_level4/test_paused.py
    test_level4/test_placeholder_shown.py
    test_level4/test_playing.py
    test_level4/test_read_only.py
    test_level4/test_read_write.py
    test_level4/test_required.py
    test_level4/test_scope.py
    test_level4/test_target_within.py
    test_level4/test_user_invalid.py
    test_level4/test_where.py
    test_versions.py
    util.py
)

NO_LINT()

END()
