# Generated by devtools/yamaker.

LIBRARY()

LICENSE(
    BSD-2-Clause AND
    BSD-3-Clause
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(4.12.0)

PEERDIR(
    contrib/libs/eigen
    contrib/libs/opencv/modules/calib3d
    contrib/libs/opencv/modules/core
    contrib/libs/opencv/modules/features2d
    contrib/libs/opencv/modules/flann
    contrib/libs/opencv/modules/imgcodecs
    contrib/libs/opencv/modules/imgproc
    contrib/libs/opencv/modules/video
    contrib/libs/opencv/modules/ximgproc
)

IF (HAVE_CUDA)
    PEERDIR(
        contrib/libs/opencv/modules/cudev
    )
ENDIF()

ADDINCL(
    contrib/libs/eigen
    contrib/libs/opencv
    contrib/libs/opencv/modules/calib3d/include
    contrib/libs/opencv/modules/core/include
    contrib/libs/opencv/modules/features2d/include
    contrib/libs/opencv/modules/flann/include
    contrib/libs/opencv/modules/imgcodecs/include
    contrib/libs/opencv/modules/imgproc/include
    contrib/libs/opencv/modules/optflow
    contrib/libs/opencv/modules/optflow/include
    contrib/libs/opencv/modules/video/include
    contrib/libs/opencv/modules/ximgproc/include
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -D__OPENCV_BUILD=1
)

SRCS(
    opencl_kernels_optflow.cpp
    src/deepflow.cpp
    src/interfaces.cpp
    src/motempl.cpp
    src/pcaflow.cpp
    src/rlof/geo_interpolation.cpp
    src/rlof/rlof_localflow.cpp
    src/rlofflow.cpp
    src/simpleflow.cpp
    src/sparse_matching_gpc.cpp
    src/sparsetodenseflow.cpp
    src/tvl1flow.cpp
)

INCLUDE(${ARCADIA_ROOT}/contrib/libs/opencv/cv_cuda_config.inc)

END()
