name: rightlib sync
description: Automatically sync rightlib branch into main
inputs:
  base_branch:
    required: true
    description: "Branch to merge into"
  head_branch:
    required: true
    description: "Branch to merge into base"
  label:
    required: true
    description: "Label to mark your PR with"
  repository:
    required: true
    description: "token for access GitHub"
  merge_ours:
    description: "File to resolve with --ours (base branch) upon merge conflict"
  merge_theirs:
    description: "File to resolve with --theirs (head branch) upon merge conflict"
  gh_personal_access_token:
    required: true
    description: "token for access GitHub"
runs:
  using: "composite"
  steps:
    - name: install packages
      shell: bash
      run: |
        pip install PyGithub==2.5.0

    - name: configure
      shell: bash
      run: |
          git config --global user.name YDBot
          git config --global user.email ydbot@ydb.tech
          git config --local github.token ${INPUTS_GH_PERSONAL_ACCESS_TOKEN}
      env:
        INPUTS_GH_PERSONAL_ACCESS_TOKEN: ${{ inputs.gh_personal_access_token }}

    - name: run-command
      shell: bash
      env:
        REPO: ${{ inputs.repository }}
        TOKEN: ${{ inputs.gh_personal_access_token }}
        INPUTS_MERGE_OURS: ${{ inputs.merge_ours }}
        INPUTS_MERGE_THEIRS: ${{ inputs.merge_theirs }}
        INPUTS_BASE_BRANCH: ${{ inputs.base_branch }}
        INPUTS_HEAD_BRANCH: ${{ inputs.head_branch }}
        INPUTS_LABEL: ${{ inputs.label }}
      run: |
        cd ./ydb/ci/rightlib
        MERGE_ARGS=''
        if [ -n "${INPUTS_MERGE_OURS}" ]; then
          MERGE_ARGS+="--merge-ours ${INPUTS_MERGE_OURS}"
        fi
        if [ -n "${INPUTS_MERGE_THEIRS}" ]; then
          MERGE_ARGS+=" --merge-theirs ${INPUTS_MERGE_THEIRS}"
        fi
        echo $MERGE_ARGS
        ./create_sync_pr.py --base-branch="${INPUTS_BASE_BRANCH}" --head-branch="${INPUTS_HEAD_BRANCH}" --process-label="${INPUTS_LABEL}" $MERGE_ARGS

