name: rightlib sync
description: Automatically sync rightlib branch into main
inputs:
  base_branch:
    required: true
    description: "Branch to merge into"
  head_branch:
    required: true
    description: "Branch to merge into base"
  label:
    required: true
    description: "Label to mark your PR with"
  repository:
    required: true
    description: "token for access GitHub"
  gh_personal_access_token:
    required: true
    description: "token for access GitHub"
runs:
  using: "composite"
  steps:
    - name: install packages
      shell: bash
      run: |
        pip install PyGithub==2.5.0

    - name: configure
      shell: bash
      run: |
          git config --global user.name YDBot
          git config --global user.email ydbot@ydb.tech
          git config --local github.token ${{ inputs.gh_personal_access_token }}

    - name: run-command
      shell: bash
      env:
        REPO: ${{ inputs.repository }}
        TOKEN: ${{ inputs.gh_personal_access_token }}
      run: |
        cd ./ydb/ci/rightlib
        ./create_sync_pr.py --base-branch="${{ inputs.base_branch }}" --head-branch="${{ inputs.head_branch }}" --process-label="${{ inputs.label }}"

