SELECT
    1 BETWEEN 2 AND 4,
    3 BETWEEN 2 AND 4,
    5 BETWEEN 2 AND 4,
    3 BETWEEN 4 AND 2,
    5 BETWEEN 4 AND 2,
    NULL BETWEEN 2 AND 4,
    1 BETWEEN NULL AND 4,
    1 BETWEEN 4 AND NULL,
    1 BETWEEN 0 AND NULL,
    1 BETWEEN NULL AND NULL,
    NULL BETWEEN NULL AND NULL
;

SELECT
    1 BETWEEN ASYMMETRIC 2 AND 4,
    3 BETWEEN ASYMMETRIC 2 AND 4,
    5 BETWEEN ASYMMETRIC 2 AND 4,
    3 BETWEEN ASYMMETRIC 4 AND 2,
    5 BETWEEN ASYMMETRIC 4 AND 2,
    NULL BETWEEN ASYMMETRIC 2 AND 4,
    1 BETWEEN ASYMMETRIC NULL AND 4,
    1 BETWEEN ASYMMETRIC 4 AND NULL,
    1 BETWEEN ASYMMETRIC 0 AND NULL,
    1 BETWEEN ASYMMETRIC NULL AND NULL,
    NULL BETWEEN ASYMMETRIC NULL AND NULL
;

SELECT
    1 BETWEEN SYMMETRIC 2 AND 4,
    3 BETWEEN SYMMETRIC 2 AND 4,
    5 BETWEEN SYMMETRIC 2 AND 4,
    1 BETWEEN SYMMETRIC 4 AND 2,
    3 BETWEEN SYMMETRIC 4 AND 2,
    5 BETWEEN SYMMETRIC 4 AND 2,
    NULL BETWEEN SYMMETRIC 2 AND 4,
    1 BETWEEN SYMMETRIC NULL AND 4,
    1 BETWEEN SYMMETRIC 4 AND NULL,
    1 BETWEEN SYMMETRIC 0 AND NULL,
    1 BETWEEN SYMMETRIC NULL AND NULL,
    NULL BETWEEN SYMMETRIC NULL AND NULL
;
