#pragma once

#include <util/system/defaults.h>

namespace NKikimr::NSQS {

enum EQueryId {
    DELETE_MESSAGE_ID = 0,
    LOCK_GROUP_ID = 1,
    READ_MESSAGE_ID = 2,
    WRITE_MESSAGE_ID = 3,
    PURGE_QUEUE_ID = 4,
    CHANGE_VISIBILITY_ID = 5,
    CLEANUP_DEDUPLICATION_ID = 6,
    CLEANUP_READS_ID = 7,
    LIST_QUEUES_ID = 8,
    SET_QUEUE_ATTRIBUTES_ID = 9,
    SET_RETENTION_ID = 10,
    LOAD_MESSAGES_ID = 11,
    INTERNAL_GET_QUEUE_ATTRIBUTES_ID = 12,
    PURGE_QUEUE_STAGE2_ID = 13,
    GET_MESSAGE_COUNT_METRIC_ID = 14,
    GET_OLDEST_MESSAGE_TIMESTAMP_METRIC_ID = 15,
    GET_RETENTION_OFFSET_ID = 16,
    LOAD_INFLY_ID = 17,
    ADD_MESSAGES_TO_INFLY_ID = 18,
    GET_STATE_ID = 19,
    LIST_DEAD_LETTER_SOURCE_QUEUES_ID = 20,
    LOAD_OR_REDRIVE_MESSAGE_ID = 21,
    READ_OR_REDRIVE_MESSAGE_ID = 22,
    GET_USER_SETTINGS_ID = 23,
    GET_QUEUES_LIST_ID = 24,

    QUERY_VECTOR_SIZE,
};

} // namespace NKikimr::NSQS
