--!syntax_v1
CREATE TABLE ScriptingTest (
    Key Uint64,
    Value String,
    PRIMARY KEY (Key)
);
COMMIT;

REPLACE INTO ScriptingTest (Key, Value) VALUES
    (1, "One"),
    (2, "Two");
COMMIT;

REPLACE INTO ScriptingTest (Key, Value) VALUES
    (3, "Three"),
    (4, "Four");
COMMIT;

PRAGMA kikimr.ScanQuery = "true";
SELECT count(*) FROM ScriptingTest;
COMMIT;

PRAGMA kikimr.ScanQuery = "false";
SELECT count(*) FROM ScriptingTest;
COMMIT;

PRAGMA kikimr.ScanQuery = "true";
SELECT count(*) FROM ScriptingTest;
COMMIT;

PRAGMA kikimr.ScanQuery = "false";
SELECT count(*) FROM ScriptingTest;
COMMIT;

PRAGMA kikimr.ScanQuery = "true";
SELECT 1*2*3*4*5;
COMMIT;

PRAGMA kikimr.ScanQuery = "false";
SELECT 1*2*3*4*5;
COMMIT;
