# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(21.0.0)

LICENSE(MIT)

PEERDIR(
    contrib/python/idna
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    hyperlink/__init__.py
    hyperlink/_socket.py
    hyperlink/_url.py
    hyperlink/hypothesis.py
)

RESOURCE_FILES(
    PREFIX contrib/python/hyperlink/py3/
    .dist-info/METADATA
    .dist-info/top_level.txt
    hyperlink/idna-tables-properties.csv.gz
    hyperlink/py.typed
)

END()

RECURSE_FOR_TESTS(
    tests
)
