# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(8.1.7)

LICENSE(BSD-3-Clause)

PEERDIR(
    contrib/python/colorama
    library/python/symbols/python
)

NO_LINT()

NO_CHECK_IMPORTS(
    click._winconsole
)

PY_SRCS(
    TOP_LEVEL
    click/__init__.py
    click/_compat.py
    click/_termui_impl.py
    click/_textwrap.py
    click/_winconsole.py
    click/core.py
    click/decorators.py
    click/exceptions.py
    click/formatting.py
    click/globals.py
    click/parser.py
    click/shell_completion.py
    click/termui.py
    click/testing.py
    click/types.py
    click/utils.py
)

RESOURCE_FILES(
    PREFIX contrib/python/click/py3/
    .dist-info/METADATA
    .dist-info/top_level.txt
    click/py.typed
)

END()

RECURSE_FOR_TESTS(
    tests
)
