name: graph_compare
description: Compare graphs between current and previous commits (merge commit base in case of a merge commit), and list affected tests in ya.make
runs:
  using: "composite"
  steps:
    - name: original_ref
      id: oref
      shell: bash
      run: |
        echo "value=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    - name: generate_ya_make
      shell: bash
      run: |
        ./.github/scripts/graph_compare.sh ${{ steps.oref.outputs.value }}~1 ${{ steps.oref.outputs.value }}
    - name: restore_ref
      shell: bash
      run: |
        git checkout ${{ steps.oref.outputs.value }}
