GO_LIBRARY()
IF (TRUE)
    SRCS(
        alias.go
        api.go
        api_predicates.go
        array.go
        assignments.go
        basic.go
        builtins.go
        call.go
        chan.go
        check.go
        const.go
        context.go
        conversions.go
        decl.go
        errors.go
        eval.go
        expr.go
        exprstring.go
        gccgosizes.go
        gcsizes.go
        generate.go
        index.go
        infer.go
        initorder.go
        instantiate.go
        interface.go
        labels.go
        lookup.go
        map.go
        methodset.go
        mono.go
        named.go
        object.go
        objset.go
        operand.go
        package.go
        pointer.go
        predicates.go
        resolver.go
        return.go
        scope.go
        selection.go
        signature.go
        sizes.go
        slice.go
        stmt.go
        struct.go
        subst.go
        termlist.go
        tuple.go
        type.go
        typelists.go
        typeparam.go
        typeset.go
        typestring.go
        typeterm.go
        typexpr.go
        under.go
        unify.go
        union.go
        universe.go
        util.go
        validtype.go
        version.go
    )
ENDIF()
END()
