#pragma once

#include "my_config-linux.h"

#define alloca _alloca

#undef HAVE_ALLOCA_H
#undef HAVE_ARPA_INET_H
#undef HAVE_DLFCN_H
#undef HAVE_FNMATCH_H
#undef HAVE_NETINET_IN_H
#undef HAVE_POLL_H
#undef HAVE_PWD_H
#undef HAVE_SYS_IOCTL_H
#undef HAVE_SYS_MMAN_H
#undef HAVE_SYS_RESOURCE_H
#undef HAVE_SYS_SELECT_H
#undef HAVE_SYS_SOCKET_H
#undef HAVE_SYS_TIMES_H
#undef HAVE_SYS_TIME_H
#undef HAVE_SYS_UN_H
#undef HAVE_UNISTD_H

#undef HAVE_ENDIAN_CONVERSION_MACROS
#undef HAVE_FDATASYNC
#undef HAVE_FSEEKO
#undef HAVE_FSYNC
#undef HAVE_GETPASS
#undef HAVE_GETPWNAM
#undef HAVE_GETRLIMIT
#undef HAVE_GETRUSAGE
#undef HAVE_POLL
#undef HAVE_PTHREAD_SETNAME_NP_LINUX
#undef HAVE_STPNCPY
#undef HAVE_SYS_GETTID
#undef HAVE_ULONG

#undef HAVE_CLOCK_GETTIME
#undef HAVE_GETTIMEOFDAY
#undef HAVE_POSIX_TIMERS
#undef TIME_WITH_SYS_TIME

#define HAVE_ALIGNED_MALLOC 1
#undef HAVE_MEMALIGN
#undef HAVE_POSIX_MEMALIGN

#undef HAVE_UNIX_DNS_SRV
#define HAVE_WIN32_DNS_SRV 1

#define DEFAULT_TMPDIR ""
