RECURSE(
    actors
    audit
    checkpointing
    checkpointing_common
    checkpoint_storage
    cloud_audit
    common
    compute
    config
    control_plane_config
    control_plane_proxy
    control_plane_storage
    db_id_async_resolver_impl
    db_schema
    events
    gateway
    graph_params
    health
    hmac
    http_api_client
    init
    logs
    metrics
    mock
    pretty_printers
    private_client
    quota_manager
    rate_limiter
    read_rule
    result_formatter
    shared_resources
    signer
    tasks_packer
    test_connection
    ydb
)
