# generated by datamodel-codegen:
#   filename:  boolean_property.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel


class Model(BaseModel):
    field: Optional[Any] = None
