# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(2.9.1)

LICENSE(MIT)

PEERDIR(
    contrib/python/aiohttp
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    aiohttp_retry/__init__.py
    aiohttp_retry/client.py
    aiohttp_retry/retry_options.py
    aiohttp_retry/types.py
)

RESOURCE_FILES(
    PREFIX contrib/python/aiohttp-retry/
    .dist-info/METADATA
    .dist-info/top_level.txt
    aiohttp_retry/py.typed
)

END()
