generic:
  mlock: false

  logging:
    stderr: false

  server:
    http_port: 8788
    https_port: 8789
    ca_cert_file: path/to/ca.crt
    ssl_cert_file: path/to/ssl.crt

  auth:
    token: your_ydb_token
    token_file: path/to/ydb_token

ydbc:
  locations:
    - name: "alpha"
      environment: "alpha"
      endpoints:
        api: "grpc://ydb.yandex.net:2135"
        cluster-api: "grpc://ydb.yandex.net:2135"
        cp-api: "grpcs://ydbc.ydb.cloud.yandex.net:2135"
        http-mon: "http://ydb.yandex.net:8765"
      root_domain: "/alpha"
      data_centers: ["myt", "sas", "vla"]
      unit_resources:
        &unit_resources
        - type: compute
          kind: slot
          cpu: 10
          memory: 53687091200 # 50*1024*1024*1024
          storage: 0
        - type: storage
          kind: hdd
          cpu: 10
          memory: 536870912000 # 500*1024*1024*1024
          storage: 0
        - type: storage
          kind: ssd
          cpu: 10
          memory: 107374182400 # 100*1024*1024*1024
          storage: 0
    - name: "preprod"
      environment: "preprod"
      endpoints:
        api: "grpc://ydb.yandex.net:2135"
        cluster-api: "grpc://ydb.yandex.net:2135"
        cp-api: "grpcs://ydbc.preprod.yandex.net:2135"
        http-mon: "http://ydb.yandex.net:8765"
      root_domain: "/preprod"
      data_centers: ["myt", "sas", "vla"]
      unit_resources: *unit_resources
      serverless_document_proxy_endpoint: "https://docapi.preprod.yandex.net"
