# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(3.0.0)

LICENSE(MIT)

PEERDIR(
    contrib/python/aiohttp
    contrib/python/pytest-asyncio
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    aresponses/__init__.py
    aresponses/errors.py
    aresponses/main.py
    aresponses/utils.py
)

RESOURCE_FILES(
    PREFIX contrib/python/aresponses/
    .dist-info/METADATA
    .dist-info/entry_points.txt
    .dist-info/top_level.txt
)

END()


IF (NOT AUTOCHECK)
  RECURSE_FOR_TESTS(tests)
ENDIF()
