RECURSE(
    kv
    log
    mixedpy
    node_broker
    olap_workload
    oltp_workload
    s3_backups
    simple_queue
    show_create/view
    statistics_workload
    transfer
    reconfig_state_storage_workload
)
