# Allows to override chart & chart resources name
nameOverride: ""
fullnameOverride: ""

# Enable kube-prometheus-stack chart
kube-prometheus-stack:
  enabled: true

  # Install prometheus crd object
  prometheus:
    enabled: true

    # Enable only for monitoring ydb external clusters
    # prometheusSpec:
    #   additionalScrapeConfigsSecret:
    #     enabled: true
    #     name: ydb-prometheus-additional-scrape-configs
    #     key: additional-scrape-configs.yaml

# Grafana dashboards
grafanaDashboards:
  # Enable dashboards generation
  enabled: true

  # Label which will be used to mark configmaps with grafana dashboards
  markerLabel:
    key: grafana_dashboard
    value: "1"

# Prometheus server related configuration
prometheusConfig:
  # Enable service monitors & scrape configs generation
  enabled: true

  # Additional scrape configs that referenced in prometheus.spec
  #
  additionalScrapeConfigs:
    # Generated secret key
    key: additional-scrape-configs.yaml
    # Generated secret name, if empty chart name will be used
    name: ""

# YDB Monitoring related configuration
ydb:
  # Predefined monitoring counters to scrape
  counters:
    # Counter name
    # counter: <counter name>
    #
    # Counter type
    # If unspecified, will be used for both targets
    # type: <static|dynamic>
    #
    # Metrics path
    # If unspecified, will be used /counters/counters=%s/prometheus
    # metricsPath: <url to prometheus metrics>
    #
    # Metrics path params
    # If specified, will be set as params variables for scrape configs or service monitor spec
    # Specified as key: value, where value can be specified as {{ .counter.<counter field> }} or {{ .target.<target field> }}
    # metricsPathParams: {}
    #
    # Skip Name Relabeling
    # If specified, will skip relabel metric name to counter_<__name__>
    # skipNameRelabeling: true
    #
    - counter: ydb
      metricsPath: /counters/counters=ydb/name_label=name/prometheus
    # - counter: ydb_serverless
    - counter: auth
    - counter: coordinator
    - counter: dsproxy_queue
    - counter: dsproxy
    - counter: dsproxy_percentile
    - counter: grpc
    - counter: pdisks
      type: static
    - counter: kqp
      type: dynamic
    - counter: processing
    - counter: proxy
    - counter: followers
    - counter: storage_pool_stat
    # - counter: streaming
    - counter: tablets
    - counter: utils
    # - counter: yql
    - counter: dsproxynode
    - counter: interconnect
    - counter: vdisks
      type: static
    - counter: healthcheck
      type: static
      metricsPath: /healthcheck
      metricsPathParams:
        format: prometheus
      skipNameRelabeling: true
    - counter: healthcheck-dynamic
      type: dynamic
      metricsPath: /healthcheck
      metricsPathParams:
        format: prometheus
        tenant: "{{ .target.path }}"
      skipNameRelabeling: true
    - counter: dsproxy_mon

  # Cluster which will be monitored
  clusters: []
  # Cluster name
  # name: <cluster name>
  #
  # Cluster type
  # For external clusters, additional scrape config secret will be generated
  # For internal clusters, service monitor with appropriate configuration will be generated
  # type: <external|internal>
  #
  # Storage nodes monitoring configuration
  # storage:
  #   name: <name of prometheus job/target>
  #
  #   Internal cluster specific spec
  #   namespace: <namespace of ydb storage pods>
  #   selector: <label selector for ydb storage pods>
  #   port:
  #     name: <service port name for ydb storage pods>
  #
  #   External cluster specific spec
  #   hosts:
  #   - <ydb storage host>
  #   port:
  #     number: <ydb storage monitoring (status) port number>
  #
  # Dynamic nodes monitoring configuration
  # Each item represents ydb database
  # databases:
  # - name: <name of prometheus job/target>
  #   path: <path to database>
  #
  #   Internal cluster specific spec
  #   namespace: <namespace of ydb database pods>
  #   selector: <label selector for ydb database pods>
  #   port:
  #     name: <service port name for ydb database pods>
  #
  #   External cluster specific spec
  #   hosts:
  #   - <ydb database host>
  #   port:
  #     number: <ydb database monitoring (status) port number>
