#pragma once
#include "defs.h"

namespace NKikimr {
namespace NDataShard {

enum class EExecutionUnitKind: ui32 {
    CheckDataTx,
    CheckSchemeTx,
    CheckSnapshotTx,
    CheckDistributedEraseTx,
    CheckCommitWritesTx,
    CheckRead,
    CheckWrite,
    StoreDataTx,
    StoreWrite,
    StoreSchemeTx,
    StoreSnapshotTx,
    StoreDistributedEraseTx,
    StoreCommitWritesTx,
    BuildAndWaitDependencies,
    FinishPropose,
    FinishProposeWrite,
    CompletedOperations,
    WaitForPlan,
    PlanQueue,
    LoadTxDetails,
    LoadWriteDetails,
    FinalizeDataTxPlan,
    ProtectSchemeEchoes,
    BuildDataTxOutRS,
    BuildKqpDataTxOutRS,
    BuildWriteOutRS,
    BuildDistributedEraseTxOutRS,
    StoreAndSendOutRS,
    StoreAndSendWriteOutRS,
    PrepareDataTxInRS,
    PrepareKqpDataTxInRS,
    PrepareWriteTxInRS,
    PrepareDistributedEraseTxInRS,
    LoadAndWaitInRS,
    ExecuteDataTx,
    ExecuteKqpDataTx,
    ExecuteDistributedEraseTx,
    ExecuteCommitWritesTx,
    ExecuteRead,
    ExecuteWrite,
    CompleteOperation,
    CompleteWrite,
    ExecuteKqpScanTx,
    MakeScanSnapshot,
    WaitForStreamClearance,
    ReadTableScan,
    MakeSnapshot,
    BuildSchemeTxOutRS,
    PrepareSchemeTxInRS,
    Backup,
    Restore,
    CreateTable,
    ReceiveSnapshot,
    ReceiveSnapshotCleanup,
    AlterMoveShadow,
    AlterTable,
    DropTable,
    DirectOp,
    CreatePersistentSnapshot,
    DropPersistentSnapshot,
    CreateVolatileSnapshot,
    DropVolatileSnapshot,
    InitiateBuildIndex,
    FinalizeBuildIndex,
    DropIndexNotice,
    MoveTable,
    CreateCdcStream,
    AlterCdcStream,
    DropCdcStream,
    MoveIndex,
    Count,
    Unspecified
};

} // namespace NDataShard
} // namespace NKikimr
