# https://github.com/RDFLib/rdflib-jsonld/blob/feature/json-ld-1.1/rdflib_jsonld/keys.py
BASE = "@base"
CONTAINER = "@container"
CONTEXT = "@context"
# DIRECTION = u'@direction'
GRAPH = "@graph"
ID = "@id"
IMPORT = "@import"
INCLUDED = "@included"
INDEX = "@index"
JSON = "@json"
LANG = LANGUAGE = "@language"
LIST = "@list"
NEST = "@nest"
NONE = "@none"
PREFIX = "@prefix"
PROPAGATE = "@propagate"
PROTECTED = "@protected"
REV = REVERSE = "@reverse"
SET = "@set"
TYPE = "@type"
VALUE = "@value"
VERSION = "@version"
VOCAB = "@vocab"
