# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(1.2.0)

LICENSE(BSD-3-Clause)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    siteforms/__init__.py
    siteforms/apps.py
    siteforms/base.py
    siteforms/composers/__init__.py
    siteforms/composers/base.py
    siteforms/composers/bootstrap4.py
    siteforms/composers/bootstrap5.py
    siteforms/fields.py
    siteforms/formsets.py
    siteforms/metas.py
    siteforms/toolbox.py
    siteforms/utils.py
    siteforms/widgets.py
)

RESOURCE_FILES(
    PREFIX contrib/python/django-siteforms/
    .dist-info/METADATA
    .dist-info/top_level.txt
    siteforms/locale/ru/LC_MESSAGES/django.mo
)

END()
