syntax = "proto3";

import "ydb/core/nbs/cloud/storage/core/compat/protos/rdma.proto";
import "ydb/core/nbs/cloud/storage/core/compat/protos/certificate.proto";
import "ydb/core/nbs/cloud/storage/core/compat/protos/endpoints.proto";
import "ydb/core/nbs/cloud/storage/core/compat/protos/media.proto";

package NCloud.NBlockStore.NProto;

option go_package = "github.com/ydb-platform/nbs/cloud/blockstore/config";

////////////////////////////////////////////////////////////////////////////////

message TAffinity
{
    repeated uint32 CPU = 1;
}

////////////////////////////////////////////////////////////////////////////////

message TLocation
{
    optional string DataCenter = 1;
    optional string Rack = 2;
    optional uint64 Body = 3;
}

////////////////////////////////////////////////////////////////////////////////

message TChecksumFlags
{
    reserved 1;

    // Enables data integrity validation client that calculates checksums for
    // write requests and validates checksums for read requests. Calculation for
    // reads and validation for writes needs to be done in the storage layer.
    optional bool EnableDataIntegrityClient = 2;

    // Same as "EnableDataIntegrityClient", but enables the client only for the
    // specified media kinds.
    repeated NCloud.NProto.EStorageMediaKind MediaKindsToValidateDataIntegrity = 3;
}

////////////////////////////////////////////////////////////////////////////////

enum EEncryptZeroPolicy
{
    EZP_WRITE_ENCRYPTED_ZEROS = 0;
    EZP_WRITE_ZERO_BLOCKS = 1;
}

////////////////////////////////////////////////////////////////////////////////

message TServerConfig
{
    // Host name or address to listen on.
    optional string Host = 1;

    // Port to listen on.
    optional uint32 Port = 2;

    // Host name or address to listen on (for data service requests).
    optional string DataHost = 3;

    // Port to listen on (for data service requests).
    optional uint32 DataPort = 4;

    // Number of gRPC threads.
    optional uint32 ThreadsCount = 5;

    // Maximum size of gRPC message.
    optional uint32 MaxMessageSize = 6;

    // Number of prepared gRPC requests.
    optional uint32 PreparedRequestsCount = 7;

    // Memory quota for gRPC request processing.
    optional uint32 MemoryQuotaBytes = 8;

    // Host name or address to listen on (with TLS enabled).
    optional string SecureHost = 50;

    // Port to listen on (with TLS enabled).
    optional uint32 SecurePort = 9;

    // TLS details.
    optional string RootCertsFile = 10;
    // The following 2 are deprecated in favor of Certs.
    optional string CertFile = 11;
    optional string CertPrivateKeyFile = 12;
    repeated NCloud.NProto.TCertificate Certs = 27;

    // TCP KeepAlive details.
    optional bool KeepAliveEnabled = 13;
    optional uint32 KeepAliveIdleTimeout = 14;   // (in milliseconds).
    optional uint32 KeepAliveProbeTimeout = 15;  // (in milliseconds).
    optional uint32 KeepAliveProbesCount = 16;

    // Run additional checks for interactions between client and server .
    optional bool StrictContractValidation = 17;

    // Load configs from cms.
    optional bool LoadCmsConfigs = 18 [deprecated = true];

    // Shutdown timeout (in milliseconds).
    optional uint32 ShutdownTimeout = 19;

    // Request timeout (in milliseconds).
    optional uint32 RequestTimeout = 20;

    // Unix-socket details.
    optional string UnixSocketPath = 21;
    optional uint32 UnixSocketBacklog = 22;

    // Limit of grpc threads count.
    optional uint32 GrpcThreadsLimit = 23;

    // Vhost server details.
    optional bool VhostEnabled = 24;
    optional uint32 VhostThreadsCount = 25;
    optional TAffinity VhostAffinity = 37;

    // [obsolete] Client details for endpoints.
    // optional TClientThrottlingConfig ClientThrottlingConfig = 30;

    // NVMEoF initiator enabled.
    optional bool NvmfInitiatorEnabled = 31;

    // Node type
    // deprecated. moved to storage config.
    optional string NodeType = 32;

    // Endpoint storage details.
    optional NCloud.NProto.EEndpointStorageType EndpointStorageType = 106;
    optional string RootKeyringName = 33;
    optional string EndpointsKeyringName = 42;
    optional string EndpointStorageDir = 107;

    // Nbd server details.
    optional bool NbdEnabled = 34;
    optional uint32 NbdThreadsCount = 35;
    optional bool NbdLimiterEnabled = 61;
    optional uint64 MaxInFlightBytesPerThread = 36;
    optional TAffinity NbdAffinity = 38;

    // Dynamic node registration params.
    // The following 3 are deprecated in favor of params in storage config
    optional uint32 NodeRegistrationMaxAttempts = 39;
    optional uint32 NodeRegistrationTimeout = 40;   // in ms
    optional uint32 NodeRegistrationErrorTimeout = 41;  // in ms

    // Suffix for nbd-socket
    optional string NbdSocketSuffix = 43;

    // GRPC KeepAlive
    optional uint32 GrpcKeepAliveTime = 44; // ms
    optional uint32 GrpcKeepAliveTimeout = 45; // ms
    optional bool GrpcKeepAlivePermitWithoutCalls = 46;
    optional uint32 GrpcHttp2MinRecvPingIntervalWithoutData = 47; // ms
    optional uint32 GrpcHttp2MinSentPingIntervalWithoutData = 48; // ms

    // [obsolete] Enable disk-agent in dedicated process.
    // optional bool DedicatedDiskAgent = 53;

    // NVMe endpoint details.
    optional bool NVMeEndpointEnabled = 54;
    optional string NVMeEndpointNqn = 55;
    repeated string NVMeEndpointTransportIDs = 56;

    // SCSI endpoint details.
    optional bool SCSIEndpointEnabled = 57;
    optional string SCSIEndpointName = 58;
    optional string SCSIEndpointListenAddress = 59;
    optional uint32 SCSIEndpointListenPort = 60;

    // RDMA endpoint details.
    optional bool RdmaEndpointEnabled = 62;
    optional string RdmaEndpointListenAddress = 63;
    optional uint32 RdmaEndpointListenPort = 64;

    // RDMA client details.
    optional bool RdmaClientEnabled = 65;
    optional NCloud.NProto.TRdmaClient RdmaClientConfig = 66;

    // Throttling service details.
    optional bool ThrottlingEnabled = 100;
    // Bytes per second.
    optional uint64 MaxReadBandwidth = 101;
    optional uint64 MaxWriteBandwidth = 102;
    // Iops.
    optional uint32 MaxReadIops = 103;
    optional uint32 MaxWriteIops = 104;
    // Max burst length in milliseconds.
    optional uint32 MaxBurstTime = 105;

    // Path to vhost server executable.
    optional string VhostServerPath = 108;

    // Prefix for nbd device paths, e.g. "/dev/nbd"
    optional string NbdDevicePrefix = 109;

    // Access mode for endpoint socket files
    optional uint32 SocketAccessMode = 110;

    // Use netlink interface to setup nbd device
    optional bool NbdNetlink = 111;

    // NBD request timeout in milliseconds, applied only in netlink mode
    optional uint32 NbdRequestTimeout = 112;

    // NBD connection timeout in milliseconds
    optional uint32 NbdConnectionTimeout = 113;

    // Endpoint Proxy unix socket path. Triggers proxy device factory usage
    // instead of ioctl-based nbd device factory usage (but NbdNetlink flag has
    // higher priority).
    optional string EndpointProxySocketPath = 114 [deprecated = true];

    // Allow all control requests via unix socket (e.g., for CSI-driver)
    optional bool AllowAllRequestsViaUDS = 115;

    // Causes E_NOT_IMPLEMENTED errors in endpoint storages to be logged.
    optional bool EndpointStorageNotImplementedErrorIsFatal = 116;

    // auth token for node registration via ydb discovery api.
    // deprecated. moved to storage config.
    optional string NodeRegistrationToken = 117;

    // How many seconds will the external vhost server continue to work after
    // the parent process die.
    optional uint32 VhostServerTimeoutAfterParentExit = 118;

    // Flags for managing checksums.
    optional TChecksumFlags ChecksumFlags = 119;

    // Use fake RDMA client (over Interconnect). For use in tests.
    optional bool UseFakeRdmaClient = 120;

    // Enable Discard and WriteZeroes features for vhost devices. Applies to
    // network-ssd and network-hdd disks.
    optional bool VhostDiscardEnabled = 121;

    // Maximum request size in bytes for ZeroBlocks.
    // Requests exceeding this size will be split into smaller sub-requests,
    // each with a size up to MaxZeroBlocksSubRequestSize.
    // Max value for MaxZeroBlocksSubRequestSize is 2 GiB
    optional uint32 MaxZeroBlocksSubRequestSize = 122;

    // If set to a non-zero value, PTEs of the external vhost server backing
    // the guest memory regions for blockdev are flushed (unmapped and mapped
    // back) every N bytes processed by the backend. E.g. if this value is 4096,
    // PTEs will be flushed after the guest reads/writes 8 512-byte blocks or
    // 1 4KiB block.
    optional uint64 VhostPteFlushByteThreshold = 123;

    // Ask system to provide a free nbd device
    optional bool AutomaticNbdDeviceManagement = 124;

    // Disables per-client throttlers.
    optional bool DisableClientThrottlers = 125;

    // Policy for encryption of zeroed blocks.
    optional EEncryptZeroPolicy EncryptZeroPolicy = 126;

    // Optimal IO size for vhost devices. Zero value is the default one.
    // For linux, sets the value of /sys/block/<device>/queue/optimal_io_size.
    optional uint32 VhostOptimalIoSize = 127;

    // Enables protection from executing overlapping zero or write requests.
    optional bool EnableOverlappingRequestsGuard = 128;

    // Enables splitting requests across device and stripe boundaries.
    optional bool EnableRequestSplitter = 129;

    // Enable Discard feature for vhost devices. Unlike the VhostDiscardEnabled
    // flag, this flag does not affect the WriteZeroes feature. Applies to
    // network-ssd and network-hdd disks.
    //
    // If this flag is enabled, discards are
    // enabled for all network-ssd and network-hdd disks. Otherwise, discards
    // are enabled only for disks that have the VhostDiscardEnabled flag set in
    // the VolumeConfig in SchemeShard.
    optional bool VhostDiscardOnlyEnabled = 130;

    // Enable WriteZeroes feature for vhost devices. Applies to
    // network-ssd and network-hdd disks.
    optional bool VhostWriteZeroesEnabled = 131;

    // Drop all discard requests without processing them.
    optional bool DropDiscardRequests = 132;

    // Size of the thread pool for the external vhost server.
    optional uint32 ExternalVhostServerThreadPoolSize = 133;

    // Certificate refresh period (in milliseconds) for automatic TLS certificate
    // reloading. Zero disables periodic certificate reloading.
    optional uint32 RefreshCertsPeriod = 134;
}

////////////////////////////////////////////////////////////////////////////////

message TNullServiceConfig
{
    optional bool AddReadResponseData = 1;
    optional uint32 DiskBlockSize = 2;
    optional uint64 DiskBlocksCount = 3;
    optional uint32 IopsLimit = 4;
}

////////////////////////////////////////////////////////////////////////////////

message TLocalServiceConfig
{
    optional string DataDir = 1;
    // Shutdown timeout (in milliseconds).
    optional uint32 ShutdownTimeout = 2;
}

////////////////////////////////////////////////////////////////////////////////

message TKikimrServiceConfig
{
}

////////////////////////////////////////////////////////////////////////////////

message TServerAppConfig
{
    optional TServerConfig ServerConfig = 1;

    optional TNullServiceConfig NullServiceConfig = 4;
    optional TLocalServiceConfig LocalServiceConfig = 2;
    optional TKikimrServiceConfig KikimrServiceConfig = 3;
}
