PY2_LIBRARY()

LICENSE(MIT)

VERSION(2.6.4)

PEERDIR(
    contrib/python/lxml
    contrib/python/jdcal
)

PY_SRCS(
    TOP_LEVEL
    openpyxl/__init__.py
    openpyxl/_constants.py
    openpyxl/cell/__init__.py
    openpyxl/cell/_writer.py
    openpyxl/cell/cell.py
    openpyxl/cell/read_only.py
    openpyxl/cell/text.py
    openpyxl/chart/_3d.py
    openpyxl/chart/__init__.py
    openpyxl/chart/_chart.py
    openpyxl/chart/area_chart.py
    openpyxl/chart/axis.py
    openpyxl/chart/bar_chart.py
    openpyxl/chart/bubble_chart.py
    openpyxl/chart/chartspace.py
    openpyxl/chart/data_source.py
    openpyxl/chart/descriptors.py
    openpyxl/chart/error_bar.py
    openpyxl/chart/label.py
    openpyxl/chart/layout.py
    openpyxl/chart/legend.py
    openpyxl/chart/line_chart.py
    openpyxl/chart/marker.py
    openpyxl/chart/picture.py
    openpyxl/chart/pie_chart.py
    openpyxl/chart/pivot.py
    openpyxl/chart/plotarea.py
    openpyxl/chart/print_settings.py
    openpyxl/chart/radar_chart.py
    openpyxl/chart/reader.py
    openpyxl/chart/reference.py
    openpyxl/chart/scatter_chart.py
    openpyxl/chart/series.py
    openpyxl/chart/series_factory.py
    openpyxl/chart/shapes.py
    openpyxl/chart/stock_chart.py
    openpyxl/chart/surface_chart.py
    openpyxl/chart/text.py
    openpyxl/chart/title.py
    openpyxl/chart/trendline.py
    openpyxl/chart/updown_bars.py
    openpyxl/chartsheet/__init__.py
    openpyxl/chartsheet/chartsheet.py
    openpyxl/chartsheet/custom.py
    openpyxl/chartsheet/properties.py
    openpyxl/chartsheet/protection.py
    openpyxl/chartsheet/publish.py
    openpyxl/chartsheet/relation.py
    openpyxl/chartsheet/views.py
    openpyxl/comments/__init__.py
    openpyxl/comments/author.py
    openpyxl/comments/comment_sheet.py
    openpyxl/comments/comments.py
    openpyxl/comments/shape_writer.py
    openpyxl/compat/__init__.py
    openpyxl/compat/abc.py
    openpyxl/compat/accumulate.py
    openpyxl/compat/numbers.py
    openpyxl/compat/singleton.py
    openpyxl/compat/strings.py
    openpyxl/descriptors/__init__.py
    openpyxl/descriptors/base.py
    openpyxl/descriptors/excel.py
    openpyxl/descriptors/namespace.py
    openpyxl/descriptors/nested.py
    openpyxl/descriptors/sequence.py
    openpyxl/descriptors/serialisable.py
    openpyxl/descriptors/slots.py
    openpyxl/drawing/__init__.py
    openpyxl/drawing/colors.py
    openpyxl/drawing/connector.py
    openpyxl/drawing/drawing.py
    openpyxl/drawing/effect.py
    openpyxl/drawing/fill.py
    openpyxl/drawing/geometry.py
    openpyxl/drawing/graphic.py
    openpyxl/drawing/image.py
    openpyxl/drawing/line.py
    openpyxl/drawing/picture.py
    openpyxl/drawing/properties.py
    openpyxl/drawing/relation.py
    openpyxl/drawing/spreadsheet_drawing.py
    openpyxl/drawing/text.py
    openpyxl/drawing/xdr.py
    openpyxl/formatting/__init__.py
    openpyxl/formatting/formatting.py
    openpyxl/formatting/rule.py
    openpyxl/formula/__init__.py
    openpyxl/formula/tokenizer.py
    openpyxl/formula/translate.py
    openpyxl/packaging/__init__.py
    openpyxl/packaging/core.py
    openpyxl/packaging/extended.py
    openpyxl/packaging/interface.py
    openpyxl/packaging/manifest.py
    openpyxl/packaging/relationship.py
    openpyxl/packaging/workbook.py
    openpyxl/pivot/__init__.py
    openpyxl/pivot/cache.py
    openpyxl/pivot/fields.py
    openpyxl/pivot/record.py
    openpyxl/pivot/table.py
    openpyxl/reader/__init__.py
    openpyxl/reader/drawings.py
    openpyxl/reader/excel.py
    openpyxl/reader/strings.py
    openpyxl/reader/workbook.py
    openpyxl/styles/__init__.py
    openpyxl/styles/alignment.py
    openpyxl/styles/borders.py
    openpyxl/styles/builtins.py
    openpyxl/styles/cell_style.py
    openpyxl/styles/colors.py
    openpyxl/styles/differential.py
    openpyxl/styles/fills.py
    openpyxl/styles/fonts.py
    openpyxl/styles/named_styles.py
    openpyxl/styles/numbers.py
    openpyxl/styles/protection.py
    openpyxl/styles/proxy.py
    openpyxl/styles/styleable.py
    openpyxl/styles/stylesheet.py
    openpyxl/styles/table.py
    openpyxl/utils/__init__.py
    openpyxl/utils/bound_dictionary.py
    openpyxl/utils/cell.py
    openpyxl/utils/dataframe.py
    openpyxl/utils/datetime.py
    openpyxl/utils/escape.py
    openpyxl/utils/exceptions.py
    openpyxl/utils/formulas.py
    openpyxl/utils/indexed_list.py
    openpyxl/utils/inference.py
    openpyxl/utils/protection.py
    openpyxl/utils/units.py
    openpyxl/workbook/__init__.py
    openpyxl/workbook/_writer.py
    openpyxl/workbook/child.py
    openpyxl/workbook/defined_name.py
    openpyxl/workbook/external_link/__init__.py
    openpyxl/workbook/external_link/external.py
    openpyxl/workbook/external_reference.py
    openpyxl/workbook/function_group.py
    openpyxl/workbook/properties.py
    openpyxl/workbook/protection.py
    openpyxl/workbook/smart_tags.py
    openpyxl/workbook/views.py
    openpyxl/workbook/web.py
    openpyxl/workbook/workbook.py
    openpyxl/worksheet/__init__.py
    openpyxl/worksheet/_read_only.py
    openpyxl/worksheet/_reader.py
    openpyxl/worksheet/_write_only.py
    openpyxl/worksheet/_writer.py
    openpyxl/worksheet/cell_range.py
    openpyxl/worksheet/cell_watch.py
    openpyxl/worksheet/controls.py
    openpyxl/worksheet/copier.py
    openpyxl/worksheet/custom.py
    openpyxl/worksheet/datavalidation.py
    openpyxl/worksheet/dimensions.py
    openpyxl/worksheet/drawing.py
    openpyxl/worksheet/errors.py
    openpyxl/worksheet/filters.py
    openpyxl/worksheet/header_footer.py
    openpyxl/worksheet/hyperlink.py
    openpyxl/worksheet/merge.py
    openpyxl/worksheet/ole.py
    openpyxl/worksheet/page.py
    openpyxl/worksheet/pagebreak.py
    openpyxl/worksheet/picture.py
    openpyxl/worksheet/properties.py
    openpyxl/worksheet/protection.py
    openpyxl/worksheet/related.py
    openpyxl/worksheet/scenario.py
    openpyxl/worksheet/smart_tag.py
    openpyxl/worksheet/table.py
    openpyxl/worksheet/views.py
    openpyxl/worksheet/worksheet.py
    openpyxl/writer/__init__.py
    openpyxl/writer/excel.py
    openpyxl/writer/theme.py
    openpyxl/xml/__init__.py
    openpyxl/xml/constants.py
    openpyxl/xml/functions.py
)

NO_LINT()

RESOURCE_FILES(
    PREFIX contrib/python/openpyxl/py2/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
