# Generated by devtools/yamaker (pypi).

PY2_LIBRARY()

VERSION(3.3.0)

LICENSE(MIT)

NO_LINT()

NO_CHECK_IMPORTS(
    statsd.defaults.django
)

PY_SRCS(
    TOP_LEVEL
    statsd/__init__.py
    statsd/client/__init__.py
    statsd/client/base.py
    statsd/client/stream.py
    statsd/client/timer.py
    statsd/client/udp.py
    statsd/defaults/__init__.py
    statsd/defaults/django.py
    statsd/defaults/env.py
)

RESOURCE_FILES(
    PREFIX contrib/python/statsd/py2/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
