CREATE EXTERNAL DATA SOURCE local_solomon WITH (
    SOURCE_TYPE="Solomon",
    AUTH_METHOD="NONE",
    USE_SSL="false",
    HTTP_ENDPOINT="${SOLOMON_HTTP_ENDPOINT}",
    GRPC_ENDPOINT="${SOLOMON_GRPC_ENDPOINT}"
);
