RECURSE(
    canondata_sync
    datastreams_helpers
    fq_runner
    idx_test
    kqprun
    mdb_mock
    pq_read
    s3_recipe
    token_accessor_mock
    ydb_serializable
    ydb_serializable/replay
)
