# Generated by devtools/yamaker.

PROGRAM()

WITHOUT_LICENSE_TEXTS()

PEERDIR(
    contrib/libs/c-ares
)

ADDINCL(
    GLOBAL contrib/libs/c-ares
    GLOBAL contrib/libs/c-ares/include
    GLOBAL contrib/libs/c-ares/src/lib
    contrib/libs/c-ares/src/tools
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

CFLAGS(
    -DHAVE_CONFIG_H=1
)

SRCDIR(contrib/libs/c-ares/src)

SRCS(
    lib/ares_nowarn.c
    lib/ares_strcasecmp.c
    tools/ahost.c
    tools/ares_getopt.c
)

END()
