PY2_LIBRARY()

LICENSE(BSD-3-Clause)

VERSION(2.2)

PEERDIR(
    contrib/python/decorator
    contrib/python/pydot
    contrib/python/setuptools
)

NO_CHECK_IMPORTS(
    networkx.algorithms.connectivity.__init__
    networkx.algorithms.flow.__init__
    networkx.testing.__init__
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    networkx/__init__.py
    networkx/algorithms/__init__.py
    networkx/algorithms/approximation/__init__.py
    networkx/algorithms/approximation/clique.py
    networkx/algorithms/approximation/clustering_coefficient.py
    networkx/algorithms/approximation/connectivity.py
    networkx/algorithms/approximation/dominating_set.py
    networkx/algorithms/approximation/independent_set.py
    networkx/algorithms/approximation/kcomponents.py
    networkx/algorithms/approximation/matching.py
    networkx/algorithms/approximation/ramsey.py
    networkx/algorithms/approximation/steinertree.py
    networkx/algorithms/approximation/treewidth.py
    networkx/algorithms/approximation/vertex_cover.py
    networkx/algorithms/assortativity/__init__.py
    networkx/algorithms/assortativity/connectivity.py
    networkx/algorithms/assortativity/correlation.py
    networkx/algorithms/assortativity/mixing.py
    networkx/algorithms/assortativity/neighbor_degree.py
    networkx/algorithms/assortativity/pairs.py
    networkx/algorithms/bipartite/__init__.py
    networkx/algorithms/bipartite/basic.py
    networkx/algorithms/bipartite/centrality.py
    networkx/algorithms/bipartite/cluster.py
    networkx/algorithms/bipartite/covering.py
    networkx/algorithms/bipartite/edgelist.py
    networkx/algorithms/bipartite/generators.py
    networkx/algorithms/bipartite/matching.py
    networkx/algorithms/bipartite/matrix.py
    networkx/algorithms/bipartite/projection.py
    networkx/algorithms/bipartite/redundancy.py
    networkx/algorithms/bipartite/spectral.py
    networkx/algorithms/boundary.py
    networkx/algorithms/bridges.py
    networkx/algorithms/centrality/__init__.py
    networkx/algorithms/centrality/betweenness.py
    networkx/algorithms/centrality/betweenness_subset.py
    networkx/algorithms/centrality/closeness.py
    networkx/algorithms/centrality/current_flow_betweenness.py
    networkx/algorithms/centrality/current_flow_betweenness_subset.py
    networkx/algorithms/centrality/current_flow_closeness.py
    networkx/algorithms/centrality/degree_alg.py
    networkx/algorithms/centrality/dispersion.py
    networkx/algorithms/centrality/eigenvector.py
    networkx/algorithms/centrality/flow_matrix.py
    networkx/algorithms/centrality/harmonic.py
    networkx/algorithms/centrality/katz.py
    networkx/algorithms/centrality/load.py
    networkx/algorithms/centrality/percolation.py
    networkx/algorithms/centrality/reaching.py
    networkx/algorithms/centrality/second_order.py
    networkx/algorithms/centrality/subgraph_alg.py
    networkx/algorithms/chains.py
    networkx/algorithms/chordal.py
    networkx/algorithms/clique.py
    networkx/algorithms/cluster.py
    networkx/algorithms/coloring/__init__.py
    networkx/algorithms/coloring/greedy_coloring.py
    networkx/algorithms/coloring/greedy_coloring_with_interchange.py
    networkx/algorithms/communicability_alg.py
    networkx/algorithms/community/__init__.py
    networkx/algorithms/community/asyn_fluid.py
    networkx/algorithms/community/centrality.py
    networkx/algorithms/community/community_generators.py
    networkx/algorithms/community/community_utils.py
    networkx/algorithms/community/kclique.py
    networkx/algorithms/community/kernighan_lin.py
    networkx/algorithms/community/label_propagation.py
    networkx/algorithms/community/modularity_max.py
    networkx/algorithms/community/quality.py
    networkx/algorithms/components/__init__.py
    networkx/algorithms/components/attracting.py
    networkx/algorithms/components/biconnected.py
    networkx/algorithms/components/connected.py
    networkx/algorithms/components/semiconnected.py
    networkx/algorithms/components/strongly_connected.py
    networkx/algorithms/components/weakly_connected.py
    networkx/algorithms/connectivity/__init__.py
    networkx/algorithms/connectivity/connectivity.py
    networkx/algorithms/connectivity/cuts.py
    networkx/algorithms/connectivity/disjoint_paths.py
    networkx/algorithms/connectivity/edge_augmentation.py
    networkx/algorithms/connectivity/edge_kcomponents.py
    networkx/algorithms/connectivity/kcomponents.py
    networkx/algorithms/connectivity/kcutsets.py
    networkx/algorithms/connectivity/stoerwagner.py
    networkx/algorithms/connectivity/utils.py
    networkx/algorithms/core.py
    networkx/algorithms/covering.py
    networkx/algorithms/cuts.py
    networkx/algorithms/cycles.py
    networkx/algorithms/dag.py
    networkx/algorithms/distance_measures.py
    networkx/algorithms/distance_regular.py
    networkx/algorithms/dominance.py
    networkx/algorithms/dominating.py
    networkx/algorithms/efficiency.py
    networkx/algorithms/euler.py
    networkx/algorithms/flow/__init__.py
    networkx/algorithms/flow/boykovkolmogorov.py
    networkx/algorithms/flow/capacityscaling.py
    networkx/algorithms/flow/dinitz_alg.py
    networkx/algorithms/flow/edmondskarp.py
    networkx/algorithms/flow/gomory_hu.py
    networkx/algorithms/flow/maxflow.py
    networkx/algorithms/flow/mincost.py
    networkx/algorithms/flow/networksimplex.py
    networkx/algorithms/flow/preflowpush.py
    networkx/algorithms/flow/shortestaugmentingpath.py
    networkx/algorithms/flow/utils.py
    networkx/algorithms/graphical.py
    networkx/algorithms/hierarchy.py
    networkx/algorithms/hybrid.py
    networkx/algorithms/isolate.py
    networkx/algorithms/isomorphism/__init__.py
    networkx/algorithms/isomorphism/isomorph.py
    networkx/algorithms/isomorphism/isomorphvf2.py
    networkx/algorithms/isomorphism/matchhelpers.py
    networkx/algorithms/isomorphism/temporalisomorphvf2.py
    networkx/algorithms/isomorphism/vf2userfunc.py
    networkx/algorithms/link_analysis/__init__.py
    networkx/algorithms/link_analysis/hits_alg.py
    networkx/algorithms/link_analysis/pagerank_alg.py
    networkx/algorithms/link_prediction.py
    networkx/algorithms/lowest_common_ancestors.py
    networkx/algorithms/matching.py
    networkx/algorithms/minors.py
    networkx/algorithms/mis.py
    networkx/algorithms/node_classification/__init__.py
    networkx/algorithms/node_classification/hmn.py
    networkx/algorithms/node_classification/lgc.py
    networkx/algorithms/node_classification/utils.py
    networkx/algorithms/operators/__init__.py
    networkx/algorithms/operators/all.py
    networkx/algorithms/operators/binary.py
    networkx/algorithms/operators/product.py
    networkx/algorithms/operators/unary.py
    networkx/algorithms/planarity.py
    networkx/algorithms/reciprocity.py
    networkx/algorithms/richclub.py
    networkx/algorithms/shortest_paths/__init__.py
    networkx/algorithms/shortest_paths/astar.py
    networkx/algorithms/shortest_paths/dense.py
    networkx/algorithms/shortest_paths/generic.py
    networkx/algorithms/shortest_paths/unweighted.py
    networkx/algorithms/shortest_paths/weighted.py
    networkx/algorithms/similarity.py
    networkx/algorithms/simple_paths.py
    networkx/algorithms/smallworld.py
    networkx/algorithms/smetric.py
    networkx/algorithms/sparsifiers.py
    networkx/algorithms/structuralholes.py
    networkx/algorithms/swap.py
    networkx/algorithms/threshold.py
    networkx/algorithms/tournament.py
    networkx/algorithms/traversal/__init__.py
    networkx/algorithms/traversal/beamsearch.py
    networkx/algorithms/traversal/breadth_first_search.py
    networkx/algorithms/traversal/depth_first_search.py
    networkx/algorithms/traversal/edgebfs.py
    networkx/algorithms/traversal/edgedfs.py
    networkx/algorithms/tree/__init__.py
    networkx/algorithms/tree/branchings.py
    networkx/algorithms/tree/coding.py
    networkx/algorithms/tree/mst.py
    networkx/algorithms/tree/operations.py
    networkx/algorithms/tree/recognition.py
    networkx/algorithms/triads.py
    networkx/algorithms/vitality.py
    networkx/algorithms/voronoi.py
    networkx/algorithms/wiener.py
    networkx/classes/__init__.py
    networkx/classes/coreviews.py
    networkx/classes/digraph.py
    networkx/classes/filters.py
    networkx/classes/function.py
    networkx/classes/graph.py
    networkx/classes/graphviews.py
    networkx/classes/multidigraph.py
    networkx/classes/multigraph.py
    networkx/classes/ordered.py
    networkx/classes/reportviews.py
    networkx/convert.py
    networkx/convert_matrix.py
    networkx/drawing/__init__.py
    networkx/drawing/layout.py
    networkx/drawing/nx_agraph.py
    networkx/drawing/nx_pydot.py
    networkx/drawing/nx_pylab.py
    networkx/exception.py
    networkx/generators/__init__.py
    networkx/generators/atlas.py
    networkx/generators/classic.py
    networkx/generators/community.py
    networkx/generators/degree_seq.py
    networkx/generators/directed.py
    networkx/generators/duplication.py
    networkx/generators/ego.py
    networkx/generators/expanders.py
    networkx/generators/geometric.py
    networkx/generators/intersection.py
    networkx/generators/joint_degree_seq.py
    networkx/generators/lattice.py
    networkx/generators/line.py
    networkx/generators/mycielski.py
    networkx/generators/nonisomorphic_trees.py
    networkx/generators/random_clustered.py
    networkx/generators/random_graphs.py
    networkx/generators/small.py
    networkx/generators/social.py
    networkx/generators/spectral_graph_forge.py
    networkx/generators/stochastic.py
    networkx/generators/trees.py
    networkx/generators/triads.py
    networkx/linalg/__init__.py
    networkx/linalg/algebraicconnectivity.py
    networkx/linalg/attrmatrix.py
    networkx/linalg/graphmatrix.py
    networkx/linalg/laplacianmatrix.py
    networkx/linalg/modularitymatrix.py
    networkx/linalg/spectrum.py
    networkx/readwrite/__init__.py
    networkx/readwrite/adjlist.py
    networkx/readwrite/edgelist.py
    networkx/readwrite/gexf.py
    networkx/readwrite/gml.py
    networkx/readwrite/gpickle.py
    networkx/readwrite/graph6.py
    networkx/readwrite/graphml.py
    networkx/readwrite/json_graph/__init__.py
    networkx/readwrite/json_graph/adjacency.py
    networkx/readwrite/json_graph/cytoscape.py
    networkx/readwrite/json_graph/jit.py
    networkx/readwrite/json_graph/node_link.py
    networkx/readwrite/json_graph/tree.py
    networkx/readwrite/leda.py
    networkx/readwrite/multiline_adjlist.py
    networkx/readwrite/nx_shp.py
    networkx/readwrite/nx_yaml.py
    networkx/readwrite/p2g.py
    networkx/readwrite/pajek.py
    networkx/readwrite/sparse6.py
    networkx/relabel.py
    networkx/release.py
    networkx/utils/__init__.py
    networkx/utils/contextmanagers.py
    networkx/utils/decorators.py
    networkx/utils/heaps.py
    networkx/utils/mapped_queue.py
    networkx/utils/misc.py
    networkx/utils/random_sequence.py
    networkx/utils/rcm.py
    networkx/utils/union_find.py
    networkx/version.py
)

RESOURCE_FILES(
    PREFIX contrib/python/networkx/py2/
    .dist-info/METADATA
    .dist-info/top_level.txt
    networkx/generators/atlas.dat.gz
)

END()
