# Generated by devtools/yamaker.

LIBRARY()

LICENSE(BSL-1.0)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

PEERDIR(
    contrib/libs/poco/Foundation
)

ADDINCL(
    GLOBAL contrib/libs/poco/Data/include
    contrib/libs/poco/Data/src
    contrib/libs/poco/Foundation/include
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DPOCO_ENABLE_CPP11
    -DPOCO_ENABLE_CPP14
    -DPOCO_NO_AUTOMATIC_LIBS
    -DPOCO_UNBUNDLED
    -DTHREADSAFE
)

IF (OS_DARWIN)
    CFLAGS(
        -DPOCO_OS_FAMILY_UNIX
        -DPOCO_NO_STAT64
    )
ELSEIF (OS_LINUX)
    CFLAGS(
        -DPOCO_OS_FAMILY_UNIX
        -DPOCO_HAVE_FD_EPOLL
    )
ELSEIF (OS_WINDOWS)
    CFLAGS(
        -DPOCO_OS_FAMILY_WINDOWS
    )
ENDIF()

SRCS(
    src/AbstractBinder.cpp
    src/AbstractBinding.cpp
    src/AbstractExtraction.cpp
    src/AbstractExtractor.cpp
    src/AbstractPreparation.cpp
    src/AbstractPreparator.cpp
    src/ArchiveStrategy.cpp
    src/Bulk.cpp
    src/Connector.cpp
    src/DataException.cpp
    src/Date.cpp
    src/DynamicLOB.cpp
    src/Limit.cpp
    src/MetaColumn.cpp
    src/PooledSessionHolder.cpp
    src/PooledSessionImpl.cpp
    src/Position.cpp
    src/Range.cpp
    src/RecordSet.cpp
    src/Row.cpp
    src/RowFilter.cpp
    src/RowFormatter.cpp
    src/RowIterator.cpp
    src/SQLChannel.cpp
    src/Session.cpp
    src/SessionFactory.cpp
    src/SessionImpl.cpp
    src/SessionPool.cpp
    src/SessionPoolContainer.cpp
    src/SimpleRowFormatter.cpp
    src/Statement.cpp
    src/StatementCreator.cpp
    src/StatementImpl.cpp
    src/Time.cpp
    src/Transaction.cpp
)

END()
