# Generated by devtools/yamaker from nixpkgs 24.05.

LIBRARY()

LICENSE(
    BSD-3-Clause AND
    BSL-1.0 AND
    Bison-exception-2.2 AND
    GPL-3.0-or-later AND
    Hdf5 AND
    ISC AND
    LicenseRef-scancode-free-unknown AND
    LicenseRef-scancode-unknown-license-reference AND
    MIT AND
    NetCDF AND
    Public-Domain AND
    Zlib
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(4.10.0)

ORIGINAL_SOURCE(https://github.com/Unidata/netcdf-c/archive/v4.10.0.tar.gz)

PEERDIR(
    contrib/libs/curl
    contrib/libs/hdf5/hl/src
    contrib/libs/hdf5/src
    contrib/libs/libc_compat
)

ADDINCL(
    GLOBAL contrib/restricted/netcdf-c/include
    contrib/libs/hdf5/hl/src
    contrib/libs/hdf5/src
    contrib/restricted/netcdf-c
    contrib/restricted/netcdf-c/include
    contrib/restricted/netcdf-c/libncpoco
    contrib/restricted/netcdf-c/libnczarr
    contrib/restricted/netcdf-c/libsrc
    contrib/restricted/netcdf-c/oc2
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DCURL_STATICLIB=1
    -DHAVE_CONFIG_H
    -DRELAX_COORD_BOUND
)

SRCS(
    libdap2/cache.c
    libdap2/cdf.c
    libdap2/constraints.c
    libdap2/dapattr.c
    libdap2/dapcvt.c
    libdap2/dapdebug.c
    libdap2/dapdump.c
    libdap2/dapodom.c
    libdap2/daputil.c
    libdap2/dceconstraints.c
    libdap2/dcelex.c
    libdap2/dceparse.c
    libdap2/dcetab.c
    libdap2/getvara.c
    libdap2/ncd2dispatch.c
    libdap2/ncdaperr.c
    libdap4/d4chunk.c
    libdap4/d4curlfunctions.c
    libdap4/d4cvt.c
    libdap4/d4data.c
    libdap4/d4debug.c
    libdap4/d4dump.c
    libdap4/d4file.c
    libdap4/d4fix.c
    libdap4/d4http.c
    libdap4/d4meta.c
    libdap4/d4odom.c
    libdap4/d4parser.c
    libdap4/d4printer.c
    libdap4/d4read.c
    libdap4/d4swap.c
    libdap4/d4util.c
    libdap4/d4varx.c
    libdap4/ncd4dispatch.c
    libdispatch/datt.c
    libdispatch/dattget.c
    libdispatch/dattinq.c
    libdispatch/dattput.c
    libdispatch/dauth.c
    libdispatch/daux.c
    libdispatch/dcompound.c
    libdispatch/dcopy.c
    libdispatch/dcrc32.c
    libdispatch/dcrc64.c
    libdispatch/ddim.c
    libdispatch/ddispatch.c
    libdispatch/denum.c
    libdispatch/derror.c
    libdispatch/dfile.c
    libdispatch/dfilter.c
    libdispatch/dglobal.c
    libdispatch/dgroup.c
    libdispatch/dhttp.c
    libdispatch/dinfermodel.c
    libdispatch/dinstance.c
    libdispatch/dinstance_intern.c
    libdispatch/dinternal.c
    libdispatch/dmissing.c
    libdispatch/dnotnc3.c
    libdispatch/dnotnc4.c
    libdispatch/doffsets.c
    libdispatch/dopaque.c
    libdispatch/dparallel.c
    libdispatch/dpathmgr.c
    libdispatch/dplugins.c
    libdispatch/drc.c
    libdispatch/dreadonly.c
    libdispatch/ds3util.c
    libdispatch/dstring.c
    libdispatch/dtype.c
    libdispatch/dudfplugins.c
    libdispatch/dutf8.c
    libdispatch/dutil.c
    libdispatch/dv2i.c
    libdispatch/dvar.c
    libdispatch/dvarget.c
    libdispatch/dvarinq.c
    libdispatch/dvarput.c
    libdispatch/dvlen.c
    libdispatch/nc.c
    libdispatch/ncbytes.c
    libdispatch/ncexhash.c
    libdispatch/nchashmap.c
    libdispatch/ncindex.c
    libdispatch/ncjson.c
    libdispatch/nclist.c
    libdispatch/nclistmgr.c
    libdispatch/nclog.c
    libdispatch/ncproplist.c
    libdispatch/nctime.c
    libdispatch/ncuri.c
    libdispatch/ncxcache.c
    libdispatch/utf8proc.c
    libhdf5/H5FDhttp.c
    libhdf5/hdf5attr.c
    libhdf5/hdf5create.c
    libhdf5/hdf5debug.c
    libhdf5/hdf5dim.c
    libhdf5/hdf5dispatch.c
    libhdf5/hdf5file.c
    libhdf5/hdf5filter.c
    libhdf5/hdf5grp.c
    libhdf5/hdf5internal.c
    libhdf5/hdf5open.c
    libhdf5/hdf5plugins.c
    libhdf5/hdf5set_format_compatibility.c
    libhdf5/hdf5type.c
    libhdf5/hdf5var.c
    libhdf5/nc4hdf.c
    libhdf5/nc4info.c
    libhdf5/nc4mem.c
    libhdf5/nc4memcb.c
    liblib/nc_initialize.c
    libncpoco/cp_unix.c
    libncpoco/ncpoco.c
    libncxml/ncxml_tinyxml2.cpp
    libncxml/tinyxml2.cpp
    libnczarr/zarr.c
    libnczarr/zattr.c
    libnczarr/zchunking.c
    libnczarr/zclose.c
    libnczarr/zcreate.c
    libnczarr/zcvt.c
    libnczarr/zdebug.c
    libnczarr/zdim.c
    libnczarr/zdispatch.c
    libnczarr/zfile.c
    libnczarr/zfilter.c
    libnczarr/zgrp.c
    libnczarr/zinternal.c
    libnczarr/zmap.c
    libnczarr/zmap_file.c
    libnczarr/zmetadata.c
    libnczarr/zmetadata2.c
    libnczarr/zodom.c
    libnczarr/zopen.c
    libnczarr/zplugins.c
    libnczarr/zprov.c
    libnczarr/zsync.c
    libnczarr/ztype.c
    libnczarr/zutil.c
    libnczarr/zvar.c
    libnczarr/zwalk.c
    libnczarr/zxcache.c
    libsrc/attr.c
    libsrc/dim.c
    libsrc/httpio.c
    libsrc/lookup3.c
    libsrc/memio.c
    libsrc/nc3dispatch.c
    libsrc/nc3internal.c
    libsrc/ncio.c
    libsrc/ncx.c
    libsrc/posixio.c
    libsrc/putget.c
    libsrc/v1hpg.c
    libsrc/var.c
    libsrc4/nc4attr.c
    libsrc4/nc4cache.c
    libsrc4/nc4dim.c
    libsrc4/nc4dispatch.c
    libsrc4/nc4grp.c
    libsrc4/nc4internal.c
    libsrc4/nc4type.c
    libsrc4/nc4var.c
    libsrc4/ncfunc.c
    oc2/daplex.c
    oc2/dapparse.c
    oc2/dapy.c
    oc2/oc.c
    oc2/occompile.c
    oc2/occurlfunctions.c
    oc2/ocdata.c
    oc2/ocdebug.c
    oc2/ocdump.c
    oc2/ochttp.c
    oc2/ocinternal.c
    oc2/ocnode.c
    oc2/ocread.c
    oc2/ocutil.c
    oc2/xxdr.c
)

IF (NOT OS_WINDOWS)
    SRCS(
        libsrc/mmapio.c
    )
ENDIF()

IF (OS_WINDOWS)
    SRCS(
        libncpoco/cp_win32.c
    )
ENDIF()

RUN_PROGRAM(
    contrib/tools/m4 -DERANGE_FILL libsrc/attr.m4
    CWD ${ARCADIA_BUILD_ROOT}/contrib/restricted/netcdf-c/libsrc
    STDOUT_NOAUTO libsrc/attr.c
    IN libsrc/attr.m4
    OUTPUT_INCLUDES assert.h config.h fbits.h nc3dispatch.h nc3internal.h ncdispatch.h ncutf8.h ncx.h rnd.h
        stdlib.h string.h
)

RUN_PROGRAM(
    contrib/tools/m4 -DERANGE_FILL libsrc/ncx.m4
    CWD ${ARCADIA_BUILD_ROOT}/contrib/restricted/netcdf-c/libsrc
    STDOUT_NOAUTO libsrc/ncx.c
    IN libsrc/ncx.m4
    OUTPUT_INCLUDES assert.h config.h float.h inttypes.h limits.h nc3dispatch.h ncx.h stdint.h stdio.h
        stdlib.h string.h
)

RUN_PROGRAM(
    contrib/tools/m4 -DERANGE_FILL libsrc/putget.m4
    CWD ${ARCADIA_BUILD_ROOT}/contrib/restricted/netcdf-c/libsrc
    STDOUT_NOAUTO libsrc/putget.c
    IN libsrc/putget.m4
    OUTPUT_INCLUDES assert.h config.h fbits.h nc3dispatch.h nc3internal.h ncx.h netcdf.h onstack.h stdio.h
        stdlib.h string.h
)

END()
