syntax = "proto3";

package NLogBroker;

import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/common/ydb_operation.proto";

option cc_enable_arenas = true;
option go_package = "a.yandex-team.ru/logbroker/public/api/common;logbroker_common";

message ExecuteModifyCommandsResponse {
    NLogBroker.Operations.Operation operation = 1;
}

message ExecuteModifyCommandsResult {
    uint64 version = 1;
    repeated string applied_clusters = 2;
    repeated string disabled_clusters = 3;
}

message Entry {
    oneof entry {
        string directory = 1;
        string topic = 2;
        string consumer = 3;
    }
}

message ClusterKey {
    string cluster = 1;
}

message ClusterProperties {
    StringOrDefaultValue balancer = 1;
    BoolOrDefaultValue write_enabled = 2;
    BoolOrDefaultValue apply_changes_enabled = 3;
}

message ClusterAdminProperties {
    StringOrDefaultValue zk_proxy = 1;
    StringOrDefaultValue kikimr_host = 2;
    IntOrDefaultValue kikimr_msgbus_in_flight = 3;
    IntOrDefaultValue kikimr_msgbus_max_msg_size = 4;
    IntOrDefaultValue kikimr_port = 5;

    BoolOrDefaultValue mirroring_enabled = 6;
    IntOrDefaultValue mirroring_max_delay_threshold = 7;
    IntOrDefaultValue mirroring_max_message_lag = 8;
    IntOrDefaultValue mirroring_partitions_per_fetcher = 9;

    IntOrDefaultValue write_speed_capacity = 10;
    IntOrDefaultValue read_speed_capacity = 11;

    IntOrDefaultValue weight = 12;
    StringOrDefaultValue ydb_location = 13;
}

message TopicAdminProperties {
    IntOrDefaultValue max_message_size = 1;
    IntOrDefaultValue max_disk_size = 2;
    IntOrDefaultValue partitions_per_tablet = 3;
    IntOrDefaultValue max_partition_write_speed = 4;
}

message QuotaUsageProperties {
    QuotaUsageDescription directories_count = 1;
    QuotaUsageDescription topics_count = 2;
    QuotaUsageDescription consumers_count = 3;
    QuotaUsageDescription topic_partitions_count_max = 4;
    QuotaUsageDescription topic_partitions_count_sum = 5;
}

message AdminQuotaUsageProperties {
    QuotaUsageDescription clusters_count = 1;
    QuotaUsageDescription accounts_count = 2;
    QuotaUsageDescription account_templates_count = 3;
    QuotaUsageDescription topic_templates_count = 4;
    QuotaUsageDescription consumer_templates_count = 5;
}

message AccountProperties {
    IntOrDefaultValue topic_partitions_count_max = 1;
    IntOrDefaultValue topic_partitions_count_sum = 2;
    IntOrDefaultValue topics_count = 3;
    IntOrDefaultValue consumers_count = 5;
    IntOrDefaultValue directories_count = 10;
    IntOrDefaultValue max_metadata_per_entry = 11;
    StringOrDefaultValue abc_service = 12;
    IntOrDefaultValue abc_id = 16;
    StringOrDefaultValue responsible = 14;
    StringOrDefaultValue mailing_list = 15;
    StringOrDefaultValue monitoring_project_id = 17;
}

message AccountAdminProperties {
    IntOrDefaultValue topic_templates_count = 4;
    IntOrDefaultValue consumer_templates_count = 6;
    IntOrDefaultValue clusters_count = 7;
    IntOrDefaultValue accounts_count = 8;
    IntOrDefaultValue account_templates_count = 9;
    IntOrDefaultValue write_speed_notify_threshold = 13;
    BoolOrDefaultValue abc_service_validated = 14;
    StringOrDefaultValue folder_id = 15;
    BoolOrDefaultValue switched_to_database = 16;
    StringOrDefaultValue abc_folder_id = 17;
}

message Path {
    string path = 1;
}

message DirectoryProperties {
    StringOrDefaultValue abc_service = 1;
    IntOrDefaultValue abc_id = 8;
    StringOrDefaultValue responsible = 2;
    StringOrDefaultValue mailing_list = 7;
}

message DirectoryAdminProperties {
}

message TopicProperties {
    IntOrDefaultValue partitions_count = 1;
    IntOrDefaultValue retention_period_sec = 2;
    StringOrDefaultValue abc_service = 3;
    IntOrDefaultValue abc_id = 10;
    BoolOrDefaultValue allow_unauthenticated_read = 4;
    BoolOrDefaultValue allow_unauthenticated_write = 5;
    StringOrDefaultValue responsible = 6;
    StringOrDefaultValue mailing_list = 7;
    IntOrDefaultValue supported_format_version = 8;
    StringOrDefaultValue supported_codecs = 9;
    StringOrDefaultValue federation_account = 11;
    IntOrDefaultValue max_partitions_count = 12;
    IntOrDefaultValue auto_partitioning_stabilization_window_seconds = 13;
    IntOrDefaultValue auto_partitioning_up_utilization_percent = 14;
    IntOrDefaultValue auto_partitioning_down_utilization_percent = 15;
    StringOrDefaultValue auto_partitioning_strategy = 16;
    BoolOrDefaultValue partition_metrics_enabled = 17;
}

message ConsumerProperties {
    BoolOrDefaultValue important = 1;
    IntOrDefaultValue availability_period_sec = 11;
    StringOrDefaultValue abc_service = 4;
    IntOrDefaultValue abc_id = 10;
    StringOrDefaultValue limits_mode = 5;
    StringOrDefaultValue responsible = 6;
    StringOrDefaultValue mailing_list = 7;
    IntOrDefaultValue supported_format_version = 8;
    StringOrDefaultValue supported_codecs = 9;
    BoolOrDefaultValue partition_metrics_enabled = 12;
    IntOrDefaultValue consumer_type = 13;
    BoolOrDefaultValue keep_messages_order = 14;
    BoolOrDefaultValue dead_letter_policy_enabled = 15;
    IntOrDefaultValue dead_letter_policy = 16;
    IntOrDefaultValue max_processing_attempts = 17;
    IntOrDefaultValue default_processing_timeout_seconds = 18;
    StringOrDefaultValue dead_letter_queue = 19;
    IntOrDefaultValue default_delay_message_time_ms = 20;
    IntOrDefaultValue default_receive_message_wait_time_ms = 21;
}

message ConsumerAdminProperties {
    IntOrDefaultValue max_delay_threshold_sec = 2;
    IntOrDefaultValue max_message_lags = 3;
    oneof allowed_read_rule_mode {
        ClusterKey mirror_to_cluster = 4;
        AllOriginal all_original = 5;
    }
    IntOrDefaultValue max_read_rules = 8;
    IntOrDefaultValue max_partitions = 9;
}

message ReadRule {
    ReadRuleKey read_rule = 1;
    ReadRuleProperties properties = 2;
}

message ReadRuleAdmin {
    ReadRuleKey read_rule = 1;
    ReadRuleProperties properties = 2;
    ReadRuleAdminProperties admin_properties = 3;
}

message ReadRuleKey {
    Path topic = 1;
    Path consumer = 2;
    oneof mode {
        ClusterKey mirror_to_cluster = 3;
        AllOriginal all_original = 4;
    }
}

message AllOriginal {
}

message ReadRuleProperties {
}

message ReadRuleAdminProperties {
    BoolOrDefaultValue important = 1;
    IntOrDefaultValue read_from_time_sec = 2;
}

message IamCredentials {
    string endpoint = 1;
    string service_account_key = 2;
}

message Credentials {
    oneof credentials {
        string oauth_token = 1;
        IamCredentials iam = 3;
    }
}

message RemoteMirrorRule {
    RemoteMirrorRuleKey remote_mirror_rule = 1;
    RemoteMirrorRuleProperties properties = 2;
}

message RemoteMirrorRuleAdmin {
    RemoteMirrorRuleKey remote_mirror_rule = 1;
    RemoteMirrorRuleProperties properties = 2;
    RemoteMirrorRuleAdminProperties admin_properties = 3;
}

message RemoteMirrorRuleKey {
    Path topic = 1;
    ClusterKey cluster = 2;
}

message RemoteMirrorRuleProperties {
    StringOrDefaultValue src_cluster_endpoint = 1;
    StringOrDefaultValue src_database = 2;
    StringOrDefaultValue src_topic = 3;
    StringOrDefaultValue src_consumer = 4;
    IntOrDefaultValue read_from_time_sec = 5;
    Credentials credentials = 6;
}

message RemoteMirrorRuleAdminProperties {
}

message YtConsumerProperties {
    StringOrDefaultValue binary_path = 1;
    IntOrDefaultValue cluster_ratio_denominator = 2;
    IntOrDefaultValue cluster_ratio_nominator = 3;
    StringOrDefaultValue destination = 4;
    BoolOrDefaultValue enabled = 5;
    StringOrDefaultValue flavor = 6;
    StringOrDefaultValue format = 7;
    StringOrDefaultValue hosts_handle = 8;
    IntOrDefaultValue max_work_time = 9;
    IntOrDefaultValue max_work_time_delta = 10;
    StringOrDefaultValue output_pattern = 11;
    StringOrDefaultValue state_path = 12;
    IntOrDefaultValue threads = 13;
    IntOrDefaultValue timeout = 14;
    StringOrDefaultValue token = 15;
    IntOrDefaultValue total_buffer_limit = 16;
    StringOrDefaultValue push_token = 17;
    StringOrDefaultValue lock_token = 18;
    StringOrDefaultValue merge_token = 19;
}

message DirectoryRateLimitProperties {
    ClusterKey cluster = 2;
    IntOrDefaultValue write_speed_per_sec = 3;
    IntOrDefaultValue read_speed_per_sec = 4;
}

message AccountRateLimitProperties {
    DirectoryRateLimitProperties base_rate_limit_properties = 1;
    ClusterKey cluster = 2;
    IntOrDefaultValue rolling_dc_write_speed_per_sec = 3;
    IntOrDefaultValue write_speed_per_sec = 4;
    IntOrDefaultValue read_speed_per_sec = 5;
}

message InheritedDirectoryRateLimit {
    Path path = 1;
    repeated DirectoryRateLimitProperties rate_limits = 2;
}

message TopicRateLimitProperties {
    ClusterKey cluster = 2;
    IntOrDefaultValue write_speed_per_sec = 3;
}

message ConsumerRateLimitProperties {
    ClusterKey cluster = 2;
    IntOrDefaultValue read_speed_per_sec = 4;
}

message Metadata {
    string key = 1;
    string value = 2;
}

message Permissions {
    repeated string permission_names = 1;
    string subject = 2;
    string subject_type = 3;
    string subject_name = 4;
}

message QuotaUsageDescription {
    oneof variant {
        uint64 user_defined = 1;
        uint64 default = 2;
    }
    uint64 usage = 3;
}

message BasicDescribeAccountResult {
    string name = 1;
    IntOrDefaultValue abc_id = 2;
    StringOrDefaultValue abc_folder_id = 3;
    repeated AccountRateLimitProperties account_rate_limits = 4;
}

message ListFilter {
    oneof condition {
        uint64 abc_id = 1;
    }
}

message IntOrDefaultValue {
    oneof variant {
        uint64 user_defined = 1;
        uint64 default = 2;
    }
}

message StringOrDefaultValue {
    oneof variant {
        string user_defined = 1;
        string default = 2;
    }
}

message BoolOrDefaultValue {
    oneof variant {
        bool user_defined = 1;
        bool default = 2;
    }
}

message TopicInstance {
    string target_cluster = 1;
    string origin_cluster = 2;
}
