syntax = "proto3";

import "google/protobuf/any.proto";
import "google/protobuf/duration.proto";

import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/common/validation.proto";
import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/common/ydb_common.proto";
import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/common/ydb_issue_message.proto";
import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/common/ydb_status_codes.proto";

package NLogBroker.Operations;

option cc_enable_arenas = true;
option java_package = "com.yandex.logbroker";
option java_outer_classname = "OperationProtos";
option go_package = "a.yandex-team.ru/logbroker/public/api/common;logbroker_common";

message OperationParams {
    enum OperationMode {
        OPERATION_MODE_UNSPECIFIED = 0;
        SYNC = 1;
        ASYNC = 2;
    }

    OperationMode operation_mode = 1;
    google.protobuf.Duration operation_timeout = 2;
    google.protobuf.Duration cancel_after = 3;
    google.protobuf.Duration forget_after = 6;
    map<string, string> labels = 4;
    NLogBroker.FeatureFlag.Status report_cost_info = 5;
}

message GetOperationRequest {
    string id = 1 [(required) = true];
}

message GetOperationResponse {
    Operation operation = 1;
}

message CancelOperationRequest {
    string id = 1 [(required) = true];
}

message CancelOperationResponse {
    StatusIds.StatusCode status = 1;
    repeated NLogBroker.Issue.IssueMessage issues = 2;
}

message ForgetOperationRequest {
    string id = 1 [(required) = true];
}

message ForgetOperationResponse {
    StatusIds.StatusCode status = 1;
    repeated NLogBroker.Issue.IssueMessage issues = 2;
}

message ListOperationsRequest {
    string kind = 1 [(required) = true];
    uint64 page_size = 2;
    string page_token = 3;
}

message ListOperationsResponse {
    StatusIds.StatusCode status = 1;
    repeated NLogBroker.Issue.IssueMessage issues = 2;
    repeated Operation operations = 3;
    string next_page_token = 4;
}

message Operation {
    string id = 1;
    bool ready = 2;
    StatusIds.StatusCode status = 3;
    repeated NLogBroker.Issue.IssueMessage issues = 4;
    google.protobuf.Any result = 5;
    google.protobuf.Any metadata = 6;
    CostInfo cost_info = 7;
}
