syntax = "proto3";

package NLogBroker;

option cc_enable_arenas = true;
option java_package = "com.yandex.logbroker";
option java_outer_classname = "CommonProtos";
option go_package = "a.yandex-team.ru/logbroker/public/api/common;logbroker_common";

message FeatureFlag {
    enum Status {
        STATUS_UNSPECIFIED = 0;
        ENABLED = 1;
        DISABLED = 2;
    }
}

message CostInfo {
    double consumed_units = 1;
}

message QuotaExceeded {
    bool disk = 1;
}

message VirtualTimestamp {
    uint64 plan_step = 1;
    uint64 tx_id = 2;
}
