# Generated by devtools/yamaker from nixpkgs 24.05.

LIBRARY()

VERSION(1.55.5)

ORIGINAL_SOURCE(https://gitlab.gnome.org/api/v4/projects/GNOME%2Fpango/repository/archive.tar.gz?sha=1.55.5)

LICENSE(
    BSD-3-Clause AND
    ICU AND
    LGPL-2.0-only AND
    LGPL-2.0-or-later AND
    LGPL-2.1-or-later AND
    TCL AND
    Unicode
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

PEERDIR(
    contrib/libs/harfbuzz
    contrib/restricted/fribidi
    contrib/restricted/glib
    contrib/restricted/glib/include
)

ADDINCL(
    contrib/libs/harfbuzz/include
    contrib/libs/pango
    contrib/libs/pango/pango
    contrib/restricted/fribidi/include
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

CFLAGS(
    -DG_LOG_DOMAIN=\"Pango\"
    -DG_LOG_USE_STRUCTURED=1
    -DLIBDIR=\"/tmp/yamaker/pango/out/lib\"
    -DPANGO_COMPILATION
    -DSYSCONFDIR=\"/var/empty/pango-1.55.5/etc\"
)

SRCS(
    pango/break.c
    pango/ellipsize.c
    pango/fonts.c
    pango/glyphstring.c
    pango/itemize.c
    pango/json/gtkjsonparser.c
    pango/json/gtkjsonprinter.c
    pango/modules.c
    pango/pango-attributes.c
    pango/pango-bidi-type.c
    pango/pango-color.c
    pango/pango-context.c
    pango/pango-coverage.c
    pango/pango-emoji.c
    pango/pango-engine.c
    pango/pango-enum-types.c
    pango/pango-fontmap.c
    pango/pango-fontset-simple.c
    pango/pango-fontset.c
    pango/pango-glyph-item.c
    pango/pango-gravity.c
    pango/pango-item.c
    pango/pango-language.c
    pango/pango-layout.c
    pango/pango-markup.c
    pango/pango-matrix.c
    pango/pango-renderer.c
    pango/pango-script.c
    pango/pango-tabs.c
    pango/pango-utils.c
    pango/reorder-items.c
    pango/serializer.c
    pango/shape.c
)

END()

RECURSE(
    pangocairo-1.0
    pangoft2-1.0
)
