name: Acceptance-run
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
    inputs:
      test_label_regexp:
        required: false
        type: string

jobs:
  ya_x86_64:
    name: Build/test x86_64 using YA
    uses: ./.github/workflows/build_and_test_ya_provisioned.yml
    secrets: inherit
    with:
      runner_label: auto-provisioned
      build_preset: relwithdebinfo
      build_target: ydb/
      run_build: true
      run_tests: true
