name: Build-YDB-DSTool
run-name: Build YDB DSTool

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Do not change this unless you know what you are doing
        type: string
        default: ""
      build-linux-amd:
        type: boolean
        description: Build YDB DSTool for Linux (amd64)
        default: true
      build-linux-arm:
        type: boolean
        description: Build YDB DSTool for Linux (arm64)
        default: true
      build-darwin-amd:
        type: boolean
        description: Build YDB DSTool for MacOS (amd64)
        default: true
      build-darwin-arm:
        type: boolean
        description: Build YDB DSTool for MacOS (arm64)
        default: true
      build-windows-amd:
        type: boolean
        description: Build YDB DSTool for Windows (amd64)
        default: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build binaries
    uses: ./.github/workflows/build_binaries.yml
    with:
      build-target: ydb/apps/dstool
      binary-name: ydb-dstool
      additional-ya-make-args: "-DUSE_SSE4=no"
      version-argument: "--version"
      ref: ${{ inputs.commit_sha || github.ref }}
      build-linux-amd: ${{ inputs.build-linux-amd }}
      build-linux-arm: ${{ inputs.build-linux-arm }}
      build-darwin-amd: ${{ inputs.build-darwin-amd }}
      build-darwin-arm: ${{ inputs.build-darwin-arm }}
      build-windows-amd: ${{ inputs.build-windows-amd }}

  gather-and-push-to-s3:
    name: Gather built binaries and push to s3
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.commit_sha || github.ref }}
      - name: Get YDB DSTool version
        id: get-version
        shell: bash
        run: |
          VERSION=$(cat ydb/apps/dstool/version.txt)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "YDB DSTool version: $VERSION"
      - name: Gather and upload to S3
        uses: ./.github/actions/gather_and_upload_to_s3
        with:
          version: ${{ steps.get-version.outputs.version }}
          s3-bucket: "yandexcloud-ydb-dstool"
          s3-key-id: ${{ secrets.CLI_S3_KEY_ID }}
          s3-key-secret: ${{ secrets.CLI_S3_KEY_SECRET_ID }}
          build-linux-amd: ${{ inputs.build-linux-amd }}
          build-linux-arm: ${{ inputs.build-linux-arm }}
          build-darwin-amd: ${{ inputs.build-darwin-amd }}
          build-darwin-arm: ${{ inputs.build-darwin-arm }}
          build-windows-amd: ${{ inputs.build-windows-amd }}
