name: Rebuild documentation

on:
  pull_request_target:
    types: [labeled]

jobs:
  build-docs:
    if: |
      github.event.label.name == 'rebuild_docs' &&
      github.event.pull_request.state == 'open'
    concurrency:
      group: docs-build-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get commit SHA
        id: sha
        run: echo "value=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Build
        uses: diplodoc-platform/docs-build-action@v3
        with:
          revision: "pr-${{ github.event.pull_request.number }}-${{ steps.sha.outputs.value }}"
          src-root: "./ydb/docs"
          cli-version: stable
