name: Prewarm-Ccache
on:
  schedule:
    - cron: "0 4 * * *"  # At 04:00 every day
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, auto-provisioned]
    strategy:
      fail-fast: false
      matrix:
        version: ["ubuntu-2204", "ubuntu-2004", "ubuntu-1804"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build
        shell: bash
        run: |
          echo "::group::docker-build"
          docker build -f .github/prewarm/${{ matrix.version }}.dockerfile -t $IMG .
          echo "::endgroup::"
          
          docker run --rm -v `pwd`:/ydbwork/ydb \
            -e CCACHE_REMOTE_STORAGE="${CCACHE_REMOTE_STORAGE}" \
            $IMG \
            bash /ydbwork/ydb/.github/prewarm/build.sh
        env:
          IMG: runner-${{ matrix.version }}
          CCACHE_REMOTE_STORAGE: ${{ vars.REMOTE_CACHE_URL && format('http://{0}{1}', secrets.REMOTE_CACHE_AUTH, vars.REMOTE_CACHE_URL) || ''}}
