name: Prewarm-debug
on:
  schedule:
    - cron: "15 */6 * * *"  # At minute 15 past every 6th hour
  workflow_dispatch:

jobs:
  build_ya_make:
    name: Build/test x86_64 using YA
    uses: ./.github/workflows/build_and_test_ya.yml
    secrets: inherit
    with:
      build_target: ydb/
      build_preset: debug
      run_build: true
      run_tests: false
      secs: ${{ format('{{"TESTMO_TOKEN2":"{0}","AWS_KEY_ID":"{1}","AWS_KEY_VALUE":"{2}","REMOTE_CACHE_USERNAME":"{3}","REMOTE_CACHE_PASSWORD":"{4}"}}',
        secrets.TESTMO_TOKEN2, secrets.AWS_KEY_ID, secrets.AWS_KEY_VALUE, secrets.REMOTE_CACHE_USERNAME, secrets.REMOTE_CACHE_PASSWORD ) }}
      vars: ${{ format('{{"AWS_BUCKET":"{0}","AWS_ENDPOINT":"{1}","REMOTE_CACHE_URL":"{2}","TESTMO_URL":"{3}","TESTMO_PROJECT_ID":"{4}"}}',
        vars.AWS_BUCKET, vars.AWS_ENDPOINT, vars.REMOTE_CACHE_URL_YA, vars.TESTMO_URL, vars.TESTMO_PROJECT_ID ) }}

