name: Prewarm-debug
on:
  schedule:
    - cron: "15 */6 * * *"  # At minute 15 past every 6th hour
  workflow_dispatch:

jobs:
  build_ya_make:
    name: Build/test x86_64 using YA
    uses: ./.github/workflows/build_and_test_ya_provisioned.yml
    secrets: inherit
    with:
      build_target: ydb/
      build_preset: debug
      run_build: true
      run_tests: false
