name: Rightlib sync
on:
  schedule:
    # If you change the schedule here, please also update it in the conditionals for the create-pr and check-pr steps.
    - cron: "30 0 * * *"   # At 00:30 -- for PR creation
    - cron: "30 1-23 * * *"   # Hourly during 1-23 interval for PR completion
  workflow_dispatch:
    inputs:
      command:
        default: check-pr
        options:
          - create-pr
          - check-pr
        required: true
        type: choice
        description: ""
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: install packages
        run: |
          pip install PyGithub==2.5.0
      - name: checkout main
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ydb/ci/rightlib
      - name: configure
        run: |
          git config --global user.email "alex@ydb.tech"
          git config --global user.name "Alexander Smirnov"

      - name: create-pr
        if: github.event.schedule == '30 0 * * *' || (github.event.inputs && github.event.inputs.command == 'create-pr')
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: |
          cd ./ydb/ci/rightlib
          ./sync-rightlib.py create-pr

      - name: check-pr
        if: github.event.schedule == '30 1-23 * * *' || (github.event.inputs && github.event.inputs.command == 'check-pr')
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: |
          cd ./ydb/ci/rightlib
          ./sync-rightlib.py check-pr
