name: Sync cmakebuild with main
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: cmakebuild
    - name: Sync
      run: |
        curl https://raw.githubusercontent.com/ydb-platform/ydb/main/ydb/ci/sync_cmakebuild.sh > ~/sync_cmakebuild.sh
        chmod +x ~/sync_cmakebuild.sh
        ~/sync_cmakebuild.sh
        git push
