# Generated by devtools/yamaker (pypi).

PY2_LIBRARY()

VERSION(3.3.1)

LICENSE(Apache-2.0)

PEERDIR(
    contrib/python/html5lib
    contrib/python/packaging
    contrib/python/six
    contrib/python/webencodings
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    bleach/__init__.py
    bleach/callbacks.py
    bleach/html5lib_shim.py
    bleach/linkifier.py
    bleach/sanitizer.py
    bleach/utils.py
)

RESOURCE_FILES(
    PREFIX contrib/python/bleach/py2/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()

RECURSE_FOR_TESTS(
    tests
)
