#pragma once

namespace NKikimr::NPDisk {

enum class ERequestType {
    RequestLogRead,
    RequestLogReadContinue,
    RequestLogReadResultProcess,
    RequestLogSectorRestore,
    RequestLogWrite,
    RequestChunkRead,
    RequestChunkReadPiece,
    RequestChunkWrite,
    RequestChunkWritePiece,
    RequestChunkTrim,
    RequestYardInit,
    RequestCheckSpace,
    RequestHarakiri,
    RequestYardSlay,
    RequestChunkReserve,
    RequestChunkLock,
    RequestChunkUnlock,
    RequestYardControl,
    RequestAskForCutLog,
    RequestConfigureScheduler,
    RequestWhiteboartReport,
    RequestHttpInfo,
    RequestUndelivered,
    RequestNop,
    RequestCommitLogChunks,
    RequestLogCommitDone,
    RequestTryTrimChunk,
    RequestReleaseChunks,
    RequestStopDevice,
    RequestChunkForget,
    RequestReadMetadata,
    RequestInitialReadMetadataResult,
    RequestWriteMetadata,
    RequestWriteMetadataResult,
    RequestPushUnformattedMetadataSector,
    RequestContinueReadMetadata,
    RequestShredPDisk,
    RequestPreShredCompactVDiskResult,
    RequestShredVDiskResult,
    RequestChunkShredResult,
    RequestContinueShred,
    RequestYardResize,
    RequestChangeExpectedSlotCount,
    RequestChunkReadRaw,
    RequestChunkWriteRaw,
    RequestCompactionBidder,
};

} // NKikimr::NPDisk
