syntax = "proto3";

import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/protos/config_manager.proto";
import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/common/common.proto";
import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/common/ydb_operation.proto";

package NLogBroker;

option cc_enable_arenas = true;
option java_outer_classname = "Service";
option go_package = "a.yandex-team.ru/logbroker/public/api/grpc;logbroker_grpc";

service ConfigurationManagerService {
    rpc DescribeCluster(DescribeClusterRequest) returns (DescribeClusterResponse);
    rpc DescribePath(DescribePathRequest) returns (DescribePathResponse);

    rpc ListClusters(ListClustersRequest) returns (ListClustersResponse);
    rpc ListAccounts(ListAccountsRequest) returns (ListAccountsResponse);
    rpc ListDirectory(ListDirectoryRequest) returns (ListDirectoryResponse);

    rpc ListYtDeliveries(ListYtDeliveriesRequest) returns (ListYtDeliveriesResponse);

    rpc ExecuteModifyCommands(ExecuteModifyCommandsRequest) returns (ExecuteModifyCommandsResponse);

    rpc GetOperation(NLogBroker.Operations.GetOperationRequest) returns (NLogBroker.Operations.GetOperationResponse);
}
