syntax = "proto3";

import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/admin/config_manager_admin.proto";
import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/common/common.proto";
import "ydb/public/tools/federation_recipe/proto/logbroker/public/api/common/ydb_operation.proto";

package NLogBroker.NAdmin;

option cc_enable_arenas = true;
option java_outer_classname = "Service";
option go_package = "a.yandex-team.ru/logbroker/public/api/grpc;logbroker_grpc";

service ConfigurationManagerAdminService {
    rpc DescribeCluster(DescribeClusterRequest) returns (DescribeClusterResponse);
    rpc DescribePath(DescribePathRequest) returns (DescribePathResponse);
    rpc DescribeYtConsumer(DescribeYtConsumerRequest) returns (DescribeYtConsumerResponse);
    rpc DescribeAccountTemplate(DescribeAccountTemplateRequest) returns (DescribeAccountTemplateResponse);
    rpc DescribeTopicTemplate(DescribeTopicTemplateRequest) returns (DescribeTopicTemplateResponse);
    rpc DescribeConsumerTemplate(DescribeConsumerTemplateRequest) returns (DescribeConsumerTemplateResponse);

    rpc ListClusters(ListClustersRequest) returns (ListClustersResponse);
    rpc ListAccounts(ListAccountsRequest) returns (ListAccountsResponse);
    rpc ListAccountsAndDescribe(ListAccountsAndDescribeRequest) returns (ListAccountsAndDescribeResponse);
    rpc ListDirectory(ListDirectoryRequest) returns (ListDirectoryResponse);
    rpc ListYtConsumers(ListYtConsumersRequest) returns (ListYtConsumersResponse);
    rpc ListYdbConsumers(ListYdbConsumersRequest) returns (ListYdbConsumersResponse);
    rpc ListAccountTemplates(ListAccountTemplatesRequest) returns (ListAccountTemplatesResponse);
    rpc ListTopicTemplates(ListTopicTemplatesRequest) returns (ListTopicTemplatesResponse);
    rpc ListConsumerTemplates(ListConsumerTemplatesRequest) returns (ListConsumerTemplatesResponse);

    rpc ExecuteModifyCommands(ExecuteModifyCommandsRequest) returns (NLogBroker.ExecuteModifyCommandsResponse);

    rpc GetOperation(NLogBroker.Operations.GetOperationRequest) returns (NLogBroker.Operations.GetOperationResponse);

    rpc GetCurrentVersion(GetCurrentVersionRequest) returns (GetCurrentVersionResponse);
    rpc GetBackendVersions(GetBackendVersionsRequest) returns (GetBackendVersionsResponse);
    rpc GetCommandsLog(GetCommandsLogRequest) returns (GetCommandsLogResponse);
}
